### ISSUE TITLE
Due Date in GMT?

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1003]
I believe the due date is in GMT? It might be either good just to clarify this, or the friendlier way would be to be able to select the time zone - yeah, a bit more complicated...

It will probably mess up some high school students initially (even us teachers setting the due date wrong.)

**Comment by bnmnetp** [comment]
So, the server is definitely set up to store everything in UTC.  The trick is to figure out how to use JavaScript correctly to read and display the deadlines correctly in the local time zone.  I’ve not spent much time trying to figure out how to do it.  Maybe that can be one of tomorrows project.

**Comment by bnmnetp** [comment]
So, when you set the due date for the assignment, it is stored un-altered in whatever time you set, this will be from the instructors timezone.

When students do their work, its timestamped as UTC -- thats what the server is set to operate on.

So, I **think** the only thing we have to do is when we are checking the deadline we need to adjust the time of submission into the instructors timezone. -- which I have now done.

**Comment by psmaker** [comment]
I tried testing it out with a due date of today at 2:12 pm PST.

When I auto graded, all the scores were 0 even though there were correct answers.

Then I changed the assignment due date to tomorrow. Auto-graded and then the scores were as expected.

Then I changed the assignment due date to today, but at 21:12, which was the UTC equivalent of 14:12 PST.

In this case, I saw the expected score for my test case - where some answers done before the due date were correctly credited, but answers done after the due date was not credited.

So, it seems like it is interpreting the time I enter in the Assignment page as in UTC time.

![image](https://user-images.githubusercontent.com/28868409/29192745-6e0cb2b2-7dd7-11e7-8d5a-c52ff1b0af17.png)

**Comment by bnmnetp** [comment]
I think its more a matter of whether your timezone offset was set the first time you tried. Its trickier than you might imagine.  I had to insert a snippet of javascript into the pages of the book that have the browser calculate its offset from UTC (an integer number of hours -- I Don't know what will happen in those weird australian timezones that go by half-hours!! but I digress)  The javascript then sends that offset to the server where it gets stored in your session cookie.    

Then I realized that if you went straight to the instructor interface, or if you were already in the instructor interface and didn't login or out that you would not have that value set.  So I added a similar snippet to all of the instructor interface code.  -- that would still have required a page reload **if** you did this after I pushed those changes to the server.  The fact that it worked right the second time makes me think that there was no offset in your session cookie the first time you tried.

**Comment by psmaker** [comment]
So, I tried it again.  I re-auto-graded Try13 with 3 different due date settings.

First  8/10 14:12.   Score was LHS_Admin 0 and LHS_Chrome: 0.
Then 8/10 21:12.  Score was LHS_Admin: 0 and LHS_Chrome: 1.  This is the the "score" I want.
Then 8/10 22:12.  Score was LHS_Admin  2 and LHS_Chrome: 1.  So, in this case, it was accepting the "late" work of LHS_admin who submitted his questions at around 21:14 UTC.

Maybe you can check the database Try13 assignment if that helps.

**Comment by bnmnetp** [comment]
Two paths, I only fixed one.

I have verified the correct behavior on a test assignment of my own.  Hopefully you can too.

**Comment by psmaker** [comment]
Yup verified. Thanks!
