### ISSUE TITLE
Activity Count Required jumped up

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1005]
The activity counts required for Chapter 1 sections jumped up in some areas.

Ex. 1.2 Algorithms is 8, but I only see 2 problems + 1 page view.

![image](https://user-images.githubusercontent.com/28868409/29201431-1279390c-7e13-11e7-9271-29d026fcd1e1.png)

**Comment by bnmnetp** [comment]
Grrr, I only fixed half of the problem yesterday.   Sometimes I think I have made changes when I haven't.   I definitely have now, and the counts look correct to me even with the other custom course in place again.
