### ISSUE TITLE
lost password - cannot send e-mail?

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1006]
In dev site, when trying to reset password of "lhs_chrome" user -
![image](https://user-images.githubusercontent.com/28868409/29232999-7d63b2fc-7ea3-11e7-9bec-a9e019174f73.png)

This Reset Password will be a very regularly used feature of (my) students...

**Comment by bnmnetp** [comment]
I had not configured the email setup on this installation yet.  I have now, but there are some lingering concerns as Google 's mailer wants to reject this domain and I suspect many forgetful people use gmail.

I will experiment with configuring the mailer to use a gmail account to send from.
