### ISSUE TITLE
reading assignment activity count changes

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1011]
I created a new assignment (thinkcspy base course) and added readings to it.
![capture1](https://user-images.githubusercontent.com/30346207/29277209-9b6b929e-80d6-11e7-92f4-ad0dd66f390f.PNG)

I moved to the grading tab but did nothing. Then I returned to the assignment tab and displayed the assignment I had created. All the values in the activity count column changed.
![capture2](https://user-images.githubusercontent.com/30346207/29277247-b5bb10d4-80d6-11e7-9fa1-eca06187fe9b.PNG)

**Comment by bnmnetp** [comment]
Thanks.   I think this should be a pretty easy fix.  Just one more place where we did not check the base course.

**Comment by bnmnetp** [comment]
OK, I'm getting the correct counts now after a reload.  How about you?

**Comment by haugrud** [comment]
yes - that was quick
