### ISSUE TITLE
discrepancy in gradebook

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1012]
Here is the overall gradebook - notice %
![capture1](https://user-images.githubusercontent.com/30346207/29279152-8c8a661e-80dc-11e7-9706-d3e3c623c7a6.PNG)

Here is drilling down into the assignment - the score is 3/8
![capture2](https://user-images.githubusercontent.com/30346207/29279174-9fcb8622-80dc-11e7-979d-18f227077123.PNG)

**Comment by haugrud** [comment]
now the % is correct - maybe it was a cache issue

**Comment by haugrud** [comment]
I just changed the score for ch01_1 of the assignment. The % in the gradebook has not been updated but when drilling down the score is correct.

**Comment by bnmnetp** [comment]
When you changed the score how did you change it?  Manual grade update?  Or did you go and do something in the book?  Are you doing this in multiple tabs or browser windows or just in a single tab?

A lot of data for the Student Progress tab is preloaded on the first page, so as you click on things there is not always a new database hit.

Getting a really precise sequence of events might help track this down.

**Comment by haugrud** [comment]
I used manual grade update on just a single browser tab

**Comment by haugrud** [comment]
I just noticed that I did not choose manual for that question in the assignment. I changed it to manual then regraded it and the scores shows correctly.

**Comment by haugrud** [comment]
The score for the assignment was 50% (4/8).
I changed the points for the question from 1 to 2. There are now 9 points in the assignment.
I regraded assigning a score of 2 (it was 1).  
The % for the assignment is now 44.44 (4/9).
Drilling down shows 5/9

**Comment by haugrud** [comment]
I returned to the grading tab and view the manual graded problems but did not change/save anything.
I then returned to the gradebook and the % is correct.

**Comment by bnmnetp** [comment]
Its hard to say for sure, with you testing and me adding fixes all at the same time.  It feels to me like there is something just slightly off timing.  As I've seen similar problems that just disappeared after a couple of minutes.  I'll definitely keep looking.

**Comment by bnmnetp** [comment]
OK, I think I've fixed this now.  It was a combination of things I fixed yesterday, and a problem I found today where when you manually grade it was not updating the assignment totals.  The only way was to re-autograde.  Now entering a manual total looks like it is correctly updating the total for the assignment.
