### ISSUE TITLE
auto/manual grading

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1013]
I created an assignment that is partly auto graded and partly manually graded.
I press the button to auto grade.
I then select a question to manually grade. The comments for that question are filled with autograded.
After manually grading, I press the auto grade button. The manual grading scores are replaced with None.

**Comment by bnmnetp** [comment]
Thanks.  I had seen that a couple of days ago and made a mental note to fix it...  So much for mental notes.  I just pushed a one line change that prevented this from happening on my dev machine.
