### ISSUE TITLE
runestone.academy logon issues?

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1015]
When I log into the runestone.academy as user lhs_chrome, I get immediately redirected to 

https://dev.runestone.academy/runestone/default/user/login?_next=https://runestone.academy/runestone/static/LHSIntroCS/index.html

as an unlogged in user.

Then from here, I need to log in again.

**Comment by bnmnetp** [comment]
This is a hold-over problem from the dev.runestone.academy days.

To fix this up you need to go to the instructors page, then manually remove the dev from the url in the address bar and hit enter to load the page with the dev no longer part of the domain name.  Then rebuild your course.

If that doesn't work, let me know and I can fix it the old school way with sed.

Brad

**Comment by psmaker** [comment]
Yep - worked!  Thanks!
