### ISSUE TITLE
rebuilt book and 1.15 disappeared

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1016]
I just rebuilt my LHSIntroCS book (there was a pop up saying I should rebuild, so I did...)

Upon the rebuild, the entire 1.15 Exercise section disappeared.

**Comment by bnmnetp** [comment]
There was never anything in the Exercises section of 1.15.

It was added as a placeholder so that when instructors add their own exercises there is a valid home for them in that chapter.

I can add some text to that to avoid confusion.
