### ISSUE TITLE
Progress checkmarks showing unexpectedly for student on a new course

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1017]
So, for my test lhs_chrome user who was previously reading the LHSIntroCS course, I made a new course called LHSIntroCS_2017.

When I changed the course for the lhs_chrome user to the new LHSIntroCS_2017 course. It is showing the green checkmark progress from the LHSIntroCS course. I was not expecting this.

But, digging into certain section pages, the actual activities are "clean" w/o any activity (as I would have expected.)

**Comment by bnmnetp** [comment]
Yes, the code that puts the check-marks in the table of contents will show a green check if **any** course you have been enrolled in contains that chapter/sub-chapter from the same parent course.

Its never really bothered anyone, but with the new reading assignments feature I can see where it might be time to tighten this up.

**Comment by psmaker** [comment]
It's not really a big deal for now.  I just thought the behavior was a bit odd... Thanks for at least clarifying.
