### ISSUE TITLE
missing scores in grade book

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1018]
The gradebook does not show assignment 1 scores for the last 11 students in my class. Scores are visible for these students via the grading tab.

**Comment by bnmnetp** [comment]
How many students total?

It sounds like the grades are all there, but somehow are not being rendered on the table generated on the gradebook page.

**Comment by bnmnetp** [comment]
If you download the gradebook are they all there?

I can't find anything in the code that would limit the number of students.  There isn't some page forward button or scrolling??  I could image there being some kind of max height to the table that would introduce scrolling or paging... 

Have you tried searching for one of the missing students in the Filter by Student box?

**Comment by haugrud** [comment]
Those scores are not present when I download - that's where I first noticed the problem. Searching for a student does not make a difference. All the students are listed on the gradebook page but the bottom ones are missing scores.

I had one student that had made 2 accounts and enrolled in my class twice. The gradebook showed his scores but for no other students below him. I unenrolled his duplicate account. Then the scores for several more (consecutive) students were displayed. The rest below that point were blank.

**Comment by haugrud** [comment]
64 student scores are displayed. That's an interesting number

**Comment by haugrud** [comment]
I just unenrolled a student that dropped. His score had been displayed. After removing him 63 student scores are displayed. It still stops at the same point

**Comment by bnmnetp** [comment]
Does the next student in line have any interesting characters in the name??

**Comment by haugrud** [comment]
I unenrolled the last student whose score was displayed. Then scores appeared for all the following ones!!
His id is ur3840rb

**Comment by haugrud** [comment]
Can you determine why the account I previously mentioned caused the problem? What can I do about this student?

**Comment by bnmnetp** [comment]
I've worked through the code for the grades controller in dashboard.py running each query manually, and I cannot find anything wrong.  I get 74 students in the course, and I get the grades for each student for two assignments?

Did the scores in the last row look correct to you when they were stopping early?

I might need to join your class and make myself an instructor temporarily to see if I can add enough logging to figure out whats going on.

**Comment by haugrud** [comment]
I see he is back in the class. However, his score is the last one listed in the gradebook. All students following him have blank scores.
Go ahead and add yourself as instructor if that will help.

**Comment by bnmnetp** [comment]
So the students are listed but their scores are blank??

**Comment by haugrud** [comment]
I will email you a picture

**Comment by bnmnetp** [comment]
OK, I **think** I see it now....  The issue is that the student in question somehow has two grades for the same assignment in the database!  That should not happen.  I'm going to remove one (the lowest 40 versus 46) from the database and lets see what happens.  then I'm going to add a constraint to make sure that user_id and assignment_id are unique in the grades table.

**Comment by haugrud** [comment]
The gradebook is fine now - thanks
