### ISSUE TITLE
nltk module request

### ISSUE THREAD

**Issue by jiangjiangflies** [RunestoneInteractive/RunestoneServer#1019]
Hi,
My teacher and I want to write an interactive book "**natural language processing with python**", it requires nltk module. Is it possible to port this module into Runestone?

**Comment by bnmnetp** [comment]
Hi,

Runestone uses skulpt as its in-browser Python interpreter.  You can check at github.com/skulpt/skulpt   -- to my knowledge nobody has tried to port nltk to skulpt.  But a PR like that would certainly be welcome.

**Comment by jiangjiangflies** [comment]
Is there any possibility that I can get any help?
