### ISSUE TITLE
unittest showing %0, but autograde gives a 1.0/1.0

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1024]
Where: LHSIntroCS / Assignment - New Exercise / Problem - lhs_sample_activecode

It is a basic unittest. I wrote it where it failed the test - and reported 0% of the tests passed.

But, after auto-grading, it scored 1/1.

![image](https://user-images.githubusercontent.com/28868409/29744940-cb2f9408-8a63-11e7-99f2-cdc5e612c8da.png)

**Comment by bnmnetp** [comment]
How do you have the grading set up for this?  It looks to me like you actually passed 50% of the tests not 0% -- which is a problem all by itself.  do you have it set up all or nothing or percent or ??

**Comment by psmaker** [comment]
It is written as % correct
![image](https://user-images.githubusercontent.com/28868409/29745014-b296a678-8a65-11e7-8008-03b2d794e71e.png)

I was not sure how the % was calculated.  At first I was expecting 50% as well. 

Then, I thought that if any assertion failed within a test_xxx(), then this meant 0%. So, I modified where I put 1 assert in test_one() and the 1 assert in test_two(). Then it reported 50%.  Therefore, I thought that the 0% was the intended behavior when 1 of 2 asserts passed within a single test_xxx().

**Comment by psmaker** [comment]
Hmm... I'm wondering if the 50% of 1 point is being rounded up to 1 point - thus the 1 / 1 score?

And that the printing out of the 0% is separate issue.

**Comment by psmaker** [comment]
I verified that if the problem is a 10 point problem, the it gets 5 points - 50%, even though it says 0% on the student's screen.
![image](https://user-images.githubusercontent.com/28868409/29985286-2efec4f0-8f13-11e7-97d3-ded03f147c84.png)

So, the problem is now just why is it displaying 0%, when it really should be displaying 50%?

The auto-grading seems to calculate the 50% correctly and use it when generating the score.

**Comment by psmaker** [comment]
This is closed now also. See #1034 

Thanks!  Another instructor was puzzled why a problem he was writing up acted like Python2 in the Assignment page - and now this clears everything up!
