### ISSUE TITLE
Writing Matching problem - does not auto-grade

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1025]
I tried making a Matching problem using Write - even though it did not have a menu item for this...

It seemed to work - and created a working problem - lhs_try_match.

But, it does not auto-grade.  When correct, it is scored as a 0.

Just checking if this was not intentionally implemented yet.

**Comment by bnmnetp** [comment]
Just to be clear, You mean the dragndrop directive?

**Comment by psmaker** [comment]
Oh yes! it is the drag and drop!  So, it is in the menu!  My bad...

But the grading is still nevertheless weird.

**Comment by bnmnetp** [comment]
I tried the same test, but auto grade seems to work fine.   What options do you have set up for the auto grading?

**Comment by psmaker** [comment]
% correct

![image](https://user-images.githubusercontent.com/28868409/29745293-a5d78ed8-8a6b-11e7-8775-2cef5f370d74.png)

**Comment by bnmnetp** [comment]
dragndrop is also an all or nothing prospect at the moment.

**Comment by psmaker** [comment]
I tried changing it to 'All or nothing' grading, and after auto-grading, it still comes up as 0/1.
