### ISSUE TITLE
Auto-Grading a class of 120+

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1029]
I have an assignment of 18 items and 120+ students.

When I auto-grade the assignment, I do not get a pop-up indicating the grading has complete. Perhaps it is taking too long and I'm not waiting long enough for a pop-up. 

Then, I tried bringing up a new window and tried to auto-grade one single person. Also, no pop-up saying that the grading is done. I'm suspecting that the server might be busy grading the first request? Not sure.

Then after sometime, it seems like auto-grading a single person works again.

But, the main issue is I'm not sure what happens when I try to auto-grade 120 students. Does it complete? Does if stop and timeout?

**Comment by bnmnetp** [comment]
If you go to the gradebook now, what does it show?

Clearly we have not tested the limits on this, and I'm not sure what will happen when you autograde 120 for 18 items.  There is a limit on the amount of memory that any one request can use, I have that set relatively small as I'm still figuring out resource usage on this new machine.

**Comment by bnmnetp** [comment]
It looks to me like they were all autograded successfully for the assignment:  Reading Unit 1  :  Read and do all items within Unit 1

**Comment by psmaker** [comment]
Yeah, but just about 10 minutes ago, I ran the auto-grade on each questions.  So, a 148 x 1 works OK.

But the 148x18 does not seem to work

**Comment by psmaker** [comment]
With the browser console, when doing a full class auto-grade I get this.

![image](https://user-images.githubusercontent.com/28868409/29956163-f4d4201e-8e99-11e7-8103-0e1c1ab48b5c.png)

With smaller "grading" jobs - like question by question, it may take a few seconds still, but doesn't seem to timeout like this.

**Comment by bnmnetp** [comment]
OK, 504 -- Gateway Timeout Error. -- I'll have to look into what we can do about this.

I noticed that even with my own class of just 20 it was noticeably slower to auto grade an entire chapter of reading assignments than it was with test classes of 4.

**Comment by psmaker** [comment]
Shadaj made me a little script that would grade student by student on the client side. So, I can kick this off and it runs a single student auto-grade through the entire list of students.

Maybe that is how to work around this where then the auto-grade is hit, it iterates on the client side through either the questions or the students.

**Comment by bnmnetp** [comment]
I have done some reconfiguring of the uwsgi server as well to provide more time.  Don't know if that will solve the problem for 120 students...
