### ISSUE TITLE
active code time display in Grade window in GMT

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1034]
I wrote a simple program in active code at 2:47 PM PST.

But when displayed in the Grading window, the scrubber says 7 hours later (GMT time).

![image](https://user-images.githubusercontent.com/28868409/29947134-f68461d6-8e5c-11e7-828e-65b46a9ee64c.png)

I'm not sure if this is an issue when it is comparing the time vs. the deadline (in PST time), but at least it is not displaying correctly to my time zone.  

I need to experiment more if it is an issue in the auto-grade deadline itself.

**Comment by psmaker** [comment]
I did a more detailed test.

Course: LHSIntroCS
Assignment: Test Exercises
Problem: lhs_2_5
Student: LHS Chrome
Deadline was set for 2017-08-31 22:40:00

I did a partially correct version before the deadline at 10:32 PM PST. 
![image](https://user-images.githubusercontent.com/28868409/29956929-440f0cac-8e9f-11e7-864a-c64b36877d3f.png)
Then I did a fully correct version at 10:48 PM PST (past deadline).

When I auto-graded LHS Chrome, the program scored 1 / 1 even though the good version was past the deadline.  I didn't really expect this - I thought maybe neither versions would get credit but this is strange nonetheless.

BTW, I may need to edit lhs_2_5 as I noticed some typos that I'd like to fix.  Hopefully this won't mess up the debug.

**Comment by psmaker** [comment]
My bad...  I'm closing this.  The 0% display is messing my mind up... #1024 

The scoring and deadline features are working.  When I set the problem to 10 points, the pre-deadline submission is 63% correct and scores a 6 / 10.

Then when I set it to ignore the deadline, then the problem scores the full 10 points.  This is the correct expected scoring per ignored deadline settings.

**Comment by bnmnetp** [comment]
OK, I'll take a look at the skulpt side and see whats up with the 0% in our graphical unittest module.

**Comment by bnmnetp** [comment]
OH, I'll bet you don't have the Python3 flag set...  That would explain it.  

Of course I can fix it in our unittest module too, but I thought everyone turned on the Python3 flag these days.

**Comment by psmaker** [comment]
Hmm... you are right, although our full intention has been to run in Python3.

When I run the activecode in the Assignment I the following. And as you say, it sure looks like Python2 - which is not what we want.

![image](https://user-images.githubusercontent.com/28868409/29991809-c99b293e-8f42-11e7-84ba-97f626a1d319.png)

When I run the same code in the Assignment Editor, I get the following. 
![image](https://user-images.githubusercontent.com/28868409/29991829-1119c036-8f43-11e7-99f6-833578e7f851.png)
We have the `:language: python` as our setting and it seems to default to python 3.

Are we missing a flag somewhere?  I'm pretty sure we did our build with the python3 button clicked.  

Or, do we need to explicitly say `:language: python3` ??  I guess I can give it a try.

**Comment by psmaker** [comment]
I'm confused now... I just tried all three.

With `:language: python3` I get the following.  Note: no Fail/Pass messages  
![image](https://user-images.githubusercontent.com/28868409/29991907-95665e48-8f44-11e7-82ce-90cd8bdfc819.png)

With `:language: python2` I get the following:   Note: no Fail/Pass messages  
![image](https://user-images.githubusercontent.com/28868409/29991921-cd46890a-8f44-11e7-995d-b4445f896da3.png)

With `:language: python` I get the following:    Note: now I get the Fail/Pass messages, but with the 0% reported...
![image](https://user-images.githubusercontent.com/28868409/29991937-19df9342-8f45-11e7-8fca-6c9ec94320f8.png)

**Comment by bnmnetp** [comment]
And yet:
<img width="682" alt="screen shot 2017-09-02 at 7 17 55 am" src="https://user-images.githubusercontent.com/51115/29995438-f6118b5e-8fae-11e7-902c-f2e93a2995eb.png">

I was referring to the python3 checkbox when you built your course.

`:language: python3` or `:language: python2` invoke a sandboxed server side python -- no ability to do graphical unit tests in the browser.

**Comment by psmaker** [comment]
I'm pretty sure (95%) that we left the python3 button checked on the initial build - but can't say with 100% certainty.

On rebuilds, I know that we leave this box checked. 
![image](https://user-images.githubusercontent.com/28868409/29996421-dff4e5ce-8fb2-11e7-97f0-fef752c292ef.png)

I see three windows that are inconsistent within the Unit 1:

This one in section 1.4 - the behavior is like Python3
![image](https://user-images.githubusercontent.com/28868409/29996487-3d2fadf4-8fb4-11e7-9386-69f525d7fd4a.png)

Later in section 1.4 - the codelens title says Python2.7
![image](https://user-images.githubusercontent.com/28868409/29996491-565f68b4-8fb4-11e7-8a5b-121cb7300f59.png)

Later in the exercise section - the codelens title says Python3.6
![image](https://user-images.githubusercontent.com/28868409/29996493-63eda82e-8fb4-11e7-8d26-02aed8301755.png)

Is there a way to know for sure how LHSIntroCS or LHSIntroCS_2017 was built?  Bottomline we would like python3 and don't want any old python2 behavior.

**Comment by bnmnetp** [comment]
You can look at the html source for any page under runestone/static/yourcourse....  search for eBookConfig and you can see how python3 is set.  Your courses are indeed set for python3.

That said, there was a bug in the unittestgui module that would cause result in 0% under python2.  I fixed that by floating the first argument to the division.  Now it should calculate properly regardless.

I built a new release of the runestone components and deployed all of that to the server.  If you want to do a rebuild of your course to get the latest.   -- clear your cache -- and reload your pages to see if the percent appears correctly now. Then let me know one way or the other.

**Comment by psmaker** [comment]
Odd thing on the eBookConfig...

On page most pages:  https://runestone.academy/runestone/static/LHSIntroCS_2017/index.html,  I see this `eBookConfig.python3 = true;`

But in the Assignment html: https://runestone.academy/runestone/assignments/doAssignment?assignment_id=191, I see do not see any eBookConfig.python3 statement. 

Maybe the Assignment html is missing something?

**Comment by bnmnetp** [comment]
OK, now we are on the same page and looking at the same problem.

Easy fix.
