### ISSUE TITLE
Problems with short answer questions

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneServer#1036]
I'm trying to grade a short answer question. There are two issues. 

The first, is that newlines are displayed as \n, which makes the student's answer very hard to read.

The bigger issue is that after I enter a score and comment, when I press Save & Next, it seems to save, but instead of going to the next student, it puts me back at the default grading page, so I have to select the assignment, question, and student again.

This only happens the first time I grade each student. If I return to the list, Save & Next behaves like it should.

Save seems to work with no problems, so I've been using it and then manually clicking on the next student.

This seems to be a problem with short answer questions. When I grade active code, both last week and this week, Save & Next works just like I expect it to.

**Comment by bnmnetp** [comment]
I have a fix for the newline problem.  It needed to be JSON.parse'd when retrieved for grading.

The second issue is confusing to me.  I don't understand this sentence:  `This only happens the first time I grade each student. If I return to the list, Save & Next behaves like it should.` . Are you saying it mis-behaves once for each assignment or once for each student?  If it mis-behaves for every student then I don't see how it would ever behave well.

Part of what you are describing makes it sound like the button is doing a form submit.  Which I've seen a few cases of in browsers where buttons default to a submit action.  but it should be consistent across problem types!  What browser are you using?
