### ISSUE TITLE
Can't log in or register

### ISSUE THREAD

**Issue by BaashaBob** [RunestoneInteractive/RunestoneServer#1037]
I was in the middle of a course on the old server. Since you moved to the new site I have not been able to log in using my old user name and password nor am I able to re-register with a new account. Every time I try either procedure it just kicks me back to the login page and I am being told I am not logged in.

**Comment by bnmnetp** [comment]
If you were in the middle of a course on the old server then you should stay there.  I did not move any courses in progress, nor did I migrate any user accounts from the old to the new for the very reason that I did not want to disrupt courses that were already going.
