### ISSUE TITLE
Embedded YouTube not working due to http / https mixed content

### ISSUE THREAD

**Issue by schellenberg** [RunestoneInteractive/RunestoneServer#1039]
The video on https://runestone.academy/runestone/static/thinkcspy/Labs/pythonshell.html is not displaying, as causes the following error to show up in the browser console:
>Mixed Content: The page at 'https://runestone.academy/runestone/static/thinkcspy/Labs/pythonshell.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/9EfGpN1Pnsg'. This request has been blocked; the content must be served over HTTPS.

Likely need to update RunestoneComponents to load YouTube via https instead of http?

**Comment by bnmnetp** [comment]
Thanks, I just got a PR from another developer that adds https as an option for the embedded vimeo and youtube videos.    It may take a couple of days for me to get it released and onto the academy site.

**Comment by schellenberg** [comment]
I assume it would take a bit of JS wizardry, but it would be nice to have the embed fail gracefully if mixed content does occur. Perhaps it would be possible to simply display a text link to the video if the browser is unable to load the embedded video? My web programming chops aren't up to making that happen, or I'd put this in as a pull request as well...

**Comment by bnmnetp** [comment]
I'm not sure either.  It would be easy on the normal ``<video>`` tag but with the embedded youtube I'm just not sure.   Anyway, there are very very few embedded youtube videos in the books, but I've been told that many high schools block youtube, so I've kept all the videos I have recorded (except those for instructors) as html5 embedded videos.
