### ISSUE TITLE
Autograding assignment shows more than 100%

### ISSUE THREAD

**Issue by dianeroux** [RunestoneInteractive/RunestoneServer#1045]
In one of my courses, F17-SH01C, when I autograde the Chapter 4 assignment, the scores for some students are more than 100%.  I have deleted and re-created the Chapter 4 assignment twice.  I also tried creating an assignment with only Readings, and another with only Problems; the problem still shows up.  I have three other courses on the Runestone server with the identical assignment that are grading appropriately.  Now it appears that the Chapter 1 assignment in the F17-SH01C is compromised as well.  It was grading properly before today.

I have included a screen shot of the Gradebook from F17-SH01C and also part of a list of the grades for the Chapter 4 assignment for one of the students.  It appears that each reading or problem is showing up more than once (up to three times?).

![gradebook](https://user-images.githubusercontent.com/32103576/30601007-d5da6a12-9d2e-11e7-8b03-7cf38af1acf3.PNG)

![ch4studentgrades](https://user-images.githubusercontent.com/32103576/30601013-dbbeb2ee-9d2e-11e7-8927-b6d8ee440922.PNG)

**Comment by bnmnetp** [comment]
Thanks, and sorry for the trouble.

I can see that the assignment itself is OK, and contains no duplicates, which leads me to think that the query that is showing this grade book report must have a little bug in it somewhere. -- may take a bit of time to track down.

**Comment by dianeroux** [comment]
Thanks for your quick reply.


By the way...  I am interested in helping out on the Runestone project.  I think it's a great resource.  Let me know how I can help.


Diane

________________________________

**Comment by bnmnetp** [comment]
OK, I tracked down the problem -- there were duplicate grades in the question_grades table which I removed and added a database constraint to prevent from happening in the future.

Have a look at your gradebook and let me know.

We would love additional help. Testing? Documenation? Code?  Let me know what where you are most interested in helping out!

**Comment by dianeroux** [comment]
Thanks for the help.  This is working for me as it should.

I am available to help with testing and documentation at the moment.  I won't have time for coding until the summer.


________________________________
