### ISSUE TITLE
Unable to login with just username and password

### ISSUE THREAD

**Issue by EricGT** [RunestoneInteractive/RunestoneServer#1047]
I have three ids and all three are reporting invalid login when I try to login with just user name and password.

I have been using them for a few weeks and now and all three are reporting invalid login.

However if I login by clicking on the g-mail icon they log me in to the site.

However once I login via the g-mail icon, there is no course selected and the only way I am able to see any course is via the Book Links drop down on the login page, (http://interactivepython.org/runestone/default/user/login) but this does not take me to the custom course and thus no record of what occurred with the course.

I hope that I just caught this during a maintenance period and everything will be working in a few hours.

**Comment by bnmnetp** [comment]
Are you sure you should be on interactivepython.org and not runestone.academy?

If not I won't be able to help you without knowing the course you are supposed to be registered for and what your usernames might be.

**Comment by EricGT** [comment]
Thanks for having me look at the URL. I don't know when it changed from
runestone.academy  to interactivepython.org as the pages looked familiar to
me, but once I did pay attention to the URL and ensured I was using
Runestone.academey and using the custom course URL (
https://runestone.academy/runestone/static/yourcoursename/index.html) as
noted on http://runestoneinteractive.org/customcourse.html
which for my course is
https://runestone.academy/runestone/static/solebury_2017_fall/index.html#
it is working as expected.
