### ISSUE TITLE
Grading Tab doesn't work for our book

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1048]
For our book LHSIntroCS_2017, when we hit the Grading Tab, it just jumps to the Bug Report page.

So, we a stuck in doing any grading at this point. 

I tried the Grading Tab in our other LHSIntroCS book, and it is OK.  So, it is strange.

![image](https://user-images.githubusercontent.com/28868409/30875904-c759de84-a2a9-11e7-8a65-1123b2adfb27.png)

**Comment by bnmnetp** [comment]
So, somehow you managed to create an assignment but foil the input and not have a due date.    I would love to know how you did that so I could prevent it in the future.

That caused about 200 stack traces to appear in my queue. My wrist was numb from all of the Apple Watch alerts I was getting in my 11:00 class today.

**Comment by bnmnetp** [comment]
I manually updated the offending assignment to have a due date, so I'm guessing that will get you access to the grading tab again.

Brad

**Comment by psmaker** [comment]
Oh, it is working again!!  Thanks so much and so sorry for your wrist pain!  I have no idea how we might have made the messed up assignment though. Closing for now.
