### ISSUE TITLE
Edit screen is blank for some test...

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1050]
This is a more recurring problem that I am seeing and I can't replicate it all the time.

But some test, like lhs_8_3 and lhs_8_3a and lhs_8_3b and lhs_8_9 have been created, but the edit screen is blank on them. The tests run just fine, but if I want to edit them, there is nothing to edit.

And I know that for the lhs_8_9, I had been editing it a few days ago, but now it is blank.

I made lhs_8_3b and tried to edit it right after.  But the edit screen was blank.
![image](https://user-images.githubusercontent.com/28868409/31212472-99810318-a955-11e7-865e-a56c56bab98c.png)

**Comment by bnmnetp** [comment]
It is entirely possible that handling unicode may be one of the most difficult things to do.  The Sepia Tone question has a lovely little unicode character in it that is causing your problem.  It is the '×' character.  Its not an x its a × (times).

I had fixed this in the function that gets the html, but not in retrieving the rst source.

Brad
