### ISSUE TITLE
scores rounded when autograded with percent correct option

### ISSUE THREAD

**Issue by haugrud** [RunestoneInteractive/RunestoneServer#1052]
I assigned a value of 2 points to an exercise and chose percent correct grading option. The exercise had 4 unit tests. When autograded the students scores were all rounded to integer values of 0, 1, or 2. Is it necessary for the rounding to occur? It appears to be in assignments.py lines 400-402

**Comment by bnmnetp** [comment]
I don't see why it does.  The database is set up to handle floats for scores, so I think it would be safe to change this.

**Comment by presnick** [comment]
Looks like this just needs one line changed, 402 in controllers/assignments.py, in _score_from_pct_correct. (Of course, this will make our new unittest for grading fail; but we have a way to update the unittest grading DB when we correct a bug in the autograder.
