### ISSUE TITLE
Exception on readings where chapters have an "/"

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1055]
I named one of the chapters in my book "Asynchronous Serial I/O". This seems to work fine, until I assign a reading from this chapter. Looking at [controllers/assignments.py line 1240](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/assignments.py#L1240), the code splits on a `/`, which produces incorrect results in this case. The basic problem, I assume, is how reading assignments are stored: in [controllers/admin.py line 1030](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/admin.py#L1030), they's just separated by a `/`. How about doing something like `r_sub_ch_info['id'] = json.dumps(ch.chapter_name, sub_ch.sub_chapter_name)` instead, with a corresponding `chapterSections = json.loads(r.name)`?

If so, one challenge is that we'll need to detect and decode existing assignments, which aren't JSON-encoded. I think that's pretty do-able, though; use a `try`/`except` on the `json.loads`, probably.

**Comment by bnmnetp** [comment]
I Think @presnick 's solution in #1075 is simpler.   

It does not allow us to have Chapter names with / in the but we can have subchapter names with slashes in them.  As chapters have a 1-1 correspondence with a folder I think that is reasonable though.

**Comment by bjones1** [comment]
Good point -- I like a simple solution. Good job, @presnick! Closing in favor of #1075.
