### ISSUE TITLE
TimeLimitError on example program

### ISSUE THREAD

**Issue by jimla44** [RunestoneInteractive/RunestoneServer#1056]
I am taking the "How To Think Like a Computer Scientist" course. Running the following example program from section 8.8.1 Sentinel Values in Active Code gave me a TimeLimitError. Is this normal behavior?

def checkout():
    total = 0
    count = 0
    moreItems = True
    while moreItems:
        price = float(input('Enter price of item (0 when done): '))
        if price != 0:
            count = count + 1
            total = total + price
            print('Subtotal: $', total)
        else:
            moreItems = False
    average = total / count
    print('Total items:', count)
    print('Total $', total)
    print('Average price per item: $', average)

checkout()

Error
TimeLimitError: Program exceeded run time limit. on line 10
Description
Your program is running too long. Most programs in this book should run in less than 10 seconds easily. This probably indicates your program is in an infinite loop.
To Fix
Add some print statements to figure out if your program is in an infinte loop. If it is not you can increase the run time with sys.setExecutionLimit(msecs)

I had to add these statments to make the program run:

import sys
sys.setExecutionLimit(10000)

**Comment by bnmnetp** [comment]
The default execution limit was set incorrectly.  I fixed this a while ago.
