### ISSUE TITLE
Unable to Grade

### ISSUE THREAD

**Issue by troberts** [RunestoneInteractive/RunestoneServer#1057]
My class in Runestone Academy is:  RobertsSRHSAPA
when I go into my Instructor page and select the Grading tab, I see 3 drop down boxes.  In the past I have set the first box to where I can select the student (this works as it did before) and the next drop down box, I usually set to select the assignment.  For some reason, when I chose the Select Assignment  nothing shows up in the list below and when I select Student, the student lists show up, but the grade button and check box regarding whether or not to grade past items does not show up.

I did rebuild the course, but nothing changed

Is there a way for me to set Runestone to grade an assignment for all students without having to to to each one?

**Comment by bnmnetp** [comment]
You should set the leftmost box to the assignment, the middle box to the question and then the right box to the student.   Do you not get the option to select assignment in the left box?  If not can you check the javascript console to see if there is some kind of error?  

I looked and I can't find any crash reports for this controller in the last few days, and it is working on my current course as well as test courses.

I took a quick look at your assignments in the database and I don't see anything wrong with them.

**Comment by troberts** [comment]
I set the left most box to student and the middle box to  assignment.  But NO assignments show up for me to select and the rest of the page does not load


[cid:3c43f861-818a-4762-940f-9762ced466da]


If I set the first one to assignment, none of my assignments show up:


[cid:1c1cdf54-be5c-4f2c-9ee7-ccb98ad6c499]?


Terry Roberts
South River High School
troberts@aacps.org<https://riva.aacps.org/owa/redir.aspx?C=85011c87c1e0453b8e568ffe5426d83b&URL=mailto%3atroberts%40aacps.org>


Good teaching is more a giving of the right questions than a giving of the right answers.
                                                                                                            - J. Albers
________________________________

**Comment by troberts** [comment]
I set them up as you requested and my screen look like:


[cid:92440623-3d9d-45cd-8028-c9972f3fee94]?


I do not see any errors,

Where is the javascript console?

TNR


Terry Roberts
South River High School
troberts@aacps.org<https://riva.aacps.org/owa/redir.aspx?C=85011c87c1e0453b8e568ffe5426d83b&URL=mailto%3atroberts%40aacps.org>


Good teaching is more a giving of the right questions than a giving of the right answers.
                                                                                                            - J. Albers
________________________________

**Comment by troberts** [comment]
Found the javascript console under developer tools:  not sure if this helps


Uncaught SyntaxError: Unexpected token
 in JSON at position 2500
    at JSON.parse (<anonymous>)
    at pickedAssignments (admin.js:487)
    at showColumn1 (admin.js:617)
    at HTMLSelectElement.onchange (grading:259)?



Terry Roberts
South River High School
troberts@aacps.org<https://riva.aacps.org/owa/redir.aspx?C=85011c87c1e0453b8e568ffe5426d83b&URL=mailto%3atroberts%40aacps.org>


Good teaching is more a giving of the right questions than a giving of the right answers.
                                                                                                            - J. Albers
________________________________

**Comment by bnmnetp** [comment]
Thanks, none of your screen shots are coming through to github.  It looks like you are replying by email?

The information from the Javascript console is a good clue.

**Comment by bnmnetp** [comment]
OK, I **may** have tracked it down.   I found a problem with the id of one of the questions in your assignment. So I fixed it in the database, which may let you get further.

IF you are still having a problem it would be really helpful if you could go back to the javascript console and type ``assignmentinfo`` at the prompt.  This should give you the string that is causing the syntax error in the above.  If you could cut and past that long string here that should be enough to figure out the problem.

Thanks,

Brad

**Comment by troberts** [comment]
Yes, I was replying via email.  Your fix appears to have done the trick.  

Many thanks

**Comment by bnmnetp** [comment]
Hooray!!
