### ISSUE TITLE
sign in via google not working on interactivepython.org

### ISSUE THREAD

**Issue by blackstartrade** [RunestoneInteractive/RunestoneServer#1059]
Message "Redirecting to http://interactivepython.org/runestone/default/user/login"

**Comment by rjwehner** [comment]
I am also unable to use my google account login.  The pop-up window shows a loading animation then simply says "Internal Server Error" in courier font.

**Comment by bnmnetp** [comment]
We have been using the Janrain service to handle social logins.  However the success of Runestone has meant that the cost of using Janrain has become prohibitive.  In the near future all new accounts will be redirected to https://runestone.academy we are working on free alternatives for social auth on that new server.
