### ISSUE TITLE
Database Initialization

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1069]
I am proposing that we write a python script that takes care of the first time initialization of lots of things in the Runestone server database setup.

1. There are quite a few indices that I have created manually for many tables that you cannot specify using DAL
2. There are a number of tables, such as `courses` that should be populated with some initial data.
3. Running a script `python web2py.py -S runestone -M path/to/script.py` is a LOT clearer thing to do for initializing the database and making sure all tables are built rather than saying you have to start runestone and bring up the home page.
4. This will be a small performance gain as we won't need to do these one time checks on every request.

If you know of one of these initializations please add it to the list as a reply.

tagging @presnick @bjones1

**Comment by bjones1** [comment]
Great idea! Something that correctly deals with the case of missing/corrupted tables would be also be great. Mainly, code to automate the process at https://github.com/RunestoneInteractive/RunestoneServer/blob/master/README.rst.

Of course, the ultimate solution is migrating all this mess to Flask :)...

**Comment by presnick** [comment]
I think we should also have a flag for *resetting* the database. This would delete everything from databases/ and would run dropdb.

Once we are in a clean state, I think the shell script can run craetedb, just like it does in our testing script.

In the py file, we could have:

- create static rows for courses table
- create an authorized user who is the instructor for the bogus course.
```
userinfo = dict(first_name='test', last_name='instructor', email='foo@bar.com', password='password')
user = auth.get_or_create_user(userinfo, update_fields=['email', 'first_name', 'last_name', 'password'])
db.user_courses.update_or_insert(user_id=user.id,course_id=course_id)
db.course_instructor.update_or_insert(instructor = user.id, course = course_id)

**Comment by presnick** [comment]
If the python file is called install.py, perhaps it could import local_install.py. That would be a file that isn't committed to the repo, analogous to 1.py, which could create additional rows in the courses table, and rows in the lti_keys table if desired.

**Comment by bnmnetp** [comment]
I'm thinking of a command like `rsmanage` . with subcommands like
* `initdb`  -- makes sure the database is initialized and any pre-populations are done including local options as suggested by @presnick 
* `init <book>` -- clones a book from github, creates a db entry, builds and deploys the book
* `run` -- starts up a development web2py dev server with scheduler
* `resetdb` -- cleans out the database, drops all the tables, and deletes all files from databases/
* `checkconfig` -- Makes sure all environment variables are set, the database is accessable, and web2py is where we think it should be. --- This will be called by
* `inituser [--instructor coursename] [--fromfile filename] ` -- add user(s) to the database

I think I like this architecture as it allows for modular expansion and automation of different admin tasks.   I was initially thinking only of the `initdb` subcommand, but the more we can make the rest of it drop dead easy the less time we'll spend helping people get set up, and that might even attract more people to help with development in the end.

**Comment by presnick** [comment]
Looks great. With `inituser --fromfile` you'll finally have a way to give teachers the thing they keep asking for, prepoluating accounts!

I especially like `init <book>`. Instead of just allowing a book name, how about allowing any github url for a book?

**Comment by bjones1** [comment]
Wow, these are all great ideas. Good work!

**Comment by bnmnetp** [comment]
@presnick for `init <book>` I was thinking that if the book name started with https then pulling from github would be the behavior, but if it was a standard name like thinkcspy then we would automatically fetch.  But now that I type that, it might be easier to just require a URL.

As I look over the README it seems that a lot of the complexity is in installing postgresql.  As I look through the controllers, it appears that there are only 20 places where we are using executesql instead of the DAL db query syntax.  Most of these 20 could easily be re-written to use the DAL syntax.   In the far back corners of my memory I think I recall there is ONE query that we wrote that used some postgres specific syntax.   I think its in the getCorrectStats function in ajax.py (there are definitely alternatives to redo that)

It might be worth the effort to do some testing to bring up a development server with sqlite.  That would definitely remove a whole class of hassles for newbies.

**Comment by bjones1** [comment]
I agree -- with the database easy to set up, the highest barrier is installing postgres. I've actually used sqlite, but found it incredibly slow. There's tuning that would make it faster, but that would take some investigation to do correctly (unless either of yall has played with this before).

I do like the idea of running all possible queries through the DAL, since that makes it easier to switch databases. Eventually, we could hopefully port this to SQLAlchemy...

**Comment by bnmnetp** [comment]
@presnick 

I have the user creation stuff working (though haven't done the csv import just yet.  But now that I can create users the hard part is done.

I've been thinking about the book building side, and I think at least to start I'm going to limit it to one of the well known books that we pre-populate in the `initdb` process.  This should not be a replacement for building a book through the web interface, nor do I want to get into trying to programmatically edit some arbitrary pavement.py file to change the project name.

I think being able to say `rsmanage build thinkcspy`  where we clone thinkcspy, from RunestoneInteractive,  build and deploy it would be a nice win and would go long way toward eliminating user errors in getting a first book up and running.

But, maybe you had a different flow in mind for building any old book and giving it some arbitrary name?

One step in a more general direction would be to allow the user to specify a coursename we could verify that the coursename given matches the project name in the cloned book and if they match then we could go forward with populating the database as well as building the book.

**Comment by presnick** [comment]
I agree that any github repo is probably too risky.

However, I do want to be able to grab something other the five standard repos would be good. In particular, I'd like to be able to script something so that after I deploy using a Dockerfile, I can have an initialization script that does a runestone deploy of a custom book and create and create a course matching it.

How about `rsmanage insert coursename basecoursename`? It could check that there is something with that coursename already deployed.

**Comment by bnmnetp** [comment]
@presnick 

1.  I've added another command called `addcourse` that takes a name and prompts you for all of the information needed to add a row to the `courses` table.  It checks to make sure its not already there. etc.  And I'll add command line flags for all the fields so it can be scripted.

2. The `build` command will take a course_name and a URL to a github repository.  
   a. It will check to be sure that the course exists in the database, if not it will have you add one first. ¥  
   b. Next it will clone the repo into our build directory.  
   c. Then it will do `from pavement import project_name` and compare project_name to the course_name if the two match then the build will go on.  If the names do not match it will abort and tell you to fix `project_name` in the pavement.py file in the repo.

I think this is a very solid first step.


¥ - I will make a simple enhancement to rsmange that lets you chain commands so one could do `rsmanage addcourse --name testcourse --rest-of-args build --course testcourse --repo http://blah`   this would first add the course and then if successful build it using the build command.  This is just like the runestone command `runestone build --all serve --port 8083`

**Comment by bnmnetp** [comment]
OK, I invite you all to give this a spin:
```
Usage: rsmanage [OPTIONS] COMMAND [ARGS]...

  Type subcommand --help for help on any subcommand

Options:
  --verbose  More verbose output
  --help     Show this message and exit.

Commands:
  addcourse  Create a course in the database
  build      Build the book for an existing course
  initdb     Initialize and optionally reset the database
  inituser   Add a user (or users)-- coming soon
  run        Starts up the runestone server and optionally...
  shutdown   Shutdown the server and any schedulers
```

All of this should work, except for loading a batch of users from a csv file.

Brad

**Comment by yarikoptic** [comment]
I am the newbie mentioned above, and wondered if it would be possible to support sqlite as the underlying DBM - I think it should be enough for any small scale (a class) deployment and would be much easier to try on.
Myself I just discovered the Runestone and I would have no problem setting up the postgresql DB if I decide to go with it, but for evaluation etc, being able to quickly run a server with sqlite backend would be super sweet -- may be it is already possible due to enough abstraction and just docs need to be adjusted?

**Comment by bjones1** [comment]
I used to run Runestone builds using sqlite. but it was terribly slow compared to Postgres. I'd invest the time to use Postgres.
