### ISSUE TITLE
Unit test coverage

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1070]
We have recently begun a project to get a good set of unittests created for the Runestone Server.  Its great to have more contributors coming aboard but its increasingly difficult for me to accept PR's without a baseline of unittests to rely on.  I ran a coverage report for the small set of tests we have written over the last week and it shows we have a LONG way to go.  If you have been looking for a way to contribute to Runestone this would be a great opportunity to dive in. If you look at our examples you will see they are pretty easy to write, and I've created a test database with assignments and students and grades and lots of data that we can use to test against.  I would love to see us get above 90%.  The highest priority for work is in the controllers folder:

- [ ] admin.py
- [ ] ajax.py
- [ ] assignments.py
- [ ] dashboard.py
- [ ] default.py
- [ ] designer.py
- [ ] proxy.py

This is a pretty big project but even if you only contribute a test for a single function in one of the above files it will be a huge help.  If you are pretty new I think you can get a pretty good idea of what to do by looking in tests/test_ajax.py This file contains a number of tests for various functions in the ajax.py controller but there are many more to go.  I think I have a list of them in comments, so it will be pretty easy to pick them off one at a time.  there is also a script `run_tests.sh` that runs all of the unit tests.  Also if you make a pull request with a new test I have set up Travis-CI to automatically run the unittests for all new PR's.

```
# Coverage Baseline
Name                                                        Stmts   Miss  Cover
-------------------------------------------------------------------------------
applications/runestone/controllers/admin.py                   814    814     0%
applications/runestone/controllers/ajax.py                    612    463    24%
applications/runestone/controllers/appadmin.py                264    264     0%
applications/runestone/controllers/assignments.py             720    620    14%
applications/runestone/controllers/coach.py                    51     51     0%
applications/runestone/controllers/dashboard.py               135    135     0%
applications/runestone/controllers/default.py                 228    228     0%
applications/runestone/controllers/designer.py                 97     97     0%
applications/runestone/controllers/everyday.py                 11     11     0%
applications/runestone/controllers/feed.py                     24     24     0%
applications/runestone/controllers/lti.py                      74     74     0%
applications/runestone/controllers/mygroup.py                 137    137     0%
applications/runestone/controllers/proxy.py                    47     47     0%
applications/runestone/controllers/sections.py                 82     82     0%
applications/runestone/models/0.py                             39      5    87%
applications/runestone/models/1.py                             18      3    83%
applications/runestone/models/db.py                            95     27    72%
applications/runestone/models/db_dashboard.py                 306    247    19%
applications/runestone/models/db_ebook.py                      16      0   100%
applications/runestone/models/db_ebook_chapters.py             11      3    73%
applications/runestone/models/db_ebook_groups.py                4      0   100%
applications/runestone/models/db_sections.py                   31     18    42%
applications/runestone/models/db_wizard.py                      0      0   100%
applications/runestone/models/db_wizard_populate.py             3      1    67%
applications/runestone/models/grouped_assignments.py          321    282    12%
applications/runestone/models/lti.py                            1      0   100%
applications/runestone/models/menu.py                           6      0   100%
applications/runestone/models/modulesmodel.py                   2      0   100%
applications/runestone/models/questions.py                      4      0   100%
applications/runestone/models/scheduler.py                     70     55    21%
applications/runestone/models/user_biography.py                 1      0   100%
applications/runestone/tests/make_clean_db_with_grades.py       9      9     0%
applications/runestone/tests/test_ajax.py                      67      0   100%
applications/runestone/tests/test_assignments.py               15      0   100%
-------------------------------------------------------------------------------
TOTAL                                                        4315   3697    14%
```

**Comment by Utsal20** [comment]
I was writing unit tests for some functions in admin.py. I am assuming that we get the data from the database and test against that, but I am not getting results when I run select queries. I am using Ubuntu 16.04 and followed the instructions in readme.

**Comment by bnmnetp** [comment]
Have you run the tests once to load the database?  The name of the database that the script creates is runestone_test. I see you typed runestone-test instead but that should give you an error.  Also you are missing a semicolon at the end of your select statement so that could also explain why you are not seeing any results as psql is expecting you to finish the query.

**Comment by Utsal20** [comment]
Yes, that explains it. It is working now, thank you. One of the functions I was writing the tests for is _get_questions_id() and what I was planning on doing is first using a name that does not exist and assertEqual that with None and then using a name that does exist and assertEqual that with correct value. Would that be enough?

**Comment by bnmnetp** [comment]
Yes, that will test both options, thanks.

**Comment by Utsal20** [comment]
When I try to run the individual test file using: python web2py.py -S runestone -M -R applications/runestone/tests/test_admin.py

It gives the following error. Do you have any idea of what might be going on?
    rv = self.cursor.execute(command, *args[1:], **kwargs)
ProgrammingError: relation "useinfo" does not exist
LINE 1: DELETE FROM "useinfo" WHERE ("useinfo"."div_id" = 'unit_test...

**Comment by bnmnetp** [comment]
Do you have your WEB2PY_CONFIG and TEST_DBURL environment variables set correctly?

**Comment by Utsal20** [comment]
I have set WEB2PY_CONFIG=test and TEST_DBURL=postgres://myusername:pw@localhost/runestone_test
which I think are correct. Must be the way I set up 1.py then?

**Comment by Utsal20** [comment]
I think I figured it out. I had different database connection strings in 1.py and the environment variable. Thank you!
