### ISSUE TITLE
Control whether migrations run with environment variable

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#1071]
We are moving towards more control over migrations. Currently, in db.py we have:

```
    if os.environ.get("WEB2PY_CONFIG","") == 'test':
        db = DAL(settings.database_uri,migrate=False,migrate_enabled=False)
    else:
        db = DAL(settings.database_uri,fake_migrate_all=False)
```
Because our Docker-based deployment is not saving the databases/ folder between deployments, I would like to run migrations only when I explicitly ask for them.

How about this?

```
    if os.environ.get("WEB2PY_CONFIG","") == 'test':
        db = DAL(settings.database_uri,migrate=False,migrate_enabled=False)
    else:
        db = DAL(settings.database_uri, fake_migrate_all=os.environ.get("WEB2PY_FAKE_MIGRATE", False), migrate=os.environ.get("WEB2PY_MIGRATE", True), migrate_enabled=os.environ.get("WEB2PY_MIGRATE", True) )
```

**Comment by bnmnetp** [comment]
I'm in transit today, but on Slack.   I think the default for migrate should be 'runestone' instead of True.  On the constructor, `migrate=` provides the default value, which we provide an all our tables for the migrate parameter there.  Defaulting this to migrate might help with the common problems we run into with the session table.

**Comment by presnick** [comment]
I will try it with migrate='runestone' and see if it generates file names of the form runestone_
I'm not sure it works that way.

**Comment by presnick** [comment]
Can't provide migrate='runestone' and have it used as a prefix, although that does work when creating a Scheduler. 

I did it with migrate=False so that if there were ever a new table without explicit metadata file it would just not get migrations (until the model include a migrate=...)
