### ISSUE TITLE
Ability to include datafiles in assignments

### ISSUE THREAD

**Issue by aerenchyma** [RunestoneInteractive/RunestoneServer#1077]
Currently, when an activecode uses `:datafile:` (or an `:include:`), it is grabbing from a div id on the same page, not from the database. 

In the current assignment interface, this can be fixed for an `include` to include the activecode you wish to include in the same assignment, but doesn't work for `:datafile:`. 

A solution may be to have datafiles save themselves to the database so that we can “read” them with an API call.

(May be able to apply the same logic to `include`ing code, but that may be a related issue.)

**Comment by bnmnetp** [comment]
I just pushed a fix for this to RunestoneComponents
