### ISSUE TITLE
Create new book

### ISSUE THREAD

**Issue by libremente** [RunestoneInteractive/RunestoneServer#1078]
Hi all, 
I didn't find any relevant information on creating a new book. There was a `README_new_book.rst` file but it's gone (even if the README.md still points to it) as well as a new project template folder. Which is the best way to start my own book?

Thanks

**Comment by bnmnetp** [comment]
Hi,

Please have a look at the README in the RunestoneComponents repository.  It will take you through starting your own book step by step.

Brad

**Comment by libremente** [comment]
Ok, I though there was another resource available. Should I remove the misleading information from the README file? I can make a PR.

Thanks

**Comment by bnmnetp** [comment]
That would be very helpful.  Thanks.
