### ISSUE TITLE
Chapter 2: Question ca_id_ints

### ISSUE THREAD

**Issue by sjjackson** [RunestoneInteractive/RunestoneServer#1080]
This text question has an error in it.  It asks to identify the variables that are integers.  The answer specifies the variable total_secs should be one of 4 highlighted variables that are integers.  However, this variable has never been assigned in the code displayed.  

Best, 
Sandra Jackson

**Comment by bnmnetp** [comment]
I just accepted a PR for the thinkcspy book that fixes this one.
