### ISSUE TITLE
14_3_1 Genuine question - easy fix?

### ISSUE THREAD

**Issue by MrShaunMcG** [RunestoneInteractive/RunestoneServer#1081]
I've just attempted this question by way of changing and running the code each time and none of the options seem to work. I have attached a screenshot. Now I will accept **full** stupidity responsibility but I really think there is a fault here. I have included a screenshot so you can see clearly what is going on. Selecting '17', whilst correct is misleading as it **doesn't** fill up the top half of the screen. Have I misread the question?
<img width="1332" alt="screenshot 2018-01-13 09 07 10" src="https://user-images.githubusercontent.com/33232546/34904774-ac27f506-f844-11e7-9b52-102f12521569.png">

**Comment by bnmnetp** [comment]
My guess is that the default window size  changed somewhere along the way and became 400 rather than 320.  You could verify this by printing the space.window_height()

To ensure this works into the future pass the height and width for the window to the Screen constructor.

**Comment by MrShaunMcG** [comment]
Okay 👍 thanks! So it's not really a bug, more of a silent problem in it'self :)
