### ISSUE TITLE
toctree

### ISSUE THREAD

**Issue by MrShaunMcG** [RunestoneInteractive/RunestoneServer#1082]
I'm unaware whether or not this is visible to students but I can certainly see it on my student progress panel. I don't understand what it is. Is it something I should ignore, or being chasing the students to complete something? The screenshots are from 2 different students. toctree appears differently on different students progress panel. All my courses are in the CS Principles book.

<img width="500" alt="screenshot 2018-01-17 15 14 54" src="https://user-images.githubusercontent.com/33232546/35050190-235b76fe-fb9a-11e7-9b30-2a88ee495eed.png">
<img width="560" alt="screenshot 2018-01-17 15 15 25" src="https://user-images.githubusercontent.com/33232546/35050195-2631af9c-fb9a-11e7-9e13-77d1301dcb8f.png">

**Comment by bnmnetp** [comment]
Toctree represents "table of contents tree" it's how we structure the books by including separate source files for different sub chapters.  However it should not be visible.

Its distracting, but its something you can ignore.
