### ISSUE TITLE
Creating new exercise in Recursion Chapter does not show up in Browser Tree

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1084]
We are creating new exercises to the Recursion Chapter of the ThinkCSPy book. (lhs_15_1 for example)

After adding it, it does not show up in the Tree Browser. 

![image](https://user-images.githubusercontent.com/28868409/35116524-9d9ba6a4-fc40-11e7-96ca-57b711c41ae0.png)

If we Search for all exercises in the IntroRecursion chapter, the exercises show up.

![image](https://user-images.githubusercontent.com/28868409/35116457-68a507f6-fc40-11e7-83c0-416ab52ff412.png)

This behavior is unique to the Recursion chapter.  All other exercises added to previous chapters were showing up in the Browse Tree.

**Comment by bnmnetp** [comment]
OK, I know whats going on here.  There is an assumption in the code that allows you to write your own exercises that they are going to go into a subchapter for the selected chapter called `Exercises`

I had thought that I had worked around this by adding an Exercises chapter everywhere one was needed.  I guess I missed the recursion chapter.

A better solution would be to have a dropdown that allowed you to choose the sub-chapter when you write the question.  I don't think this would be a hard one.
