### ISSUE TITLE
exam question code and comments different

### ISSUE THREAD

**Issue by evelynzayas** [RunestoneInteractive/RunestoneServer#1085]
Hello,

On page https://runestone.academy/runestone/static/StudentCSP/CSPTuring/exam1a2.html,
on the 5th question: 2-5-5: What shape would the following code draw?

The code will have the turtle draw a rectangle but the comments that go along with each line infer that a square is being drawn. 

It's a good teachable moment but not sure if this was on purpose :-)

**Comment by anujinm** [comment]
Comments changed
![1085](https://user-images.githubusercontent.com/30271091/35244945-bbf43b3c-ff76-11e7-947b-c5dd9705a003.png)
