### ISSUE TITLE
Auto-grading not updating score even if unit test passes 100%

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1088]
Course: LHSIntroCS_2017
Assignment: Exercises - Unit 12 Additional
Question: lhs_12_17
Student: Anisha Kirpekar

We are writing exercises where the unit testing is initially "disabled" and the unit test will score a 0%.

I auto-graded an assignment with the unit testing "disabled" and all the auto-grades were scored as a 0. (I forgot to enable the unit tests before running the auto-grade.)

Then I updated the unit test and "enabled" the testing so that it will run the actual test code.

But even when a test scores 100%, the grade is not being updated. It still is 0.

The setting was % correct w/ Best Answer.

Here's a picture of this.

![bugpict](https://user-images.githubusercontent.com/28868409/35370520-27d6bd02-0143-11e8-9338-678185407a33.png)

**Comment by bnmnetp** [comment]
Sorry, I don't understand what you mean that the unittests are "initially disabled". Can you say more?

Also what happens if you remove the comment autograded? Save, and then try again?

**Comment by psmaker** [comment]
In our .rst, we have the following code in the unit test.

When the students are working on the code, we have the flag set to True, then when the assignment is ready to be graded, we set SelfTest to False.

This is what I meant by "disabling" (student must self-test) and then "enabled" (when we want to grade the exercise) the unit test.

```
def testOne(self):
            SelfTest = True
            if (SelfTest):
                self.assertEqual(0,1,"Auto-testing if OFF - you must check the program yourself for now")
                return
```

**Comment by bnmnetp** [comment]
OK, this is interesting.  It seems vaguely related to a problem you reported previously about modifying an assignment or a question in an assignment.  But this seems concrete enough that I should be able to reproduce.

@presnick @bjones1 Any ideas???

**Comment by psmaker** [comment]
I tried clearing the "autograded" comment. Saved it. Ran the Auto Grade again on this one person.

And nothing changed - even the "autograded" comment is still not there.

![bugpict2](https://user-images.githubusercontent.com/28868409/35371148-42667348-0147-11e8-8483-0583dd3d6372.png)

**Comment by presnick** [comment]
A few ideas to explore:

1. If there is a question_grade row and the comment is not "autograded", I think it won't run the autograder on it, for fear of overwriting a manual grade.
2. I'm not sure what their mechanism is for changing the code to set `SelfTest = False`. Perhaps that is creating a new row in the questions table, or somehow not being associated with the assignment?
3. After you run autograder on just one student-question, it may not reload the info. I remember I used to sometimes click to another student and then back to the student I had run the autograder on, in order to see the result. Might be worth checking if that's the issue.

**Comment by bnmnetp** [comment]
OK, here is the problem, modifying the unit tests after the deadline is not a use case we thought about.

The autograde mechansim looks in the database to find the last time that the **student** ran the problem (before the deadline if that box is checked) and uses the autograde results from that run.

The autograder does not actually RUN the students code after the fact.  So, changing the tests does not do anything as far as the autograde process is concerned.

What you did seems perfectly logical, and it took me a while to realize the issue.  Unfortunately I don't think there is a super quick fix for this.

@presnick definitely a reasonable use case we ought to think about supporting.

**Comment by presnick** [comment]
Of course; should have thought of that... 

Don't see an easy solution for that. We don't even run the code on the server right now, so we can't easily run it at autograding time. One possibility would be to have public tests and hidden tests written into the directive, with the students only seeing the results of public tests but the results of hidden tests getting recorded in the DB.

**Comment by psmaker** [comment]
> 2. I'm not sure what their mechanism is for changing the code to set SelfTest = False. Perhaps that is creating a new row in the questions table, or somehow not being associated with the assignment?

I go back to the Assignment tab and Edit the problem (changing one word True to False), generating the new HTML view and then saving the edited problem.

Now here is something to consider... When `SelfTest = True`, there is a **single** assert statement in the unit test that will always trigger. But, when `SelfTest = False`, we generally have **more than 1** assert statement. I'm not sure if that could be an issue. You mentions some "question table" - not sure if this is associated with the number of assert statements in the unit test.

> 3. After you run autograder on just one student-question, it may not reload the info. I remember I used to sometimes click to another student and then back to the student I had run the autograder on, in order to see the result. Might be worth checking if that's the issue.

I'm have tried leaving the Grade tab completely, coming back to it to try to Auto-Grade. Still nothing happens to the score.

**Comment by bnmnetp** [comment]
@psmaker see my answer, non of this really applies. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by psmaker** [comment]
OK, this now perfectly describes the situation that we have been seeing today and also last semester on the "in-class" programming test where we only turned on the unit test after the assignment due date had past.

**Comment by psmaker** [comment]
So, the temporary "fix" is to have our student TA manually grade each of these after we have turned on the unit testing... This will work for us in the time being.

**Comment by bnmnetp** [comment]
Yes!   I'm really glad we finally have a good explanation for both of these issues.

What do you think of Paul's idea of having public and private tests?  Both sets of tests would always run, but the student would only see the public results.  During the autograding process both sets would be calculated into the total.  -- I think in any case the current behavior should be made more clear so others won't run into this.  This would be my preferred approach, at least for now, but we ought to think this through in case there are other similar use cases that would not work. 

The other option would be to try to re-run the code on the server at grading time, but this has a number of things we would need to keep in mind:

1.  We would have to run the code using 'real' python.  I think this would be fine in 99.9% of the time, but I worry that there could be some small difference between Skulpt and real python that would cause trouble.

2.  We would have to devise a way to make sure that the most recent version of the unit tests were run during testing, not the version saved when the student last ran the test.  See #1087 

3.  Python only?? -- Maybe we could harness the JOBE server for this to support other languages.

**Comment by psmaker** [comment]
I like the idea of public and private tests. That way I would not need to change the test to turn it on and off all the time!

There are times when I mess up and want to add/change the unit test code - but this is not the normal situation, so in this case, it is OK to have to manually re-run and manually re-score the tests.
