### ISSUE TITLE
using python3 is hardcoded in the grading interface

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1091]
I thought I had fixed this last summer, but line 1653 in admin.js still has

```
opt.python3 = true;
```

The solution to this is to set  `eBookConfig.python3` in the grading.html template and then update admin.js to use the value from ebookConfig rather than hardcoding to true.

**Comment by Utsal20** [comment]
I have made the changes in my fork. Would you mind checking them out before I make a pull request? Thanks.
[https://github.com/Utsal20/RunestoneServer/commit/3d325e3b6c3ee1ec26c5ac9d727e4eaaffa2b4de](url)
[https://github.com/Utsal20/RunestoneServer/commit/b278b77860acefb6661620073e4165cf2162b9ed](url)
