### ISSUE TITLE
Compute with Numbers

### ISSUE THREAD

**Issue by pvsbarrios** [RunestoneInteractive/RunestoneServer#1092]
The Audio Tour is not working.

**Comment by bnmnetp** [comment]
There are many audio tours in many different books.  You are going to have to give us more to go on than this if you want us to fix the problem.

**Comment by valmonaco** [comment]
Not sure if it is related, but there is an open issue that identified an overall issue with audio tours in the CS Principles: Big Ideas book related to a http vs https URL construction. https://github.com/RunestoneInteractive/RunestoneComponents/issues/484
