### ISSUE TITLE
Incorrect parameter when grading

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1093]
I think I've tracked down a subtle bug in assignment grading, but wanted to confirm. I'm getting an `IntegreityError` in [_save_question_grade](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/assignments.py#L666). Tracking this down, the `db.question_grades.update_or_insert` call has `useinfo_id = useinfo_id`, and the ID being passed is invalid. Per the [question_grades table](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/models/grouped_assignments.py#L545), this should be an entry in the `useinfo` table. However, the ID passed is actually an ID from whatever table held the relevant answer (in my case, `fitb_answers`): [here](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/assignments.py#L662) is the call; at this point, `id` is set from a row of `results`; `results` comes from a `_scorable_xxxx` function, which returns a question-specific table, not a `useinfo` entry. For example, [here](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/assignments.py#L607) is the call for a fill-in-the-blank question, which [queries](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/assignments.py#L526) the `fitb_answers` table.

So, what's the best fix? Is this field (which has obviously been invalid for a bit) even used anywhere? Finding the correct `useinfo` id seems non-trivial to me, since there's no direct ID in each `xxx_answers` table back to `useinfo`. Searching the code, I can only find `useinfo_id` being used by `_save_question_grade`. For a temporary fix, I set `useinfo_id=None` in the update, and can now at least grade assignments without an exception.

**Comment by bnmnetp** [comment]
I have no idea what the useinfo_id field is used for. I’ve wondered for a while but never dug into it.

**Comment by bjones1** [comment]
Unless @presnick has a specific purpose, let's set it to `None` to avoid errors.

**Comment by presnick** [comment]
I think there was some vague notion that we wanted to have a record of what run was graded. It is probably left over from when autograding only worked on activecodes and thus we didn't notice the problem. I agree that setting it to None is the best quick solution.

**Comment by bjones1** [comment]
@bnmnetp, do you want a PR for this, or will you just make the edit yourself?

**Comment by bnmnetp** [comment]
I would be happy to get a PR.

**Comment by bjones1** [comment]
Closing this for the fix in #1094.
