### ISSUE TITLE
Assignment feature of grade book not working

### ISSUE THREAD

**Issue by mcddanielle** [RunestoneInteractive/RunestoneServer#1095]
I cannot use the grade book to view my students work.  I've included a screenshot of what I see, with my students names crossed out.  This is most definitely not what the help documentation indicates I should see ([link](http://interactivepython.org/runestone/static/sigcse2017/CustomCourses/gradeAssignment.html)).  

![gradebook](https://user-images.githubusercontent.com/25964846/35588605-0342fc40-05b6-11e8-9e47-8f9db3625782.jpeg)

**Comment by bnmnetp** [comment]
This is not what I see when I look at the interface for my own course.  What browser are you using?  When you pull down the assignment menu what do you see?  You should see a list of the assignments you have created.  Then you select and assignment, and then a question.   Can you bring up the javascript console in your browser and tell me if you see any error messages or other information that looks like it might be helpful?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bnmnetp** [comment]
I just made myself an instructor for your course, and I can see the list of assignments, and when I select an assignment I can select a question.  As far as I can tell things are working fine.  Please tell me more if you can't get it to work.

**Comment by mcddanielle** [comment]
Hi Bradley,

I've tried Safari and Firefox and Chrome and saw the same lack of
information.  I could see student names (as in the image I posted in the
help forum) but nothing else.  However, I checked it just now from my home
and it works great.  Is it possible the network security on Pacific
University's campus was blocking the functionality of the interface?

Thank you for looking into the problem.  Tomorrow when I'm back on campus
I'll see if I can find anything useful in the javascript.

Best,
Danielle

**Comment by bnmnetp** [comment]
Anything to report?  I'm skeptical of a network security issue because this is implemented so that all of the data needed for those three panels is loaded at the time we load the initial page.  So if its still not working for you at school then hopefully there will be a javascript error that can give us a clue.

**Comment by mcddanielle** [comment]
No.  Strangely it has been working well at school the last 24 hours.  I
don't know what the change was, but it was definitely NOT working before I
submitted the bug report.

Thank you for your help.  If the error occurs again, I will let you know.
