### ISSUE TITLE
CSPrinciples Module Chapter Code with Images

### ISSUE THREAD

**Issue by pvsbarrios** [RunestoneInteractive/RunestoneServer#1099]
I am using the Runestone Academy to learn about coding. This particular module is not allowing me to play the Audio Tour. I am using MacOS Sierra 10.12.6. I am trying to run the Audio Tour for the Code with Images Chapter in CS Principles. I appreciate your help with this.

**Comment by bnmnetp** [comment]
Yes, this is a known issue that I am working on now.  We moved the main site over to https, and some browsers are not happy about serving audio files from plain http.   We are working on it.

**Comment by pvsbarrios** [comment]
Thank you!
