### ISSUE TITLE
CS Principles Chapter 3 Exercises

### ISSUE THREAD

**Issue by pvsbarrios** [RunestoneInteractive/RunestoneServer#1100]
Hi. I really am enjoying using your book to learn about computer science. I had a couple of glitches: 
1. The survey came before the chapter 3 exercises, so I wasn't able to give feedback on the Chapter 3 exercises.
2. As a result of the survey coming before the Chapter 3 exercises, I gave a good review of chapter 3, but the exercises have a major glitch. 
a. When I click on Discussions, it doesn't open any discussion. It simply goes to the next exercise. 
b. I am also unable to click on Comments. 
c. These two issues make it difficult to know whether I successfully completed the exercises or not. This is not only discouraging to me as a learner, but also as a teacher, since I know that my students may be frustrated by not being able to tell if they are completing the exercises within acceptable parameters. 

I am using MacOs Sierra 10.12.6. Don't know if there are known problems with this operating system. 

Thanks for any help you can give.

**Comment by ericsonga** [comment]
Which ebook are you using?

**Comment by pvsbarrios** [comment]
CS Principles : Chapter 3 exercises
