### ISSUE TITLE
How to make interactive books in other languages?

### ISSUE THREAD

**Issue by ofenerci** [RunestoneInteractive/RunestoneServer#1102]
I am interested in writing  a book in NetLogo, which is a java based language (https://ccl.northwestern.edu/netlogo/). I wonder it is possible to extend Runestone into other computer languages.

**Comment by bnmnetp** [comment]
@ofenerci 

We already supportPython,  javascript and html in the browser.  We support Java and C++ through a sandboxed environment running on a server.  From my few minutes of looking at netlogo, I would say it depend on the state of the Javascript/HTML5 version of NetLogo.

My approach would be to create a Runestone Component that would allow you to embed an instance of the Javascript NetLogo.  If you are interested in pursuing this let me know and we can arrange a time to talk in more detail.

Brad

**Comment by pearcej** [comment]
Hi Brad, Lets chat about the best way to do the translation to C++.

**Comment by ofenerci** [comment]
Dear Brad, 
my interest on Netlogo is at educational level and not having any kind of development experience on Netlogo, my help would be limited. I could only help re-write some free books on Netlogo by using Runestone.
