### ISSUE TITLE
Test data carrying over from one set of practice questions to another

### ISSUE THREAD

**Issue by UnrelatedString** [RunestoneInteractive/RunestoneServer#1106]
On the tests on [Chapter 24 - PRACTICE EXAMS](https://runestone.academy/runestone/static/StudentCSP/CSPPracticeQuestions/toctree.html), when I try to open another set after already dong one set, it thinks I have already done the other set with the same time and correctnesses as on the previous.

**Comment by ericsonga** [comment]
I will check into it.
