### ISSUE TITLE
Question Error

### ISSUE THREAD

**Issue by arcurroy** [RunestoneInteractive/RunestoneServer#1107]
This is not a bug report in the technical sense, but I believe Question 14-4-15 on Untimed Practice Test 3 in the AP CS Review has an error. The question asks for the minimum number of iterations in a binary search, yet the answer and obviously the intended question is "what is the maximum number of passes needed..?"

**Comment by ericsonga** [comment]
I can see why you found the wording confusing.  It is also asking the minimum number of passes to guarantee that the name is not in the list.  I have modified it to make it clearer.
