### ISSUE TITLE
Think Like A Computer Scientist ActiveCode problems

### ISSUE THREAD

**Issue by ghost** [RunestoneInteractive/RunestoneServer#1108]
A typo. Ignore the other bit, I see now that adding a main block breaks the tests.

![bugs](https://user-images.githubusercontent.com/30204601/40095387-cc9c411a-5899-11e8-82b9-8abd526d826a.png)

I'm directed here thanks to the How To Contribute section in the textbook. "We invite you to join our open source project. Please visit our web page for more information about obtaining the source: Runestone Interactive"

**Comment by bnmnetp** [comment]
That is a good idea to mark the exercises that have unit tests with an icon of some kind.
