### ISSUE TITLE
Canvas LTI Integration

### ISSUE THREAD

**Issue by matthewmagnusson** [RunestoneInteractive/RunestoneServer#1117]
Does the server product currently interface with Canvas using LTI.  I was unclear from documentation, if it was available or is still a feature request.  If it is still a feature request, what work is necessary.  I'd be interested in helping in that area.

**Comment by matthewmagnusson** [comment]
Thanks, we are looking at a private server for our intro cs courses.  @presnick do you have any advice on how to implement?  This is a summer project, so if it seems like there could be a good fit for improving functionality in this area, I'd be open to helping, just would need some general guidance on where to start.  Is there an IRC for this group or other preferred form of communication?

**Comment by presnick** [comment]
I will try to write up a description of how the existing lti.py gets used, and what some of its limitations are. Will try to get to it this week. @matthewmagnusson: in the meantime, please do join the Runestone slack group and let's create an lti channel within that for coordinating on this.

**Comment by presnick** [comment]
Sorry, I didn't get to this before vacation. I'm off for the next week. Let me give you a little info, though, to at least know where to look to get started. I will try to document better at some point.

There is a file, controllers/lti.py, that is a good starting point. It handles the LTI-based single sign-on. If the user already has an account, it signs them in. If not, it creates the account and signs them in.

If an assignment id is passed to lti.py, then after the sign-in the student is redirected to that assignment page. The code also saves the ID that the LMS passed in for the particular student-assignment cell, which runestone has to send back when reporting a grade for that assignment.

There is an lti table in runestone where the credentials are saved. Those credentials have to be put in the LMS when configuring it.

I have a sample XML file that one has to edit and upload to the LMS for configuring it. In an ideal world, we'd have another controller endpoint which would have a few form fields and would spit out basically that same XML, in the format that an LMS expects for configuration. But I've never tried to implement that part of the LTI spec.
