### ISSUE TITLE
Should check instructor created exercises for special characters in the unique id

### ISSUE THREAD

**Issue by gramlogic** [RunestoneInteractive/RunestoneServer#1141]
I created the course CollegiateCS1 and made an assignment that includes inline exercises from chapter 1. To add the exercises, I checked the box next to General Introduction in the Problems section of the Assignments tab. As expected, this added all available exercises. I then removed unwanted exercises by unchecking the boxes next to them.

Two user-created exercises in the Exercises section of the chapter cannot be removed. They are inst#2 and FCHSIntroD&D1. The latter produces an error in the student view when rendered:

```
System Message: ERROR/3 (/home/bmiller/Runestone/web2py/applications/runestone/build/preview/_sources/index.rst, line 6)

Error in “dragndrop” directive: maximum 1 argument(s) allowed, 18 supplied.

.. dragndrop:: FCHSIntroD&D1
    :feedback: Uh oh, try again!
    :match_1: Commercial Appeal|||Memphis
    :match_2: Chronicle|||Houston
    :match_3: Post|||Washington
    etc. (up to 20 matches)

   Match the newspaper to its city.

```

When these exercises are unchecked, they disappear from the list in the instructor interface as expected, but they remain visible to the students. In addition, they continue to contribute to the total score count for the assignment. Re-adding them allows me to change the order and points assigned, but still does not allow me to remove them using either the checkbox in the tree view or the Delete "x" in the list view.

**Comment by bnmnetp** [comment]
The quick workaround is to not use characters that HTTP considers special to a URL.  Namely & and #

Yes, I should be checking for those and not letting you use those characters.  But until I do...

**Comment by bnmnetp** [comment]
I have manually removed the questions from the assignment for you.

**Comment by M1chaelMc** [comment]
Thank you!
