### ISSUE TITLE
Assignment Work not saving for Java assignments

### ISSUE THREAD

**Issue by dvermes** [RunestoneInteractive/RunestoneServer#1154]
When students (or I) complete an assignment and click Save & Run, it appears fine. If they log out and log back in, go to the same assignment, and click Load History, they just get a completely blank code window that only has 1 line with nothing on it. I was able to reproduce this myself.

Course name is: cs925
Name of the assignment is: While Loops Practice Problems
Specific problem is: cs925_whileloops_1
I just tested it at 11:35 AM today EST (10/26/2018), but it shows in the system as 3:35 PM due to time zone.

The attached screenshot is what I see when I go back to the assignment and try to load my history.

![image](https://user-images.githubusercontent.com/9136374/47577223-585f1600-d914-11e8-81f8-21d88578f368.png)

**Comment by bnmnetp** [comment]
Doug, please rebuild your course and see if that solves the problem. 

This is a Java based course correct?  Does the code compile and run?  it sounds like it but I didn't see any run events in the screenshot you sent.

Looking in the database I can see that there are a lot of entries for the code with timestamps and student ids and your course, but the column that should contain the code is blank.

Not sure whats going on, this is the first report I've had of something like this going wrong.

**Comment by dvermes** [comment]
Hi Brad,

Thanks for your e-mail. Rebuilding the course does not appear to have
solved the problem.

Yes, it's a Java based course. The code compiles and run fine. The problem
only seems to manifest itself when you leave and come back later and try to
view your work.

This is the first time I've experienced this issue as well. I made some of
these problems a few years ago, so maybe something changed in the last few
years as to how I am supposed to create custom problems such that the old
problem no longer works right?

Thanks,

Doug
=============================================
Douglas Vermes -- dvermes@scarsdaleschools.org
Computer Science & Mathematics
Scarsdale High School
==============================================

**Comment by dvermes** [comment]
OK. Thanks, Brad. I assume I should rebuild the course after the fix is
deployed?

- Doug

=============================================
Douglas Vermes -- dvermes@scarsdaleschools.org
Computer Science & Mathematics
Scarsdale High School
==============================================
