### ISSUE TITLE
Two students with same name - can't see one of the student's work

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1158]
I have two students called Ethan Lin.

They look to be get identical scores.

When I go to the Grading interface and bring up code for a particular exercise, I see only one of the two Ethan Lin's code. I cannot see the other Ethan Lin's code. It gets duplicated no matter which name I select in the Grading interface.

I'm concerned that when I'm auto-grading it, it is always accessing only one of the Ethan's records and not the other one. It's fuzzy to me.

I think for now, I may have to have one of them create a brand new account with a different name to avoid the problem.

**Comment by bjones1** [comment]
As far as I know, the grading interface code is broken, since it uses names instead of userids for all its operations. However, the underlying sever-side code that actually does the grading is correct, and the code that produces the grades in the gradebook (click on the student progress tab, then click the gradebook button) works. I'll let @bnmnetp and @presnick comment, since they would have the final answers.

**Comment by psmaker** [comment]
That's what I was suspecting. I think an easy fix on my end is for them to edit their first / last name so there is no overlap.

**Comment by bjones1** [comment]
This is one of the grading interface areas where I'm guessing that netids aren't used. (But I haven't looked at the code).

A related bug: if a student didn't submit an answer, then clicking on that student in the grading interface doesn't clear it. For example:

1. I click on student A and see his/her answer and points for a specific question. I give this student partial credit during a manual regrade.
2. I click on student B and see his/her answer and points for a specific question. This student provided the same answer as student A, so nothing in the answer/feedback boxes changes. I also give this student partial credit during a manual regrade.
3. I click on student C and see his/her answer and points for a specific question. However, student C didn't submit an answer, but it appears the he/she did. I give this student partial credit during a manual regrade, **even though he/she never answered the question!**

**Comment by bnmnetp** [comment]
@bjones1 that seems more like a case of where we simply are not clearing the answer when we should not be.  Which is not at all what is going on in this Issue.

**Comment by bjones1** [comment]
Oops, you're correct. I'll move this to another issue.
