### ISSUE TITLE
Integrating birdseye into Python books

### ISSUE THREAD

**Issue by alexmojaki** [RunestoneInteractive/RunestoneServer#1165]
I'm the author of [birdseye](https://github.com/alexmojaki/birdseye), a visual debugger for Python. I think birdseye has the potential to be very useful for educational platforms like this one. In Runestone, it could serve as an alternative Codelens alongside PythonTutor. Does this seem like a good idea to you?

It looks like the books don't run user-written Python code on the Runestone server. If you'd like to continue avoiding that, the birdseye UI could be shown only for code samples which have already been run when the book was built. Unfortunately I don't see birdseye ever working on Skulpt.

**Comment by bnmnetp** [comment]
birdseye definitely looks interesting.  I'm still digging out after an extended vacation but would love to think / brainstorm about how this could be integrated.

**Comment by alexmojaki** [comment]
Great. How about we have a chat in https://gitter.im/RunestoneInteractive/RunestoneServer to figure out a path forward?

**Comment by alexmojaki** [comment]
I don't see this happening anymore, but it is in https://github.com/alexmojaki/futurecoder
