### ISSUE TITLE
"create new course" upon registration is not in effect

### ISSUE THREAD

**Issue by yarikoptic** [RunestoneInteractive/RunestoneServer#1181]
as you now could quickly test on a new instance using https://github.com/RunestoneInteractive/RunestoneServer/pull/1178 - if during registration you mention that you would like to establish new course, you aren't redirected to that magical `runestone/designer/index.html/newCourse` page, and need to know to compose that url manually

**Comment by bnmnetp** [comment]
Well, I'm not sure how that ended up being broken.  git blame would make me think it never worked an yet it did.  Nevertheless I just pushed a tiny fix that restores this.
