### ISSUE TITLE
How to change assignment ordering label

### ISSUE THREAD

**Issue by irmaR** [RunestoneInteractive/RunestoneServer#1187]
Hi,

when I create my custom assignments all of them get label Q_1. How do I change the label to Q_2, Q_3 and so on?

Irma
![screenshot from 2019-01-09 16-57-14](https://user-images.githubusercontent.com/2535881/50938992-c0ab9700-142f-11e9-8b77-18574c241322.png)

**Comment by bnmnetp** [comment]
Thanks, thats a flaw in our approach for compiling these questions to html and then inserting them in the assignments page.  

I can't think of a quick fix right now, so hopefully this won't cause too much confusion.

Brad
