### ISSUE TITLE
bug on comparing types?

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#1190]
Discovered while investigating a bug reported by a student trying to do ac17_5_1
type comparisons for 

`print(type("good morning") == list)`  yields true. Is this a skulpt bug, or runestoneServer?

**Comment by bnmnetp** [comment]
This is the same bug you ran into last fall.  It is a bug in skulpt.  There is a fix but it is intertwined with a bunch of other stuff in skulpt that I'm looking at.
