### ISSUE TITLE
Some Problems are not available for selection in Assignments dialogue

### ISSUE THREAD

**Issue by yarikoptic** [RunestoneInteractive/RunestoneServer#1192]
Originally "reported" on slack, but could not figure it out, so decided to file for posterity.
I am running my "own" server in the docker, with recipe in #1178 (with some changes not yet in the PR) and the whole setup at https://github.com/dartmouth-pbs/psyc161-wi19-srv .

NB If no obvious ideas, I will try to reproduce it using the docker image and similar setup but without "secrets".

My problem is that when I go to `/runestone/admin/assignments` and try to add `Problems` by navigating the tree -- only a few sections have problems listed under them.  I know that others have them too since they did miraculously appear after starting a new instance from committed docker state (just running on a different port, related issue detected was also #1191 ).
Here is an example on almost pristine fopp:
![image](https://user-images.githubusercontent.com/39889/51157682-0e206d80-184f-11e9-82db-4cfca3422649.png)

Some of those already added I "found" via Search and blindly changing their Auto-grade.

Please advise on possible workaround or where to dig to unravel the mystery.  Thanks in advance for any guidance ;-)

**Comment by bjones1** [comment]
No idea, but some debug thoughts. Browse to the assignments page you provided an image of then look at the value of `eBookConfig.toc.question_picker` in the console. If this is missing sections, then the problems is in the backend (Python) side; if the sections are present, the bug is in JS.

**Comment by yarikoptic** [comment]
thanks @bjones1 - I think I am looking at the right thing.  It has sections but no children per section:
![image](https://user-images.githubusercontent.com/39889/51209006-2ccd4580-18dd-11e9-8154-72a920736698.png)

How to debug python side?

**Comment by yarikoptic** [comment]
ok, I guess it is this function [_get_toc_and_questions](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/admin.py#L1339) within admin.  Will try to debug at "run time"! ;)

**Comment by yarikoptic** [comment]
but actually it feels that it might be deeper -- where DB is populated...
on a somewhat populated "deployed" one I have
```
runestone=# SELECT chapter, count(chapter) FROM QUESTIONS WHERE autograde!='' GROUP BY chapter;
       chapter        | count 
----------------------+-------
 Dictionaries         |    19
 Sequences            |     4
 Functions            |     7
 AdvancedAccumulation |     7
 SimplePythonData     |     1
(5 rows)
```
and on the blanking out devel one I have
```
runestone=# SELECT chapter, count(chapter) FROM QUESTIONS WHERE autograde!='' GROUP BY chapter;
     chapter      | count 
------------------+-------
 SimplePythonData |     1
(1 row)
```
so need to look at that stage whereever it is ;)

**Comment by bjones1** [comment]
Chapters are populated by the Runestone build process. Perhaps your build is referencing the wrong/invalid database? See https://github.com/RunestoneInteractive/RunestoneComponents/blob/master/runestone/server/componentdb.py.

**Comment by yarikoptic** [comment]
`runestone build --all` seems has fixed this issue!  I am still not sure how I arrived to this state (had only ~300 questions within DB from total ~1,700 from two books), but overall -- resolved! thanks!
