### ISSUE TITLE
upgrade of the RunestoneServer looses progress indicators on the book sections etc

### ISSUE THREAD

**Issue by yarikoptic** [RunestoneInteractive/RunestoneServer#1204]
I thought to upgrade the server deployment to take advantage of possible recent fixes features.
So testing in docker (that is why #1178 with a single image/container with everything is nice for that), but it seems that if I upgrade the server from  [375cf1d3 to 53a69715](https://github.com/RunestoneInteractive/RunestoneServer/compare/375cf1d310ec54a6dbdc4e07e37cf7c51b534a1e...53a69715b497a50d46ebfa1900fb97ced3602b0c) (upgraded via just "git pull" within applications/runestone) -- I immediately noticed that students lose their progress indicators (green marks and "Completed this topic ..." hints) on the Table of Contents of the book (fopp)... Progress indicators in assignments pages seems to be ok but "Load History" seems also to not bring anything.  So may be something changed about storing the history and DB migration is needed?

<details>
<summary>more details about my bash history, most likely not interesting</summary>

```shell
runestone@ef7fb2a8533b:~/applications/runestone$ git reflog
66f75f04 HEAD@{0}: pull: Merge made by the 'recursive' strategy.
279907eb HEAD@{1}: commit: LCL: disable register action
0da96665 HEAD@{2}: commit: LCL: some books were removed/disabled by startup script
375cf1d3 HEAD@{3}: clone: from https://github.com/RunestoneInteractive/RunestoneServer
runestone@ef7fb2a8533b:~/applications/runestone$ git show
commit 66f75f04666bfc7dbb3b8fc2d88c1737b76a8232
Merge: 279907eb 53a69715
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu Feb 7 04:39:53 2019 +0000

    Merge branch 'master' of https://github.com/RunestoneInteractive/RunestoneServer

runestone@ef7fb2a8533b:~/applications/runestone$ git show 375cf1d3
commit 375cf1d310ec54a6dbdc4e07e37cf7c51b534a1e
Merge: 676b945f eeba900e
Author: Bradley Miller <bradleymiller@google.com>
Date:   Thu Jan 3 07:25:05 2019 -0800

    Merge branch 'master' of github.com:RunestoneInteractive/RunestoneServer

runestone@ef7fb2a8533b:~/applications/runestone$ git show 53a69715
commit 53a69715b497a50d46ebfa1900fb97ced3602b0c
Merge: d8f39f0e ff7d52e4
Author: Bradley Miller <bnmnetp@users.noreply.github.com>
Date:   Wed Feb 6 12:23:13 2019 -0600

    Merge pull request #1201 from presnick/bugfix-assignment-template-for-ungraded-assignment

    URGENT; fix bug when there are 0 points for the assignment

```
</details>

**Comment by bnmnetp** [comment]
Hmm, I can't reproduce either

* progress indicators in the table of contents --- still working
* load history -- still working

None of the recent changes required a migration.

Sounds like maybe your container is missing something in the database?  Like it didn't get restored properly when you recreated the container?? -- just guessing as we've already established I'm no docker expert.

**Comment by yarikoptic** [comment]
I don't think it is any docker effect.  I also tried to not restart it during upgrade -- just did git pull while it is running -- to the same effect: progress indicators are there when I start saved image into a new container, then do git pull within applications/runestone -- indicators are gone upon page reload.
I guess I will try to provide a full reproducible example (if it does reproduce ;)) using that docker setup later today/tomorrow

**Comment by vsoch** [comment]
Did you do this @yarikoptic ? I can give it a try.

**Comment by yarikoptic** [comment]
Eh, by now I forgot any detail... But I am 80% certain that I just rolled back and finished teaching without server upgrade

**Comment by vsoch** [comment]
Cool!  Well hey this is just in time for the weekend so I’ll poke around, see what I can figure out, and post an update after some work. Happy Friday!
