### ISSUE TITLE
Adding a student back after removing them leaves them marked as inactive

### ISSUE THREAD

**Issue by dianeroux** [RunestoneInteractive/RunestoneServer#1205]
I cannot see anything one of my students, Shar'na Clement, has done in my course on the Runestone server.  The course is S19-EE01C.  Her name is listed in the gradebook, but I cannot access the logs for her because her name is not listed on this page (see image).  And the page looks odd, too.  I wonder if there's a problem due to the apostrophe in her name.

![image](https://user-images.githubusercontent.com/32103576/52417319-a100a080-2ab9-11e9-849f-1d6449b8f054.png)

**Comment by bnmnetp** [comment]
I looked in the database and she is marked as an Inactive student.  The only way that a student could get that status is if you removed her from your course from the admin page.

**Comment by dianeroux** [comment]
Well, she's still showing up in my list of students (see below).  I did delete her from my F18-EE01C course, however.
![image](https://user-images.githubusercontent.com/32103576/52420060-4bc78d80-2abf-11e9-8761-d9f7881a21b9.png)

**Comment by bnmnetp** [comment]
OK, I think that scenario uncovers a little bug in the system.

I'll manually mark her as active and lets see if that fixes it.

**Comment by dianeroux** [comment]
I still cannot see her work or her log file (after logging out and logging back in again).  Will she have to do everything over again?

Just to be clear, she was registered for both F18-EE01C and S19-EE01C.  When I saw that, I deleted her from F18-EE01C.  I did that for some other students as well, and I can still see their work.

________________________________

**Comment by bnmnetp** [comment]
Wow, give a guy a few minutes to do something...

I just made the change in the database a minute ago.

**Comment by dianeroux** [comment]
Yes, it's working now.  Please forgive my impatience.  If I had thought about it, I would have realized I should wait a bit.

Thank you for your quick response.

________________________________
