### ISSUE TITLE
Assignment not loading (for editing)

### ISSUE THREAD

**Issue by irmaR** [RunestoneInteractive/RunestoneServer#1206]
Hi,

not sure what happened, but today I created an assignment and saved it. But when I wanted to update it later, I couldn't access it through the assignment interface. It's in the drop list, but when I click on it it doesn't load. It never happened before and I have created several assignments.

The assignment is also showing in the gradebook, but I cannot edit it.

Best,
Irma

**Comment by bnmnetp** [comment]
What course?  What assignment?  Please, help me help you.
