### ISSUE TITLE
Links on user menu redirects to localhost in web site

### ISSUE THREAD

**Issue by elifsudegokay** [RunestoneInteractive/RunestoneServer#1209]
When I click on any link in user menu, it redirects to localhost but it is running on server. 
Is there anything did I miss ? I would be appreciate for your help :)

![screen shot 2019-02-11 at 13 41 00](https://user-images.githubusercontent.com/28874640/52558231-c7e50c80-2e02-11e9-9a4f-625b8bd4e652.png)
![screen shot 2019-02-11 at 13 40 41](https://user-images.githubusercontent.com/28874640/52558233-c9aed000-2e02-11e9-86e1-13547b77a9df.png)
![screen shot 2019-02-11 at 13 29 43](https://user-images.githubusercontent.com/28874640/52558237-cb789380-2e02-11e9-84cd-ddeea376cd47.png)

**Comment by bnmnetp** [comment]
You need to check the pavement.py files for you books and make sure the master_url is set to your server.  Otherwise it defaults to a dev server that it expects to be running on local host.

**Comment by elifsudegokay** [comment]
thank you so much it worked. Is there any other settings I should configure to work with server.

Thanks
