### ISSUE TITLE
Custom problems not showing up in assignment

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1210]
Course: LHSIntroCS_2018

I made Assignment: "Programming Test 3 Period 7"

I had made 4 custom questions. When I added it to the assignment, it looked OK. But when I made it visible and I opened up the assignment in the normal student view, the assignment was empty.

Picture of the empty assignment:

![image](https://user-images.githubusercontent.com/28868409/52652141-64122080-2ea2-11e9-889c-fd92044b692c.png)

Picture of the assignment as created in the Instructor View:

![image](https://user-images.githubusercontent.com/28868409/52652182-78561d80-2ea2-11e9-837f-1d348decf95e.png)

**Comment by psmaker** [comment]
In a panic (because the test was to be in 30 minutes...) I just tried to remake each of the custom questions.

I called them lhs_test3_[1234] instead. When I made them, I put them into the "Chapter 17" - whereas when I made the original 4 questions named lhs_test_3_[1234], I put them into the "Labs" section.

I'm not sure if this has anything to do with it, but when I made a new Assignment called "Test 3 Period 2", the 4 new question thankfully appeared OK.

Not sure if this helps in the debugging process.

**Comment by bnmnetp** [comment]
Ugh! Sorry.  For such an innocuous looking PR this https://github.com/RunestoneInteractive/RunestoneServer/pull/1189#discussion_r255585568 has caused a LOT of panic. Sorry.  I'll add an Exercises section to the Labs section and double check that the rest of the chapters all have an Exercises section.

**Comment by psmaker** [comment]
Well, at least there is an understanding now on how I need to make sure it works OK. I guess I was "lucky" that I put it in the Ch 17 so that it would work.

**Comment by bnmnetp** [comment]
Yeah, we are going to implement a warning or error in the build step if a chapter is missing an Exercise section.
