### ISSUE TITLE
I have questions about running my own Runestone Server / Don't understand all the functionality of the server

### ISSUE THREAD

**Issue by elifsudegokay** [RunestoneInteractive/RunestoneServer#1211]
Hello,
When I click student name to display student report in student progress page, i can not display report and page error message is  "invalid function".

Should i change  settings or did i miss anything in server implementation ?

If you can help, i would be appreciate

Best regards

<img width="704" alt="ekran resmi 2019-03-02 12 23 50" src="https://user-images.githubusercontent.com/28874640/53680016-2c9ad500-3ce6-11e9-875e-256d05e35832.png">

**Comment by bnmnetp** [comment]
Is this a course you are running on https://runestone.academy ?  What is the name of your course?  does this happen for all students or just one in particular?  Can you give me the URL of the page from which you were clicking so that I can investigate further?

Thanks

**Comment by elifsudegokay** [comment]
Course running on       foo.yeditepe.edu.tr  
Course name is            ACM114

URL is           http://foo.yeditepe.edu.tr/runestone/static/ACM114/index.html

Also I can not create new course after changing master url in pavement.py

Thank you so much

**Comment by bnmnetp** [comment]
I see that in the book you linked to you have it configured to not use runestone services.  If you are running a runestone server you should enable those services in your book along with logging, and you should have your students log in.  Without enabling the runestone services nothing gets saved.

**Comment by bnmnetp** [comment]
Also, changing the master url in pavement.py does not create a new course.  Please check out my youTube channel with help for these kinds of administrative tasks.  Since you are running your own runestone server you should also check out the rsmanage command as that lets you do common things like adding a new course from the command line.
