### ISSUE TITLE
I can not create assignment with questions in book

### ISSUE THREAD

**Issue by elifsudegokay** [RunestoneInteractive/RunestoneServer#1218]
In a fopp base course, when I choose a chapter to add a question to the assignment, 
it does not work. 

Is there any settings to modify this feature ? 

I would be appreciate for your helps

![Screen Shot 2019-03-22 at 18 38 06](https://user-images.githubusercontent.com/28874640/54834648-a44e9500-4cd1-11e9-8950-cd90b4935d74.png)

**Comment by bnmnetp** [comment]
Hi,

Can you check your javascript console in your browser and let me know if you see some error messages?  I have tried this on two courses of my own based on fopp and I can't reproduce your problem.

**Comment by elifsudegokay** [comment]
This is from Google Chrome:

<img width="552" alt="Ekran Resmi 2019-03-22 20 59 18" src="https://user-images.githubusercontent.com/28874640/54843533-9276ed00-4ce5-11e9-97ea-50cfc143650d.png">

this is from Safari:

<img width="402" alt="Ekran Resmi 2019-03-22 20 59 05" src="https://user-images.githubusercontent.com/28874640/54843588-c81bd600-4ce5-11e9-827b-5b57208d6d79.png">

After saving:
<img width="2048" alt="Ekran Resmi 2019-03-22 20 50 59" src="https://user-images.githubusercontent.com/28874640/54843620-dcf86980-4ce5-11e9-8320-c3b9f7ad1fea.png">

Thank you so much

**Comment by bnmnetp** [comment]
That just a warning not an error.

So, I see that you are running your own server and not using runestone.academy.

So, I'm guessing that there is a problem with how you have set up the course, and that there is a database error somewhere.  How did you build your ACM114S195 course? Through the web interface?  On the command line?

Have you checked the errors folder under web2py/applications/runestone/errors ??

Do you know SQL well enough to go into the database and check the questions, assignments, and assignment_questions table to see if there are questions in the database?

**Comment by elifsudegokay** [comment]
I created course with "runestone init" command then I changed _sources directory with fopp's  _sources then I wrote "ACM114S195" in "create course interface" as a course name because when I try to create course directly  from interface it gives error. 

This is terminal error:

![Screen Shot 2019-03-26 at 18 35 12](https://user-images.githubusercontent.com/28874640/55011898-a4af9e80-4ff7-11e9-86fe-44c89afce0dc.png)

runestone/errors:
![Screen Shot 2019-03-26 at 18 38 06](https://user-images.githubusercontent.com/28874640/55011956-bbee8c00-4ff7-11e9-9d64-58730e02c3a7.png)

There are Attribute and I/O errors in this error files
![Screen Shot 2019-03-26 at 18 38 06](https://user-images.githubusercontent.com/28874640/55012077-e9d3d080-4ff7-11e9-922e-3902961711d5.png)

![Screen Shot 2019-03-26 at 18 40 12](https://user-images.githubusercontent.com/28874640/55012093-f0624800-4ff7-11e9-8776-e03eb96e85bc.png)

I do not know SQL  but I will try to check database

Thank you so much

**Comment by elifsudegokay** [comment]
This is create course error
![Screen Shot 2019-03-27 at 17 48 19](https://user-images.githubusercontent.com/28874640/55085877-747c0480-50b8-11e9-9c54-3b3b2e110d46.png)

**Comment by bnmnetp** [comment]
You need to update fopp

**Comment by elifsudegokay** [comment]
Now, when I try to build, the error message is  "Error while trying to add directive"

![Screen Shot 2019-03-28 at 18 58 45](https://user-images.githubusercontent.com/28874640/55172825-b9bd3680-518b-11e9-9d47-490ca157c9ae.png)

**Comment by elifsudegokay** [comment]
There are only old assignment questions in the assignment_question table 

![Screen Shot 2019-04-01 at 18 15 32](https://user-images.githubusercontent.com/28874640/55338770-10878080-54aa-11e9-8f1c-868693e58ce0.png)

**Comment by bnmnetp** [comment]
It looks like you are trying to build your course from the command line, but you created it through the web interface.  And the error messages are telling me that you don't have your environment variables set up correctly so that the build will add the right information to the database.

**Comment by elifsudegokay** [comment]
After updating environment variables I try to build a new book and this is the output

![Screen Shot 2019-04-02 at 13 25 50](https://user-images.githubusercontent.com/28874640/55395692-b8ed2180-554a-11e9-9d99-6bc5af479ca8.png)

**Comment by bnmnetp** [comment]
I think all this is telling you is that you are not getting connected.

Please try to run the command `rsmanage env` and show me the output. -- but you can hide the password part of the database url!

**Comment by elifsudegokay** [comment]
I have fixed environment variables. Now I can add questions to assignment but I still can not create course :(

![Screen Shot 2019-04-03 at 16 33 09](https://user-images.githubusercontent.com/28874640/55483271-edd2a480-562e-11e9-9034-928bb65d1a29.png)

**Comment by elifsudegokay** [comment]
This is the output of "rsmanage env" 

![Screen Shot 2019-04-03 at 17 43 23](https://user-images.githubusercontent.com/28874640/55488003-dba93400-5637-11e9-8469-c598c1aff5fd.png)

**Comment by bnmnetp** [comment]
Getting closer....

Make sure that your pavement.py file has a line like the last in this example:

```
                       'enable_chatcodes': 'false',
                       'allow_pairs': 'false'

```
It is part of the ``template_args`` dictionary

**Comment by bnmnetp** [comment]
Also it looks to me like your server code is out of date.  You may want to do a git pull to make sure you have all the latest bug fixes.
