### ISSUE TITLE
https:///RunestoneInteractive/pythonds

### ISSUE THREAD

**Issue by ledbettersa** [RunestoneInteractive/RunestoneServer#1219]
I am a student with Park U, doing a intro to Python class.  I am using a interactive class on the sight above, and it is not tracking my progress.  I seen a article for another instructor and their student and the end result it showed the student was inactive in the data base.  The instructor asked me to disenroll and try to reregister for the class on the site.  It would not allow me to do it.  

Thanks for any help.

**Comment by ledbettersa** [comment]
I guess a name and class would be important too, sorry.

Scott Ledbetter
CS152SP22019
 How to Think Like a Computer Scientist: Interactive Edition

**Comment by bnmnetp** [comment]
I can see 25 entries in the course name for you.  You are registered for the course you sent me.  Although on further investigation it seems you have created two accounts.  saledbetter and ledbettersa (this one has 0 activity)

My guess is that you did not bookmark your course or are using google to find the course and then you end up using the course called 'thinkcspy' which does not require you to login but has the same content as your course.

Please make sure you log in on https://runestone.academy and consistently use one or the other of the usernames you have created.
