### ISSUE TITLE
[greater good pledge] request for participation

### ISSUE THREAD

**Issue by vsoch** [RunestoneInteractive/RunestoneServer#1228]
hey @bnmnetp!
 
I'm creating a new initiative, [The Greater Good](https://good-labs.github.io/greater-good-pledge/) that aims to highlight projects with no underlying incentives or ulterior motives - those that are "for the greater good." I think that your family of runestone projects fit strongly within the criteria, and I'm hoping that the community (you?) would like to participate. Participation simply means adding the community name to the pledge, and then (optionally) adding a badge to any associated project repos.

Details are provided at the page, and any maintainers / users here are welcome to also join the organization [The Good Labs](https://www.github.com/good-labs) if open source transparency is important to them. It's still early (I'm going to be creating media and other community interactions) and right now I'm getting in touch with projects that I've worked with.

**Comment by bnmnetp** [comment]
Cool.  Thanks.   I'll read through it more carefully.

**Comment by vsoch** [comment]
Awesome! Any comments / feedback is appreciated - this is the first draft and (I haven't yet put up) the FAQ or example scenarios, so if you are looking for specific scenarios or answers to questions, let me know and I'll target them specifically.

**Comment by vsoch** [comment]
Here is the FAQ, as promised! https://good-labs.github.io/greater-good-pledge/faq/ Let me know if you have more questions, or have other example scenarios. A primarily goal of mine is to help support projects for the greater good, and this initiative is around that.

**Comment by vsoch** [comment]
Also see discussion here https://github.com/pydicom/pydicom/issues/842#issuecomment-488366124 about making it more about disclosure, less about profits. Feel free to join the conversation!
