### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1235]
I wanted to get this idea down, for discussion.

We were talking about end to end integration tests, and I think that our new 'dockerized' server could really help.  I can see a path where we leverage the selenium tests we now have for the components with a full server running in a docker container.  This would let us perform actions from the browser using selenium and then verify that the correct data was in the database.

@bjones1

**Comment by bjones1** [comment]
Yes, this is the next step. We need tests that exercise the interaction between the server and the components using Selenium. Let's talk in more detail / plan this out! My obvious concern: after a test runs, we still need to clean the database to remove changes made by a test. The context manager approach seems to work for me to do this, but I'm also open to better ways.

I'd guess we'd basically update some of the objects to either log in using the web2py test client or using Selenium.
