### ISSUE TITLE
Problems not showing up 

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/RunestoneServer#1237]
I have a local build of the runestone server on my laptop, still getting the bugs out of this installation.  One problem is in the Assignments page (/runestone/admin/assignments): I can create assignments from the Readings, but when I go to Problems there is no little + button next to Exercises, for instance: the problems are not showing up to be selected.
I looked into the SQL database, and the table called `problems` is empty; I'm not sure if that's a clue or not.

**Comment by sahi1l** [comment]
This is fixed now, though I don't remember how I did it, sorry.

**Comment by bnmnetp** [comment]
I fixed this in entrypoint.sh -- see the comments on lines 74-77 for the explanation (or below)

```
# since this is a dev environment a rebuild of the container does not necessarily
# mean that the book you want will be totally clean, and so a build of an already built
# book in a fresh container will result in a database that is missing the questions.
# setting buildargs to --all when we have a clean db will ensure that does not happen

```
