### ISSUE TITLE
Use Dynamic Pages to create instructor only reveal

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1243]
Currently the reveal directive has an `:instructoronly:` flag that will hide the reveal button and all content from students.  This works OK, but the content is all still there in the source, we are simply hiding the button and all content with a display: none style setting.

I propose to change this behavior using our new dynamic pages, so that at the time we render the page we can include or exclude the button and content altogether.

1.   Modify _route_book to provide an `is_instructor` variable to the template renderer
2.  Modify the TEMPLATE_START and TEMPLATE_END variables of the reveal directive when the  the `dynamic_pages` template variable AND `:instructoronly:` flag is set to surround the entire directive with an `{{ if is_instructor }}`  / `{{ endif }}` check.  This will tested for when the page is rendered.

This really means that we will need to generate:

```
{% raw %}
{{ if is_instructor: }}
... all of directive ...
{{ pass }}
{% endraw %}}
```

I sure do wish Sphinx and web2py used the same template language!  

Also we can surround the entire template like this because nothing else in the template needs to be expanded by sphinx.

@bjones1 We ought to look into creating some kind of sphinx macro that makes this a bit easier.  I imagine this kind of thing happening more often as we take advantage of server side dynamic pages.

**Comment by bnmnetp** [comment]
Actually it is a bit simpler.   We don't need to worry about the `{% raw %}` part when we are expanding the directive.  Which means we only have to remember we are inserting WEB2PY template language.

```
{{ if is_instructor: }}
... all of directive ...
{{ pass }}
```

**Comment by bjones1** [comment]
Overall, I like it. It's exciting to see what neat things dynamics pages opens up. One minor concern: I think we need to develop some nice mechanism for a specific page to import what unique objects its needs, rather than passing everything in `_route_book`. In my dynamic pages, I'm already seeing that -- "Oh, for my team eval, I need a function that..." "Oh, for another page, I need another database entry that..."

Instead, can't `is__instructor` be imported from `modules/`? Then the code would be

```
{{ from xxx import is_instructor
if is_instructor: }}
... all of directive ...
{{ pass }}
```

where `xxx` is the name of some module in `modules/`?

**Comment by bjones1** [comment]
I've actually written a for loop for use in Sphinx. I suspect we'll want to write a few more similar things as well.

**Comment by bnmnetp** [comment]
The import solution seems like a real duplication of effort.  We already have 99% of what we need to know in the route controller to tell if the user is an instructor for a given course.  So it would need to start over when rendering.

Plus: importing things in a page?  That seems icky.

I think it will be instructive to work through a few samples and then step back and think about where we are going and what the issues are.  If we are worried about dictionary creep maybe we just need to add things to request.  But I also hear you that the more we add to `_route_book`, the slower it gets.

I think I can make the case that by including is_instructor here, we are actually saving a lot of time because we don't need to incur the round trip API call for every page just to figure out if we are serving a page to an instructor.  Same for login.  I am going to work on that right away.  It is painful to me that we have KNOW whether the user is logged in or not when we generate the page, yet the first thing that happens after the page is loaded is that we make an api call to figure out who the user is and whether they are logged in.  We can easily just populate the isLoggedIn field when we generate the template.

**Comment by bnmnetp** [comment]
We really ought to take a step back and think about all of this in a dynamic context.

How much information that we get now via individual API calls after the page is loaded could be provided by the server at the time the page is rendered.  There are tradeoffs between overall server load and time to render a page.

1. Only dynamically fill in eBookConfig parameters? (not what is intended by this PR)
2. Previous answers to questions on the page?  Right now each component makes its own call to restored its previous answers.
3. active code histories -- pretty much the same as the previous
4. Feedback of various kinds as you reference in your testing_mode PR
5. Can/should/how could we allow instructors to set flags for different pages to show or hide content?  For example a decent number of instructors would love to hide whole chapters from the table of contents.  Some would like to unhide chapters as they go.  There is already a mechanism for making assignments visible.  Some have created assignments and used them as "exams"

**Comment by bjones1** [comment]
Good points. I agree that we should just implement some features and see how it feels. As you say, `is_instructor` is basically free. Also as you say, providing common info (login status) make sense. I think it would make sense to catalog "common" items -- anything in a template used by all/many pages, for example (eBookConfig, user name, course name, etc.).

My thoughts on other items:

1. You mean, dynamically fill in all `eBookConfig` params? We're already doing that with some of them.
2. This is a good idea and would reduce server load. But, again, let's think first:
    1. How to maintain compatibility with static pages?
    2. What about other things: hiding problems? Hiding feedback? Dynamically generating problems? Even if we don't implement this, it sounds like some common code for a question could be put in a base class.
3. Yep.
4. Yep.
5. I think that makes sense, but implementing might be harder, depending. If "invisible" pages render as a "this page is hidden by your instructor", it's easy. If it involved modifying the TOC on pages it's hard.

**Comment by bnmnetp** [comment]
done
