### ISSUE TITLE
server side feedback/grading and online testing in the dynamic world

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1244]
Moving the discussion off PR #1242 @bjones1 writes:

1. How should feedback hiding work?
    1. Statically -- feedback is either always hidden or always shown until the student submits another answer or the page is refreshed.
    2. Dynamically -- the instructor can show/hide feedback, and students will see immediate updates. Doing this means that adding server push ability, a level of complexity I want to avoid.
2. What granularity should we support?
    1. Site-wide -- the current approach. I currently have a `runestone` application with all answers shown, and another `exam_runestone` application with all answers hidden. Both applications use the same course name, which means there's no extra steps for me to duplicate enrollment between a normal class and a class used only for exams.
    2. Book-wide -- That seems reasonable. However, it breaks my model above -- now, I need to create another course with the same enrollment as the non-exam course.
    3. Chapter/subchapter/page-wide -- sounds nice. If there was an exam "chapter", I could make all problems there hide feedback.
    4. Per-problem -- the most flexible.
3. Specifying hidden vs. revealed feedback
    1. As an additional parameter in the declaration of a problem. It would be a pain to go and change this for every problem type we support.
    2. Via some GUI where instructors could show/hide feedback in the admin interface. This appeals the most to me.
4. Security
    1. For low-stakes assessments -- in-class exercises where you don't want to give feedback until students have already worked the problem; hiding feedback before an assignment is due.
    2. High-stakes assessments -- provide some means to ensure student's can't even see the problems before they begin the exam. I do this my requiring an auth code only TAs know; TAs proctor the exam to help reduce cheating.

@bnmnetp responds:  There is also an issue to consider around how much of the timed_exam directive we can leverage. At a minimum it can benefit from some of this work, and we should not duplicate work that is already done there.

@presnick follows up with a use case to consider:  a problem set where unit tests are used for auto grading but results are not shown to students.

**Comment by bnmnetp** [comment]
## Use Cases we are trying to address with this change.

1.  Giving an exam or quiz where students cannot see the questions until they start the quiz and do not see their results or any sort of feedback until the instructor is ready for everyone to see.

2. Assigning a problem set to students but the results/feedback are not shown until released by the instructor.


## Questions

1.  When is feedback given?
   a) immediately
   b) when the answers to a group of questions are irrevocably submitted (current timed exam)
   c) When an instructor allows it (not currently possible)
   d) never

2. When is grading done?
   a) immediately
   b) when the instructor asks for it to be done
   c) upon submission of a group of questions

3. Where is grading done?
   a) server side
   b) in the browser

4. When are the questions shown to students?
   a) Always
   b) During some scheduled time period
   c) During some block of time when the instructor has manually enabled it

## Potential Solutions

My initial stake in the ground would be that we do not make this over complicated.  I think we can address a lot of the use cases by enhancing the current assignment mechanism.  This puts the level of control over most of the questions raised at the level of an assignment page, which seems manageable.  And allows us to take advantage of work we have already done. -- such as server side grading (although admittedly incomplete in terms of the kinds of questions it can handle).

I can imaging a small number of flags we could add to an assignment to control many of the aspects raised above.

**Comment by bjones1** [comment]
If a given question appears in two assignments and feedback is hidden in one and shown in another assignment, what happens? I think any mechanism we have need to be something that maps directly to questions, not assignments, for this reason.

**Comment by bnmnetp** [comment]
I was thinking about this a bit more.  Controlling all of those variables question by question just seems very hard and complicated.  But I had an idea that I would like to push on a bit more but I’ll share my preliminary thoughts.

1.  A question is a question ....  
2.  A question can appear in many different contexts, and the question is answered in the context.
3.  Students can see the results, get feedback, or whatever, but only in a matching context.
4. The context is set at the page level

**Comment by bjones1** [comment]
By 1 above, are you proposing moving to a question bank? That is, questions don't natively live on a page, but exist in a bank that can be deployed to a page? I'm having trouble understanding the rest of your proposal.

**Comment by bnmnetp** [comment]
I'm not sure what you mean by question bank.  But in my mind that is essentially what we have today.  When you build a book, the database gets populated with every question from the text.  In addition, instructors can add tests through the web interface.

Right now we can add arbitrary questions to assignments, but of course we cannot alter the textbook.

My proposal is that we do NOT make a lot of duplicates of questions by making the same question have different configuration information about feedback and grading.  

Rather we handle the issues of feedback and visibility and grading by attaching a "context" to the answers to the questions.  Maybe context is not the right word because it carries some connotations for you, but it is the word that occurred to me.

If we need to hash this out through a hangout thats fine too.

**Comment by bjones1** [comment]
OK, I'll wait until next week's hangout.

**Comment by bnmnetp** [comment]
It would help me be more clear if you could say something about what you don't understand.

Let me try to make this more concrete.  Suppose we have just 4 different contexts (I'm sure there are more)

- OPEN: in the open context (a regular page of the textbook) students answer questions and get immediate response and helpful feedback.

- PRACTICE: in the practice context students see the same questions as they do on the pages of the textbook, but all previous answers are ignored.  In the practice context students are given feedback but only on the answer they supply on the practice page.

- QUIZ: in the quiz context students do not see any of the questions until they begin the quiz, the quiz use questions they have seen in the text, or they may only see questions that the instructor has created through the web interface or through the timed directive.  In this context the students do not see any previous answers, and are not given feedback until they submit the answers to the entire quiz, then they see what they answered correctly and are given helpful feedback on questions they answered incorrectly.

 - EXAM: similar to the QUIZ but even more restrictive in that the students will see no feedback whatsoever until the instructor releases the feedback.  This way students don't know how they have done until everyone has finished the exam.

The point is that the context controls what and when students can see, not the individual questions.

**Comment by bjones1** [comment]
At some point, I'd like to port this to the bookserver. Let's leave it closed until then.
