### ISSUE TITLE
Clarify web redirection 

### ISSUE THREAD

**Issue by jenniferskay** [RunestoneInteractive/RunestoneServer#1256]
If I click on a textbook I can't preview it any more without being in a course, if I do go to a book without registering for it a pop up says 
"Hey there you appear to have wandered into <bookname> But you are not registered for this course. Sending you to safety"

Novice instructors won't know that they need to sign up for a course with that book in it. Please give more detailed instructions on the redirect message

**Comment by bnmnetp** [comment]
This only happens when you are already registered for a course AND logged in.  The problem is that too many students were googling to find the page in they were going to work on and ended up in the WRONG course, then they would get frustrated that they weren't getting credit, and then the instructors would get frustrated that Runestone wasn't "grading correctly".  

Finally when I figured this out, I added this popup to force people to do their work in the right place.

Please suggest what more detailed instructions I could give to make this a better experience.

**Comment by jenniferskay** [comment]
OK, multiple user interface issues that I, an inexperienced user, hit today. Here’s how to fix them:

Issue 1:
I think some of the issue is that if I’m logged on and I go to:
https://runestone.academy/runestone/default/courses

and then I try to pick a link under the booklinks dropdown menu I get that redirection message – so you need to ditch the booklinks dropdown menu there

Issue 2:  wording
perhaps you could modify the wording to:

Hey there you appear to have wandered into java4python But you are not registered for this course. Redirecting you to your course list. If you just want to preview the book, log out and access the book from the home page runestoneinteractive.org.


Issue 3: User interface issues with accessing Book links from home page when not logged on:

Book links drop down was non obvious to me on the home page. (Maybe rename it “preview our books”)

Instead of using book links drop down I clicked through to “see the list” option on the first view on the home page and got sent to http://runestoneinteractive.org/pages/library.html

Some of the links on there should be fixed. E.g. I go to: http://runestoneinteractive.org/pages/library.html

I scroll down and click on “data science” it takes me to:
http://runestoneinteractive.org/pages/library.html#data-science

Fair enough. But if I then click on the first occurrence of
“Regular expressions in Python” (i.e. the title) it takes me to
http://runestoneinteractive.org/pages/library.html#id17
i.e. higher up on the same page, not to the book.

So from there I click on “regular expressions in Python” and it takes me back down to http://runestoneinteractive.org/pages/library.html#regular-expressions-in-python

And, of course, if I click on the first  “Regular Expressions in Python” I see, I get redirected back up the page to http://runestoneinteractive.org/pages/library.html#id17 again.

It took a little while to figure out that I needed to click on the title *after* the description when I got back to  http://runestoneinteractive.org/pages/library.html#regular-expressions-in-python in order to actually access the book.

Thanks

**Comment by bnmnetp** [comment]
Thanks, that is very helpful feedback.
