### ISSUE TITLE
Unit Test endpoints -- Help write one test

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1259]
For anyone wanting to jump in and help us get our test coverage up, here is a list of endpoints that could really use some unit tests.  If you have never written a unit test before don't worry, this is a really low stakes way to help out the project, since you are not doing anything that affects the production server!  After all you are not going to cause the server to fail (except if you write a really good test that identifies when the server would fail anyway!)

Here is a list of functions that need unit tests! You can claim just one and submit a PR.
To help you get started check out the documentation here:  https://github.com/RunestoneInteractive/RunestoneServer/tree/master/tests

## admin.py

- [x] assignments
- [ ] practice
- [ ] add_practice_items
- [x] removeStudents
- [x] removeInstructor
- [x] deletecourse
- [x] getQuestions
- [x] questionBank
- [x] getQuestionInfo
- [ ] edit_question
- [x] question_text
- [x] searchstudents
- [x] gettemplate
- [x] createquestion
- [x] htmlsrc
- [x] getStudentCode
- [x] coursename
- [x] releasegrades
- [ ] get_assignment_release_states
- [ ] get_assignment
- [x] save_assignment
- [ ] delete_assignment_question
- [ ] reorder_assignment_questions 
- [x] ~checkQtype~ Not used -- removed

## ajax.py

- [x] ~savegrade~ No longer used.  Remove `listassignments`, `listassessments`, `assessdetai`l and `gradeassignment`
- [ ] checkTimedReset
- [ ] Many many tests do not check for the exception blocks.

## assignments.py

- [ ] record_assignment_score
- [x] autograde
- [ ] record_grade
- [ ] get_problem
- [x] doAssignment (user not logged in)
- [x] chooseAssignment (user not logged in)
- [ ] checkanswer
- [x] practice (user not logged in)
- [x] practice (after course configured for practice)
- [ ] like_dislike
- [ ] practice_feedback

## books.py

- [x] published (for open book when not logged in)

## dashboard.py

- [ ] grades (with practice set up)
- [ ] questiongrades
- [ ] exercisemetrics

## default.py

- [ ] user registering for a course with a prepopulated url
- [ ] coursechooser
- [ ] removecourse
- [ ] sendreport

## designer.py

- [x] build
- [x] ~delete_course~ this was an older duplicate of the function in admin

## proxy.py

- [ ] jobeRun
- [ ] jobePushFile
- [ ] jobeCheckFile

## sections.py

We need to figure out if sections can be made useful before we worry about this file.

**Comment by santos22** [comment]
Hi @bnmnetp 👋

I would love to help out on this issue. My name is Santos and used the Python's data structures and algorithms course found on Runestone last summer to learn Python. I was a big fan of the website so I searched for and found this GitHub page and starred this repo.

Is the list of functions needing unit tests up to date? I also stumbled upon this blog [post](http://runestoneinteractive.org/2019/08/15/fall_homework.html). I can help out on that front as well.

**Comment by bnmnetp** [comment]
Thanks!  Would love help on either front.  This list should be pretty close to current.  If you find something in tests/test_xxxx.py that covers something that isn't checked let me know.

**Comment by santos22** [comment]
- Installation went smoothly
- Installing the test requirements was a little rocky but I was able to run individual tests 😅

**Comment by santos22** [comment]
I believe there is already a test for the [get_assignment](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/tests/test_admin.py#L178) endpoint.

I am working on the following endpoints (x denoting that the test has been written):
- [ ]  practice
- [ ]  add_practice_items
- [x]  get_assignment_release_states
- [x]  delete_assignment_question
- [x]  reorder_assignment_questions
