### ISSUE TITLE
2 Videos Missing

### ISSUE THREAD

**Issue by jdinda** [RunestoneInteractive/RunestoneServer#1268]
Hi!

The two videos that are associated with Python modules do not play when I click on them.  Nothing happens.  When I try entering their URLs directly into my browser, I get an error message.

Links to the videos I'm trying to watch are listed below:
https://runestone.academy/thinkcsVideos/modules.mov
http://media.interactivepython.org/thinkcsVideos/mathrandommodule.mov  (a.k.a. https://runestone.academy/thinkcsVideos/mathrandommodule.mov)

(Their parent web pages seem to work fine, otherwise.  I've listed them below:
https://runestone.academy/runestone/static/CPS141-Fall2018/PythonModules/intro-ModulesandGettingHelp.html
https://runestone.academy/runestone/static/CPS141-Fall2018/PythonModules/Therandommodule.html    )

The error message I'm getting for both videos when I try entering their URLs directly into the browser URL field is listed below:
"Sorry, Something went wrong

The error is: invalid request

We recently reorganized the books, and so some of the chapters have new links. Please go to the table of contents for your book and navigate to the desired section from there. Our Home Page is a good starting point

If you got an invalid request were hoping to find a course in /static/mycourse/xxxx.html That course may need to be rebuilt, or the course may no longer be available. Please contact your instructor. If you are an instructor then go to the Instructors Page and follow the instructions to rebuild or create your course.

For any other error, please report this on our github page (github account required) Or, tweet us @iRunestone Please try to include the error message, and the page you were trying to get to. "

Thanks for taking a look into this, and fixing it if possible.

Sincerely,
Joe Dinda
jdinda@gmail.com

**Comment by bnmnetp** [comment]
The book/course you are in is very outdated.  We moved the videos to YouTube last year. 

You can use https://runestone.academy/runestone/books/published/thinkcspy/index.html. Or if you are an instructor you should create a new course that is using the latest version of everything.

**Comment by jdinda** [comment]
Hi Mr. Miller,

Please forgive the delay in my response to your previous email.  I thought I had replied, but realized after receiving today's email that I never finished wordsmithing it, and it was stuck in my rolling collection of ~75 tabs on my browser 🙁

Thank you very much for your reply.  The link to the updated course was very helpful.  In addition to having the videos I was missing, it also has sections on Image Processing and GUIs that I look forward to reading soon.

Thanks again for your help!

Joe
________________________________
