### ISSUE TITLE
Can't access reading assignments

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneServer#1280]
I'm in the new course CS152HOFA2019. I created a reading assignment like I have been over the past 2 years, but when I return to the book and click on the Assignments link (https://dev.runestone.academy/runestone/books/assignments/chooseAssignment.html, or I've also seen the link https://runestone.academy/runestone/books/assignments/chooseAssignment.html)
I get the following error page:

Sorry, Something went wrong

The error is: invalid function (books/assignments)

We recently reorganized the books, and so some of the chapters have new links. Please go to the table of contents for your book and navigate to the desired section from there. Our Home Page is a good starting point

If you got an invalid request were hoping to find a course in /static/mycourse/xxxx.html That course may need to be rebuilt, or the course may no longer be available. Please contact your instructor. If you are an instructor then go to the Instructors Page and follow the instructions to rebuild or create your course.

For any other error, please report this on our github page (github account required) Or, tweet us @iRunestone Please try to include the error message, and the page you were trying to get to.

**Comment by irunestone** [comment]
Hi John,

There was a bad link in the index page for thinkcspy.  That is fixed now so all should be fine for you.

Brad

Bradley Miller, PhD
Professor Emeritus Computer Science
Luther College
Founder, Runestone Interactive
Blog: A Reputable Journal

**Comment by cigas** [comment]
Thanks Brad. That  worked.
