### ISSUE TITLE
Cannot run Docker to build runestone

### ISSUE THREAD

**Issue by utsab** [RunestoneInteractive/RunestoneServer#1281]
Hi Runestone, 

I am having issues following the [Docker setup instructions](https://github.com/RunestoneInteractive/RunestoneServer/tree/master/docker). I wasn't sure where to ask for help, so I am posting here.  

When I run the command 

```docker compose up```

I get the following error: 

```
sqlalchemy.exc.CompileError: Unconsumed column names: from_source
runestone_1  | The full traceback has been saved in /tmp/sphinx-err-p40rlqpb.log
....
Build failed running runestone.build: Subprocess return code: 2
```

Do you know what the problem could be?  I am building on Mac OSX.  I would appreciate any insight you can offer.  Thank you.

**Comment by bnmnetp** [comment]
Please make sure you have the latest source from github for the server.  The from_source column is needed by both runestone server and componenets and was just added this week.
