### ISSUE TITLE
Outdated report

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1283]
When I browse to the (somewhat hidden) Overview Reports from the student progress tab of the instructor's interface, the report I get includes only a few students and chapter/subchapter names show up as NaN. I suspect this is simply an overlooked / rarely used feature. I suggest we remove it. @presnick, @bnmnetp, do yall use this? Does it work for you?

**Comment by bnmnetp** [comment]
@bjones1 It was working just fine.  I added this feature because many instructors asked for something like this.  I can take a look and see if it is broken, but lets not remove it.

**Comment by bnmnetp** [comment]
I suspect it has something to do with the move to dynamic pages that broke it.

**Comment by bnmnetp** [comment]
@bjones1 -- lots of things broke with `dynamic_pages` because individual courses no long have entries in the chapters / subchapters tables, so we need update the query in subchapoverview to use the base_course instead of the course.

**Comment by bjones1** [comment]
Good point! I'll work on that. It should be fairly easy, assuming tests were written correctly.

In the report, I see only a small subset of my students -- I assume this is broken too.

![image](https://user-images.githubusercontent.com/2125584/62149494-73a2eb80-b2c1-11e9-8e34-b2b6cf2d3605.png)

**Comment by bnmnetp** [comment]
After  #3801fe8  I am seeing all of my students and non NaN entries.

I don't think I can look at the failing tests for #1284 until next week.

**Comment by bjones1** [comment]
Yes, 3801fe8 makes the NaN entries correct. However, I still see only a few students in my class, so something still isn't right.

**Comment by bnmnetp** [comment]
I wonder what is different about your class and mine that you are missing students.  One explanation is that students that have no entries in the useinfo table for this course will not show up.

**Comment by bnmnetp** [comment]
The queries are all plain SQL not DAL so you could try them and see.

**Comment by bnmnetp** [comment]
@bjones1 is this working for you now? Can we close?

**Comment by bjones1** [comment]
No, it's still not working for me.
