### ISSUE TITLE
Answer to Active code ch3Ex5q is incorrect

### ISSUE THREAD

**Issue by agrayburn** [RunestoneInteractive/RunestoneServer#1303]
CSAwesome
Knowing the course will help us a lot

Section 1.8

agrayburn

**Describe the bug**
The exercise reads: The following code should calculate the number of hours in 320893 seconds. However, the code has errors. Fix the code so that it compiles and runs correctly.

320893 / 60 = 5349.2166 min
5349.2166 / 60 = 89.136944 hours

There are a few issues with the answer:

1. The code returns a value for the variable numDays, but the question asks for hours
2. The answer code has this line: int numHours = numSecs / 60; which should be a number of minutes not hours
3. So that makes the answer provided, 222, not at all correct.

**Comment by bhoffman0** [comment]
Thanks!  I'll change it to numHours/3600 and print out numHours. It will be up with the next update.
