### ISSUE TITLE
Active Code Problems in Assignment revert to default settings after save

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1307]
**What Course are you in**
csawesome
**What Page were you on**
Instructor's page
**What is your username**
hoffmanb
**Describe the bug**
When setting up an assignment, in the Problems section, if you add some Activecode problems and set them to Interaction/Best Answer and save, and go to a different tab and come back, the settings have reverted back to the default of Manual/Empty.  I'm not sure if this is a bug, or just how Active Code problems work.  The interaction setting does work for multiple choice problems in Problems and for the page containing Active Code in the Readings section. 
Thanks,
Beryl

**Comment by bnmnetp** [comment]
So, this is a by product of my attempt to ensure that instructors do not try to autograde programming exercises that do not have unit tests.

Is this a use case that you think will come up often?  I understand using interaction for reading assignments, but I've always assumed that problems should be summative.

I'm sure I can fix this in the code, but let's talk through the pros and cons before we allow instructors to shoot themselves in the foot.

**Comment by bhoffman0** [comment]
I thought it might be something like that. I had told teachers to use
Manual or Interaction for Active Code, since we don't have unit tests for
those in Java, but I can tell them to only use Interaction in the readings
section. Could you pop up a warning message if they change the grading
setting for active code problems in the Problems section?
