### ISSUE TITLE
Certificate and re-direct errors

### ISSUE THREAD

**Issue by Wildhair2** [RunestoneInteractive/RunestoneServer#1315]
**What Course are you in**
Knowing the course will help us a lot
EdX  GTx: CS1301xII Computing in Python II: Control Structures

This report on general site issues and is not related to the course on this site. It originates from an invalid link at EdX, of which I have already informed them. But it results in errors from this site that should have been addressed by the site admin already.

**What Page were you on**
3.1 Supplemental Materials link to this site to further reference python control structures and use. 

**What is your username**
dglenn99
**Describe the bug**
Certificate error:
This site does not have a current SSH certificate which causes errors due to current browsers using https by default now instead of http. The site admin needs to either update the certificate or remove it from the nginx web server to avoid the error that is occurring.

Redirect missing for an original page that existed: http://interactivepython.org/runestone/static/pythonds/Introduction/ControlStructures.html that originally existed doesn't redirect the user to the new page location when the site was restructured. Redirects are commonly available in any Open Source CMS's and I assume in commercial CMS's available as well.

I'm aware redirects are a PITA to create, especially when entire sections are moved, but crucial for sites referencing this site that have not used tools available to notify them of bad links. The site admin does not demonstrate experience or knowledge of proper web practices that are the basis of the errors encountered. 

I know reading the CMS documentation is a PITA as well, but if they are administering the site simply because they learned the rudiments of building one from another CMS, it isn't good enough to present a professional appearance and user experience without digging deeper into the documentation to utilize the tools available to them IMHO. I've administered Wordpress and Joomla sites since 2010 and learned to avoid potential errors before they occur and resulted in a comment/complaint such as this one..

 I've done numerous redirects due to the organizational managements desire to restructure an existing site to modernize the appearance or create a more user friendly and intuitive navigational experience. Corporations and businesses loose business when a referring site link no longer works and a user is stuck wandering around to find the page they need.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
None

**Comment by bnmnetp** [comment]
1.  All links to http://interactivepython.org are permanently forwarded to https://runestone.academy which does have an up-to-date certificate.

2.  Specifically the link you include above automatically redirects me to https://runestone.academy/runestone/books/published/pythonds/Introduction/ControlStructures.html  without any errors or warnings.

I gave over 1 years worth of warnings about about shutting down the server on interactivepython.org and forwarding everything to runestone.academy.

I'm not sure how EdX is handling the link, but I am not aware of anything more I can do on my end.  The forwarding has been in place since July 4th and this is the first complaint I've had.

**Comment by Wildhair2** [comment]
I am using the latest version of Chrome on Linux. There are the errors I experience with the link to https://interactivepython.org/runestone/static/pythonds/Introduction/ControlStructures.html.

What browser are you using?

**Comment by Wildhair2** [comment]
Or do I need to notify Google there is an issue with Chrome?

**Comment by bnmnetp** [comment]
I am using the latest Chrome on macOS.  But I also use Safari pretty regularly and Firefox sometimes as well.

The link you just sent me was to https://interactivepython.org -- there never was an https version of that website so I'm not sure where that is coming from.  Your initial report contained an http link.

**Comment by Wildhair2** [comment]
http://interactivepython.org/runestone/static/pythonds/Introduction/ControlStructures.html is the link I referenced above.
![Screenshot_20190829_094733](https://user-images.githubusercontent.com/19353779/63946095-8fc1b600-ca42-11e9-8f0e-330373ca61ce.png)

**Comment by Wildhair2** [comment]
As I pointed out, the latest browsers default to https and convert http addressed to https automatically when pasted in the address bar.  That is why you saw the https in front of the link.

**Comment by Wildhair2** [comment]
The Nginx server should have a re-write function like apache to convert https addressed to the original to http so the current redirect works with the new browser functionality of defaulting to https

**Comment by Wildhair2** [comment]
BTW, I tried editing the https in the address bar to http and it won't take it. So legacy links used to link the original site in the most current browsers appears to be the source of the problem because they will be automatically converted to a https link by the browser.

**Comment by Wildhair2** [comment]
You should have enough information to modify the redirect so when a https call is made to the original site, it is converted to http and avoid the issue that is occurring.
server {
    listen 443 ssl;

    # You will need a wildcard certificate if you want to specify multiple
    # hostnames here.
    server_name domain.example www.domain.example;

    # If you have a certificate that is shared among several servers, you
    # can move these outside the `server` block.
    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/cert.key;

    # 301          indicates a permanent redirect.  If your redirect is
    #              temporary, you can change it to 302 or omit the number
    #              altogether.
    # $http_host   is the hostname and, if applicable, port--unlike $host,
    #              which will break on non-standard ports
    # $request_uri is the raw URI requested by the client, including any
    #              querystring
    return 301 http://$http_host$request_uri;
}

**Comment by Wildhair2** [comment]
or
set $request_host $server_name:$server_port;
if ($http_host) {
    set $request_host $http_host;
}

**Comment by Wildhair2** [comment]
Note: I have notified EdX of the issue with the link and the reference to InteractivePython in their comments should be modified to reflect Runestone Academy to correct the problem on their end.

I hope the Nginx example code above will allow you to eliminate the error. Once I accepted the original certificate, my next attempt using the link worked correctly, but the average Joe Average will freak out at the warning and refuse to continue,

Regards,
Doug

**Comment by bnmnetp** [comment]
Thanks, I'll work on it.  You understand this is a small group and its hard to be an expert on everything.

**Comment by bnmnetp** [comment]
So I'm really supposed to set up another certificate just to redirect ??  That seems like an incredible waste of time.

**Comment by bnmnetp** [comment]
I'm not able to reproduce this error (checked safari, Chrome and Firefox) after tweaking my forwarding rules.
