### ISSUE TITLE
Put gradebook in a separate tab

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/RunestoneServer#1316]
**Is your feature request related to a problem? Please describe.**
The dashboard can take a little while to load, which is frustrating if I want to go directly to the gradebook.

**Describe the solution you'd like**
Make the gradebook a separate tab like "Student Progress" or "Grading".  

**Describe alternatives you've considered**
Alternatively, add a button to make the gradebook accessible from other tabs like Grading or Assignments.

**Comment by bnmnetp** [comment]
I hate to make yet another tab.  The idea of the tabs is to keep things high level.

What about adding an additional link to the gradebook on the grading tab?

In the meantime you can make your own bookmark to: https://runestone.academy/runestone/dashboard/grades

**Comment by bnmnetp** [comment]
How about this @sahi1l 

<img width="751" alt="Screen Shot 2019-08-30 at 10 46 41 AM" src="https://user-images.githubusercontent.com/51115/64034128-a1bf5980-cb13-11e9-982c-3aeeb737c586.png">

**Comment by sahi1l** [comment]
I think I'd rather the button be on the Grading tab and/or the Assignments tab, just for thematic reasons.
