### ISSUE TITLE
August 15 Post - Help Wanted - Make Autograding Awesome

### ISSUE THREAD

**Issue by Wildhair2** [RunestoneInteractive/RunestoneServer#1317]
You posted this code, but not instructions on where to place the activecodeID.
Should I assume it should be test_activecodeID_Num(self): for the def test_XXX(self): function below in order to create your ideal solution post and the ... represents any additional code that is required in order to give the response desired?

from unittest.gui import TestCaseGui

class MyTest(TestCaseGui):

    def test_XXX(self):
        assertEqual(variable, correct_value, feedback)
        assertEqual(function_call(), correct_return_value, feedback)
        ...

myTest.main()

Regards,
Doug
dglenn99

**Comment by bnmnetp** [comment]
In the post I said:

> ... the activecode ID (shown below the activecode) ...

All I need to know is the id so I can add it in the right place in the right textbook without a ton of searching.

**Comment by Wildhair2** [comment]
Works for me.
