### ISSUE TITLE
Platform Discussion

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1320]
At the end of #1318 @bjones1 raises the question of moving away from web2py....

Well, as always.  We have to weight the benefits of switching.  The cost to switch to a new framework is very high.  What things are we going to give up just to have a different platform?

Every platform has its own warts that you have to live with, unless you write your own platform, then you don't think it has warts, but other people do.  😄 

Lets use this Issue as a place to gather pros and cons of switching.

**Comment by bjones1** [comment]
A mistake I made earlier when I was porting to Flask: porting both web2py and the DAL. These should be done in separate steps -- probably first port to another web framework, then consider another ORM (sqlalchemy, etc.)

Also, we should IMHO divorce porting the student-facing code (which is much smaller -- mostly `ajax.py`, I think) from the instructor interface code (much, much larger). I think would make sense to run two web apps (web2py and something else), one for the student code and another for instructor interface.

**Comment by bjones1** [comment]
One big question: how long with the author continue to maintain web2py, given that he's trying to write a new framework (py4web)?

**Comment by bnmnetp** [comment]
The plan that has been percolating in the back of my head looks like this:

![RunestoneArch](https://user-images.githubusercontent.com/51115/64029511-55bbe700-cb0a-11e9-837c-7e2d1b1180fd.png)

The LTI boxes and arrows may not be placed quite right...

In my mind the first step is to separate the book server from the dashboard server into two separate web apps.

## Book Server
* Ideally this could be a moderately configurable version of `runestone serve`
* Serves dynamic Pages
* Responds to api calls currently in ajax.py
* Serves Assignment pages
* Serves Practice Pages


## Dashboard Server
* Grading
* Student Progress
* Assignment Creation
* Instructor Help
* Class Management
* LTI configuration

This would allow us to divide and conquer any sort of migration to a new Framework.

**Comment by bnmnetp** [comment]
What would we want from a new Framework?

1.  Keep our current database largely or completely intact.
2. Should be flexible about the ORM we use.
3. Should allow for easy Containerized deployment and scalability
4. Should be easy enough to pip install requirements.txt and get going.
5. Should be based on modern scalable Python features (3.6+)

I don't want a monolithic framework that imposes a lot of stuff.  So Django is out.  (would also rule out web2py) . Although interestingly if you do some googling for what frameworks to learn in 2018/19 web2py makes most of the lists.  There are a LOT of alternatives see: 
 (https://wiki.python.org/moin/WebFrameworks)

 I -- personally -- don't care if the framework provides a lot of admin junk. I don't use appadmin at all.  I dont' care if it has an editor for web editing, etc.

If we think about starting out by migrating the book server, then I think we want to think about one that allows us to achieve a big amount of scalability without spending a lot on hardware.  So three that come to mind:

1. Flask
2. Quart -- API compliant with Flask built built using modern python async architecture
3. Sanic

**Comment by bnmnetp** [comment]
Still -- with all of the above said what is the case for dumping web2py?  I don't think there is a rush, even with py4web there is a big community around web2py that will continue to support it.

## CONS of Web2py

* The custom importer that creates magical global objects that confuse editors and programmers
* The lack of ability to install with pip
* everything in every controller file is an endpoint.

Sure, all of them are annoying, but annoying enough to justify the time and opportunity cost of dropping everything else to port to a new framework?

I think our first step should be to break the current monolithic runestone app into two applications.  Make sure we have really strong unit and integration tests for the book server, and THEN consider our alternatives.  Having comprehensive tests in place prior to any port will make that effort a LOT easier.  (Note I think we are pretty close for the book server side)

**Comment by bjones1** [comment]
I would attach LTI and the LMS to the book server, not the instructor dashboard server.

Other book server items:
- Serves progress page

**Comment by bjones1** [comment]
I agree the first step is more tests, the breaking the current app into two pieces. As you say, the case for porting isn't strong, given the pain level.

**Comment by bnmnetp** [comment]
1.  More tests especially for the book serving side, but we are closer there than other areas.
2. Reorganize the current controller code:
    1. Make new practice.py file for practice code 
    1. Consolidate assignment code into assignments.py from admin and assignments
    1. Create the equivalent of an ajax.py file for the instructor pages? Or should API and endpoint be in the same controller file?
    1.  Move non-endpoints to a module to be imported

3. Then start on the breakup
