### ISSUE TITLE
Problem in a java book uses python syntax

### ISSUE THREAD

**Issue by robotabc773** [RunestoneInteractive/RunestoneServer#1324]
In the csawsome book, in chapter 1.8.1, question 2, there are two possible blocks for printing a variable, with the intent that one of them has incorrect case. However, both use the syntax `print(perPersonCost);` instead of `System.out.println(perPersonCost);` The other questions on the page have the correct syntax, so I assume this is just a typo.

**Comment by bhoffman0** [comment]
Thanks! Fixed and will be uploaded on Saturday.
