### ISSUE TITLE
not getting password-reset email while using my username (not email) to request it.

### ISSUE THREAD

**Issue by codethestack** [RunestoneInteractive/RunestoneServer#1326]
forgot my password, didn't save it in browser

not getting the email to reset it

this is for the ryerson university course CPS305-Fall-2019.

**Comment by bnmnetp** [comment]
What is your username?

**Comment by codethestack** [comment]
adubovik

**Comment by bnmnetp** [comment]
I just sent an email to the address I have for that username in the database.  I haven't had it bounce back to me, so if you didn't get it then you entered the wrong email address when you registered.

**Comment by codethestack** [comment]
i didn't enter the wrong email because when I tried to re-register with a different username and correct email, the system told me the email is in the database.

still not getting the password-reset email. I received your test-email email
