### ISSUE TITLE
Students should not be able to add the same course more than once from Courses  page

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1327]
One student added himself to the same course 3 times.  This should not be allowed to happen.

**Comment by bryantal** [comment]
Hello, I am Alex Bryant, a Berea College student.  I can take a look at this issue and hopefully solve it.

**Comment by bnmnetp** [comment]
Great!

**Comment by bryantal** [comment]
![issue#1237_screenshot](https://user-images.githubusercontent.com/28715731/65905206-21984800-e38e-11e9-89cd-96cf03763998.png)

I wasn't able to recreate the issue for a particular course.  It did not allow me to register for the same course under the same email.

**Comment by bnmnetp** [comment]
I think this issue shows up when you choose "Change Course" from the 👤 menu.  Then at the bottom of the list on that page choose "Enroll in a Course"

If you can't recreate it that way, then I'm not sure.

**Comment by bryantal** [comment]
![issue#1237_screenshot2](https://user-images.githubusercontent.com/28715731/66070478-63a4c380-e51f-11e9-80eb-642a6a27837e.png)

Dr. Jan Pearce and I are trying to recreate the issue.  She had me enroll in an old course of hers that she doesn't use.  I did it a few times, but I still only pop in the course one time as pictured above.  We are trying with a new dummy course she is making specifically for this now.

**Comment by bnmnetp** [comment]
I made this issue after an email with another instructor.   

If Dr. Pearce removes you from the class, using the manage students interface then you should still be able to log in.  But you will be in the "base course" for her course.  Now if you add yourself back again, how many times are you registered when you go to the Change Course?

**Comment by bryantal** [comment]
![issue#1237_screenshot3](https://user-images.githubusercontent.com/28715731/66071592-67d1e080-e521-11e9-8b09-abc21ff9940d.png)

Yep, that did it.  The dummy course she created was based off of fopp, so as soon as I was removed, this all popped up under where I change my courses.

**Comment by bnmnetp** [comment]
OK, each of those should represent an entry in the user_courses table of the database.

Now if you can figure out how they all got there!
