### ISSUE TITLE
Not all checkmarks appear for completed assignment items

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneServer#1328]
**What Course are you in**
CS152HOFA2019

**What Page were you on**
https://runestone.academy/runestone/assignments/doAssignment?assignment_id=6885

**What is your username**
pkfrance (I'm submitting for the student who has this problem)

**Describe the bug**
There is never a green checkmark for completing the summary page activity, which is just viewing the page and clicking the "Mark as completed box"
![ch3-nocheck-1](https://user-images.githubusercontent.com/11619455/64399253-4dddd480-d02d-11e9-9dda-ed31a0602b0a.png)
![ch3-nocheck-2](https://user-images.githubusercontent.com/11619455/64399260-5504e280-d02d-11e9-8411-e848d5532c73.png)

**Additional context**
The student did complete the activity before the deadline and the gradebook reflects the correct score. He just can't get the checkmark to appear.

**Comment by Jazzyforcefield** [comment]
The following image shows the same problem:
Course: CS4131Fall2019
Username: ungxx028

![image](https://user-images.githubusercontent.com/44912573/64466720-19bfed80-d0d9-11e9-97bf-17aed774d6a7.png)

**Comment by bnmnetp** [comment]
Fixed
