### ISSUE TITLE
Problems added to an assignment are added out of order

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/RunestoneServer#1331]
**Is your feature request related to a problem? Please describe.**
In the Assignments tab, when you select a Chapter, all of the sections of that chapter are added to the assignment, but they are not added in order. Similarly, if you check multiple sections too quickly, they don't always end up in the right order.  I assume each click spawns a separate process whose timing varies slightly.

**Describe the solution you'd like**
I would like sections to be added in order of selection, or when a chapter is clicked, the sections be assigned in the order they appear.

I assume clicking on a chapter loops through all of the sections to add them; a small time delay in that loop might do the trick in the easiest possible way.  A more sophisticated way would be to submit the sections to a queue which handles them one by one, or by tracking the time each assignment is added, and sorting by that time.

**Alternative**
Add a button to sort a reading assignment in chapter/section order after the fact.

**Comment by bnmnetp** [comment]
This should be fixed by #1336 

I'll push it to the live system tomorrow (Saturday).
