### ISSUE TITLE
Configuring Course Parameters

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1334]
Before dynamic pages (BDP) specific course oriented configurations were stored persistently for each course in a separate pavement.py file.  That doesn't make sense in this new world.  Instead these should be stored in the database.

We have some of them already as columns in the courses table.  term_start_date, allow_pairs, python3.  Others are not yet in the database such as enable_chatcodes, downloads enabled.

Do we continue to add columns to the courses table for every new option?  Or do we move to a model where we have a course_options table?

Any preferences?  I lean toward a course_options table to keep from having to update courses whenever we add something new to configure.

@bjones1 @presnick -- Thoughts??

**Comment by bjones1** [comment]
I like your dating system (BDP) :).

Separate seems nice to me -- I can see referring to a single course_options record as the usual defaults for a bunch of child courses of the same base course.

**Comment by bnmnetp** [comment]
I was thinking along the lines of :

course_id | option                          | value
----------| ----------------------|-------
3               | enable_chatcodes      | true 
3               | downloads_enabled   | true
3               | allow_pairs                  | false
...

Just moving it to a separate table means we just move the problem to another table instead of the     courses table.

**Comment by presnick** [comment]
I especially like the second version, with no migration needed.

But I still need a way to populate that DB from *some* text file on
deployment of a fresh server. Where would that live if not pavement?

**Comment by bnmnetp** [comment]
for the basecourses that would still be pavement, and we would populate from pavement.  For the created courses on academy it would all be database driven based on the form the instructors fill out when they make the course, or changes they make from the course settings panel.

**Comment by bjones1** [comment]
That's fine. On a related note, this might be a good opportunity to review what's configurable and in what context. Specifically:

- Does this config value need to be in a template, or does it actually belong directly in `conf.py`?
- Does this config value apply only to a static site? Or does it only apply to dynamic pages?

So, here's my list. Please update/edit/improve!

- `dynamic_pages`: needed only in the Sphinx template.
- `use_services`: At some point, can we merge this with `dynamic_pages`? Is anyone building a static site that's hosted on a Runestone server?
- `author`: needed only in `conf.py`.
- `project_title`: I can't find where this is used at all.
- `jobe_server`: Does this need to be configurable? Does anyone change this value?
- `proxy_uri_runs`: Same.
- `proxy_uri_files`: Same.
- `python3`: used only in the Sphinx template. For hosted sites, can be drawn from the DB.
- `default_ac_lang`: used only in the Sphinx template. For hosted sites, can be drawn from the DB.
- `project_name`: is defined as the containing directory's name for hosted sites. Why not do the same for static pages?
- `build_dir`, `dest` -- likewise -- do these need to be configurable?
- `master_url`: I don't see where this is used.
- `short_name`: I don't see where this is used.
- Hosted only
  - `log_level`: I don't see where this is used.
  - `dburl`: This is overridden in `pavement.py`, so why ask for it?
  - `enable_chatcodes`: Sphinx template only. Can be drawn from the DB.
  - `server_side_grading`: This should be put into `conf.py`.
  - `allow_pairs`: Sphinx template only. Can be drawn from the DB.
  - `downloads_enabled`: Sphinx template only. Can be drawn from the DB.

**Comment by bjones1** [comment]
Based on a video chat with @bnmnetp, updates are:

- Combine `dynamic_pages` and `use_services`, instead of keeping these separate.
- `jobe_server`, `proxy_uri_runs`, `proxy_uri_files`: these don't need to be configurable. There's a Runestone Academy URL we should point these to instead. So, let's just embed them in the Sphinx template files. @bnmnetp, what's the correct values to embed for these parameters?

A question: can we set `python3` to true now? Or are there still Python 2 books out there?

**Comment by bnmnetp** [comment]
I don't know of any books that do not have the python3 flag set.

**Comment by DaveParillo** [comment]
Re:
> * `jobe_server`: Does this need to be configurable? Does anyone change this value?

Yes. I host a book on github pages and the only way to access the http jobe server from https github.io is through a proxy I set up that only connects my book to jobe.

So that's 1 vote to keep it.
