### ISSUE TITLE
Reading assignment link differs from page link

### ISSUE THREAD

**Issue by peattiey** [RunestoneInteractive/RunestoneServer#1338]
**What Course are you in**
Cps305 Ryerson

**What Page were you on**
3.7. Balanced Symbols (A General Case)
**What is your username**

**Describe the bug**
The link is pointing to an incorrect address.

https://runestone.academy/runestone/static/CPS305-Fall-2019/BasicDS/BalancedSymbols(AGeneralCase).html

is right, 

in the assignment it is , 

https://runestone.academy/runestone/static/CPS305-Fall-2019/BasicDS/BalancedSymbolsAGeneralCase.html

This will cause us not to get marks! Imagine the horror!

**Traceback**
i dont know what this is

**Additional context**
great site

**Comment by bnmnetp** [comment]
I think you should get all your marks. The problem is that we made some pretty dramatic changes about how runestone works this summer, but tried to stay backward compatible.   Your course was created before all of this.

**Comment by peattiey** [comment]
Cool, Yeah i was mostly kidding. I'm sure my prof will be very accommodating. But in all honestly we cannot mark that complete because the page does not count as part of the assignment.

when we go to the actual page that loads and not the 404 error, it says this is not part of any assignment. But great product none the less!
