### ISSUE TITLE
Only the first question in the exercise page is runnable code.

### ISSUE THREAD

**Issue by nmarchio1** [RunestoneInteractive/RunestoneServer#1345]
**What Course are you in**
MarchioCPS9 or StudentCSP
**What Page were you on**
Chapter 3 Exercise Page and it is also happen under the assignment page
**What is your username**
nmarchio
**Describe the bug**
Only the first question in any set of exercise is runnable python code. I tried to clear my history and it is only a re-sizable textbox after the first questions.  This is true for the Assignment tab as well. 

**Traceback**
No traceback.

**Additional context**
My students first reported this to me and I am having the same issue.

**Comment by bnmnetp** [comment]
I just checked it with my own browser and I can't reproduce your problem.  Can you try it in a Private Browsing window to see if it is still happening?  Also if you can go to the Javascript Console to see if there are any error messages you could pass on.

**Comment by bnmnetp** [comment]
Was this still happening today or was this happening yesterday or before?  I fixed a bug and deployed it this morning that fixed a problem that sounds like this one.

**Comment by nmarchio1** [comment]
I did another clear of history and cache and restarted computer and told me student to do the same and we were both able to get it working again. Thank you.

**Comment by nmarchio1** [comment]
I think I just had to clear further back, When I first cleared I only cleared 1 hour. Thank you for looking into it.
