### ISSUE TITLE
Forgot Password: Email not sending

### ISSUE THREAD

**Issue by hwidger** [RunestoneInteractive/RunestoneServer#1347]
-I am attempting to log on to Subgoals.

-On the home page.

- Username: hwidger

-I forgot my password so I clicked Lost Password and it said that email was not able to send even though my email is on file I saw that this is a problem that another person had in the bugs reported below.

Thank you for your help!

**Comment by bnmnetp** [comment]
Hi,

Sorry, I don’t have any access to the system running the subgoals class.  You will need to contact the instructor or one of the TA’s for help in getting your password reset.
