### ISSUE TITLE
Dashboard grade showing incorrect percentage

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1348]
Course - LHSIntroCS_2019
Page - https://runestone.academy/runestone/dashboard/questiongrades?sid=lhs_5191430&assignment_id=7014
Username - lhsadmin

Bug Description:  Some percentages on this page are inconsistent with other pages. Example, for assignment Unit 4 Problem Set, James Wang shows 83.3%.

![image](https://user-images.githubusercontent.com/28868409/65528529-62cdbb00-dea9-11e9-946d-951b90da2a8c.png)

When I click on the 83.3% link to see the details, I see full 100% credit.

![image](https://user-images.githubusercontent.com/28868409/65528599-88f35b00-dea9-11e9-8262-50ab6c06b3bb.png)

When I go to the Grading page, the problem ex_3_10 that I manually graded as a 10, got auto-graded back down to a 0 (because I forgot to remove the "autograded" comment). So, the 83.3% is probably the "correct" score that should be shown in the 'Report for James Wang' page above.

![image](https://user-images.githubusercontent.com/28868409/65529150-788fb000-deaa-11e9-91db-9e966295a4cb.png)

**Comment by bnmnetp** [comment]
I made a change that I haven't pushed to the live system yet that automatically resets the "autograded" comment to nothing when you click either Save Grade or Save and next.


The report that you are showing is 50/60 which is 83% so that does match the percentage shown in the grade book as well as the 50 points showing in the orange box...

**Comment by psmaker** [comment]
Yes, but it does not match the 'Report for James Wang' that pops up when I press on the 83.3% link. That one is showing 60/60. So, 1 of the views is inconsistent with the other 2 views.

**Comment by psmaker** [comment]
You know, I have no idea why I reported this bug! I think I was just not looking at the windows correctly... I'm closing this right away.
