### ISSUE TITLE
Timestamp on code shows the GMT time

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1349]
COURSE: LHSIntroCS_2019 (but I don't think it is specific to this)
PAGE: https://runestone.academy/runestone/assignments/doAssignment?assignment_id=7014

DESCRIPTION: When I type in some code, I look at the timestamp and it shows the correct time that I made the change in PST time. See the picture I took right after I ``Save & Ran``.

![Voila_Capture 2019-09-25_10-41-20_PM](https://user-images.githubusercontent.com/28868409/65661420-76cb0700-dfe6-11e9-9a76-9f93c836fbf7.png)

I then immediately refreshed the page and reloaded the code. The time that it shows is now the GMT time. This is can be confusing. It appears that I changed it in the future 7 hours from now.

![Voila_Capture 2019-09-25_10-42-22_PM](https://user-images.githubusercontent.com/28868409/65661723-3c159e80-dfe7-11e9-9337-71716ecc0e11.png)

I believe that this GMT time is OK when doing the auto-grading - it seems to adjust the deadline to the GMT time. (Although I'm wondering if this was just fixed a few days ago because when I graded some problems today, I noticed the GMT time on the grading page. But, I don't remember this a few days ago. And some students were complaining that they had finished their code at 9pm on the due date, but it was marked as 4am the next day.)

**Comment by bnmnetp** [comment]
All timestamps are recorded on the server in UTC time.

The timestamps shown above the history slider have always been converted to the local timezone as it is determined by your browser and the toLocaleString(). that has not changed in years.

I have just tried to recreate your experiment and I cannot.  times are consistently showing in CDT in my browser both before the page refresh and after.  The difference is that the before timestamp comes directly from the browser whereas the after refresh is the time stored in UTC on the server converted to your timezone.

The thing that did change on Monday was only on the grading interface where I added a display  of deadline time to the assignment page, and fixed an old bug where the manual grader interface was showing a blank editor window if the student turned in work after the deadline.

**Comment by bnmnetp** [comment]
Grrrrr... this seems to be browser related.  Safari is correctly showing the timestamps in the right timezone.  But Chrome is showing them in UTC.

**Comment by bnmnetp** [comment]
So, on the server I return the date for the history slider using a function from web2py called `timestamp.isoformat()`. Sounds reasonable enough, lets use an international standard for dates and times.  This returns a string that looks like this:  "2019-09-26T13:14:46"

On the browser I pass that string to `new Date("2019-09-26T13:14:46").toLocaleString()` Safari converts it to my timezone and Chrome leaves it alone... I'm not sure who is "right" but it is definitely annoying to get different behaviors.

**Comment by psmaker** [comment]
Oh yeah, I should have mentioned that I was using Chrome when I did this
experiment.

**Comment by psmaker** [comment]
I'm pretty sure that somehow that the change that you made on Monday fixed a problem I had when I was grading. On Sunday, I graded a bunch of problems. I had marked some lower because the "last code prior to the due date" was not functioning. Yesterday (Wednesday) when I looked at those same ones in the Grader, the code was showing the code done before the UTC.

All the grading was done in Chrome.

In fact, this is how the bug even came to my attention. Some students were complaining that they did the work on time, yet they were not getting full scores. The we looked at the time stamp and they said they were not working at 4am in the morning. So, I think the Money push somehow "fixed" the problem in the Grader.

So, I might be careful about the Chrome fix so that it does not inadvertently break the Grader that was just accidentally fixed on Monday...

**Comment by bnmnetp** [comment]
Yes, that is the problem I set out to fix in the grade on Monday.  And you are correct I better be sure not to break it again.

**Comment by bnmnetp** [comment]
@psmaker -- just pushed out this weeks release.  All looks good to me in both Safari and Chrome.  Please take a look.

**Comment by psmaker** [comment]
@bnmnetp Looks really good. I like the additional tweak of adding the number of revisions that they have done. Thanks!
