### ISSUE TITLE
Help on WEB2PY_CONFIG and rsmanage initdb 

### ISSUE THREAD

**Issue by sanyaade-teachings** [RunestoneInteractive/RunestoneServer#1353]
Hello Everybody,

Good to be and many thanks for putting runestone as open source on the internet and on github.
I ran into a deadlock while trying to stack up Runestone Server locally.

**What Course are you in**
I am trying to set-up RunestoneServer locally

**Describe the bug**
Following the documentation/Readme page setting Runestone Server locally.  

I am on Linux Centos 7 and got all the requirements installed. I have setup Postgres previously and have been working flawlessly well. I created database for runestone and tested it.
Download and set-up We2py which works very well and I was able to access its pages locally.
Next git clone RunestoneServer into the applications folder as runestone. then run the pip command with the requirements.txt. This went well with no errors
Then git clone thinkscpy book into books folder.
Next I set the following values inside the 0.py file:
config = environ.get("WEB2PY_CONFIG", "production")

> if config == "production":

    #settings.database_uri = environ["DBURL"]
    settings.database_uri = environ["postgres://samel:mi331@host/runestone"]

Now if I run the command: **rsmanage initdb** , I get the following error

> [sanyaade@skillmender runestone]$ rsmanage initdb
Traceback (most recent call last):
  File "/home/sanyaade/.pyenv/versions/3.7.4/bin/rsmanage", line 11, in <module>
    load_entry_point('rsmanage', 'console_scripts', 'rsmanage')()
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 1146, in invoke
    Command.invoke(self, ctx)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/var/www/html/site48/runestone/web2pytest1/applications/runestone/rsmanage/rsmanager.py", line 37, in cli
    checkEnvironment()
  File "/var/www/html/site48/runestone/web2pytest1/applications/runestone/rsmanage/rsmanager.py", line 831, in checkEnvironment
    assert os.environ["WEB2PY_CONFIG"]
  File "/home/sanyaade/.pyenv/versions/3.7.4/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'WEB2PY_CONFIG'
[sanyaade@skillmender runestone]$ 

It seem rsmanage  is not picking up the environmental values from 0.py file
I also went and created a bash file to export those values as shown below:
`export WEB2PY_CONFIG=production 	
export WEB2PY_MIGRATE=Yes
export DBURL=postgresql://samel:mi331@host/runestone
export TEST_DBURL=postgresql://samel:mi331@host/runestone
export DEV_DBURL=postgresql://samel:mi331@host/runestone`

Unfortunately this did not help my situation.
Please I need help as I ma stuck here toward the last steps.
Is there a sample configuration file I could get to help me.
This is my first of using runestone and web2py but I do web development and system work including coding around python as well as other languages. I will be happy if I could stack runestone locally for learning, research and teaching. Many thanks!

Thank you for this amazing framework. I have spent few days trying to figure out this issue, I went through documentation  and search on issues raised previously on the sites before posting here!

Hear from you all. Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by bnmnetp** [comment]
You need to have WEB2PY_CONFIG set up so it is in your command line environment.

What do you get from `echo $WEB2PY_CONFIG`  if you run it just before you run `rsmanage initdb`

**Comment by bnmnetp** [comment]
rsmanage does not try to get its environment variables from 0.py because it may or may not need to run web2py at all for what it does.

**Comment by sanyaade-teachings** [comment]
@bnmnetp : 

Many thanks for your quick reply.
I did create a batch/shell script .sh file containing the following environmental values:

> 
**export WEB2PY_CONFIG=production
export WEB2PY_MIGRATE=Yes 
export DBURL=postgresql://samel:mi331@host/runestone 
export TEST_DBURL=postgresql://samel:mi331@host/runestone 
export DEV_DBURL=postgresql://samel:mi331@host/runestone** 

save those values into a file called **setRunestoneEnv.sh**, I then turn it into executable: chmod +x ./setRunestoneEnv.sh . Next I ran it which I believe it should export and set those values as expected. This did not work up to yesterday. I am away from the server machine, I will put those values into my **~/.bashrc** or **~/.bash_profile** when I get back home today. Hopefully this will work at **system wide level.**  I will get back to you with the results.

Many thanks for your continuous support!
Speak to you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by bnmnetp** [comment]
Running the shell script does not have the effect you want.  Those exports are only available to other commands in the shell script.

You can use the command `. setRunestoneEnv.sh` or `source setRunestoneEnv.sh` to export those variables into your current shell.

**Comment by sanyaade-teachings** [comment]
@bnmnetp : 
Many thanks for your continuous support.
I was able to get the environmental values for WEB2PY_CONFIG working. A test returns:

> 
[sanyaade@skillmender runestone]$ echo $WEB2PY_CONFIG
production
[sanyaade@skillmender runestone]$

My new problem now is postgres connection, rsmanage initdb seem to hang for sometime before returning connection errors: (unable to connect to postgres).

I can connect via console to postgres: **psql -d runestone  -U sam131  -W**

I read about postgres **ident** problems when I google the problems so just trying everything to get this sorted out

Any tip/hint will be well appreciated. many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by bnmnetp** [comment]
Typically Postgres is configured to allow any connections of a unix socket, which is what you are using in your psql command.

You will need to edit `pg_hba.conf` and maybe even postgresql.conf in order to allow connections over a network connection.    Make sure Postgres is configured to listen on all interfaces `listen_addresses = '*'` in postgresql.conf. 

My `pg_hba.conf` file looks like this:

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             runestone             xxx.xxx.xxx.xxx/32       md5
```
fill in the IP address of the machine running runestone in place of the xxx's

**Comment by bnmnetp** [comment]
Also is `host` really the name of the server you are running Postgres on??   You should make sure that is the real name of the host.

**Comment by sanyaade-teachings** [comment]
@bnmnetp : 

Many thanks for your tips and directions. I finally got it working and I was able to run
rsmanage initdb command and also I was able to build five(5) of the books without any problems.
My Solutions:
I modified => pg_hba.conf  as shown below:
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
host    all             runestone             xxx.xxx.xxx.xxx/32       trust

Next I have to change **postgresql** to **postgres** in the export environmental variables for it to work:
export DBURL=postgresql://sam:olla131@localhost:5432/runestone
to:
export DBURL=postgres://sam:olla131@localhost:5432/runestone

This work for me on Centos 7 operating systems.

My next now is to study runestone for few days, use and follow the documentation.
I am on the forum as well.

Many thanks for your assistance. Much appreciated!

God blesses!!!

Best regards,
Sanyaade

**Comment by bnmnetp** [comment]
Wonderful!  I'm happy that you got it to work.
