### ISSUE TITLE
`settings.security_key` in `0.py`

### ISSUE THREAD

**Issue by donnerc** [RunestoneInteractive/RunestoneServer#1354]
In the file `models/0.py`, there is a line like 

```
settings.security_key = 'key'
```

What is the purpose of `settings.security_key` in `0.py` ? Is seems to be web2py related but I didn't find anything relevant in the web2py book. Does it have to be changed in production in order for the server to be secure ? Why leaving such a key in the public repo ? Would it be best set through an env var ?

**Comment by bnmnetp** [comment]
That is a leftover as far as I can tell.  There is a better way to do it which is to read it from private/auth.key

I'll remove it to reduce future confusion.
