### ISSUE TITLE
Runestone logged me out..

### ISSUE THREAD

**Issue by NTeuma** [RunestoneInteractive/RunestoneServer#1356]
-I am enrolled on coursera.org in course: Python Basics. This course uses Runestone program _Foundations of Python Programming_.

The last page that I was on was Flow of Execution of the for Loop.

The issue I am dealing with is that I am currently logged in on coursera.org but i got logged out on Runestone. When I try to log in on Runestone, it tells me to log in on coursera.org (which I am logged in)

On every page on Runestone, there is a small message at the bottom left corner saying "user not logged in"

I already tried refreshing and clearing my cache.

Could you please share some insight on the issue?
Thanks in advance

**Comment by bnmnetp** [comment]
The coursera course uses their own installation of Runestone, we have no control over or access to your login information here on Runestone.academy.  I suggest you contact the administrator of the coursera course you are taking for help getting logged in to their runestone installation.

**Comment by NTeuma** [comment]
@bnmnetp 
Hi and thanks for your help
What I cannot understand is why I am still successfully logged on on Coursera while logged out on Runestone. 
I shall try to ask Coursera for help, maybe its a tech, issue from their side
