### ISSUE TITLE
Late grade incorrectly shows up on Grading page

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1363]
Course: LHSIntroCS_2019
Page: https://runestone.academy/runestone/admin/grading

Description: When I bring up an assignment/question for a student who did a problem after the due date, the grade appears as "full credit" even though it was late. (The student did not do it initially, but then completed it after the due date.)

Here is a picture of the student's grade showing "10/10" even though it was late.

![image](https://user-images.githubusercontent.com/28868409/66706555-14ae1980-ece9-11e9-8936-621b06b777a8.png)

Then I click the Auto-Grade. Then the student's score goes down to a 0 as I would have expected.

![image](https://user-images.githubusercontent.com/28868409/66706607-a4ec5e80-ece9-11e9-95f8-2054198108fa.png)

It is weird for the Grade to show a 10 when it was previously scored as a 0 when I Auto-Graded it just after the due date. When the student completes it late, then it shows up as a 10 until I re-Auto-Grade it. Then it shows correctly as a 0.

**Comment by bnmnetp** [comment]
Is it possible you accidentally regraded with the deadline unchecked?  It is incredibly easy to accidentally hit that.  I just made a little change to make that harder.

Also -- I assume you had to reload the page to see that the grade had changed to a 0?

Also -- I have confirmed (and added a warning until I fix it) that Autograding and multiple selections do not play well together. 😬

**Comment by psmaker** [comment]
No, I'm pretty sure I did not regrade. This has been showing up multiple time in this last couple of weeks as I've been getting late submissions from students. My workaround is to select the student and Auto-Grade so that it rescores all the late assignments to 0. Then I can see which assignments were done after the due date and give them the partial late score credit.

My suspicion is that they are scoring it and that somehow is the score I see? 

And yes, I did have to do a reload to see the new score go from 10 to 0. (Or more precisely, I just unselect the question or the student and the reselect it again.)

**Comment by bnmnetp** [comment]
Aha!

Yes, they can continue to score until you release.  When they score it does not update the total for the assignment that you would see in the grade book.  But it does change the value that you would see in the manual grading interface....  And when they score it is without deadlines in effect.

So, the way I do it is to always re-run the autograder right before I release.

**Comment by psmaker** [comment]
Hmm... did something just happen? I don't see the questions in the Grading anymore.

It just says "Questions Display"

![image](https://user-images.githubusercontent.com/28868409/66708461-92801e00-ed05-11e9-9576-d578e15c22af.png)

**Comment by bnmnetp** [comment]
crap.. just a minute

**Comment by bnmnetp** [comment]
Overconfidence will get you every time....  One should always test even the simplest of changes.

questions are back.

**Comment by psmaker** [comment]
Oh, I see. I guess it is just strange to me that the student's "Score Me" button has the same effect as the instructor's "Auto-grade" button. I did not really understand what the "Score Me" button was doing. Now I think I get it.

So, this makes it more clear to me. But I am wondering if it makes it confusing to others as well.

**Comment by bnmnetp** [comment]
I'm sure it is then.

What did you think was happening?  What would be a good way to resolve this?  

When do you typically release the grades?  For reading assignments I do an auto grade and release them within 12 hours of the deadline typically.  But for mixed assignments I understand why you might not want to do that, but allowing students to continue to self grade after the deadline is confusing. -- so maybe rather than hiding the button after release, I should hide the self grade button after the deadline??

**Comment by psmaker** [comment]
Sometimes I don't get to releasing the grades right away... Maybe a few days after the due date - maybe even up to a week if I'm behind. 

Maybe the Score Me button should be deactivated after the deadline as you mention. In general, I'm wondering how much the student really needs the Score Me button as for the auto-testing programs, they can already pretty clearly see how they are doing.

I do like the Score Me button on the reading assignments since it is nice to see in one place reading activity.

So, it seems reasonable to remove the Score Me button after the due date.

**Comment by bnmnetp** [comment]
The reason for the score me button was that I heard from a lot of instructors that their students didn't know what they had completed and what they had left to do and thought that was unfair.  So the self grade button answers that question.

Sometimes I think the days where you had to listen to your professor and write down your homework assignment was not a bad thing..  Or maybe I'm just getting to be a curmudgeon.
.

**Comment by bnmnetp** [comment]
Alright, I'll look into disabling the score me button after the deadline.

**Comment by psmaker** [comment]
Definitely for the Reading Assignments, it was difficult for students before the progress bar was introduced this year. It has been a **significant** improvement this year just with the reading progress bar. No more complaints from students wondering why they were not getting full credit on the reading.

But for the Exercises, I never really had any problems from students.
