### ISSUE TITLE
No Score Me

### ISSUE THREAD

**Issue by mclarke123** [RunestoneInteractive/RunestoneServer#1365]
**What Course are you in**
Knowing the course will help us a lot
Foundations of Python Programming
**What Page were you on**
Assignments>"More About Sequences"> Question/Reading Page
**What is your username**
mclarke
**Describe the bug**
There should be a "Score Me" button at the bottom of the page to score the questions you answered and return a grade. All of my other assignments have this and other students in my class can score the same assignment I am trying to. I have tried different browsers, restarting my computer, and even using different computers.
![Screen Shot 2019-10-16 at 10 09 38 AM](https://user-images.githubusercontent.com/56642218/66927069-2a7b5180-effd-11e9-8eb5-b2affe88f4bd.png)

**Comment by bnmnetp** [comment]
Once the instructor has released the grades for the assignment, the Score Me button is hidden and you cannot grade yourself.

**Comment by mclarke123** [comment]
Ok! Thank you!
