### ISSUE TITLE
Assignment grades missing from gradebook

### ISSUE THREAD

**Issue by madsesmith** [RunestoneInteractive/RunestoneServer#1366]
It looks like the grading workflow has recently been updated and now I'm having a problem I didn't have before. 

On the grading page I select the assignment from the dropdown, check the box to grade all questions, check the box to grade all students, then click the Autograde and Display Totals button. It spins for a minute then the cursor returns to normal and I see scores/notes for most of the students/questions shown on the right. I'm guessing the blank ones are students who did not do the assignment. 

Next I go to the gradebook to review those scores. But for the assignment in question there is only a score for the first student. For all other students that column is empty. For all previous assignments, graded last week or earlier, the gradebook shows scores for every student. 

Course: Colgate-COSC-101-F19
Assignment: Lecture 13 Reading
My username: mesmith

**Comment by bnmnetp** [comment]
Please read the instructions on the right hand side of the page.  As well as the warning message below the auto grade button.

To auto grade everything you just need to select the assignment and click on the auto grade button.
