### ISSUE TITLE
Show chapter/section numbers on assignments page

### ISSUE THREAD

**Issue by madsesmith** [RunestoneInteractive/RunestoneServer#1367]
**Is your feature request related to a problem? Please describe.**
I have a list of the chapters/sections numbers I want students to complete before each class, e.g., 10.1-10.9. When I go to setup the assignments I end up with the Assignments tab open in one window and the Table of Contents in another so I can figure out which sections I'm meaning to assign. 

**Describe the solution you'd like**
I'd like the section numbers to be shown on the assignment tab, along with the title. 

**Describe alternatives you've considered**
My clunky workaround is manually looking up the section titles for each section to be assigned before adding them to the assignment. 

**Additional context**
<img width="952" alt="Screen Shot 2019-10-16 at 10 59 08 AM" src="https://user-images.githubusercontent.com/4765540/66931673-7087e380-f004-11e9-87f2-e33dcfed90e5.png">

**Comment by bnmnetp** [comment]
done
