### ISSUE TITLE
Could not reset "Pretest for the AP CS A Exam" after student had issue with submit of exam

### ISSUE THREAD

**Issue by howardmo-lwa** [RunestoneInteractive/RunestoneServer#1371]
Student reported an issue with exam ending without being able submit the exam. Their exam did not have any results submitted. They attempted to reset the exam so they could retake but it only showed the results of the test. I asked them to drop the class and re-enroll only to be in the same state after dropping class. The class name was "AdvancedCompSciJavaAssessment"

**Comment by bnmnetp** [comment]
What did they do to drop the class?

I'm a little skeptical of the student's story because when the timer runs out everything is automatically saved.

Running out of time isn't a "resettable event" so the exam would not let someone reset just because they ran out of time.
