### ISSUE TITLE
Page freezing after running code

### ISSUE THREAD

**Issue by 016X** [RunestoneInteractive/RunestoneServer#1375]
**What Course are you in**
Knowing the course will help us a lot
Chapter 8 for Computer Science Principles
**What Page were you on**
Chapter 8 exercises
**What is your username**
I do not have a login
**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.
If I go to the second question on the exercises page and press run without changing any code the webpage will simply freeze. I cannot scroll down or up on the page and cannot interact with the page but I can still switch through my tabs on google chrome
**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
I encountered the bug when trying to complete other exercises but I can recreate the bug on all of the exercises.

**Comment by bnmnetp** [comment]
This is not a bug.  If you read the problem statement it tells you that the program is going to go into an infinite loop, and your job is to fix it.  If you wait about 30 seconds your program will time out.  But by then your browser may be so overwhelmed by print statements that it will take even longer to become unfrozen.
