### ISSUE TITLE
Implementing a Sound Library in Skulpt

### ISSUE THREAD

**Issue by bryantal** [RunestoneInteractive/RunestoneServer#1377]
We are a team of Berea students working to implement a sound library in Skulpt.

**Comment by jennahughes15** [comment]
We have been attempting to understand the overall working of skulpt through the documentation and your blog post. We added a file to simply print "Hello World!" from your example to make sure that we could run that. We were able to perform the npm run dist command, but we encountered errors when running npm run docbi. It stated "missing script: docbi."

**Comment by jennahughes15** [comment]
Great, thank you! Is there a particular sound library that you would like us to implement? Here is a link to the one that we seemed most likely to be helpful: https://docs.python.org/3/library/winsound.html?fbclid=IwAR1iBOSaiHmd7jmsycFy5exOwroQ2hdbo2zAc_S7TmNJ_HoSbWOx46j1ZFk.

**Comment by bnmnetp** [comment]
It is important that the solution be cross platform.  It looks like winsound only works on windows.

The simpler the better, for this really.   If can can just allow students to manipulate a tone play frequency 440 for 3 seconds for example.  would be a great start.  The idea for the sound library is to let students manipulate a linear media stream.  If Dr. Pearce or your library has a copy of Guzdial's media computation book, we would like to be able to replicate some of the examples in that book.

**Comment by bryantal** [comment]
We tried to run a Python file using ./skulpt.py run to generate the compiled program to look through like the HACKING.md file suggested.  We are having trouble understanding what it actually did and where the compiled program is.  It gives us a list of commands and options after we run it, and we are not sure what to do next.

**Comment by jennahughes15** [comment]
We made some progress that we would like to test to see how things are going so far.  We tried to test it the way we described above with no luck, and we also tried to run it by uploading it through fopp to test it that way.  Is there another way that would make testing possible?  We are also in the process of submitting a draft pull request so you can see what we have so far.

**Comment by ashimaathri** [comment]
@bnmnetp Hello! Here's the repository https://github.com/web-cat/skulpt (although it's been several years since the changes and it's not up to date with the latest skulpt version)
