### ISSUE TITLE
2.11-1 can't assign a double to an int

### ISSUE THREAD

**Issue by JackStan** [RunestoneInteractive/RunestoneServer#1378]
**What Course are you in**
CS Awesome

**What Page were you on**
2.11-1

**What is your username**
stansbuj

**Describe the bug**
The following line of code in 2.11-1 has an error:
int num = Math.random() * 50;
since you can't assign a double to an int. I believe both those lines involving the random method are wrong.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
Thanks! Fixed. Will be live on Saturday.
