### ISSUE TITLE
Removing code history from a problem to allow testing redo

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1379]
**Describe the solution you'd like**
I'd like to be able to have students retake a test that they have attempted already. So, a test may have a variety of coding problems. If they have tried it already, then the Load History button will have all of their code attempts already saved up for them. I'd like to be able to give students a retake where the Load History is 'cleared' of all previous attempts.

**Describe alternatives you've considered**
I have duplicated problems - so if I have a program problem called `lhs_test_1` I will make a duplicate of this called `lhs_test_1m`. Then I will make a new assignment that has these duplicate problems.

**Comment by bnmnetp** [comment]
Eliminating history may be possible, but this is one that will probably be a lot more work than it seems like it should.
