### ISSUE TITLE
Codelens in Timed Assessment mode not working

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1383]
**What Course are you in**
LHSIntroCS_2019

**What Page were you on**
Timed Assessment for the Practice Example assignment

**Describe the bug**
The Codelens button, though visible, does not bring up Codelens.

**Comment by bnmnetp** [comment]
Any messages in the Javascript console that might be useful?

**Comment by psmaker** [comment]
When I pressed the Codelens button (in the timed assessment), nothing appeared in the console. 

For reference, when I pressed the Run button I would get a log messages that it was running the activecode. And when I am in a normal non-timed assessment, when I hit the Codelens button, I would see a log message in the console that it is logging the event codelens.
