### ISSUE TITLE
Turtle code won't run from an assignment.

### ISSUE THREAD

**Issue by DCGlasgow** [RunestoneInteractive/RunestoneServer#1389]
CSAwesome
Knowing the course will help us a lot

4.2 - For Loops

DCGlasgow

**Describe the bug**
After creating an assignment, students get an error when trying to run ActiveCode (lcfcp1). Iit indicates that the class World cannot be found. This only happens when selecting from the Assignments page. When going to the page from the TOC, it works fine.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
Yes, this is a known problem and we are working on a solution.  For now please use the regular page.

**Comment by bhoffman0** [comment]
This now works! Thanks Brad!
