### ISSUE TITLE
See assignment without making it visible to students

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/RunestoneServer#1392]
**Is your feature request related to a problem? Please describe.**
When I create a test I would like to see the assignment as the student sees it before giving them access.  What I currently have to do is to briefly make the assignment available to students, load up the Student Assignments page, click on the exam link, and then turn off student availability.  Once I have the link, I can access the assignment even if student visibility is turned off.  Obviously this opens a brief window and if a student happens to load their assignment page at that moment, they will have access to the link and can share it with others.

**Describe the solution you'd like**
I would like to have a link to the assignment right on the Assignment page, perhaps in a button labelled "Preview Assignment" or some such.  The link would look something like https://runestone.academy/runestone/assignments/doAssignment?assignment_id=#####

**Describe alternatives you've considered**
If I could access the assignment_id number for an assignment without making it visible to students, that would be almost as useful for me, but less user-friendly.

**Additional context**

**Comment by vqum** [comment]
https://github.com/RunestoneInteractive/RunestoneServer/issues/1525

https://github.com/RunestoneInteractive/RunestoneServer/pull/1554
