### ISSUE TITLE
Web page keeps resetting when I'm trying to read.

### ISSUE THREAD

**Issue by joshb019919** [RunestoneInteractive/RunestoneServer#1394]
Hi, everyone,

**What Course are you in**
Problem Solving with Algorithms and Data Structures using Python

**What Page were you on**
1.13 Object-Oriented Programming in Python: Defining Classes
But it does this on every page.

**What is your username**
jborthick

**Describe the bug**
Is it a bug or a purposeful reset when all my work gets lost after a few minutes of inactivity?  

Let's say I'm having to read the same paragraph over and over, as reading can sometimes be a bit difficult for me, or maybe I need to research hill climbing algorithms before going back to an activity, where I already had--well, not a lot, but some work already done, and hadn't pressed save yet before:

- Back to top of page

- All unsaved work lost

- Have to find where I was again--and again, and again, and again.

**Traceback**
N/A

**Additional context**
Is there a setting I need to switch?  A subscription I need to buy?  Maybe the server is just too small to give all these great books and still afford to allow people to leave pages open for long periods?

If it's the latter, does anyone have suggestions for overcoming this loss?  I can save every time before I leave an activity, but then there would be dozens of saves to have to look through, and I'd still have to waste time finding my spot, again.

Thank you all,
Josh Borthick

**Comment by bnmnetp** [comment]
The periodic page refresh is to keep you from losing work by thinking that you are logged in when your session has expired due to closing your laptop or whatever.  It is configured for every 15 minutes which I didn't think would be a hardship as the average time on page is definitely less than that.

I don't understand why saving your work is such a hassle.  When you load it, it goes to the most recent thing you saved automatically so there is no need for you to search for your spot.

**Comment by joshb019919** [comment]
As a full time welder preparing for college in August, I'm certainly a special case.  I just wanted, at the very least, clarification to ease my frustrated soul.

Data science and Python are also quite new to me, minus the tutorial primers I've taken, so I have to do a lot of research and playing around in Jupyter Notebook to see what I can and can't get to work for the self-checks and self-check challenges.

I mean, the video is right there, but that's why tutorial Python-as-a-second-language won't get us pay worthy skill levels.  I feel like I need to figure it out and then see how the instructor/tutor did it.

Thank you for your time, bnmnetp.
Josh

**Comment by bnmnetp** [comment]
Thanks for the explanation, and reminder that I should never assume I know anything about who's on the other side of the book.

Best of luck as you prepare for college!

**Comment by joshb019919** [comment]
Thanks!
