### ISSUE TITLE
HTTLADS - 4.1 - Anaconda Installation Link Broken

### ISSUE THREAD

**Issue by Mitch-McK** [RunestoneInteractive/RunestoneServer#1395]
**What Course are you in**
How to Think Like a Data Scientist

**What Page were you on**
https://runestone.academy/runestone/books/published/httlads/PythonReview/installing.html
Chapter 4.1

**What is your username**
Mitch_McK

**Describe the bug**
"Installation Guide" link in paragraph two leads to a 404 page. It should likely lead to this link instead: https://docs.anaconda.com/anaconda/install/

**Comment by bnmnetp** [comment]
Thanks Mitch -- they indeed moved the docs from conda.io to the location you provided.  Will be fixed in the next build.
