### ISSUE TITLE
HTTLADS - 8.5/8.6 - Dropdown Options Don't Match Subchapters

### ISSUE THREAD

**Issue by Mitch-McK** [RunestoneInteractive/RunestoneServer#1396]
**What Course are you in**
HTTLADS

**What Page were you on**
Page One: https://runestone.academy/runestone/books/published/httlads/UNGeneralDebates/graph_relations.html
Page Two: https://runestone.academy/runestone/books/published/httlads/UNGeneralDebates/sentiment_analysis.html

**What is your username**
Mitch_McK

**Describe the bug**
The textbook jumps from subchapter 8.4 to 8.7 and the dropdown does not match. This leaves the last two subchapters as 8.7 and 8.8 instead of being 8.5 and 8.6. (which it seems that they should be). 

![img1](https://user-images.githubusercontent.com/32278637/70926519-45694280-1ffb-11ea-8944-1b8a2046b0fc.png)
![img2](https://user-images.githubusercontent.com/32278637/70926520-45694280-1ffb-11ea-8560-785dede22e56.png)

**Comment by bnmnetp** [comment]
Thanks, I had never noticed that.  Its because we combined some very short sections into single files. I'll break things apart so the sections and the menu are consistent.

**Comment by bjones1** [comment]
I also use sub-subsections in my book, which breaks the dropdown's numbering. Is there any way to pull from the book's numbering, instead of assuming a numbering?

**Comment by bnmnetp** [comment]
The problem stems from combining two sections say 8.2 and 8.3 in a single file.  The whole  chapter and subchapter architecture assumes that each section lives in its own source file.

I think the only way to solve that is to completely redo that whole system which would be backward incompatible and break lots of things.  -- Don't get me wrong I wish we could have more flexibility but it would be some pretty major surgery.

Maybe we need to open an issue and start thinking about a better data model.
