### ISSUE TITLE
Automatic completed not correct

### ISSUE THREAD

**Issue by garrowolf** [RunestoneInteractive/RunestoneServer#1399]
**What Course are you in**
Knowing the course will help us a lot
Foundations of Python Programming

**What Page were you on**
12.6

**What is your username**
garrowolf

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.

There was a change so that instead of selecting completed at the end of the page, it does this automatically. Now it selects completed when you work through the problems. 
I was working through one of the problems and I got it wrong, so I went back and fixed it. Then I moved on to the next question and it showed that I had completed the page. I think that it is counting attempts on the page and not seeing if each question is actually completed so this automatic function doesn't work correctly. 

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
This is the desired behavior, as the exercises in the book are formative and not counted for correctness.
