### ISSUE TITLE
How To Think Like a Computer Scientist, Chapter 4.2 Activity 6

### ISSUE THREAD

**Issue by MayaLove** [RunestoneInteractive/RunestoneServer#1404]
In activity 6 it asks to: 
Modify this program so that before it creates the window, it prompts the user to enter the desired background color. Do similar changes to allow the user, at runtime, to set tess’ color. Do the same for the width of tess’ pen. Hint: your dialog with the user will return a string, but tess’ pensize method expects its argument to be an int. That means you need to convert the string to an int before you pass it to pensize.

When I write       z = input(int("Enter a desired pen size"))
and pass to         tess.pensize(z)

I receive an error ValueError: invalid literal for int() with base 10: 'Enter a desired pen size' on line 3. 

However when I omit "int" and write z = input("Enter a desired pen size")  it works and the pen size is thinner or thicker depending on the entered number. Not sure if it's a bug or I am doing something wrong?

**Comment by bnmnetp** [comment]
you want to have int evaluate what input returns.  Right now you are calling the int function and passing it the string "Enter a desired pen size".  Thats wrong.
