### ISSUE TITLE
FOPP - 7.13 Glossary items not formatted properly

### ISSUE THREAD

**Issue by KSandstrom** [RunestoneInteractive/RunestoneServer#1405]
**What Course are you in**
Foundations of Python Programming

**What Page were you on**
https://runestone.academy/runestone/books/published/fopp/Iteration/Glossary.html

**What is your username**
N/A

**Describe the bug**
```
System Message: WARNING/2 (/home/bmiller/Runestone/web2py/applications/runestone/books/fopp/_sources/Iteration/Glossary.rst, line 18)

glossary seems to be misformatted, check indentation
```
This is the message showing up on 3 of the Glossary items (with line number changing).

**Comment by bnmnetp** [comment]
Fixed -- Thanks.
