### ISSUE TITLE
HTTLADS - Table of Contents - Assignments Link Broken

### ISSUE THREAD

**Issue by Mitch-McK** [RunestoneInteractive/RunestoneServer#1406]
Hi there,

When in the How to Think Like a Data Scientist textbook, clicking the "Assignments" link navigates the user to Assignments page. Currently, clicking the "Assignments" link leads to an error page. 

TOC: https://runestone.academy/runestone/books/published/httlads/index.html
Error Page: https://runestone.academy/runestone/books/assignments/chooseAssignment.html

Image 1:
![assignments](https://user-images.githubusercontent.com/32278637/72268971-cadb1500-35f0-11ea-9e8c-ed7f968be2a7.png)

Image 2: 
![error](https://user-images.githubusercontent.com/32278637/72269009-d7f80400-35f0-11ea-88be-8f0e2c449e26.png)

**Comment by bnmnetp** [comment]
fixed
