### ISSUE TITLE
RunestoneServer/tests README

### ISSUE THREAD

**Issue by wesleywu20** [RunestoneInteractive/RunestoneServer#1418]
I'm currently trying to write a unit test endpoint in Issue #1259, but even after reading through the README multiple times, I still can't quite understand the fixtures, their respective methods, or how to effectively/properly use them in writing a Unit Test Endpoint.

I'd greatly appreciate it if someone could update the README to include not only the methods included with each fixture, but also how to call the methods (the methods' constructors), the methods' parameters, and when to use each fixture.

<img width="924" alt="Screen Shot 2020-02-25 at 3 11 02 PM" src="https://user-images.githubusercontent.com/31138042/75288049-24825200-57e1-11ea-9184-edfbd10cac10.png">
Here is where in the README I hope someone can help out and update!

**Comment by bnmnetp** [comment]
In the meantime, you can get a pretty good idea by looking at the existing tests.  Take a look at the code in test_ajax2.py for example and you will see how the fixtures are used in those tests.
