### ISSUE TITLE
Activities progress counting more attempts than total attempts available as  x of x-1 

### ISSUE THREAD

**Issue by janek33** [RunestoneInteractive/RunestoneServer#1422]
So far on all pages in Python textbook I can see more attempted activities than total number of activites:
"You have attempted 8 of 7 activities on this page"

https://fopp.umsi.education/books/published/fopp/SimplePythonData/Operators.html
![Screenshot 2020-03-02 at 17 28 17](https://user-images.githubusercontent.com/4177822/75696064-411ffd80-5cab-11ea-8052-dc29689e6e11.png)

**Comment by bnmnetp** [comment]
This is an issue with the umsi installation of runestone, not a general problem.
