### ISSUE TITLE
In dark mode, the text in the CodeLens turns white and is displayed on white background

### ISSUE THREAD

**Issue by HillaShx** [RunestoneInteractive/RunestoneServer#1424]
Thank you all for this amazing platform!

I'm studying with the `thinkcspy` interactive book.
I've switched the display to dark mode because I like it better, but it turns all text to white, and in the CodeLens the background stays white, which makes the text in it invisible.
This happens both in Firefox and Chrome.

![Screenshot from 2020-03-13 15-33-51](https://user-images.githubusercontent.com/44138955/76625531-1c941300-6540-11ea-9467-efbc710e70c8.png)
![Screenshot from 2020-03-13 15-33-01](https://user-images.githubusercontent.com/44138955/76625535-1e5dd680-6540-11ea-9837-8bb300f4df7f.png)

**Comment by bnmnetp** [comment]
Thanks, I've implemented a fix for this that should be live this weekend.
