### ISSUE TITLE
Implementing a Queue in Python

### ISSUE THREAD

**Issue by coci** [RunestoneInteractive/RunestoneServer#1429]
**What Course are you in**
Problem Solving with Algorithms and Data Structures using Python

**What Page were you on**
4.12. Implementing a Queue in Python
**What is your username**
cocii
**Describe the bug**
hey mate , in implementation of Queue in python i think you have wrong . in dequeue method you use self.items.pop() that will remove from last but i think you must write self.items.pop(0) which is the first item added into queue

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
Nope, think it through.  Maybe even run the code to see that it works and then figure it out. 😄

**Comment by coci** [comment]
Im so sorry , you right
