### ISSUE TITLE
 Overview of Runestone Interactives link does not work

### ISSUE THREAD

**Issue by schall2395** [RunestoneInteractive/RunestoneServer#1430]
**What Course are you in**
CS Principles: Big Ideas in Programming

**What Page were you on**
https://runestone.academy/runestone/admin/doc

**What is your username**
schall

**Describe the bug**
I am in the process of creating my own assignment for my students and I would like to write my own question.  I wanted to see the documentation so that I knew the exact syntax when writing an active code question.  However, when I click on "Overview Page", I get a 404 page not found error.

**Traceback**

**Additional context**

**Comment by bnmnetp** [comment]
fixed
