### ISSUE TITLE
"404 NOT FOUND" for sigcse2019 course

### ISSUE THREAD

**Issue by MeredinGwenlian** [RunestoneInteractive/RunestoneServer#1435]
**Course:** sigcse2019
**Page:** https://runestone.academy/runestone/books/published/sigcse2019/index.html
**My username:** mschubert

**Bug description:**
When I am logged in and have sigcse2019 as my active course, I get a "404 NOT FOUND" error for the page https://runestone.academy/runestone/books/published/sigcse2019/index.html.
The Runestone homepage redirects me to [.../sigcse2019/index.html](https://runestone.academy/runestone/books/published/sigcse2019/index.html) where I encounter the same error.

**Additional context**
I can continue the course through changing the url to a subidrectory of runestone.academy (e.g. https://runestone.academy/runestone/books/published/sigcse2019/index.html), then clicking on the Runestone logo in the upper left corner (redirects to https://runestone.academy/runestone/default/user/login) and then clicking on the "Instructor Guide" button in the upper widget.
I registered for another course (fopp) and did not encounter an error.

**Comment by bnmnetp** [comment]
The sigcse2019 course name was changed to instructorguide   Please register for that instead of sigcse2019.

**Comment by MeredinGwenlian** [comment]
I just noticed that in Chapter 1 of the instructor guide, the course is still referred to as _sigcse2019_.
Here are the sentences where the old name appears:
* "Please enter sigcse2019 in the Course Name field."
* "If you haven’t yet added this course, sigcse2019, you might want to add it now, so that your work will be saved as you go through this book."
