### ISSUE TITLE
HTTLADS, sec 9.4, problem sql_ex1

### ISSUE THREAD

**Issue by dorin317** [RunestoneInteractive/RunestoneServer#1436]
adrian_ac201s20

making an assignment out of 9.4

username: dorin

**Describe the bug**
Brad,
The statement of exercise sql_ex1 ("Q-1: What is the longest of the rides you just selected?") in not precise. I cannot figure out what "you just selected" refers to. You said that this problem probably has to be deleted. If this will happen, you probably want to relabel (unless done automatically) sql_trips_31111 as Q-1 and sql_trips_return as Q-2.
Cheers!

**Comment by bnmnetp** [comment]
I've removed this problem.

**Comment by bnmnetp** [comment]
This problem was old and when viewed in the context of the textbook it made sense, but not as a standalone question.  The auto-graded version of the question should stand alone.
