### ISSUE TITLE
HTTLADS, sec 9.5, first question in practice exercises 9.5.1

### ISSUE THREAD

**Issue by dorin317** [RunestoneInteractive/RunestoneServer#1437]
adrian_ac201s20

practice exercises 9.5.1

dorin

**Describe the bug**
I believe that the grading code is not optimal. When I execute the following I get an error:

SELECT start_station, end_station, duration
FROM trip_data
WHERE duration >= 3600
ORDER BY duration DESC
LIMIT 40
 
<img width="432" alt="Screen Shot 2020-04-08 at 9 20 22 AM" src="https://user-images.githubusercontent.com/62956644/78906302-2f213f80-7a4d-11ea-8c6d-ed511dbd9c42.png">

But simply putting _duration_ first

SELECT duration, start_station, end_station
FROM trip_data
WHERE duration >= 3600
ORDER BY duration DESC
LIMIT 40

does not lead to errors. Is it something that I do not understand about SQL at play here?
Thanks, Dorin

**Comment by bnmnetp** [comment]
Its not an error you are just not selecting the columns in the same order as the question gives them.  You can see the results of the query, so its pretty easy to see that the values are just in the wrong order.
