### ISSUE TITLE
'else' written as mandatory with an elif

### ISSUE THREAD

**Issue by MayankGoel28** [RunestoneInteractive/RunestoneServer#1438]
**What Course are you in**
pythonds

**What Page were you on**
1.10

**What is your username**
mayankgoel28
**Describe the bug**
 "Note that the final else is still necessary to provide the default case if all other conditions fail."
Untrue.

**Comment by bnmnetp** [comment]
In the context of this example the statement is correct.  You can't just drop out of the bottom of the conditional and print "F" every time.
