### ISSUE TITLE
FOPP: Broken links from projects table to chapters

### ISSUE THREAD

**Issue by MeredinGwenlian** [RunestoneInteractive/RunestoneServer#1443]
**What Course are you in**
Foundations of Python Programming

**What Page were you on**
Index (https://runestone.academy/runestone/books/published/fopp/index.html)

**What is your username**
mschubert

**Describe the bug**
All of these bugs occur in column 2 of the projects table.
- row 9: hypertext "Transforming Sequences", linking to https://runestone.academy/Runestone/books/published/TransformingSequences/toctree.html
  - raises an `invalid request` error
  - should probably link to https://runestone.academy/runestone/books/published/fopp/TransformingSequences/toctree.html
- row 10: hypertext "Nested Iteration", linking to https://runestone.academy/runestone/books/published/MoreAboutIteration/toctree.html
  - brings me to the course selection page with the message "MoreAboutIteration is not the course you are currently in, switch to or add it to go there"
  - should probably link to https://runestone.academy/runestone/books/published/fopp/MoreAboutIteration/toctree.html

**Additional context**
All the other links in column 2 seem to be working fine.

**Comment by bnmnetp** [comment]
Thanks for the report, I've fixed them and the fixes will be live when we rebuild this weekend.
