### ISSUE TITLE
LearnWebGL2 is 404ing for me

### ISSUE THREAD

**Issue by fireflamemm** [RunestoneInteractive/RunestoneServer#1444]
**What Course are you in**
LearnWebGL2

**What Page were you on**
index.html

**What is your username**
jmmarsde

**Describe the bug**
Whenever I click on the link to the LearnWebGL2 course I get an Error 404

**Traceback**
No Traceback.

**Additional context**
No known additional context

**Comment by bnmnetp** [comment]
fixed
