### ISSUE TITLE
Broken, repeated and unhelpful exercises in Chapter 1.12.1 (contributed exercises)

### ISSUE THREAD

**Issue by MeredinGwenlian** [RunestoneInteractive/RunestoneServer#1445]
**What Course are you in**
fopp (Foundations of Python Programing)

**What Page were you on**
https://runestone.academy/runestone/books/published/fopp/GeneralIntro/Exercises.html (Chapter 1.12)

**What is your username**
mschubert

**Describe the bug**
The contributed exercises for this chapter are a mess.
Here is a list of issues:
1. The same question (question1_1) is presented five times in a row instead of just once.
2. irma-Ch1_q2 is not programmed correctly. It should ask me to order five elements. Instead, the elements are just a single text block, making solving the exercise trivial. Here is a screenshot of the exercise:
![irma_Ch1_q2](https://user-images.githubusercontent.com/35040095/80284864-6d8f4d80-8721-11ea-912b-c676024d8cb9.png)
3. irma_Ch1_q3 is displayed twice.
4. ac101_pretest is, as it says, "a placeholder for the pretest score" and hence probably not useful for anyone, but its author. I would suggest removing it.
5. intro_12_1 is simply a copy of assess_question1_1_1. I suggest removing it.
6. dnd_exx1 is presented twice. On top of this, it does not have any contents and is in a language other than English. I do not see the value in foreign language questions in an English course. Knowing English is a prerequisite for the course, hence it should overtax foreign language students to solve exercises in English. On top of this, having foreign language questions increases confusion for people who don't speak the given language. I suggest removing both instances of dnd_exx1
7. Activity 15 is irma_Ch1_q2 again (from "subissue" number 2). The answer field is empty. I suggest removing this exercise.
8. pointer_1_Q1 requires knowledge that the students do not have at this point in the course (namely, if statements and Boolean expressions). The bigger problem, though, is that the answer field does not correspond to the question and is trivial to solve. The answer options should be:
   * `foobar = 0`
   * `foo = 0`
   * `result = foo`
   * `if foobar == foo: print("hello world")`
Obviously, the last line should be two lines with the second one indented. However, I don't know to to format this here on GitHub. This question should be either fixed and moved to a later point in the course (e.g. chapter 8 which covers Boolean expressions and if statements) or removed completely.
9. pa-ex1-cpp requires knowledge the students don't have at this point (e.g. the accumulator pattern) and is not even written in Python. Also, the next question (aaa) is the very same as the previous one just under a different name. I suggest deleting both of the questions.
10. TL_365_h1_q4 is presented twice. I suggest removing one of the instances.
11. Dict_Test requires knowledge that the students do not have at this point (namely, dictionaries). I suggest moving it to Chapter 11. Also, it is presented again as Dict_Test_1. I suggest removing this second instance.
12. Error_check_1 is just a copy of Error_check. I suggest removing it.
13. The exercise Turtle is presented twice (first as Activity 24, then as Activity 27). I suggest removing one of the instances.
14. LizzyPP1 is just a copy of WhileLoop1. I suggest removing LizzyPP1, because it has the worse name out of the two.

**Comment by MeredinGwenlian** [comment]
I had a quick look at some of the other contributed exercises from other chapters: They seem to be in better shape, but I could spot some of the problems of the contributed Chapter 1 exercises here and there.
All this points to a bigger issue: Allowing users to contribute exercises is a great idea imo, but it's of little use if there is no quality control. This is especially a problem for instructors like me. If instructors are not aware of the existence of the contributed exercises (like I was), students will assume that they have to solve these exercises as well. I learned about the contributed exercises through a student telling me that "not every exercise loaded correctly". While the difficulty of an exercise (i.e. if a required skill should have been covered by the course at the point the exercise is presented) is somewhat a matter of opinion, none of the exercises should be duplicates, broken or in a different programming language. Having to sift through this (as I would call it) junk and identify the ones that are at least somewhat usable is more trouble than help for students and instructors alike.
I would suggest to at least include a text block at the beginning of each contributed exercise section that says something like this "These exercises are not part of the official course. You are welcome to attempt to solve them, but they are probably not a part of your homework unless your instructor has explicitly told you otherwise."

I'm aware that this post borders on being a feature request and I'm sorry if I breached that line. Also, after so much (hopefully constructive) critique, I want to stress that I am very much thankful for the existence of Runestone Interactive and grateful for all the work that has been put into it.

**Comment by bnmnetp** [comment]
Thanks for the report.  I like the idea of adding a bit of text at the beginning of the contributed exercises section.

I am aware of the quality control problem, that having contributed exercises has created and to that end have done two things so far.  

1.  There is the Flag for Review button on the question previewer in the assignment building interface.
2.  I've created an interface for editors -- volunteer instructors -- who are willing to look at the questions that have been flagged for review and either remove them as they are duplicates, or just clearly bad.  Move them to a more appropriate chapter in the text, or edit them to make them more clear.

I just launched the "editorial page" a week or so ago, and I put out a call on a couple of the slack channels for volunteers.  Hopefully this will get better with more community help and involvement.

I would really like to institute a rating system, there is a difficulty scale at the moment and an editor can change that, but I think there is probably a lot we could do with analytics and looking at several years of history on these questions to help identify the good ones or to automatically gauge the difficulty.  Happy for more ideas.

Just as a bit of a counterpoint to your complaint, I think its reasonable to assume that instructors will exercise some discretion, and not blindly assign every exercise on a page that contains 200+ exercises!  Actually its unthinkable to me that an instructor wouldn't at least read what they are assigning. I was horrified when I learned that instructors were just clicking on the box next to Exercises and blindly assigning a huge number of problems without even looking!  So I added a warning dialog to ask "Do you REALLY want to assign X number of exercises?"  But these are stressful times...

**Comment by MeredinGwenlian** [comment]
@bnmnetp I am impressed by the breadth of your vision for the future of the exercises feature.

I would like to help with cleaning up at least the questions for chapter 1 of fopp. Could you make me an editor for the fopp course?

Your counterpoint is totally valid. In hindsight it was foolish of me to not have looked at the exercises. Two countercounterpoints (😉) in an attempt to save at least a bit of face:
- I have completed the thinkcspy course. Back then, it had a sizeable number of exercises, but all of them made some sense to me (although I did not complete all of them).
- In a professional textbook, I would expect a sensable number of exercises and for none of them to be broken. Of course, in order to ensure a good learning experience the instructor should have a look at the exercises in this case as well.

**Comment by bnmnetp** [comment]
Thanks for volunteering.  I just added you as an editor.

I agree, in a professional (especially printed) textbook you would not have exercises that are broken --  copy editors find those and make them all red.  I've seen plenty of bad ones though.  That is part of the difference that can make an OER textbook way better, or if we go off the rails -- worse than a printed book.  Hopefully we can adjust to the success of having instructors contribute questions and turn this into a real positive.

I haven't "turned on" the contributed question feature in the thinkcspy book yet, I plan to this summer in the hopes that I can recruit editors to find/fix stuff before fall classes start!  There are lots more contributed questions for that text as it has been around longer.

Here is the link to a short video on accessing and using the editorial page:  https://youtu.be/ErWAni-aAI4

Brad
