### ISSUE TITLE
External Links Broken

### ISSUE THREAD

**Issue by mrcallaghan** [RunestoneInteractive/RunestoneServer#1447]
**What Course are you in**
How to Think Like a Computer Scientist - Python

**What Page were you on**
Section 15.29

**What is your username**
mcallaghan

**Describe the bug**
All of the external hyperlinks on this page are broken.

**Traceback**
NA

**Additional context**
infohost.nmt.edu refused to connect; perhaps the resource has relocated, but I cannot find where.

**Comment by bnmnetp** [comment]
Thanks for the report.  Its hard to keep up.

In the meantime, I would check out the official python docs instead.

https://docs.python.org/3/library/tkinter.ttk.html?highlight=checkbutton

**Comment by bnmnetp** [comment]
Looks like they might have moved here: https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/index.html without a forwarding address.

**Comment by mrcallaghan** [comment]
Thanks!  This documentation always seemed easier to follow for my students rather than the official docs.
