### ISSUE TITLE
Runestone Interactive is not let me in the textbook How to enter into that?

### ISSUE THREAD

**Issue by gambler2020** [RunestoneInteractive/RunestoneServer#1449]
Please login via your learning management system (Coursera, Canvas, Blackboard, etc.)

At the beginning of each study session, you will need to first use one of the links at the top of a lesson that says something like, "Single Sign On: Interactive Textbook and Practice Opportunities." Once you've done that, you'll be able to use the textbook for the duration of your learning sessions, including the links to individual textbook pages in Coursera.
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.

**Additional context**
Every time when i try to open the link provided by Coursera the above text found in the new opened page. please solve this bug as soon as possible.

**Comment by gambler2020** [comment]
![Screenshot from 2020-05-01 15-38-36](https://user-images.githubusercontent.com/18195566/80798378-e24f0580-8bc1-11ea-8e3b-e4f7657bb355.png)
I am getting this page error every time even i am logged in Coursera.

**Comment by bnmnetp** [comment]
We have no control over how Umich and Coursera operate their instance of the Runestone Server, you need to take this up with your instructor at Umich or follow the instructions given to you by coursera.

**Comment by manoj-hariharan** [comment]
I have the same problem... please let me know how this was resolved. Thanks!

**Comment by bnmnetp** [comment]
As I said above, Runestone Interactive has NO CONTROL over the UMSI instance of the server, you need to contact your instructor or contact Coursera support for login issues related to the server used for that course.

**Comment by mostafa610** [comment]
Hi everyone!

If you're having trouble logging into the textbook, try the following steps:

At the top of the activities for each week, find an activity titled, "Ungraded External Tool: Single Sign On: Interactive Textbook and Practice Opportunities"
Click on it and open the tool - this will log you into the textbook
Once you've done so, you'll be able to follow any of the other links to particular pages. If you've been away from the textbook for a couple of days, you may need to access the Single Sign On activity again to login to the textbook again
