### ISSUE TITLE
JS4Python typo

### ISSUE THREAD

**Issue by kleinicke** [RunestoneInteractive/RunestoneServer#1450]
**What Course are you in**
JS4Python

**What Page were you on**
2.5.1 Definite Loop
Last code Example

**Describe the bug**
var data = [3, 7, 2, 9, 1, 11];
var sum = 0;
data.forEach(function(d){
    sum += d;
});
writeln(sum);

d was never initiated. It probably should be data.

**Comment by bnmnetp** [comment]
There is nothing wrong with the example.  `d` is a parameter to the function that is applied to each element in data.  Maybe you could try the example before creating an issue?
