### ISSUE TITLE
webfundamentals: 4.8 Dropdown Menu Project does not work

### ISSUE THREAD

**Issue by VictorNorman** [RunestoneInteractive/RunestoneServer#1460]
In the webfundamentals book, section 4.8, it seems like the dropdown menu project is supposed to create submenus that start invisible and become visible.  I'm not getting that at all. I just see the menu and clicking on any one of the items takes me to a web page.

Username: VictorNorman

**Comment by bnmnetp** [comment]
Somehow a typo was introduced into the CSS rule and `submenu` became `submenuu`

working on fixing it.

**Comment by bnmnetp** [comment]
Fixed
