### ISSUE TITLE
Allow instructors to set whether or not students can pause timed assessments

### ISSUE THREAD

**Issue by RandyCHS** [RunestoneInteractive/RunestoneServer#1462]
**Is your feature request related to a problem? Please describe.**
Right now students can always paused a timed assessment
**Describe the solution you'd like**
When I choose to make an assessment/exercise timed, I would also like to be able to set whether it can be paused

**Comment by bnmnetp** [comment]
Thanks, I'm not sure about this.   Everyone wants to have everything configurable, which leads to more complicated code and a more complex interface.  Just thinking about the exams... Show feedback/don't show feedback, pause/no pause, reset/no reset, show results/don't show results/don't show results until everyone has finished/...

I'm not saying no I'm just letting you know that I see this and I'm thinking about it.

**Comment by RandyCHS** [comment]
@bnmnetp Thanks for following up on this.  I understand that you have to prioritize these issues and your time.  For now, I'll keep on eye on this issue.  When I have some time, and perhaps your guidance,  I'll try to contribute towards adding this feature.  Until then, thanks for all your work in making this such a great teaching and learning platform. :-)

**Comment by bnmnetp** [comment]
Also fixed.
