### ISSUE TITLE
Short Answer does not save input if there is "." in question id

### ISSUE THREAD

**Issue by jjur** [RunestoneInteractive/RunestoneServer#1465]
**What Course are you in**
thinkcspy

**What Page were you on**
Assignment page

**What is your username**
jjur

**Describe the bug**
Some students reported that their answer is not saved after they click save and reload the page. After more investigation, I think it is related to a "." in question id.

**Traceback**

1. Go to assignment page in instructor panel
2. Create or duplicate 2 short answer problems
3. Give them name my_testing_problem1 and my_testing_problem2.1
4. Save and add them to an assignment
5. Visit assignment as student and fill in some random input.
6. Save
7. Reload page
8. my_testing_problem1 contains saved content.
9. my_testing_problem2.1 is empty

**Additional context**
It would be nice to either fix this or set the problems compiler to show warning when it unique id contains .

**Comment by bnmnetp** [comment]
Thanks for the report.    I was able to find the problem and implement a solution.  I'll push an update to runestone.academy this weekend.
