### ISSUE TITLE
Bug in Pythonds3: 7.6 Parse Tree

### ISSUE THREAD

**Issue by parkershamblin** [RunestoneInteractive/RunestoneServer#1468]
**What Course are you in**
Pythonds3

**What Page were you on**
https://runestone.academy/runestone/books/published/pythonds3/Trees/ParseTree.html

**What is your username**
parkershamblin

**Describe the bug**
Referring to Line 16 and Line 22 in Activity 1: Building a Parse Tree (parsebuild)
`current_tree = current_tree.left_child` needs to be corrected to `current_tree = current_tree.child_left`
`current_tree = current_tree.right_child` needs to be corrected to `current_tree = current_tree.child_right`

**Traceback**
AttributeError: 'BinaryTree' object has no attribute 'left_child' on line 16

**Comment by bnmnetp** [comment]
Roman,

The naming in the module does not match the examples and documentation in the book.  I think we should go with the left_child, right_child naming instead of child_left and child_right.

**Comment by parkershamblin** [comment]
@bnmnetp 

Agreed, right_child and left_child are more intuitive.

**Comment by yasinovskyy** [comment]
I agree, will update to `right_chld` and `left_child` soon.
