### ISSUE TITLE
Image link broken section 1.2.3 grace hopper bug report

### ISSUE THREAD

**Issue by GitGilmore** [RunestoneInteractive/RunestoneServer#1477]
**What Course are you in**
CSAwesome

**What Page were you on**
1.2.3

**What is your username**
Bgilmore@stjohnsprep.org
**Describe the bug**
Figure 2 shows a blank box and no image.  Clicking it produces the following:

File not found: /v1/AUTH_mw/wikipedia-commons-local-public.8a/8/8a/H96566k.jpg

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
I'm not able to reproduce this error. The image does show for me and is linked to https://upload.wikimedia.org/wikipedia/commons/8/8a/H96566k.jpg
Perhaps it's being blocked by something on your end? I can download it and include it in the book though, in case other people have the same problem. Thanks.
