### ISSUE TITLE
Lesson 9.9.1 Free Response - Trio A

### ISSUE THREAD

**Issue by stevendubey** [RunestoneInteractive/RunestoneServer#1481]
**What Course are you in**
Knowing the course will help us a lot
**CSAwesome**

**What Page were you on**
[**9.9.1. Free Response - Trio A**](https://runestone.academy/runestone/books/published/csawesome/Unit9-Inheritance/TrioA.html)

**What is your username**
**dubeys**

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.
**It looks like the code runner is expecting to see the main method in a class called "prog" (see error message below).  I added a class declaration for that and the code ran as expected without issues.  Also, I would probably remove the left brace from line 55 since a student should start writing the Trio class from the start to finish.**

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here
**Error: Could not find or load main class prog
Caused by: java.lang.ClassNotFoundException: prog**

**Additional context**

**Comment by bhoffman0** [comment]
You can call the class Trio on line 54 and it would work too (prog is the default but not necessarily the name you need to use).

public class Trio
{

We need the curly brackets to make clear that the main method should be inside that class.
-Beryl
