### ISSUE TITLE
Invalid code for CS-A 2-13-8

### ISSUE THREAD

**Issue by ashokpillaimx** [RunestoneInteractive/RunestoneServer#1483]
**What Course are you in**
CSAwesome CSA course (accessed through boston-pd-2020)

**What Page were you on**
2-13-8 (Unit 2 Practice Test for Objects, Question 8)

**What is your username**
apillai@mxschool.edu

**Describe the bug**
Line 3 is storing the result of a double calculation in an int variable so it will not compile. Also, one would have to round up the number of pizzas to ensure everyone gets their allotment so I would add both an int cast and a shift by 0.5 as follows: 
int numOfPizzas = (int) (0.5 + (numOfPeople * slicesPerPerson)/8);

**Traceback**
N/A

**Additional context**
N/A

**Comment by bhoffman0** [comment]
Thanks for pointing this out! To make it simpler, I changed the method's 2nd argument to an int:  
public void calculatePizzaOrder(int numOfPeople, int slicesPerPerson)
The change will be live on Saturday.
The changed code will compile. Try:
public class Pizza
{
            public void calculatePizzaOrder(int numOfPeople, int slicesPerPerson)
            {
                int numOfPizzas = (numOfPeople * slicesPerPerson)/8;
           
               printOrder(numOfPizzas);
            }

            public void printOrder(int number)
            {
                System.out.println("Order " + number + " pizzas ");
            }
    public static void main(String[] args)
    {
        Pizza p = new Pizza();
        p.calculatePizzaOrder(8,2);
      
    }
}
