### ISSUE TITLE
7-3-5 Activity 8 Autograder broken

### ISSUE THREAD

**Issue by ashokpillaimx** [RunestoneInteractive/RunestoneServer#1487]
**What Course are you in**
boston-pd-2020

**What Page were you on**
7.3

**What is your username**
apillai@mxschool.edu

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.
The Autograder crashes when I try to run the program because it cannot call WordPairsList

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here
Error
./RunestoneTests.java:45: error: cannot find symbol
        WordPairsList list = new WordPairsList(words);
        ^
  symbol:   class WordPairsList
  location: class RunestoneTests
./RunestoneTests.java:45: error: cannot find symbol
        WordPairsList list = new WordPairsList(words);
                                 ^
  symbol:   class WordPairsList
  location: class RunestoneTests
./RunestoneTests.java:57: error: cannot find symbol
        WordPairsList list = new WordPairsList(words);
        ^
  symbol:   class WordPairsList
  location: class RunestoneTests
./RunestoneTests.java:57: error: cannot find symbol
        WordPairsList list = new WordPairsList(words);
                                 ^
  symbol:   class WordPairsList
  location: class RunestoneTests
4 errors

**Additional context**

**Comment by bhoffman0** [comment]
Hi Ashok,
Thanks for reporting this. For some reason it's using the junit test from activity 9 instead of activity 8, but I'm not sure why. I'll look into it.
-Beryl

**Comment by bhoffman0** [comment]
This is now fixed!
