### ISSUE TITLE
Poor phrasing for question 8-1-6

### ISSUE THREAD

**Issue by ashokpillaimx** [RunestoneInteractive/RunestoneServer#1488]
**What Course are you in**
Knowing the course will help us a lot
boston-pd-2020

**What Page were you on**
Section 8.1.4

**What is your username**
apillai@mxschool.edu

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.
For Activity 6 (in section 8.1.4):
The question asks for what would be the output when the following is executed:
int[][] ticketInfo;
System.out.println(ticketInfo);
The correct answer (which took me some trial and error) is "null", however the above lines would result in a compiler error that ticketInfo has not yet been initialized so I have an issue with the phrasing of this question. 

Additionally, when I enter an incorrect answer, I am prompted to test it in the ActiveCode window below, in which the 2D array is already initialized. Thus printing the reference results in output of the form [[I@xxxxxxxx where xxxxxxxx is a memory reference, which really does not help answer the original question.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
Thanks! I will change or delete this question.
-Beryl
