### ISSUE TITLE
Remove dated "assignment dyslexia" term

### ISSUE THREAD

**Issue by thatrobotdev** [RunestoneInteractive/RunestoneServer#1491]
**Is your feature request related to a problem? Please describe.**
In https://runestone.academy/runestone/books/published/csawesome/Unit1-Getting-Started/topic-1-3-variables.html, the term "assignment dyslexia" is used to explain when you switch the order of assignment (ex: `4 = score;` instead of `score = 4;`)

This term of "assignment dyslexia" is a misuse of dyslexia of an adjective [when it is an actual reading disorder](https://en.wikipedia.org/wiki/Dyslexial). It cannot be used interchangeably to mean confusion. I think the use of "dyslexia" here is poor taste.

**Describe the solution you'd like**
All of the mentions of "assignment dyslexia" to be renamed or removed.

**Describe alternatives you've considered**
We could change the name to "assignment confusion" or "assignment switching", which would convey the same meaning.

**Additional context**
Official college board material has stopped using this term, and the furthest back I could find it being used was in [2010 scoring guidelines](https://secure-media.collegeboard.org/apc/ap10_computer_science_a_q1.pdf) 10 years ago. As this term is not being used by the college board anymore, and it is offensive to those with dyslexia, it would be of more academic value to change it or remove it.

**Comment by bhoffman0** [comment]
You're right. I'll remove it. It will be live on Saturday.
Thanks for pointing this out.
-Beryl

**Comment by thatrobotdev** [comment]
Thank you! I really appreciate this change ❤️
