### ISSUE TITLE
Missing word (small typo)

### ISSUE THREAD

**Issue by thatrobotdev** [RunestoneInteractive/RunestoneServer#1494]
**What Course are you in**
CSAawesome

**What Page were you on**
https://runestone.academy/runestone/books/published/csawesome/Unit1-Getting-Started/topic-1-4-assignment.html#operators

**What is your username**
jpkerrane01

**Describe the bug**
The section "1.4.4. Operators" includes the sentence "Isn’t surprising that it prints 0?" which is missing a word, and should be "Isn’t **it** surprising that it prints 0?"

**Additional context**
I opened a PR at https://github.com/bhoffman0/CSAwesome/pull/30 to fix this typo.

**Comment by bhoffman0** [comment]
Thanks! Fixed. It will be live on Saturday.
-Beryl
