### ISSUE TITLE
Answer in Question 9 of 2.17 Write Code Questions has the wrong syntax.

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1496]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/variables/WriteCode.html

**What is your username**
sairamdata123

**Describe the bug**
In the answer section of Q.9  in line 4, the print statement argument has the wrong syntax.

**Traceback**
Error
TypeError: unsupported operand type(s) for Add: 'int' and 'str' on line 4
Description
Type errors most often occur when an expression tries to combine two objects with types that should not be combined. Like raising a string to a power

To Fix
To fix a type error you will most likely need to trace through your code and make sure the variables have the types you expect them to have. It may be helpful to print out each variable along the way to be sure its value is what you think it should be.

**Additional context**
You just need to convert the variable arguments to string using str() function.

**Comment by barbarer** [comment]
Fixed this in py4e-int
