### ISSUE TITLE
Q.3 in 3.2. Logical operators in py4-int has the wrong answer as correct solution.

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1497]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/conditional/logicalOperators.html

**What is your username**
sairamdata123

**Describe the bug**
In Q.3, the numbers 7 and 24 are not between 0 and 5. The answer is given as x > 0 and x < 5. This is the wrong answer. Even the description in the correct answer section is wrong.
The correct answer is x > 0 and x < 25.

**Traceback**
Semantic Error

**Additional context**
Please also make the changes in the description in the correct answer dialog.

**Comment by barbarer** [comment]
Thanks for finding these problems.  They will be fixed soon.
