### ISSUE TITLE
pythonds 7.16 Equation for N_h using Fibonacci Sequence

### ISSUE THREAD

**Issue by sahil-kumar** [RunestoneInteractive/RunestoneServer#1498]
The formula listed for N_h using the Fibonacci sequence is written in this text as:
N_h = F_(h+1) - 1, h>=1

From my understanding, this should be:
N_h = F_(h+2) - 1, h>=1

Even later on, when plugging in the golden ratio, the superscript changes to (phi)^(h+2). Is this a mistake or am I missing something?

**Comment by bnmnetp** [comment]
fixed
