### ISSUE TITLE
Problem in the answer of Q.6 in the given page the i have linked, the book is py4-int

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1499]
**What Course are you in**
py4-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/strings/traversal.html

**What is your username**
sairamdata123

**Describe the bug**
In Q.6 of the given page, what the question asks and the correct result are not matching.
The question asks the number of time "i" is printed the correct answer is 2(since we only print even index characters as per code given) but the given correct answer is 4 (This is the wrong answer).
Also the given correct answer explanation in the dialog box is not correct and not clear.

**Traceback**
Semantic Error. 

**Additional context**
Here i am copying the result i got from running the code
Resutl:
m 
s 
i 
s 
p 
i

**Comment by barbarer** [comment]
Thanks for reporting the mistake.  We will fix it.

**Comment by sairamdata** [comment]
I am sairamdata123. I am reporting bugs in the book py4-int, I feel I am
reporting too many bugs or problems in the book.
I just want to confirm with you if it is ok to report all the problems i
see in the book or should i ignore it?.

Sai Ram

**Comment by barbarer** [comment]
Yes, you should report bugs in py4e-int.  You can report them on the github
for that course at https://github.com/barbarer/py4e-int

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
