### ISSUE TITLE
The activecode prompt takes 7s to load.

### ISSUE THREAD

**Issue by Maccer1** [RunestoneInteractive/RunestoneServer#1500]
**What Course are you in**
Python

**What Page were you on**

https://runestone.academy/runestone/books/published/thinkcspy/Functions/ProgramDevelopment.html

**Describe the bug**

Page takes 7s to load because it's trying to download a 8mb javascript file that makes activecode work. Blocking the request makes the page load instantly.

**Comment by bnmnetp** [comment]
But then your activecodes will not work... 😄 

With the beginning of the fall term we are experiencing extremely heavy loads on the server and doing what we can to keep things as speedy as we can afford to.

**Comment by Maccer1** [comment]
Okay thanks!

**Comment by bnmnetp** [comment]
Your comment also made me realize that my release script was not minifying the runestone.js file... will fix that for the next release.
