### ISSUE TITLE
Specify primary proficiencies in dynamic questions

### ISSUE THREAD

**Issue by numerator** [RunestoneInteractive/RunestoneServer#1502]
**Is your feature request related to a problem? Please describe.**
I need to be able to specify the **primary** proficiency a dynamic exam question tests, and have the system select only questions that have that proficiency as a **primary** proficiency.

**Describe the solution you'd like**
Perhaps a second parameter could be introduced that specifies whether the specified proficiency(-ies?) need to be primary. Perhaps

    .. selectquestion:: dynq_DT04_206_f20
        :proficiency: DT04
        :primary: true
        :points: 1

**Describe alternatives you've considered**
None considered.

**Additional context**
None.

**Comment by bnmnetp** [comment]
We don't need the true, we can just go with `:primary:` as the flag.
