### ISSUE TITLE
Tests fail on a correct solution - 2.9.1. Programming Challenge : Random Numbers

### ISSUE THREAD

**Issue by thatrobotdev** [RunestoneInteractive/RunestoneServer#1506]
**What Course are you in**
CSAwesome

**What Page were you on**
https://runestone.academy/runestone/books/published/csawesome/Unit2-Using-Objects/topic-2-9-Math.html#groupwork-programming-challenge-random-numbers

**What is your username**
jpkerrane01

**Describe the bug**
There is a test on this exercise called "Calls to Math.random() for a random number from 0 up to 40"
The tests fail when you do:
```
for(int i = 0; i < 3; i++) {
           int r = (int)(Math.random() * 40);
           System.out.println(r);
       }
```

but succeed when you do

```
System.out.println((int)(Math.random() * 40));
System.out.println((int)(Math.random() * 40));
System.out.println((int)(Math.random() * 40));
```

even though these are equivalent answers. I'm guessing that the test is counting the number of times `Math.random() * 40` appears in the code instead of counting the number of outputs.

**Comment by bhoffman0** [comment]
Yes, students do not learn to use loops until Unit 4! So this exercise in Unit 2 does assume they won't use loops.
