### ISSUE TITLE
Static columns for names in gradebook

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1507]
In the gradebook webpage, it would be really nice for the first couple columns (ideally checkmarked?) to be frozen so that I can scroll to the right along the gradebook and still see the user's FName and LName.

Can't attach screenshot due to confidentiality. :(

**Comment by bnmnetp** [comment]
I know exactly what you are asking for.  And it is on the list to change the gradebook to use the same Javascript package as we do for the chapter overview reports.
