### ISSUE TITLE
Tests fail when should succeed - Magic 8 Ball

### ISSUE THREAD

**Issue by thatrobotdev** [RunestoneInteractive/RunestoneServer#1512]
**What Course are you in**
CSAwseome

**What Page were you on**
https://runestone.academy/runestone/books/published/csawesome/Unit3-If-Statements/topic-3-2-ifs.html#groupwork-programming-challenge-magic-8-ball

**What is your username**
jpkerrane01

**Describe the bug**
The tests for this question is reporting the number of unique responses incorrectly for my solution. I have done:
```java
public class Magic8Ball
{
   public static void main(String[] args)
   {
     // Get a random number from 1 to 8
     int r = (int)(Math.random() * 7) - 1;
     // Use if statements to test the random number
      if(r == 1) {
          System.out.println("Signs point to yes!");
      } 
       if(r == 2) {
          System.out.println("Try again later.");
      } 
       if(r == 3) {
          System.out.println("Doubtful.");
      } 
       if(r == 4) {
          System.out.println("Have you considered another perspective?");
      } 
       if(r == 5) {
          System.out.println("This will happen.");
      } 
       if(r == 6) {
          System.out.println("YES! YES! YES!");
      } 
       if(r == 7) {
          System.out.println("Don't even try.");
      } 
       if(r == 8) {
          System.out.println("I weep for you.");
      }
       
     // and print out 1 of 8 random responses


   }
}
```

and I am getting this error:
![Screenshot of a table with passing and failing tests](https://user-images.githubusercontent.com/18013689/92624484-cdc3fd80-f284-11ea-919a-0138f3009a57.png).

I have 8 unique responses but it is only counting 6. Is this a bug with my code or with the website? Thank you!

**Comment by bhoffman0** [comment]
Your random numbers only go up to 6, not 8. Print out r and run multiple times to see.

**Comment by thatrobotdev** [comment]
Thank you! 😄
