### ISSUE TITLE
Typo in "How to Think Like a Computer Scientist in Python"

### ISSUE THREAD

**Issue by crjohnson09** [RunestoneInteractive/RunestoneServer#1518]
**What Course are you in**
How to Think Like a Computer Scientist in Python

**What Page were you on**
1.10. Experimental Debugging

**What is your username**
N/a

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.

In the multiple choice question, when picking an option,
Response A appears as: "programming is the process of writing and gradually debugging a program until it does what you want."
where as the correct response prompt says appears as: "Programming is the writing of the source code and debugging is the process of finding and correcting all the errors within the program until it is correct."

The correct response prompt should appear as Response A.

Web Developer View page, see attached image
![bug](https://user-images.githubusercontent.com/63559692/92960405-2b964800-f433-11ea-9fce-5cc4f053c9db.PNG)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by gaweki** [comment]
is it update a "new" definition? @crjohnson09
