### ISSUE TITLE
Cannot login to finish assignments

### ISSUE THREAD

**Issue by MParrado94** [RunestoneInteractive/RunestoneServer#1521]
**What Course are you in**
COSC 1306-17524

**What Page were you on**
Runestone Academy
**What is your username**
Parrado
**Describe the bug**
I cannot login to my account. I have reset the password  twice and the username has be resent to me as well. I am aware my username is not my email. I would like to know if there is a way to recover my profile so I don't have to redo my coding assignments. 

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
My email is Mairyn.m.parrado@gmail.com for any further reference.

**Comment by bnmnetp** [comment]
What browser are you using?  I've had a couple of reports that Safari is giving a few people trouble.  Can you try Chrome or Firefox and let me know if you are still having issues?

**Comment by MParrado94** [comment]
Safari! I just tried Chrome & it worked! Thanks so much for your help!
Enjoy your day!

**Comment by bnmnetp** [comment]
No problem, sorry for the inconvenience!  It should be working again in Safari -- it is for me, after restarting Safari and cleaning out my Cookies.
