### ISSUE TITLE
challenge-7-3-WordPairs : possible auto grade error.

### ISSUE THREAD

**Issue by cdagler** [RunestoneInteractive/RunestoneServer#1522]
Hi,

I think there might be an error in the 2nd auto grade for (challenge-7-3-WordPairs). Please see that attached image. 

![Capture](https://user-images.githubusercontent.com/23296637/93030535-a5b40180-f5d8-11ea-8206-dc5054546c4e.PNG)

or

https://drive.google.com/file/d/102RKs5agMGyYZ95Ophbd9W2mfY-vVlDU/view?usp=sharing

I hope you can see this image

Thanks,
Clay

**Comment by bhoffman0** [comment]
Hi Clay,
Take a look at the [Active Code autograder code](https://docs.google.com/spreadsheets/d/1Fp46BHowUOfgjicpMqmPW0USkEnH1QvexA0lvC2Aos4/edit#gid=723091432) in teacher resources in the shared drive. This test is looking for the output "The number of matched pairs is: 0". I think you forgot to uncomment that output statement in main which calls this method.
-Beryl

**Comment by cdagler** [comment]
I see it now - sorry to bug you.

Thanks!
