### ISSUE TITLE
Cannot score assignment that has been completed in a previous course

### ISSUE THREAD

**Issue by econeil7** [RunestoneInteractive/RunestoneServer#1524]
**What Course are you in**
python-review

**What Page were you on**
Assignments > Review Sequences

**What is your username**
ecf59

**Describe the bug**
After previously completing the fopp course (Foundations of Python Programming), I am now being tasked to complete assignments in python-review. Since the two courses share the same work, my assignment in python-review already contains checkmarks for the completed assignments, however I still had to run code snippets and answer questions in order to get the "complete" status once again. Once totally finished with the assignment, however, there is no Score Me button in order to receive a grade.

**Traceback**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/54642448/93148168-2817f080-f6c1-11ea-8abc-09f5ad2fdd4e.png)

**Comment by bnmnetp** [comment]
This is a feature.  Why would you expect to be able to score assignments that are not in your course?

Separately I have a PR in review so that we can remove the checkmark progress indicators not due to this course.  This should make things consistent.

**Comment by econeil7** [comment]
Sorry, I meant score the current assignment in python-review. At least when I did an assignment before in fopp, there was a gold button to click that would give me 100% on the blue bar at the top for completing all of the readings and activities.

**Comment by bnmnetp** [comment]
Checkmarks are no longer shown for work in previous courses.
