### ISSUE TITLE
Add Preview Assignment to assignment builder

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1525]
It would be more convenient for instructors to have a preview assignment button the assignment tab.  This way they don't have to make the assignment visible and then go all the way to the assignment page to see it.  This would allow instructors to see an assignment right from the assignment page without making it visible to students.

**Comment by vqum** [comment]
Issue also submitted previously:
https://github.com/RunestoneInteractive/RunestoneServer/issues/1392

Pull request:
https://github.com/RunestoneInteractive/RunestoneServer/pull/1554
