### ISSUE TITLE
BeckmanCSP2020 Student Login

### ISSUE THREAD

**Issue by StevanovicNina** [RunestoneInteractive/RunestoneServer#1526]
I am a student in BeckmanCSP2020. I was on the Login page. My username is P1_Stevanovic. The bug is that I cannot log in. I am not using my email address as my username. I am really using the username I made when I registered. I am using the password I made when I registered. I also cannot reset my password because ninastevanovic@yahoo.com, my email, does not, for some reason, receive anything from Runestone, not even in the spam folder.

**Comment by bnmnetp** [comment]
We made some upgrades last weekend that made Safari unhappy.  

1. restart Safari -- if that does not work then
2. clear your browsing history and cookies and restart safari.

**Comment by StevanovicNina** [comment]
I am using Firefox on my MacBook Pro.

**Comment by bnmnetp** [comment]
Have not had any reports of problems with Firefox out of thousands of users.  But I would try the same things.

**Comment by StevanovicNina** [comment]
Thank you very much! Restarting Firefox seems to have worked for me.
