### ISSUE TITLE
Problem with saving grades + comments

### ISSUE THREAD

**Issue by ScottDDexter** [RunestoneInteractive/RunestoneServer#1527]
**What Course are you in**
oop-1

**What Page were you on**
https://runestone.academy/runestone/admin/grading

**What is your username**
dextersd

**Describe the bug**
I am grading the exercise ex_2_10. My grades and comments are not being automatically saved (nor are the fields turning light green). Occasionally, the page has spontaneously 'refreshed', clearing my selections (and evaporating my grades and feedback). I've tried on both Firefox and Chrome with the same behavior. Perhaps this a server problem rather than a proper bug? But this seems to be the best reporting channel either way.

(Thank you!)

**Comment by bnmnetp** [comment]
I cannot reproduce the problem.  If you continue to have a problem can you please check the Javascript console and report any error messages here?

Thanks

**Comment by ScottDDexter** [comment]
Thank you for the lightning response! Further investigation suggests this may be user error (I'm doing it wrong) but I can't figure how to do it right. Here's what happens with JS. Everything is fine until I actually load the responses for ex_2_10, at which point the console shows several instances (probably one per student) of

> Uncaught TypeError: question_points[currAssign] is undefined
>     show https://runestone.academy/runestone/static/js/admin.js?v=1599915613:405
>     success https://runestone.academy/runestone/static/js/admin.js?v=1599915613:558

I should clarify that I'm trying to grade this exercise in the context of the 'chapter' rather than an 'assignment'--and really I'm only interested in providing feedback; I don't need to be able to assign points. But it appears that either I need to assign a point value to these exercises, or else approach them differently? 

My apologies if this turns out to be a support issue rather than something bug-like.

**Comment by bnmnetp** [comment]
@ScottDDexter 

The use case I had in mind for Chapter was just for you to be able to view your students work, not grade it or provide feedback.  If you want to provide feedback then just create an assignment and include the active code's you want to provide feedback on as part of the assignment.

This will also make it much easier for your students to see the feedback and know what you want them to do as the assignment page acts like a worksheet of things for them to complete.

I'm not sure how much work it would be to allow you to just provide feedback on things that are not assigned but I can add it to the list.

**Comment by ScottDDexter** [comment]
No need to add this to the list!--I simply hadn't understood that assignments are the proper vehicle for providing feedback etc. (I think I was a little confused by the fact that ActiveCodes that appear as "in-book" exercises do offer a 'Show Feedback' button.) I blame the headlong rush for my not recognizing this earlier. Thank you for your support...!

**Comment by bnmnetp** [comment]
Your confusion is easy to understand.  Runestone has evolved organically for several years.  Things improve, but sometimes we leave things in for backward compatibility and that ends up causing more confusion.
