### ISSUE TITLE
Syntax error in problem Q-2 of section 6.6 in the book py4-int

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1528]
**What Course are you in**
py4-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/strings/count.html

**What is your username**
sairamdata123

**Describe the bug**
The syntax of the python program in the question of Q.2 is wrong.

Code in the Question:
```
s = "peanut butter"
count = 1
for char in s:
    if char is t:
      count += 1
print(count)
```

As you can see using the **is** statement  is a problem.
And using **t** implies that t is a variable and not a string, this is wrong syntax

The Correct Code for the Question:
```
s = "peanut butter"
count = 1
for char in s:
    if char == "t":
      count += 1
print(count) 
```

This will result in the correct answer 4.

**Traceback**
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    if char is t:
NameError: name 't' is not defined

**Additional context**
Please don't forget about the is operator, although it might work due to python's internal optimization. This is bad form.

**Comment by barbarer** [comment]
Thanks for finding this.  It will be fixed by next Saturday.
