### ISSUE TITLE
Answer for code question in section 6.6 in book py4-int has a syntax error.

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1529]
**What Course are you in**
py4-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/strings/count.html

**What is your username**
sairamdata123

**Describe the bug**
The answer section of the code problem given in section 6.6 of the book has a syntax error.

As default code:
```
def count(text, aChar):
    lettercount = 0
    for c in text:
        if c == aChar:
            lettercount = lettercount + 1
return lettercount
```

The return statement has the wrong indentation.

Correct Code:
```
def count(text, aChar):
    lettercount = 0
    for c in text:
        if c == aChar:
            lettercount = lettercount + 1
    return lettercount
```

**Traceback**
  File "main.py", line 6
    return lettercount
    ^
SyntaxError: 'return' outside function

**Comment by barbarer** [comment]
Thanks for finding this.  It will be fixed by next Saturday.
