### ISSUE TITLE
Q.1 in section 7.7 of book py4-int is not clear and holds no meaning.

### ISSUE THREAD

**Issue by sairamdata** [RunestoneInteractive/RunestoneServer#1530]
**What Course are you in**
py4-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/files/tryExceptOpen.html

**What is your username**
sairamdata123

**Describe the bug**
The question Q.1 is not clear and does not state what the question means to ask.
Question:
Which of the following is something that

A. Try to break the software.
B. Finding flaws in programs.
C. Purchase software.
D. Help with quality tests on software.

As you can see it is not clear what the question is asking.

**Comment by barbarer** [comment]
Thanks for raising this issue.  We had undergraduate students add questions this summer and haven't had a chance to review all of the questions yet.  We will fix this question.
