### ISSUE TITLE
Duplicate questions in exams with ":selectquestion:"

### ISSUE THREAD

**Issue by numerator** [RunestoneInteractive/RunestoneServer#1534]
**What Course are you in**
UMSI IPC

**What Page were you on**
Exam: bpp_comp_exam_f20

**What is your username**
mwnewman@umich.edu

**Describe the bug**
Duplicate questions were chosen for 2 out of four exams. The same question was chosen for different competencies in two different exams.. 
106_W20_FinalJupyter_21 chosen for both ITER05 and DEBUG07.
106_Question_Bank_w16edits_207 chosen for both DT02 and DT04.

**Comment by bnmnetp** [comment]
Working on fix for this today.

**Comment by bnmnetp** [comment]
Version 5.5.0 and higher of the components fix this problem.
