### ISSUE TITLE
jobe_server defined in pavement.py but active code doesn't use it

### ISSUE THREAD

**Issue by cromerMHC** [RunestoneInteractive/RunestoneServer#1537]
A little background... Right now we're running a the docker version of the server for several python courses. It's been working great so far this semester! In the near future we'll be needing java to work as well. From my understanding this means that we'll need a jobe server up and running to handle the compilation process.

I have the jobe server working (tested with the jobe test file) and I edited the pavement.py file to point to the jobe server however when I try to run the code in the AC block it gets a http 500 error. It looks like the book is trying to direct to `http://localhost/runestone/proxy/jobeRun` rather than the one defined in the pavement.py file. 

I saw in the active code docs that a "sphinx_bootstrap/layout.html" file should have a few lines added to it. I assume this is where the problem is as I don't have a "layout.html" file as part of my book. Is this part of the auto-built files and if not, where do I need to put this file and what should be inside of it (just the text noted in the AC docs)?

Below is the contents of the pavement file (based on a python course that will eventually end up in a java course):

```
import os
import sys
import pkg_resources
from socket import gethostname

from paver.easy import options, Bunch
import paver.setuputils

from runestone import get_master_url
from runestone import build  # NOQA: F401 -- build is called implicitly by the paver driver.
from runestone.server import get_dburl

paver.setuputils.install_distutils_tasks()
sys.path.append(os.getcwd())

# The project name, for use below.
project_name = os.path.basename(os.path.dirname(os.path.abspath(__file__)))

master_url = ''
if not master_url:
    master_url = get_master_url()

# The root directory for ``runestone serve``.
serving_dir = "./build/" + project_name
# The destination directory for ``runestone deploy``.
dest = "./published"

options(
    sphinx=Bunch(docroot=".",),

    build=Bunch(
        builddir=serving_dir,
        sourcedir="_sources",
        outdir=serving_dir,
        confdir=".",
        template_args={
            'login_required': 'True',
            'loglevel': 10,
            'course_title': project_name,
            'python3': 'True',
            'dburl': 'postgresql://user:password@localhost/runestone',
            'default_ac_lang': 'python',
            'jobe_server': 'http://192.168.1.22:4001',
            'downloads_enabled': 'True',
            'enable_chatcodes': 'True',
            'allow_pairs': 'True',
            'dynamic_pages': 'True',
            'use_services': 'true',
            'basecourse': project_name,
            'course_id': project_name,
            # These are used for non-dynamic books.
            'appname': 'runestone',
            'course_url': master_url,
        }
    )
)

# if we are on runestone-deploy then use the proxy server not canterbury
if gethostname() == 'runestone-deploy':
    del options.build.template_args['jobe_server']
    del options.build.template_args['proxy_uri_runs']
    del options.build.template_args['proxy_uri_files']

version = pkg_resources.require("runestone")[0].version
options.build.template_args['runestone_version'] = version

# If DBURL is in the environment override dburl
options.build.template_args['dburl'] = get_dburl(outer=locals())


```

**Comment by bnmnetp** [comment]
The latest docker-compose setup has a JOBE server configured and included.

I find it far easier to proxy all of the JOBE requests through the Runestone server to avoid CORS issues.

I don't know what you are referring to for changing the layout.html but that sounds outdated at the least, and just wrong at the worst.

**Comment by bnmnetp** [comment]
PS. These 3 entries in your pavement.py file can be used to customize your JOBE server access:

```
            "jobe_server": "http://jobe2.cosc.canterbury.ac.nz",
            "proxy_uri_runs": "/jobe/index.php/restapi/runs/",
            "proxy_uri_files": "/jobe/index.php/restapi/files/",
```

If these are not there the default is to proxy through the runestone server.

**Comment by cromerMHC** [comment]
Oh ok, I'll ff my local repo and try again. 

Thanks!

**Comment by cchaz003** [comment]
What should jobe_server and the proxy_uri_runs / proxy_uri_files be set to if we're using the built-in docker jobe server? Let's assume that the server is local to my machine so my browser is being pointed to localhost when I fire up Runestone.

**Comment by bnmnetp** [comment]
The docker-compose file configures the jobe server to be simply jobe, just like the postgres server is configured as simply db.  If you don't configure anything for jobe in your pavement.py it will use the runestone server as its proxy and everything will just work.
