### ISSUE TITLE
I cannot log in 

### ISSUE THREAD

**Issue by abbeymcfarland** [RunestoneInteractive/RunestoneServer#1538]
**What Course are you in**
Computer science 121
Knowing the course will help us a lot

**What Page were you on**

abbeymcfarland

**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.
I keep trying to log in to my account and the page will refresh and not log me in. I tried changing my username and password and have received no emails from runestone in order to change it. I can't access my class or assignments.
**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
You will need to have your instructor reset your password.  They can do this through the instructor interface on the Manage Students tab.  I'm sorry but some schools have email filtering systems in place that block emails for various reasons, or require a human to click on something to verify that it is a real sender.  I cannot click on all of those emails as there are 100's of password resets every day.
