### ISSUE TITLE
xss

### ISSUE THREAD

**Issue by GeorgeTorres-py** [RunestoneInteractive/RunestoneServer#1542]
https://runestone.academy/runestone/books/published/pythonds/BasicDS/Objectives.html

hey i was able to use the "onmouseover=" and add "alert(document.domain) " for xss. just roll mouse over back arrow button on bottom of the page.

<li id="relations-prev" style="opacity: 0.4;" onmouseover="mouseOverPrev()" onmouseout="mouseOutPrev()" class="navLink" title="" data-toggle="tooltip" data-original-title="Previous Section - 4. Basic Data Structures">
    <a href="toctree.html" aria-label="4. Basic Data Structures">
        <div style="background-color: white; border-style:solid; border-color:lightgrey; border-width:2px; width:100px; height:50px">
            <i class="prevNav glyphicon glyphicon-chevron-left" style="top:50%; transform:translateY(-50%)translateX(-50%); left: 50%; color:black;"></i>
        </div>
    </a>
  </li>

![cksql_00000](https://user-images.githubusercontent.com/70286427/94386780-4c31f380-00fd-11eb-878d-b16ea413e659.png)

**Comment by bnmnetp** [comment]
Sorry, I'm not following what the problem is.  Can you elaborate a bit?

**Comment by GeorgeTorres-py** [comment]
Hey sorry,

So im able to execute reflective cross site scripting. Not only can you display the document.domain but an attacker can also use document.cookie and steal the users session cookies. 

https://portswigger.net/web-security/cross-site-scripting/reflected

**Comment by bnmnetp** [comment]
But there is no input on that page.  Of course you can do it from the console. You can do it from any browsers console window.

**Comment by GeorgeTorres-py** [comment]
But it you could possibly make stored xss

**Comment by bjones1** [comment]
We are always happy to find and fix security vulnerabilities. However, this report lacks substance. If you have a genuine vulnerability to report, please provide a specific report.
