### ISSUE TITLE
Solution Error: Multiple Choice (3-11-10-A) CSAwesome

### ISSUE THREAD

**Issue by cham30909** [RunestoneInteractive/RunestoneServer#1543]
Q-1: Shawn is 4 years older than Sam. Two years from now Shawn’s age will be twice Sam’s age. What should be in place of the following condition to solve this problem?

ERROR LINE 1:  missing ; in the for statement
               for (int s1 = 1, s1 <= 50; s1++){
  
The answer is set for NONE OF THE ABOVE.  Please clarify the question as to whether we are searching for Shawn and Sam's CURRENT age or their AGE two year from now.

If searching for current age the condition needs a set of parenthesis  around (s2+2).
             **if ( (s1 == (s2 + 4)) && ((s1 + 2) == (2 * (s2 + 2)) ) )**

If searching for the age they WILL BE in 2 years then choice C is correct for the condition
             **C. (s1 == (s2 + 4)) && ((s1 + 2) == (2 * s2 + 2))**

**Comment by bhoffman0** [comment]
This was actually a teacher-contributed question in the question bank, but I flagged and fixed it.
