### ISSUE TITLE
Unable to get to the Progress Page

### ISSUE THREAD

**Issue by coopw1** [RunestoneInteractive/RunestoneServer#1545]
**What Course are you in**
Computer Science A

**What Page were you on**
Attempting to go to the progress page
**What is your username**
coopw
**Describe the bug**
When trying to go to the Progress Page on the user dropdown, it doesn't load and goes straight to the "Report a Bug" page.
**Traceback**
```    Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/runestone/views/assignments/index.html", line 262, in <module>
KeyError: 'pct'```

**Comment by bnmnetp** [comment]
fixed
