### ISSUE TITLE
CSAwesome 3.12.3.1. More String Methods compilation errors

### ISSUE THREAD

**Issue by dmalpiCS** [RunestoneInteractive/RunestoneServer#1548]
CSAWesome

https://csawesome.runestone.academy/runestone/books/published/csawesome/Unit3-If-Statements/magpie3.html

dmalpicaAPC

When the the active code is saved and ran, there are compilation errors that don't make sense.

Code on active code window:

`public class StringExplorer
{

   public static void main(String[] args)
       {
          String sample = "The quick brown fox jumped over the lazy dog.";

              //  Demonstrate the indexOf method.
              int position = sample.indexOf("quick");
              System.out.println ("sample.indexOf(\"quick\") = " + position);

              //  Demonstrate the toLowerCase method.
              String lowerCase = sample.toLowerCase();
              System.out.println ("sample.toLowerCase() = " + lowerCase);
              System.out.println ("After toLowerCase(), sample = " + sample);

              //  Try other methods here:

      }
}`

Error messages:

./RunestoneTests.java:12: error: ';' expected
         String expect = "sample.indexOf("quick") = 4\n...";
                                          ^
./RunestoneTests.java:12: error: ';' expected
         String expect = "sample.indexOf("quick") = 4\n...";
                                               ^

**Comment by bhoffman0** [comment]
This was a missing backslash in the autograding junit test for this example. I've fixed it and it should be live soon. Thanks for reporting it.
-Beryl
