### ISSUE TITLE
Low Priority: Progress bars exceed 100%

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1550]
I just noticed that in AP CSA Course progress in unit 3 some of the progress bars exceed 100%. It doesn't really matter too much as I don't use this for grading, but I thought you might want to know in case it's indicative of a larger bug.

<img width="1212" alt="Screen Shot 2020-10-14 at 11 54 28 AM" src="https://user-images.githubusercontent.com/26631024/96020808-34a07d80-0e14-11eb-8e9a-64254abcd31b.png">

**Comment by bnmnetp** [comment]
Thanks,

Its probably related to the changes we made for only showing the completed status for the current book.  I'll have to dig into it to be sure.
