### ISSUE TITLE
Insufficient Instructor Privileges

### ISSUE THREAD

**Issue by kmcglotten** [RunestoneInteractive/RunestoneServer#1551]
I created a class about a day ago, but when I try to access the Instructor's page I am getting insufficient privileges. Is there a certain amount of time I need to wait before the class is operational?

Thank you

**Comment by bhoffman0** [comment]
No, it is immediate, but you are probably not in the right course. Do user icon/Change Course and choose your course. If you still don't see the instructor's page, then you may have picked a course name that was already in use so got placed in it as a student. Try creating a new course with a unique name, for example name-of-your-school-2020. Hope that helps!

**Comment by kmcglotten** [comment]
Thank you so much!

That was the problem.

**Comment by bnmnetp** [comment]
@bhoffman0 I fixed that issue weeks ago.  If you try to create a course with a name that already exists it will make you pick a new name.
