### ISSUE TITLE
CS Awesome Dark Mode - diagrams are unreadable

### ISSUE THREAD

**Issue by michaelsarris** [RunestoneInteractive/RunestoneServer#1552]
**What Course are you in**
CS Awesome

**What Page were you on**
4.1 While Loops, though the issue is present on any page with a diagram

**What is your username**
michaelsarris

**Describe the bug**
A student showed me "Dark Mode" In Dark Mode, any image that is a diagram has a transparent background and that makes the diagram unreadable.  Images that are pictures are unaffected.  For example, on 4.1 While Loops, Figure 3 is unreadable -- the only thing that remains are the white boxes for "loop body" and "next statement" and everything else is solid black.  Figure 4 is fine because it has a white background.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
Thanks for reporting this and to your students for testing things in dark mode! It never would have occurred to me, but you're right that the images with transparent backgrounds have problems in dark mode. I can't think of an easy way to find them all, but I'll work on it.
-Beryl

**Comment by bhoffman0** [comment]
Fixed. Should be live tomorrow.
