### ISSUE TITLE
Instructor Page > Chapter Progress > 999.0 Prefix on every row of CSV download?

### ISSUE THREAD

**Issue by gdeckart** [RunestoneInteractive/RunestoneServer#1556]
I am relatively new to Runestone and I am incredibly thankful for this wonderful tool for my AP CSP students.  My question - I have about 40 students enrolled in CS Principles: Big Ideas in Programming.  I believe I used to be able to pull a CSV download for "Chapter Progress" from my Instructor Page.  This CSV download was very useful as I could sort and filter to help understand the specifics of each students' progress.  I believe the download used to have EACH ROW labled w/ the "Chapter_Label" that included the specific chapter number and section as a part of the label.  NOW when I look at the same report, the prefix for every row in the "Chapter_Label" column (B) in the spreadsheet is 999.0 instead of the actual chapter/section number.  Am I messing something up, or did something change over the last several weeks?  Thanks

**Comment by bnmnetp** [comment]
The book needed a bit of high level restructuring to be compatible with some changes we made at least six weeks ago.

The author of StudentCSP is no longer actively maintaining that book.  We could use someone to give it some attention!

I tried a few quick changes that look like they have resolved your problem.

Brad

**Comment by gdeckart** [comment]
Brad - #1 - Thanks for jumping on that question & resolution so promptly.  #2 - Will you please email me at gdeckart@wsfcs.k12.nc.us about that book "getting some attention?"  I'd be open to putting some energy into the project as both my students and I have gotten A LOT out of it!!  That being said.......   I am surely at the "entry-level" point of my own CSP trajectory!
