### ISSUE TITLE
AP CS A Java Course 3-11-6 answer wrong 

### ISSUE THREAD

**Issue by Royhowtohack** [RunestoneInteractive/RunestoneServer#1557]
**What Course are you in**
Knowing the course will help us a lot
AP CS A Java Course
**What Page were you on**
3.11
**What is your username**
Royhack
**Describe the bug**
A clear and concise description of what the bug is.  Vague statements like X does not work are not helpful.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
<img width="690" alt="Screen Shot 2020-11-09 at 21 33 07" src="https://user-images.githubusercontent.com/52094557/98620989-4dcc1980-2341-11eb-9c3d-586b27514231.png">

**Comment by bhoffman0** [comment]
Cannot duplicate. c is accepted as the correct answer in CSAwesome. Perhaps this screenshot was taken before clicking on check me.
