### ISSUE TITLE
Failure to send Password or Username Recovery emails

### ISSUE THREAD

**Issue by KingDee241** [RunestoneInteractive/RunestoneServer#1558]
**What Page were you on**
Login, Password and Username Recovery
**What is your username**
Bragol
**Describe the bug**
Upon attempting to send a username recovery email. the site says the email was sent. however, no email shows up. Apon attempting to recover password, the site says the email failed to send. 

**Additional context**
Would really appreciate this being fixed so I can not fail my class, thanks!

**Comment by bnmnetp** [comment]
Several hundred people reset their passwords successfully each day.

I have no control over the kinds of email firewalls that various schools put in place.  Some of them allow mail from Runestone others do not.

In any case you can contact your instructor and they have the ability to reset your password for you.
