### ISSUE TITLE
turtle.Screen().setworldcoordinates() Broken on Runestone.

### ISSUE THREAD

**Issue by rckoepke** [RunestoneInteractive/RunestoneServer#1559]
**What Course are you in**
COSC1306-17524

**What Page were you on**
https://runestone.academy/runestone/assignments/doAssignment?assignment_id=51778
**What is your username**
rckoepke

**Describe the bug**
I'm facing a bug in Runestone. 

Here is a minimum code necessary to reproduce the bug:

```py
import turtle
turtle.Screen().setworldcoordinates(8, 6, 96, 96)
turtle.goto(90,  7)
turtle.dot()
turtle.goto(30,  7)
turtle.dot()
turtle.goto(30,  87)
turtle.dot()
turtle.goto(90,  87)
turtle.Screen().setworldcoordinates(8, 6, 96, 96)
```
Multiple versions of this code work in my local IDE / iPython environment, as well as on http://www.repl.it/

In that case, during the drawing phase (before the second `.setworldcoordinates()` ) I get this, incorrect, drawing:

![image](https://user-images.githubusercontent.com/18340603/100004220-d0ff5d80-2d8c-11eb-87e2-b63aedd6c8a1.png)

I would expect to get this, correct, drawing -- which was generated with the exact same code copy/pasted to another interpreter environment ( http://www.repl.it/ and also reproduced on my own personal computer)

![image](https://user-images.githubusercontent.com/18340603/100004244-d8bf0200-2d8c-11eb-8af2-8381c356ee0b.png)

It's pretty clear that only the bottom 3 points appear in Runestone.

However, this is all before the second .setworldcoordinates() runs. After the second  .setworldcoordinates() function call, Runestone no longer renders the turtle view at all, and the page renders like this:

![image](https://user-images.githubusercontent.com/18340603/100004273-e2e10080-2d8c-11eb-9636-46770d02ee9c.png)

It just shows a bold black line where the green square should be.

Additionally, there is an invisible, but selectable, element in the shape of the green square but no amount of my own HTML/CSS/JS edits were able to make it visible.

![image](https://user-images.githubusercontent.com/18340603/100004301-eb393b80-2d8c-11eb-9615-470126c36973.png)

I believe my use of .setworldcoordinates() is correct. My program runs flawlessly in other environments.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**
Here is an example of the same code working correctly in another environment (simply copy-pasted the code) and hit run.
https://repl.it/@RossKoepke/MagnificentSpicyFolder#main.py

**Comment by bnmnetp** [comment]
Thanks for the report.  This should be reported to the skulpt project which is the home for python in the browser and the turtle graphics package.

It appears that If you use setworldcoordinates(0,0,96,96) things look as expected.

**Comment by rckoepke** [comment]
@bnmnetp Thanks for pointing me in their direction, I'll follow up with them!

**Comment by bnmnetp** [comment]
Fixed in new build of skulpt, merged into Runestone.
