### ISSUE TITLE
Question display in timed exams (or maybe just selectquestions)

### ISSUE THREAD

**Issue by numerator** [RunestoneInteractive/RunestoneServer#1560]
**What Course are you in**
IPC

**What Page were you on**
taking exam: 
.. timed:: bpp_comp_exam_f20
    :timelimit: 120

**What is your username**
mwnewman@umich.edu

**Describe the bug**
All question instructions are pre-pended with 'Q-1.' regardless of where they appear in the exam. This is also true of questions that I preview using the competency search mechanism.

**Comment by bnmnetp** [comment]
Add the line
```
generate_component_labels = False
```
to conf.py
