### ISSUE TITLE
Activity 3.18.3 Bad Characters in active code window

### ISSUE THREAD

**Issue by kmcglotten** [RunestoneInteractive/RunestoneServer#1562]
**What Course are you in**
Problem Solving with Algorithms and Data Structures using C++

**What Page were you on**
3.18. Palindrome-Checker

**What is your username**
kmcglotten@facilitatesolutions.com

**Describe the bug**
When running 3.18.3 my students and I get the following error:

_Error: Bad Characters in the activecode window. Likely a quote character that has been copy/pasted._

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
Yep, it looks like some bad quotes were copied into that problem.  For example:

```
    cout << palchecker("Are we not pure? “No sir!” Panama’s moody Noriega brags. “It is garbage!” Irony dooms a man; a prisoner up to new era.") << endl;

```
