### ISSUE TITLE
my code got deleted on runestone

### ISSUE THREAD

**Issue by gwoodhead1225** [RunestoneInteractive/RunestoneServer#1563]
Hi, I was hoping there was a way to retrieve code that did not save on runestone. 
Thank you

**Comment by bhoffman0** [comment]
If you are logged into Runestone, everything is saved. For Active Codes, you do need to click on the Load History button above each Active Code to see your previous attempts.

**Comment by gwoodhead1225** [comment]
> If you are logged into Runestone, everything is saved. For Active Codes, you do need to click on the Load History button above each Active Code to see your previous attempts.

But I forgot to hit save and run so nothing shows up when I hit load History
