### ISSUE TITLE
Activity: 5.16.12 Multiple Choice (mid_1_11)

### ISSUE THREAD

**Issue by adwsmith** [RunestoneInteractive/RunestoneServer#1564]
Here is the question:

int x = -5;
while (x < 0)
{
   x++;
   System.out.print(x + " ");
}

The possible answers are: 
A. 5 4 3 2 1
B. -5 -4 -3 -2 -1
C. -4 -3 -2 -1 0
D. -5 -4 -3 -2 -1 0
E. -4 -3 -2 -1

B is given credit for being the corrected answer.

When I run the code, I get:
-4 -3 -2 -1 0  

My answer makes sense because you are incrementing before printing.

**Comment by bhoffman0** [comment]
Cannot reproduce. Your answer is graded as correct.
![image](https://user-images.githubusercontent.com/4571962/101292497-d376a400-37dd-11eb-8bf8-f45b8c759980.png)
