### ISSUE TITLE
Timed exam question display - extra " :"

### ISSUE THREAD

**Issue by numerator** [RunestoneInteractive/RunestoneServer#1566]
**What Course are you in**
UMSI IPC

**What Page were you on**
bpp_comp_exam_f20

**What is your username**
mwnewman@umich.edu

**Describe the bug**
![image](https://user-images.githubusercontent.com/1970901/101404520-bfe24080-38a4-11eb-8f11-64028e314897.png)

The question instructions are pre-pended with " :". The code for this question is here:

https://github.com/umsi/ipc/blob/master/_sources/NEST04/PP/SI106_W20_Midterm2_14.rst

Is this a bug or is my RST wrong?

**Comment by numerator** [comment]
This appears to be an issue with Parsons Problems but not Active Code problems.

**Comment by bnmnetp** [comment]
Fixed.
