### ISSUE TITLE
U7L4 use of achar and char - I think that these need to be clarified a bit in the chapter.

### ISSUE THREAD

**Issue by ewdillard** [RunestoneInteractive/RunestoneServer#1567]
In 7.4,1 the use of achar - 
for achar in "Go Spot Go":
    print(achar)
So if I read the code - and the explaination around it - I would supose that this essential pulls a one character string (a space, letter, number or other item - probably on the ASCII table.

Further down in this lesson - 7.4 
s = “python rocks”
For ch in s:   
   print(“HELLO”)
So if I read the code and the xplaination around it - I would supose that this essential pulls a one character string (a space, letter, number or other item - probably on the ASCII table.

So what is the difference between ch and achar - they both appear to be looking at a single character.  My kids will ask.  In searching around my normal spots - I can't find a good answer on the web.  Help please.  And this could use clarification in the text please.

--

**Comment by bnmnetp** [comment]
What book are you using?  Please be specific about the book and the chapter.

`achar` and `ch` are simply variable names you can use any legal variable name you want as the loop variable.  This is covered in quite a bit of detail in both the How to think book as well as the Foundations of Python programming book, but again I can't tell which book you are using.
