### ISSUE TITLE
9.6.1. groupwork Programming Challenge : Shopping Cart 2

### ISSUE THREAD

**Issue by xbousquet** [RunestoneInteractive/RunestoneServer#1568]
The last bullet point in the 9.6.1 directions state:

- Make sure you print out the number of discounted items in the main method **or in printOrder()**, so that you can test your method.

Unfortunately, it appears that if the student chooses the second option and writes the required code in **printOrder()**, the unit testing fails. For example, the following code compiles, runs, and produces good output... but fails:

/** printOrder() will call toString() to print */
   public void printOrder() {
      System.out.println(this + "\nNumber of Discounted Items: " +
                        this.countDiscountedItems());
   }

I truly appreciate that CSAwesome directions often allow the students some flexibility & creativity in their approach during each lesson. If the unit testing could for 9.6.1 could be updated to align with the directions, that would be super :)

- - - - -

PS: This CSAwesome course is worth it's weight in gold (if weight were measured in semicolons ;). Students in my diverse Title 1 school had little chance with other AP CSA curricula, but CSAweseme has closed the gap: they are engaged, confident, creative, and making incredible progress, regardless of prior coding experience--thank you!!!

**Comment by bhoffman0** [comment]
Thank you for reporting this! And the lovely compliments :-). I will take a look and make sure it accepts that too.
-Beryl

**Comment by bhoffman0** [comment]
I removed this test. It will be live on Saturday. Thanks for reporting it!
