### ISSUE TITLE
Parsons Problems have a ':' at the beginning of the instructions. There is no ':' in the rst at that position.

### ISSUE THREAD

**Issue by numerator** [RunestoneInteractive/RunestoneServer#1569]
**What Course are you in**
UMSI IPC 

This code: https://github.com/umsi/ipc/blob/master/_sources/STR05/PP/StudentCSP_CSPStringPieces_mix_stringPieces_rst_17-10-3.rst

Displays with an extra ':' at the beginning. This is true of all Parsons Problems.
![image](https://user-images.githubusercontent.com/1970901/102226392-51aa0900-3eb6-11eb-9527-fa615a5dcbdf.png)

**Comment by bnmnetp** [comment]
This is fixed in the latest release.
