### ISSUE TITLE
Scratch ActiveCode does not work thinkcpp course

### ISSUE THREAD

**Issue by n7ihq** [RunestoneInteractive/RunestoneServer#1570]
**What Course are you in**
thinkcpp

**What Page were you on**
Any

**What is your username**
jimla

**Describe the bug**
I tried to use the Scratch ActiveCode window to input the following program:

#include <iostream>
using namespace std;
// main: generate some simple output
int main () {
    cout << "Hello, World." << endl;
    return 0;
}

When I ran the program I got the following error message:

Error
SyntaxError: bad input on line 2
Description
This message indicates that Python can't figure out the syntax of a particular statement. Some examples are assigning to a literal, or a function call
To Fix
Check your assignment statements and make sure that the left hand side of the assignment is a variable, not a literal or a function.

**Comment by bnmnetp** [comment]
Thanks for the report.

@pearcej 
It appears that we are missing a parameter in template_args dictionary of the pavement.py file. `default_ac_lang : "cpp"`

**Comment by barbarer** [comment]
I have fixed this.
