### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by kwame1414** [RunestoneInteractive/RunestoneServer#1574]
**What Course are you in**
Knowing the course will help us a lot
CSA Java
**What Page were you on**

**What is your username**
kwame1414

**Describe the bug**
my email is kquansah@irvingisd.net and i have been trying to reset my password but its not working. Please help. Thanks

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
Hi,

There is no username kwame1414 in the database. - Hint:  usernames are case sensitive.
In some cases schools have various email filters that block runestone.  We can't do anything about that.  In any case you can ask your instructor to reset your password for you.

**Comment by kwame1414** [comment]
Oh ok. But it says my email (kquansah@irvingisd.net) is already in the database. Im not sure what my username is or my password.

**Comment by bnmnetp** [comment]
If the email is not coming through to you then you need to contact your instructor.  We will not reset passwords  without being able to verify that the account really belongs to you.

**Comment by kwame1414** [comment]
But i am the instructor. It is my email.

**Comment by kwame1414** [comment]
Is there a way i can prove it please?

**Comment by bnmnetp** [comment]
Well, you are not the instructor of the course called CSAJava.

I will send an email using that email address.  You will need to respond with a link to some kind of web page that shows me you are a faculty member at your school.

As a faculty member I'm sure you understand that I cannot just reset passwords without verification or there would be chaos.  I am also at the mercy of school IT departments many of whom set up weird email screens that always expect a human to click on things or answer riddles to prove that new email address is not spam. I can't spend my time doing that.
