### ISSUE TITLE
Some assigned problems not showing in assignment

### ISSUE THREAD

**Issue by bmontana** [RunestoneInteractive/RunestoneServer#1577]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

- _Didn't find this issue_

**What Course are you in**
- _PES_COOP_2021_, using **thinkcspy**

**What Page were you on**
- https://runestone.academy/runestone/assignments/doAssignment?assignment_id=52868

**What is your username**
- bmontana-edu (teacher)
- cooper.b22 (student)

**Describe the bug**
- Assignment was created in 2020, with a due date of 12/8 (the due date has since been changed to 1/8/21). All six assigned problems were visible to students in December. Today, only three of the six problems are now visible to students. Problems assigned from Chapter 8 were
  - lhs_8_2
  - lhs_8_3b
  - lhs_8_4 (not visible)
  - lhs_8_5 (not visible)
  - lhs_8_8
  - lhs_8_9 (not visible)
- Page has been reloaded, and cache has been cleared.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment]
Hi,

Over the break I updated Runestone with some big internal changes.  This included changes to the way some questions are represented in the HTML.  I ran a database update that seemed to fix the vast majority of the questions.  But the questions that were not visible had a lot of text and formatting in the question part, so my update may have done more harm than good.

In any case I fixed your 3 questions by Editing them and regenerating the html and then saving.

You can do the same if you run across any more damaged questions.

Sorry for the inconvenience.

**Comment by bmontana** [comment]
Thanks for taking care of that issue for that assignment. The same thing is happening for the problems on this page: [https://runestone.academy/runestone/assignments/doAssignment?assignment_id=51009](https://runestone.academy/runestone/assignments/doAssignment?assignment_id=51009)

I don't own the problems, so I cannot edit/save them. Would you mind fixing them for me?

**Comment by psmaker** [comment]
@bmontana - I'm the author of the lhs_* questions and just noticed the problem that you are seeing. I was wondering why some old problems were not showing up correctly and then found the issue here in the github. 

I'm trying to regenerate the HTML for the problems that don't show up, but if I miss something, just let me know and I can also regenerate the HTML w/o having to bother Brad so he can work on the hard stuff.

**Comment by bnmnetp** [comment]
Thanks @psmaker !!
