### ISSUE TITLE
Student issue - "Check Understanding" and "Coding Exercises" not displaying correctly

### ISSUE THREAD

**Issue by ktsarnowski** [RunestoneInteractive/RunestoneServer#1579]
Check Understanding and coding exercises just show up as empty boxes for one of my students. 
[csawesome 6.1.pdf](https://github.com/RunestoneInteractive/RunestoneServer/files/5791331/csawesome.6.1.pdf)

**Comment by bhoffman0** [comment]
6.1 loads okay for me. This might be a slow internet connection or the browser they are using or some kind of blocker. Please ask them to try Chrome or Firefox.

**Comment by bnmnetp** [comment]
@bhoffman0 - I'm pretty sure it was a stale cache issue.  I looked at the source and in csawesome we have

```
<script src="runestone.js"></script>
```
When we should have
```
<script src="runestone.js?v=XYZ123"></script>
```

I tracked this back to the setup function in conf.py for csawesome.  We wrote a custom version of `app.add_js_file` that adds the extra stuff to prevent stale cache issues.  I updated the setup function in conf.py and rebuilt csawesome so all should be well.  But I'll send you the updated function so it is part of the official distribution.

**Comment by bhoffman0** [comment]
Got it and merged. Thanks!

**Comment by ktsarnowski** [comment]
I finally heard back from this student today, and the issue is still not resolved. It is difficult to troubleshoot these issues for online students. Do you have other suggestions for him to try?

**Comment by bnmnetp** [comment]
Most of the time any issue like this is due to some kind of Javascript error.  A screenshot of the Javascript Console is almost always the most helpful bit of information as it will contain an error message that points to the problem.  But it is super difficult when it is isolated to just one or two students.  I've had no other reports of problems like this.

**Comment by bnmnetp** [comment]
Also, I would still have them try a "hard refresh" of their browser to make sure they are getting the latest of everything.

**Comment by ktsarnowski** [comment]
The problem was related to an antivirus program that the student's father had installed. Sorry it took so long to respond. It was difficult to get answers from the student. Thanks for your help.

**Comment by bnmnetp** [comment]
Good to know!  Do you happen to have the details about the antivirus software that caused the problems?  I would be useful to know for future reference.
