### ISSUE TITLE
Grading returns 0 for work that is completed

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1580]
Student has completed the work (all green checkmarks) and I have downloaded his code as well and it seems to be all complete. However, the autograder for the assignment still gives 0 (or almost 0). I have attached the relevant files.

The course name is CTECH_AP_CSA_FALL_2020
The student's name is Isaac Smutzer username: ISmutzer

[code_for_ISmutzer.csv.txt](https://github.com/RunestoneInteractive/RunestoneServer/files/5806066/code_for_ISmutzer.csv.txt)
![unknown](https://user-images.githubusercontent.com/26631024/104399989-6c07ee80-5517-11eb-8f86-6f1c1ba10b5c.png)

<img width="733" alt="Screen Shot 2021-01-12 at 3 09 49 PM" src="https://user-images.githubusercontent.com/26631024/104399911-41b63100-5517-11eb-94f0-3a187fe6c907.png">
<img width="377" alt="Screen Shot 2021-01-12 at 3 08 40 PM" src="https://user-images.githubusercontent.com/26631024/104399912-424ec780-5517-11eb-9db4-90eca36f5e3a.png">
<img width="816" alt="Screen Shot 2021-01-12 at 3 07 04 PM" src="https://user-images.githubusercontent.com/26631024/104399913-42e75e00-5517-11eb-9a57-8429c53b745c.png">

**Comment by bnmnetp** [comment]
If you look at the Chapter Activity report you will see that he hasn't actually done much/anything in those sections.  Checking the button at the bottom of the page will give the green checkmark, but the student actually has to do the activities to get the points.
<img width="592" alt="Screen Shot 2021-01-13 at 7 41 12 AM" src="https://user-images.githubusercontent.com/51115/104475502-07c74800-5574-11eb-9a2a-bca84ec53b5a.png">

**Comment by jobartucz** [comment]
Hi Brad, that's exactly what I was confused about and why I included the code download. When I went through the file of downloaded code, it looked like he had actually done a lot of it. Thanks, John.

**Comment by bnmnetp** [comment]
The file you included contains YOUR code not ISmutzer's code.

**Comment by bnmnetp** [comment]
Turns out that misleading code dump file is not your fault, but a bug in the new code added to allow you to download code.  Fixed.  will deploy Saturday morning.

**Comment by bnmnetp** [comment]
Doing some manual queries confirms the accuracy of the report I shared.

**Comment by jobartucz** [comment]
That makes sense. Thanks for checking it out so thoroughly.
