### ISSUE TITLE
Foundations of Python Programming: assessment question assess_ps_02_06

### ISSUE THREAD

**Issue by kkbolger** [RunestoneInteractive/RunestoneServer#1581]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Foundations of Python Programming
Knowing the course will help us a lot

**What Page were you on**
ActiveCode assess_ps_02_06
**What is your username**
katebolger
**Describe the bug**
A clear and concise description of what the bug is. Vague statements like X does not work are not helpful.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here
<img width="737" alt="Screenshot 2021-01-13 at 3 47 11 PM" src="https://user-images.githubusercontent.com/64800417/104508682-9a88d680-55b6-11eb-9085-e06894f2340e.png">

**Additional context**

**Comment by bnmnetp** [comment]
What operating system and browser are you using?  I'm not able to reproduce this problem.
