### ISSUE TITLE
Python for Everybody - Interactive: Chapter 2.17 Code Exercise ActiveCode (var-wc-fruitq)

### ISSUE THREAD

**Issue by peterdcasey** [RunestoneInteractive/RunestoneServer#1586]
The auto grader does not appear to work correctly. The float answer does not exactly equal what the grader expects. This section of the book does not discuss equality errors with type float. The correct answer may be obtained with **totalCost = int(totalCost * 100) / 100** but this is not discussed in the chapter. Using round() does not seem to work either.

![2021-01-18_15-14-25](https://user-images.githubusercontent.com/4030080/104970349-fdf07b00-599f-11eb-9de4-b70d35325d2b.jpg)

**Comment by peterdcasey** [comment]
Since this questions is **very difficult** for beginners to get correct, maybe is should be fixed. (Comparing float values with == generally fails, I expect the UnitTest did so.)

Just a thought, Peter

**Comment by bnmnetp** [comment]
Yep, this should use AlmostEqual

**Comment by barbarer** [comment]
Will do

**Comment by barbarer** [comment]
I have fixed it and it will be live on Saturday.
