### ISSUE TITLE
TestCaseGui.assertIn switches expected/actual

### ISSUE THREAD

**Issue by ProfessorO** [RunestoneInteractive/RunestoneServer#1587]
**What Course are you in**
CPTR-215-FOPP-Planning

**What Page were you on**
https://runestone.academy/runestone/assignments/doAssignment?assignment_id=42074

**What is your username**
ProfessorO

**Describe the bug**
Unit tests that use self.assertIn report the first parameter as "Actual" and the second as "Expected", when in most cases, if I'm checking that X is in Y, X is the expected item, and Y is the actual result. I can rewrite it as self.assertTrue(X in Y) instead, but that defeats the purpose of having assertIn at all.

See Exercise RO_test_getEditorText (named that because I thought self.getEditorText wasn't working). I'm testing whether a particular function definition (def stuff) appears in the source code.

**Comment by bnmnetp** [comment]
The python docs on this are frustratingly vague, referring to them as first and second rather than actual and expected.
