### ISSUE TITLE
Answers Not Saving

### ISSUE THREAD

**Issue by sweetpotatotots** [RunestoneInteractive/RunestoneServer#1588]
**What Course are you in**
SH_APCSAPeriod2b

**What Page were you on**
6.2 Traversing Arrays with For Loops

**What is your username**
parishistoria

**Describe the bug**
When I click on the score me button, my answers do not save and my score is a 0. This happened on some of my other assignments too.

**Comment by bnmnetp** [comment]
The "Score Me" button does not save your answers.  You need to click on the Check Me button or Run & Save button or the save button for each question as you are working on the problems.
