### ISSUE TITLE
Two different error cases when adding students via CSV file

### ISSUE THREAD

**Issue by bribmorrison** [RunestoneInteractive/RunestoneServer#1594]
When adding students to a course using CSV files, if a username is already taken the error message is "username already exists". Unfortunately you don't have any way of knowing if it's my student in another course or a completely different user in which case I need to create a different username for them. Any thoughts on perhaps giving a different error message on those cases? (i.e., when student ID or email match vs. don't match)?" Would be much more helpful.

**Comment by Eaw7** [comment]
Hello, I would love to work on resolving this issue if no one else is working on it.

**Comment by bnmnetp** [comment]
Thank you @Eaw7 ! Go for it.

**Comment by Eaw7** [comment]
@bnmnetp Thank you! I am working on it now.
