### ISSUE TITLE
Python for Everybody - Interactive Course: Activity: 6.9.7 Multiple Choice (e5mc7)

### ISSUE THREAD

**Issue by peterdcasey** [RunestoneInteractive/RunestoneServer#1598]
**What Course are you in**
Python for Everybody - Interactive Course

**What Page were you on**
Chapter 6.9 Question Q-7

**What is your username**
peterdcasey

**Describe the bug**
With the correct answer the "Check Me" button responds with the error **X and Red** but says "Correct"

**Comment by barbarer** [comment]
Thanks for catching this! It is fixed and should be live by Saturday.
