### ISSUE TITLE
When an assignment is updated, total score might not be.

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1600]
I assigned a bunch of exercises in 2.11-2.14 as problems. I then removed 5 of them.

Originall the assignment had 48 points, now it has 43. 

Now when I run the auto-grader it works properly (shows out of 43 points), but if I go into the gradebook after running it and look at the percentages, the scores are too low. Someone that got 43/43 shows 89.58% (43/48) instead of 100%

Thanks,
JB

**Comment by jobartucz** [comment]
It still says 38 in the assignment.

**Comment by bnmnetp** [comment]
I just checked the database, and there are 38 questions for that assignment, each worth 1 point.  So 38 is correct.  (I also see that some questions require manual grading)

**Comment by jobartucz** [comment]
Ah, never used that before. PEBKAC error again. Thanks.
