### ISSUE TITLE
Grading in Unit 19 Reading of ThinkLikeACS Not Scoring Correctly

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1601]
Course: LHSIntroCS_2020

Page: Instructor's Page/Grading Tab

Username: LHS CS Team

Description:
When grading the Unit 19 Reading assignment consisting of reading the pages in 19.1-19.7, the max score for any student is 2/7. The page 19.1, which only has a reading assignment, is being scored as a 0.

![image](https://user-images.githubusercontent.com/28868409/107815220-ebabf780-6d27-11eb-932e-c884b254312a.png)

**Comment by bnmnetp** [comment]
I'm trying to reproduce this problem but I cannot.

Is this still a problem?  Did you check the deadline?  Maybe you accidentally made the deadline too early?

**Comment by psmaker** [comment]
I just tried to change the due date to this coming Friday and to regrade it. It only scores 2 points of the possible 7. And most all students are the same way - the same 2 reading sections (19.2 and 19.7) get credit, but all the others are 0.

**Comment by psmaker** [comment]
See the summary table and how the average score is 0 on most of the reading assignments. Only 19.2 and 9.7 seem to get scored.

![image](https://user-images.githubusercontent.com/28868409/108803420-7a521d00-754f-11eb-9d19-d1d9e4775197.png)

**Comment by bnmnetp** [comment]
If you want to grade everything for just one student you cannot select all of the questions, just select the student and it will autograde everything for that student.  This is a long standing TODO and is explained in the initial grading page.

**Comment by psmaker** [comment]
Yeah, I auto-graded graded it w/o selecting the box. But then I just
displayed it afterward to see the individual scoring (because a minor issue
is that after auto-grading, the score does not show the new score, but then
by selecting all the questions, the upgraded grade will appear and show the
details of the auto-grade).

Just to triple check, I regraded all students again (no boxes selected).
Max score is still 2/7.

**Comment by bnmnetp** [comment]
Is this a new assignment or maybe is it an assignment that you copied from last term?  I'm not sure if that would matter, just trying to collect information.

Also have you tried making a new reading assignment with the same sections chosen.  Does it grade the same?  Like I said I made an identical assignment and it is grading fine.

**Comment by psmaker** [comment]
Hmm... odd. I did copy it from last year.

I made a "New Reading 19" assignment, made it the same and re-graded one
person - "LHS CS Team". It now scores 4/7. But there are still 3
assignments scored as 0 - sections 19.1, 19.5 and 19.6 still show as a 0.

**Comment by bnmnetp** [comment]
OK, found the problem.  Always a good first step toward a solution. 😬 Should have a fix for ya by Saturday.

**Comment by bnmnetp** [comment]
Actually it was a small enough change that I just pushed it.  I'm 90%+ sure this will fix your problem based on looking at the code and manually trying some of the queries.  So let me know how it goes.

Thanks!

**Comment by bnmnetp** [comment]
@psmaker Did that fix the problem??

**Comment by psmaker** [comment]
Sorry I didn't get back to you - yes it did!  Thanks so much! You may close
this issue.

**Comment by bnmnetp** [comment]
🎉
