### ISSUE TITLE
CS Awesome 8.8.2 PictureLab Day 4: 2D Array: Multiple errors in Multiple choice

### ISSUE THREAD

**Issue by michaelsarris** [RunestoneInteractive/RunestoneServer#1603]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot
CS Awesome

**What Page were you on**
8.8.2 PictureLab Day 4: 2D Arrays
https://csawesome.runestone.academy/runestone/books/published/csawesome/Unit8-2DArray/pictureLabDay4.html

**What is your username**
michaelsarris

**Describe the bug**
1) For multiple choice 9-11-2, the third option (c) appears as:
public int getCount() {
  int total = 0;
  for (int i = 0; i < matrix.length; i++) {
     for (int j = 0; j < matrix[0].length; j++) {
         total = total + arr[j][i];
     }
  }
  return total;
}

This has two errors. The first is that arr[j][i] is not defined. The only thing it could be would be matrix[j][i]

The second error is that even if it was matrix[j][i] instead, this code would blow up any time the number of rows and columns is not the same. I verified this by putting the code in a test class. It was fine for a 4x4 array, but caused an exception for a 3x8 array. This shouldn't be a correct answer as is

2) For multiple choice 9-11-4, there are also two errors

a) This method is called getColTotal() but is performing a find function -- you are finding the target, not totaling a column. This is confusing to anyone familiar with PictureLab

b) Answer choice C is:
public int getColTotal(int target) {
  int count = 0;
  for (int[] rowArray : matrix) {
     for (int item : rowArray) {
         total = total + item;
     }
  }
  return count;
}

This won't find the target, but it will total all the items in the array. Well, total is undefined, so it won't do that either. But that's what the logic would do. This choice is listed as correct, but shouldn't be.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bhoffman0** [comment]
Hi Michael,
Thank you for these fixes. A student assistant was working on these picture lab pages and has not finished them. I marked the page as not complete, but I could remove it for now. I'll fix these by Saturday.
-Beryl
