### ISSUE TITLE
Can not create instructor account

### ISSUE THREAD

**Issue by LezaBaker** [RunestoneInteractive/RunestoneServer#1605]
Good day to you.My name is Leza Marie Baker - here is my linkedin info so that you can verify that I am a teacher linkedin.com/in/leza-baker-94218461
I teach overseas in China and I am trying to use CS Awesome and your site for a new computer class that we are offering this next semester. China's company email rules are different than the USA, so I typically use my gmail email lezambaker@gmail.com for my accounts. This is the same account that I used with CSAwesome account set-up. If you can please allow me to create this account I will be grateful as my "school" email address is also a .com  - leza@ynact-edu.com, this is how they do things here - out of my control. I will be happy to provide you with a copy of my teacher's license to prove that I am a teacher if you need additional support. Your help in this matter is greatly appreciated

**Comment by bhoffman0** [comment]
Hi Leza,
You don't need to be approved to create a custom course with a instructor's page. Here are some directions and a video to get you started: [https://www.csawesome.org/runestone-e-book](https://www.csawesome.org/runestone-e-book)
-Beryl
