### ISSUE TITLE
LTI and Schoology fails with 404

### ISSUE THREAD

**Issue by stevencoombs** [RunestoneInteractive/RunestoneServer#1606]
When using the LTI with Schoology I get a error 404 page.

Please let me know what other information may be useful.

Thanks,.

Steve

**Comment by bnmnetp** [comment]
@stevencoombs in order for us to have any hope of helping with this you need to give a LOT more information and it needs to be detailed.  What you have given us doesn't even give us a starting point.

When does it fail with 404?  How do you have it configured in Schoology?  What course are you using?  What steps have you taken so far?

You may have better luck getting hellp with this on one of the mailing lists or in the LTI channel on slack.  I have never used Schoology myself nor do I have a copy of it to test with.  But others may have it working, I know people have it working on both Moodle and Canvas, so there is probably reason to hope.
