### ISSUE TITLE
"Forgot Username" issue / alternate

### ISSUE THREAD

**Issue by ktrahan** [RunestoneInteractive/RunestoneServer#1608]
"Forgot Username" indicates it sends an email, but it never arrives.  I waited main hours, and check Spam.
If I try to create a new account, I get the error that my email address is already in the database.

The github confirmation email arrived, so my school account is getting outside emails.
Other teachers in my district (and email domain) use Runestone.

If there is no code error here -- if the email is getting blocked someplace -- is there an alternative to finding my username?  Resetting my password?

Email:   keith.trahanATsduhsd.net

                    Thx, KAT

**Comment by bnmnetp** [comment]
Hi,

Can you try doing the username / email recovery from https://runestone.academy instead of csawesome.runestone.academy?

**Comment by bnmnetp** [comment]
Grrr... 

It should be fixed now for both csawesome.runestone.academy and plain runestone.academy.

Google stopped accepting connections from runestone to send email with my gmail account and there was no warning or message.  I had to reconfigure my gmail account, but this should be good for the long haul now.
