### ISSUE TITLE
2.9.1.1 ActiveCode (code2_9_3) 

### ISSUE THREAD

**Issue by MMorro1** [RunestoneInteractive/RunestoneServer#1609]
it prints the correct answer, but it says I only have 4 out of 5 correct. Here is the code:

public class MathChallenge
{
public static void main(String[] args)
{
int passcode1 = ((int)(Math.random()*40)); // 1. Use Math.random() to generate 3 integers from 0-40 (not including 40) and print them out.
int passcode2 = ((int)(Math.random()*40));
int passcode3 = ((int)(Math.random()*40));
System.out.println(passcode1 + ", " + passcode2 + ", " + passcode3);

double combinations = Math.pow(40,3); // 2. Calculate the number of combinations to choose 3 numbers between 0-40 (not including 40) using Math.pow() and print it out.
System.out.println(combinations); // For example, Math.pow(10,2) is 10^2 and the number of permutations to choose 2 numbers between 0-9.

}
}

The following code scores all 5 points (basically print out the 3 random numbers separately):

it prints the correct answer, but it says I only have 4 out of 5 correct. Here is the code:

public class MathChallenge
{
public static void main(String[] args)
{
int passcode1 = ((int)(Math.random()*40)); // 1. Use Math.random() to generate 3 integers from 0-40 (not including 40) and print them out.
int passcode2 = ((int)(Math.random()*40));
int passcode3 = ((int)(Math.random()*40));
System.out.println(passcode1);
System.out.println(passcode2);
System.out.println(passcode3);
double combinations = Math.pow(40,3); // 2. Calculate the number of combinations to choose 3 numbers between 0-40 (not including 40) using Math.pow() and print it out.
System.out.println(combinations); // For example, Math.pow(10,2) is 10^2 and the number of permutations to choose 2 numbers between 0-9.

}
}

**Comment by bnmnetp** [comment]
Please, what book are you using. The bug report template is there for a reason if you don't give us complete information its very hard to help.

**Comment by MMorro1** [comment]
My apologies - the course is "CSJava"   I had never submitted a bug before,
and was trying to get the report submitted before class began.

Kind regards,
Peggy
Dr. Morrow teaches Computer Science, Math,
Marian Consecration, and Media for homeschoolconnections.com
"One day, through the rosary and the scapular, our Lady will save the
world."
*Saint Dominic*
