### ISSUE TITLE
Applied Computing 1 Textbook (Introduction to Google Sheets and SQL) - Module C (Basic Descriptive Statistics) - link to weather data is missing

### ISSUE THREAD

**Issue by schroeder147** [RunestoneInteractive/RunestoneServer#1610]
I am working on the Applied Computer Computing Textbook 1 (Introduction to Google Sheets and SQL)

My runestone username is tschroeder@bennington.edu

In the "Basic Descriptive Statistics" Module - many activities require a weather dataset. 

There appears to be no link to this dataset in the book.

**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot

**What Page were you on**

**What is your username**

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
I see the reference to the dataset but I'm not seeing anything that actually uses it.  I don't have access to the data set in question. Can you link me to a page that actually uses it for something?

**Comment by schroeder147** [comment]
[This page](https://runestone.academy/runestone/books/published/ac1/basic_descriptive_statistics/minimum_and_maximum.html) asks for a response using the weather dataset (toward the bottom).

**Comment by schroeder147** [comment]
[This page](https://runestone.academy/runestone/books/published/ac1/basic_descriptive_statistics/measures_of_spread.html) also asks for a response using the weather dataset

**Comment by schroeder147** [comment]
[This page](https://runestone.academy/runestone/books/published/ac1/filtering_and_grouping/grouping_data.html) is asking for a response based on the Titanic dataset

**Comment by bnmnetp** [comment]
Here is a link to the weather dataset:  https://docs.google.com/spreadsheets/d/1Xsyg-UoptE-lqSxIqgPVfKXETiMNqLl79Af9q9ynxPA/edit?usp=sharing

The titanic dataset is widely available on kaggle and other places.

**Comment by schroeder147** [comment]
Great. Thanks much.

**Comment by jeremyallenjacobson** [comment]
The issue remains, there is an exercise that ask for the min of a column from this dataset for example.
