### ISSUE TITLE
I would like the ability to copy an assigngment from the same course

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneServer#1613]
**Is your feature request related to a problem? Please describe.**
I have to create two assignments for every midterm - one for people with the normal amount of time and one for people with extending time.  It would save me time if I could copy the assignment but this is currently limited to copying from another course and not the same course.

**Describe the solution you'd like**
Allow copying from the same course - you could automatically name it CopyOfOrigName.

**Describe alternatives you've considered**
I currently have to create a second assignment with the same questions in the same order and same grading.

**Additional context**
I use this for midterms.

**Comment by vqum** [comment]
For visibility to avoid duplication of effort, I'm taking a shot at building this feature this week.
