### ISSUE TITLE
12.3 Exam 2, Explanation has an error.

### ISSUE THREAD

**Issue by ashnisheth** [RunestoneInteractive/RunestoneServer#1618]
I am in the CS Awesome course, preparing for the AP CS A Exam. In exam 2 (12.3), question 14-3-2 has an error in its explanation. It says that when list.remove(2) is called on the ArrayList [6, 2, 9], "The 2 at index 1 is removed resulting in [6, 9]." It should instead say that the 9 at index 2 is removed, resulting in [6, 2]. The end result is still correct, but the explanation has to be updated.

**Comment by bhoffman0** [comment]
Thanks! Fixed. Will be live tomorrow.
