### ISSUE TITLE
CSAwesome - 9.2 - First Coding Exercise

### ISSUE THREAD

**Issue by jgw6092** [RunestoneInteractive/RunestoneServer#1619]
CSAwesome --> Chapter 9 --> Lesson 2 (Inheritance and Constructors) --> First coding exercise
When the program is run, the output is 
"Dani"
3
The correct output should be 
"Dani"
1
https://csawesome.runestone.academy/runestone/books/published/csawesome/Unit9-Inheritance/topic-9-2-constructors.html

**Comment by bhoffman0** [comment]
Thanks for reporting this. It's because our autograder is also calling the class to test things and that increments the static variable. I'll have to look into how we can fix this.

**Comment by bhoffman0** [comment]
Fixed with a hack to reset the nextId counter in the autograding code. It will be live tomorrow. Thanks for reporting this!

**Comment by jgw6092** [comment]
Ok, thanks!   And thanks for putting out a great free product.  My students truly benefit from the quality and differentiated instruction.  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Beryl Hoffman ***@***.***> Date: 3/19/21  8:24 PM  (GMT-05:00) To: RunestoneInteractive/RunestoneServer ***@***.***> Cc: jgw6092 ***@***.***>, Author ***@***.***> Subject: Re: [RunestoneInteractive/RunestoneServer] CSAwesome - 9.2 - First Coding Exercise (#1619) 
Fixed with a hack to reset the nextId counter in the autograding code. It will be live tomorrow. Thanks for reporting this!
