### ISSUE TITLE
 6.4.2.1 is not showing up as runnable in CSAwesome

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1640]
6.4.2.1 is not showing up as runnable - it just shows the text for a problem.

**Comment by bhoffman0** [comment]
Could you send me a screenshot? Activity: 6.4.2.1.2 ActiveCode (lcfrhbb1) did run for me. Is that the one you meant? Thanks!
![image](https://user-images.githubusercontent.com/4571962/114617929-bdd72680-9c76-11eb-966e-b608ba236bc0.png)

**Comment by jobartucz** [comment]
About 5 different students reported this issue. Here is a screenshot:

![unknown](https://user-images.githubusercontent.com/26631024/114618235-bc096500-9c6e-11eb-867e-7f5b4fcdb134.png)

**Comment by jobartucz** [comment]
and this one

![20210404_214652](https://user-images.githubusercontent.com/26631024/114618324-d4797f80-9c6e-11eb-8d02-37f42dcfddac.jpg)

**Comment by bhoffman0** [comment]
Hi John,
These all work in the book. When you go to your assignment page, do they work for you? Do you think there's some other problem that's teacher-contributed and not in the book. in that assignment that's making everything else not work on that page? Could you or a student can do CTRL-SHIFT-i and send us any Javascript console errors that show up?
thanks,
-Beryl

**Comment by jobartucz** [comment]
It works for me too, so I'll see if they can send me a screenshot.

**Comment by jobartucz** [comment]
![Untitled](https://user-images.githubusercontent.com/26631024/114630626-a43adc80-9c80-11eb-95ae-7c65db467329.png)

If this is not working, we can open a group chat in Discord with the students that are having the issues.

**Comment by jobartucz** [comment]
resolved as teacher-created question issue.
