### ISSUE TITLE
coding problem in assignment is different than in context

### ISSUE THREAD

**Issue by jobartucz** [RunestoneInteractive/RunestoneServer#1641]
Some of the `<string>` declarations have a lowercase `s` in the assignment, but they are correctly uppercase `<String>` "in context"

Look at Line 22, for example in 7.4.10.4:

Assignment: 
![2](https://user-images.githubusercontent.com/26631024/114629616-866c7800-9c7e-11eb-85b2-578e52456788.PNG)

"In Context":
![1](https://user-images.githubusercontent.com/26631024/114629625-89ffff00-9c7e-11eb-8c46-a01e7311fa67.PNG)

**Comment by bnmnetp** [comment]
I think you are using `frq2019Q3B-delim-copy` in your assignment??  Which will point to the same page.  The copy needs to be rebuilt to take advantage of a bug fix I made a couple months ago.

**Comment by jobartucz** [comment]
I just made this assignment a couple weeks ago, though?

**Comment by jobartucz** [comment]
Resolved.

**Comment by jobartucz** [comment]
oops, closed wrong issue.

**Comment by bhoffman0** [comment]
This one is the same problem, so if you use the book version instead of a
teacher-contributed one, it should work.

**Comment by jobartucz** [comment]
closed for real this time :)
