### ISSUE TITLE
p9-4: If x = 93, what will print when the following code executes?

### ISSUE THREAD

**Issue by smpropmanager** [RunestoneInteractive/RunestoneServer#1647]
p9-4: If x = 93, what will print when the following code executes?

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "E"
print(grade)
A. A  # <---- clicking this will provide the correct answer status. 
B. B
C. C
D. D
E. E

# I'm sure you'll see the issue here as x and score has no assignment or relationship. Great job otherwise. --Happy User and Donor

**Comment by bnmnetp** [comment]
Thanks for your support and for the report.  But can you please let me know the book you are using.  A link to the page would be even more helpful.

**Comment by smpropmanager** [comment]
Hi Bradley,

https://runestone.academy/runestone/books/published/py4e-int/conditional/chained.html

p9-4.  (Professor Eric Reed/ Foothill College / Sp2021CS49)

Thank you,
Wesley

**Comment by barbarer** [comment]
Great catch.  I will fix it and it should be live by Saturday.

**Comment by barbarer** [comment]
I also added you to the list of contributors.
