### ISSUE TITLE
8.6.3. Free Response - Route Cipher A Inner Bound Question 9-12-5

### ISSUE THREAD

**Issue by lwojick** [RunestoneInteractive/RunestoneServer#1648]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
CS Awesome

**What Page were you on**
8.6.3. Free Response - Route Cipher A
**What is your username**
wojick.laura
**Describe the bug**
It is the Inner Bounds Problem 9-12-5 but it asks the same question as 9-12-4 the Outer Bound question.  
Here is the question asked for 9-12-5
9-12-5: What can you use to set the outer bound while you iterate through your 2D array?
outer should be inner

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bhoffman0** [comment]
Thanks for reporting this typo! I will fix it by Saturday.
-Beryl
