### ISSUE TITLE
CS Awesome 8.6.1.2 Mult Choice Question

### ISSUE THREAD

**Issue by bradwray** [RunestoneInteractive/RunestoneServer#1650]
The multiple choice question labeled 9-10-13 with the questions stem of "What array will you be modifying in this method?" has answer choices that don't match the question. To be clear it says...

What array will you be modifying in this method
A. if (pv == this.WHITE)
B. if (pv == {255,255,255})
C. if (pv == 0)
D. if (pv == white)

**Comment by bhoffman0** [comment]
Thanks! The question should be something like "How will you check if pv is white?". I've fixed it and it will be live on Saturday.

**Comment by bradwray** [comment]
Thanks so much! And thanks for adding the picture lab! The kids love it!
