### ISSUE TITLE
Python for Everyone Section 7.6 Total Number of Activities Incorrect.

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/RunestoneServer#1653]
[Section 7.6 in Python for Everyone](https://runestone.academy/runestone/books/published/py4e-int/strings/count.html) lists five activities possible, but there seem to be only four.

**Comment by bnmnetp** [comment]
By default, running the answer (in the Answer tab) is counted separately.  And you always get 1 for opening the page.  

@ericsonga the Answer should probably be marked as optional to reduce the count to 4.
