### ISSUE TITLE
Question about practice question 12.3.12

### ISSUE THREAD

**Issue by johnranta** [RunestoneInteractive/RunestoneServer#1654]
I checked the current issues, this has not been asked. For question:
"12-3-12: You are trying to write a method sumRow that finds the sum of the values in a specified row of a 2-D matrix. Which of the following code segments could replace /* to be determined */ to make the code work correctly?"

The assumption is that the 2D array is symmetrical. What if it isn't? row[0] may not be the same length as row[row], right? Just wondering if this had been raised as a possibility. Thanks! JR

**Comment by bhoffman0** [comment]
Thanks! It was an assumption. I will add for a 2D **symmetrical** matrix to the directions. 
-Beryl
