### ISSUE TITLE
Data file corrupt in Python for Everybody 8.13

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/RunestoneServer#1659]
**What Course are you in**
Python for Everybody

**What Page were you on**
8.13
https://runestone.academy/runestone/books/published/py4e-int/files/writeCode.html

**What is your username**
EricReed

**Describe the bug**
It looks like the last line of uspoll.txt does not match the one displayed at the top of the page.  The last character may be missing.  The following code:

```
inFile = open("uspoll.txt","r")

for line in inFile:
    print(line)
    
inFile.close()
```
Produces:

```
...
Youngstown-Warren-Boardman, OH-PA :23 :14

Yuba City, CA :12 :7

Yuma, AZ :14 :

```
The last character should be 9

**Comment by barbarer** [comment]
I checked the file and it looks fine.

**Comment by mrericreed** [comment]
Thank you Barbarer,

Perhaps I shouldn't presume the cause but it still seems like there is an issue.  Can you reproduce the issue I described?

**Comment by barbarer** [comment]
I am on vacation with limited internet at times.  I will try to check tomorrow since this hotel has good internet.

**Comment by bnmnetp** [comment]
The example code you provided works fine for me as do other ways of checking.  I’m going to close this but if it is still an issue please reopen with more information.
