### ISSUE TITLE
instructor's guide link is broken

### ISSUE THREAD

**Issue by mstoth** [RunestoneInteractive/RunestoneServer#1662]
**What Course are you in**
Knowing the course will help us a lot

**What Page were you on**

**What is your username**
mstoth
**Describe the bug**
I'm trying to follow the link to the instructor's page.  
This is where I am taken

https://runestone.academy/runestone/static/instructorguide/index.html

It returns a 404

**Javascript Errors**

**Comment by bhoffman0** [comment]
Try https://runestone.academy/runestone/books/published/instructorguide/index.html
If it asks you to login and add the course, you can view it in incognito mode.
Where was the link you clicked on? We should fix that.
Thanks!

**Comment by bnmnetp** [comment]
What link??  There are many places where we link to the instructor guide, so knowing which one is broken will help.

In the meantime please use the Change Course link (under the user menu) and add `instructorguide` as a course. This will give you access.

**Comment by bjones1** [comment]
I'm guessing https://github.com/RunestoneInteractive/RunestoneServer/blob/master/views/default/user.html#L360 was the culprit.

**Comment by mstoth** [comment]
That looks like the place but I think there was more than one.  When I find the other I will let you know.

Thanks,
Michael

________________________________

**Comment by bnmnetp** [comment]
I found several and fixed them.  Will take a week or so before its live though.
