### ISSUE TITLE
Answer not checking correctly - Python for Everybody 9.19.12

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/RunestoneServer#1663]
**What Course are you in**
Python for Everybody - Interactive

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/lists/pogil.html

**What is your username**
EricReed

**Describe the bug**
The question asks for the output from line two of the code above.  The output is:
['Chicago', 'Detroit', 'Houston', 'New York']

However, this is not accepted as an answer.

**Comment by barbarer** [comment]
This was removed.
