### ISSUE TITLE
Python for everybody : https://runestone.academy/runestone/books/published/py4e-int/functions/mixedupcode.html

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1666]
In the page:
https://runestone.academy/runestone/books/published/py4e-int/functions/mixedupcode.html
course p4e-int
in the activity 5.15 - mixed up questions, exercise  12th, there are two mistakes:
![image](https://user-images.githubusercontent.com/85453807/120934488-b83e1000-c6fe-11eb-916b-370b6d46901d.png)
There are two:"_" missed, should be "a_num" instead of "anum"

**Comment by barbarer** [comment]
I will fix them.

**Comment by jose-csolo** [comment]
OK, 
I believe that there is anoter possible improvement, in
https://runestone.academy/runestone/books/published/py4e-int/functions/function_string_mixedUpCode.html
in last exercise might have a def missed, so instead of the text of the first block: 

passwordDifficulty(password):

 should be :

def passwordDifficulty(password):

![image](https://user-images.githubusercontent.com/85453807/121336427-c87f0680-c91b-11eb-916b-aff6ea47d565.png)
or, am I wrong?

Thanks for the effort of constructing such a wonderful course.
And sorry for any mistake made "against" the English language. I'm from Spain - Europe

**Comment by barbarer** [comment]
Good catch!

**Comment by jose-csolo** [comment]
Hi!
When I runned the code on a exercise from: https://runestone.academy/runestone/books/published/py4e-int/dictionaries/mixedupcode.html
![image](https://user-images.githubusercontent.com/85453807/123766053-9c292b00-d8c6-11eb-8b79-0b41e7cb0fb6.png)

I've received the message:
TypeError: 'int' object is not iterable 
![image](https://user-images.githubusercontent.com/85453807/123766880-5a4cb480-d8c7-11eb-81ae-a773be7bbca4.png)


Regards,

Jose

**Comment by barbarer** [comment]
You are correct.  Line 4 should have been for i in range(len(keys)):.  I will fix it.

**Comment by jose-csolo** [comment]
Thank you for all the time given to this book.

**Comment by barbarer** [comment]
You are welcome. Thanks for checking things out and reporting errors.  I
have undergraduate students working with me this summer to add content and
they don't always check their work that well.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
