### ISSUE TITLE
raw_input vs. input

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1669]
**What Course are you in**
python for everybody

**What Page were you on**
6.4
https://runestone.academy/runestone/books/published/py4e-int/iterations/continue.html

**What is your username**
josecsolo

**Describe the bug**
![image](https://user-images.githubusercontent.com/85453807/121676160-9b199080-cab4-11eb-830c-fff89609c8ef.png)

should be "input" instead of "raw_input", in a previous exercise of the chapter 6 happend the same (raw_input instead of input)

**Comment by barbarer** [comment]
Good catch.  I will fix it by next week.
