### ISSUE TITLE
Strange answer 

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1673]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
python for everybody

**What Page were you on**
8.8 writing files
https://runestone.academy/runestone/books/published/py4e-int/files/writingFiles.html
**What is your username**
Josecsolo
**Describe the bug**
The exercise said:
Click the errors in this code block.
and the answer is...inconsistent

![image](https://user-images.githubusercontent.com/85453807/122023494-e6d77d00-cdc7-11eb-99a5-12457502089f.png)

Thanks for the open course

**Comment by barbarer** [comment]
This problem is correct.  You should click on 'r', line2, file, and []

**Comment by jose-csolo** [comment]
I know, sorry  I've understood it just the opposite
