### ISSUE TITLE
Add a mark complete button to the doAssignment page

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1675]
Add a button to the bottom of the doAssignment page that says "Mark Complete". This will store a status in the database for this student-assignment that they are done. 

The status of each assignment should appear next to the assignment name on the chooseAssignment page.

A nice to have addition to this would be to display the students current score for each assignment on the chooseAssignment page.

**Comment by ShivamJhaa** [comment]
I would like to fix this issue

**Comment by Bryar-Frank** [comment]
@ShivamJhaa I would like to apologize. I didn't see this message until now, and started working on this problem at the same time as you. There are two people currently working on the problems as student interns at Berea College. @bnmnetp opened this issue and then asked us interns to do it. We are deeply sorry for any inconvenience this may cause.

**Comment by Bryar-Frank** [comment]
As an update, this last pull request adds enhancements to the student side view, adding a button for them to change the status of their assignments on the doAssignment.html page and showing their status on the chooseAssignments.html page. We are currently working on the instructors side view also, where we will add additions to the gradebook view to show the status of the students assignments.

**Comment by bnmnetp** [comment]
Thanks Bryar!  I'll work on reviewing this.

I don't really have a vision for how this might be presented on the instructor side.  But would be happy to talk about it with you if you want to sketch up some ideas.  It seems like it might best fit on the grading tab of the instructor interface.

**Comment by Bryar-Frank** [comment]
Would definitely love to meet today, maybe at scrum reports at 1 or right after if possible. Dr. Jan, Diamond, and I have done a lot of discussion about where to put it, and came to the consensus that it would probably be best to put it with the gradebook table, but would also like other opinions, as Dr. Jan and you are the only ones I know who have used the teacher side of Runestone.

**Comment by Bryar-Frank** [comment]
Have added the instructor side view in the gradebook. Now shows due dates and current status of assignments.

**Comment by Bryar-Frank** [comment]
I have submitted the final commit for this. I think it is fully working now on both instructor and student views.

**Comment by zachneill** [comment]
@bnmnetp This issue looks to be resolved by pull request #1696.
