### ISSUE TITLE
expected value ??

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1677]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
https://runestone.academy/runestone/books/published/py4e-int/lists/WriteCode.html

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/lists/WriteCode.html
**What is your username**
josecsolo

**Describe the bug**![image](https://user-images.githubusercontent.com/85453807/123542036-b1c41680-d747-11eb-940f-cc9bbdc2dd1e.png)
I believe that the second answer is not correct , tjhe exercise is "removing", not changing

And that exercise and the next one are the same: data, question, and answer

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by barbarer** [comment]
You are correct.  I will fix it.

**Comment by jose-csolo** [comment]
Thanks
