### ISSUE TITLE
py4e-int. 10.10, last exercise

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1682]
Hello, I might be mistaken, but I believe that the answer to the exercise might be improved.

**What Course are you in**
Python for everybody

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/dictionaries/writecode.html

**What is your username**
jose-csolo

**Describe the bug**

The exercise said: Write this program to record the domain name (instead of the address) where the message was sent from instead of who the mail came from (i.e., the whole email address). At the end of the program, print out the contents of your dictionary.

If I am right, the answer should add all the messages send from a domain. Am I correct?

Reading the file and highlighting the ones from "iupui.edu":

['gopal.ramasammycook@gmail.com 1\n', 'louis@media.berkeley.edu 3\n', **_'cwen@iupui.edu 5_**\n', 'antranig@caret.cam.ac.uk 1\n', **_'rjlowe@iupui.edu 2\n_**', 'gsilver@umich.edu 3\n', 'david.horwitz@uct.ac.za 4\n', **_'wagnermr@iupui.edu 1_**\n', 'zqian@umich.edu 4\n', 'stephen.marquard@uct.ac.za 2\n', 'ray@media.berkeley.edu 1\n']

iupui.edu   5
iupui.edu   2
iupui.edu   1

total :  iupui.edu   8

diccionary 
{'gmail.com': 1, 'media.berkeley.edu': 4, 'iupui.edu': 8, 'caret.cam.ac.uk': 1, 'umich.edu': 7, 'uct.ac.za': 6}

![image](https://user-images.githubusercontent.com/85453807/124101779-fb6e7300-da5f-11eb-9cc8-1ec1bc5daf3d.png)

Did I understood correctly?

Thank you again, for helping me and others to learn a lot

Jose

**Comment by barbarer** [comment]
Good catch.  I will improve the wording.
