### ISSUE TITLE
Indentation can be easily improved

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1684]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/tuples/mixedupcode.html

**What is your username**
jose-csolo

**Describe the bug**
Indentation of line numbered as "4", can be easily improved
![image](https://user-images.githubusercontent.com/85453807/124324737-c2c7ba00-db83-11eb-8196-9244521aa9d3.png)

Regards

**Comment by jose-csolo** [comment]
By the way, another possible improvemente is to add one explanation about the "lamda", I searched it and is clear after a few readings. Woul it make sense to write a few lines expalining how it works?

Thanks and regards

I'm also learning Englis, so if you have time to just rewrite my bigger mistakes, I'll appreciate  (less than I appreciate your work with that free book).

**Comment by barbarer** [comment]
Thanks for catching this.  Yes, I need to add a section explaining sorting more.
