### ISSUE TITLE
I believed that one of the identations is wrong

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1685]
**What Course are you in**
py4e-int

**What Page were you on**
Two pages: 
11:12
https://runestone.academy/runestone/books/published/py4e-int/tuples/mixedupcode.html
11.6
https://runestone.academy/runestone/books/published/py4e-int/tuples/mostcommonword.html

**What is your username**
jose-csolo
**Describe the bug**

That indentation looks strange to my scarce knowledge of Python
![image](https://user-images.githubusercontent.com/85453807/124328441-ec83df80-db89-11eb-86b2-ff2d7a36a19c.png)

having in mind that other one

![image](https://user-images.githubusercontent.com/85453807/124328664-57cdb180-db8a-11eb-898e-aba21540b61e.png)

I have a question, when I try to run instructions "opening files", there is an error message, Is that on purpose? or can be solved ?
![image](https://user-images.githubusercontent.com/85453807/124328833-a418f180-db8a-11eb-8426-1041a328a89d.png)

**Comment by bnmnetp** [comment]
file processing is not supported by CodeLens

**Comment by jose-csolo** [comment]
Thanks
