### ISSUE TITLE
Indentation of Parsons (mixedupcode_question10_7)?

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1686]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/tuples/mixedupcode.html

**What is your username**
jose-csolo

**Describe the bug**

Unsure about the indentation on: Parsons (mixedupcode_question10_7)

![image](https://user-images.githubusercontent.com/85453807/124351943-a49ea000-dbfd-11eb-97aa-a2752cef70a9.png)

**Comment by jose-csolo** [comment]
In the same page:

https://runestone.academy/runestone/books/published/py4e-int/tuples/mixedupcode.html

Am I wrong or the problen statement :
Construct a block of code that capitalizes every item in tuple ‘tup’. Note: there are four blocks that won’t be used in the solution!

and the "problem" aren't linked

**Comment by barbarer** [comment]
Good catch.  It will be fixed.
