### ISSUE TITLE
Missed example

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1689]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/regex/charactermatching.html

**What is your username**
jose-csolo
**Describe the bug**
The text said : " as shown below:"
and is empty

![image](https://user-images.githubusercontent.com/85453807/124367248-c88dd000-dc55-11eb-9d31-7ac436c3f40f.png)

Regards

Jose

**Comment by barbarer** [comment]
It will be fixed.
