### ISSUE TITLE
Activity: 12.12.8 ActiveCode (regex_writecode5q)

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1692]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/regex/writecode.html

**What is your username**
jose-csolo

**Describe the bug**
the proposed exercise said:

Define the function match_z to match a word containing the letter z. Return “Found a match!” if z is in the string and “Not matched!” if there is not a z.

but  Zippers .. seems not to match ?
![image](https://user-images.githubusercontent.com/85453807/124454650-04758200-dd89-11eb-9631-6a1762b40196.png)

I've solved both,  "Z" and "z", lower and capital. I woud add - lower -

A/  pattern = "z"    # Your regex pattern here

B/  pattern = "z"    # Your regex pattern here
      if re.search(pattern, text.lower()):

Regards

Jose

**Comment by barbarer** [comment]
I will fix it to say it will only match a lowercase z.
