### ISSUE TITLE
Missing "pos"

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1694]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/network/writecode.html

**What is your username**
jose-csolo

**Describe the bug**
after running the "Activity: 13.16.3 ActiveCode (writingcode_network_2)" seems that the variable "pos" wasn't defined.

![image](https://user-images.githubusercontent.com/85453807/124624921-a24a7900-de7d-11eb-993f-5669c7feee77.png)

Regards, 

Jose

**Comment by jose-csolo** [comment]
Activity: 13.16.11 ActiveCode (writtencode_network_7)

https://runestone.academy/runestone/books/published/py4e-int/network/writecode.html

![image](https://user-images.githubusercontent.com/85453807/124631090-54d10a80-de83-11eb-89f7-59f8d67ff9ab.png)

very unlikely that I'll guess the name of the file: "prideandprejudice" to be read and

**Comment by barbarer** [comment]
Thanks for catching this. It should have 

pos = picture.find(b"\r\n\r\n")

I will fix it.
