### ISSUE TITLE
Organize book listing pages by programming language and alphabetically

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1697]
Could we organize the list of books in https://csawesome.runestone.academy/runestone/books/index and https://csawesome.runestone.academy/runestone/designer/index alphabetically and with sections for different programming languages? It's getting harder to find the book you're looking for! Thanks!
-Beryl

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this, can you suggest me ways to get started?

**Comment by bnmnetp** [comment]
Thanks,

You can start by looking at the views/books/index.html file for the view, and then the controllers/books.py file, particularly the index function.

It would be better in the long run to make this database driven, but at least sorting them by title would be a good start.

**Comment by bnmnetp** [comment]
In the meantime I have organized the book building page to be more topically organized which will make it a lot easier.  We could do something similar until the project that the assigned group is working on is complete.  But what they are doing will be much better and searchable by keyword....
