### ISSUE TITLE
Progress page: make the assignment order by due date and don't show not visible ones

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1699]
In the assignments page, the students see the assignments in order by due date and do not see ones that are not set visible by the instructor.  The progress page (https://runestone.academy/runestone/dashboard/studentreport) should be the same, but right now, it shows assignments in alphabetical order and shows all assignments even if they are not supposed to be visible.

**Comment by bnmnetp** [comment]
This will be fixed when I merge #1696 -- which also allows students to mark their assignment as "submitted"

**Comment by bnmnetp** [comment]
This is also more or less a duplicate of #1675
