### ISSUE TITLE
Same lines of code 

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1700]
**What Course are you in**
p4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/bsoup/bs4_mixedupcode.html

**What is your username**
jose-csolo

**Describe the bug**Parsons (mixedupcode_bs4_umich)
In exercise: Parsons (mixedupcode_bs4_umich) there are two lines:

![image](https://user-images.githubusercontent.com/85453807/124934703-40b51680-e005-11eb-9dc2-b60dcdcc1855.png)

one is accepted and the other suposed to be wrong. Both lines are the same.

**Comment by jose-csolo** [comment]
Same page of previous comment 

That indentation, is it correct?

![image](https://user-images.githubusercontent.com/85453807/124935397-e8cadf80-e005-11eb-829f-456a93688ebb.png)

**Comment by barbarer** [comment]
Good catches. These will be fixed.
