### ISSUE TITLE
")" missed

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1701]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/bsoup/writecode.html

**What is your username**
jose-csolo

**Describe the bug**
In Activity: 14.7.8.7 ActiveCode (bsoup_writecode4q), text is:
Create a BeautifulSoup object named soup using the url https://en.wikipedia.org/wiki/Python_(programming_language). 
but the code lacks of the closing bracket ")"

![image](https://user-images.githubusercontent.com/85453807/125611641-e316968d-a24a-4f01-b665-155d38de451b.png)

the code is:
<a class="reference external" href="https://en.wikipedia.org/wiki/Python_(programming_language">https://en.wikipedia.org/wiki/Python_(programming_language</a>
![image](https://user-images.githubusercontent.com/85453807/125612372-d4cdd463-86e0-4ea8-a0ad-87473df659ca.png)

and should be:
<a class="reference external" href="https://en.wikipedia.org/wiki/Python_(programming_language">https://en.wikipedia.org/wiki/Python_(programming_language)</a>
![image](https://user-images.githubusercontent.com/85453807/125612394-f896e6d5-175c-41a5-af66-982e53f8d34c.png)

the page: https://en.wikipedia.org/wiki/Python_(programming_language do not exist.

Regards

Jose

**Comment by barbarer** [comment]
I just checked and bsoup_writecode4q and don't see what you mean.  What ) is missing?  The answer runs correctly.

**Comment by jose-csolo** [comment]
In the description of the exercise is one url:

Create a BeautifulSoup object named soup using the url https://en.wikipedia.org/wiki/Python_(programming_language).

that text have a code under with a href:.... at the end of the href:https://en.wikipedia.org/wiki/Python_(programming_language 

the closing bracket is missing
If you click over the url in the description of the exercise . problem statement, you'll land over a non existing pageis not the code of the soup is the code under the problem statement

**Comment by barbarer** [comment]
I just checked and both the question and answer have the correct URL.  You may have to scroll over to see it or enlarge the window.  I also clicked on the url in the description and it took me to the correct page.
