### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by Bryar-Frank** [RunestoneInteractive/RunestoneServer#1703]
It has come up in our group that there is no indication on the main page or other pages for people to donate, and the only time it comes up is with registration, adding of a book, or creation of a book.

I would like a Donate button added to the top of the page to give a spot for people to Donate later on instead of only being prompted when they are taking another action, like adding a book. Sometimes, it will serve a good reminder for people who intended to donate, but didn't want to right when they are creating a book or adding a book.

Also, this issue can serve two purposes, as it was also discussed that the Sign Up button was in an awkward spot being at the top of the page instead of being where the Login is. 

I would like to moved the Sign in button down to the Login page and change the current Sign In button to a Donate button that takes you to the Donate page.

**Comment by bnmnetp** [comment]
I like your idea... I think if you scroll down you will see there is a donate button on the home page... But I like your idea to put it at the top better.  I think people rarely scroll down as there is not much reason to on those pages.
