### ISSUE TITLE
Cannot access the Assignments Page in CSAwesome Course

### ISSUE THREAD

**Issue by jfigliulo** [RunestoneInteractive/RunestoneServer#1711]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**  CSAwesome:  Summer=2021-PD-RPP
Knowing the course will help us a lot

**What Page were you on**  https://csawesome.runestone.academy/runestone/assignments/chooseAssignment.html

**What is your username**  johnqfig

**Describe the bug**
I get an ad when I pull up this page then it logs me off and forces me to login again and returns me to the assignment with a REPORT A BUG message 

I have tried clearing my cache,  going into incognito mode and using a different browser (FireFox).  I can not get to the Assignments page.  The same thing happens over and and over.

**Traceback**
None.

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

![image](https://user-images.githubusercontent.com/48813786/126820775-15c1a267-06fa-40ef-892b-56ea97b84659.png)
![Screenshot 2021-07-23 124210](https://user-images.githubusercontent.com/48813786/126820871-b7148051-5936-424d-9ab9-5ed3032b77a0.jpg)

**Comment by bhoffman0** [comment]
@bnmnetp I just checked a bunch of CSAwesome PD courses, and they all could show the Assignments page except for this one:   Summer-2021-PD-RPP
It gives the report a bug error with this traceback. It looks like there is an assignment where assignment.points is NoneType throwing the error. Maybe that check can be added to the if or the points changed for that assignment in the db.

 ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/runestone/controllers/assignments.py", line 1320, in <module>
  File "/srv/web2py/gluon/globals.py", line 431, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/gluon/tools.py", line 3867, in f
    return action(*a, **b)
  File "/srv/web2py/applications/runestone/controllers/assignments.py", line 855, in chooseAssignment
    if (grade.score is not None) and (assignment.points > 0):
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by bnmnetp** [comment]
I just updated the assignments to set the points to 0 if they were null. So that should eliminate the problem for now.

I am confused as to how this could happen as the default for the points column is 0, so in theory it should never by null.

Were you able to isolate exactly which assignment it was?

**Comment by bhoffman0** [comment]
The assignment page still doesn't load though, so I don't think it's the null points. I haven't been able to isolate it yet. The weird thing is that the course Summer-2021-PD-California has the same assignments with null points for some, and its assignment page loads fine.

**Comment by bnmnetp** [comment]
It is working for me.

<img width="1230" alt="Screen Shot 2021-07-23 at 3 27 33 PM" src="https://user-images.githubusercontent.com/51115/126838033-319854fe-595e-4f88-953c-e4abf54422e0.png">

**Comment by bnmnetp** [comment]
I am on csawesome.runestone.academy -- I assume they are also?

**Comment by bhoffman0** [comment]
Weird. yes. It's not working for me. I tried a hard refresh and another browser.  
The assignments went back to null too though. I did see 0 points in there for a minute, and now they're null again.
![image](https://user-images.githubusercontent.com/4571962/126838479-6814f861-5c7f-4f6e-ae4b-d351f5651762.png)

**Comment by bhoffman0** [comment]
Oh, it's just that 1 assignment FlipGrid. When I make that invisible, I can see the assignment page. I'll just leave it at invisible, since that was 3 weeks ago.

**Comment by bnmnetp** [comment]
Interesting.... 

1. This assignment has no questions!

When you select an assignment in the instructor interface it updates the points There was a long standing problem with the points getting out of sync (fixed since) so that we were updating the point totals to make sure they were always correct.

That must be what is resetting the points back to null...

**Comment by bhoffman0** [comment]
Yes, I'll warn them not to put in assignments without problems. Not sure why it worked in the other PD sections, but problem solved. They did that assignment weeks ago so it's fine not to make it visible.

**Comment by bnmnetp** [comment]
I also tracked down the culprit for resetting it back to. None -- al someone had to do was to go to the assignment page in the instructor interface and pull up that assignment. - it may have even come up by default as it is at the top of the list.

**Comment by bhoffman0** [comment]
John says this now works for him too. Thanks!
