### ISSUE TITLE
How to not show pages that are not in toctree and should be invisible in the This Chapter dropdown menu?

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1712]
I just noticed that pages that we want to be invisible that we do not put in the toctree show up in the This Chapter dropdown menu:
![image](https://user-images.githubusercontent.com/4571962/126875823-84127fde-4f2d-48ac-ac59-f2fe46bb4b2f.png)

Is there a way I could block this or at least have them appear at the bottom of the dropdown instead of the top?

**Comment by bnmnetp** [comment]
Is there a reason they need to be in a particular chapter?  Could you move all of the pages you want hidden to the appendix or add a "chapter" that is not in the main toc?

**Comment by bhoffman0** [comment]
Good idea! I'll try that.
