### ISSUE TITLE
Seeing ads when logged in

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1713]
A couple people have reported seeing ads even though they are logged in.  John says he sees ads in Summer-2021-PD-RPP while logged in, but I have not been able to reproduce it.  
DI sent me the following image of an ad while logged in his course ITSC1212-vonBriesen-21SU. He got to this link through Canvas LTI though which may have affected ad-serving: 
![adWhileLoggedIn](https://user-images.githubusercontent.com/4571962/127029422-9eec8797-2794-461a-91ee-f1dc34412d4c.PNG)

**Comment by bnmnetp** [comment]
Somehow the ad serving tag got added to the template file for the instructor interface pages.

`git blame` says I did it when I checked in a bug fix for something unrelated.  I think it somehow crept back in when Bryan and I were debugging and I had reverted to a much older layout file.

They should definitely not be seeing them on pages in the book.

**Comment by bnmnetp** [comment]
I took out the offending line, so people should not see ads on the intstructor interface OR book pages.  They definitely should not have been seeing them in the book when logged in.  So I think it was just this little hiccup on th II that caused the confusion.
