### ISSUE TITLE
Activities in mobile-csp and teach-mobilecsp ebooks confused and have the wrong count

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1719]
@bnmnetp I think the mobile-csp and the teach-mobilecsp books somehow have their activities confused. I'm in the course **mcsp-test** which was created from mobile-csp, but the pages say the wrong number of activities, for example https://runestone.academy/runestone/books/published/mobilecsp/Unit2-Intro-to-Mobile-Apps/I-Have-a-Dream-Tutorial.html says there are 3 activities at the bottom, but there are much more. And in the instructor's page, when choosing problems for an assignment, it shows the exercises that are in the teach-mobilecsp book, not the mobile-csp book with the book icon. Actually the first two exercises in the mobile-csp lesson are replaced with the exercises in the teach-mobilecsp corresponding lesson.
![image](https://user-images.githubusercontent.com/4571962/127081689-704a52bf-b23d-452b-ae3b-9ec6c7358128.png)

We did give the same id to exercises in each ebook and the names of the lessons are the same. Should we change that? Or is it because of some way it's loaded in or our config file?

**Comment by bnmnetp** [comment]
UGH!  the teach-mobilecsp has its base course configured to be mobilecsp.

**Comment by bhoffman0** [comment]
Is it because of the project variable in config.py? I think that was my fault when I copied it over. Sorry! I think there's only 1 PD course that's using it: Summer-2021-MobileCSP-PD. If you can publish mobilecsp again, I think it might fix it. I think teach-csp overwrote some exercises in it.

**Comment by bnmnetp** [comment]
It is the `basecourse` variable in `pavement.py` for the teach-mobilecsp book.

I changed it and have rebuilt both teach-mobilecsp and mobilecsp

Hopefully that fixes it.

**Comment by bnmnetp** [comment]
This is why I always want to build and test on the dev server with any new book so that we can prevent problems like this from getting onto the production server.  I usually check the pavement.py for any new book to make double sure that the `project_name` and the `base_course` are configured correctly.  Unfortunately I missed it, and nobody caught the problem with the mobilecsp book on the dev server.

**Comment by bhoffman0** [comment]
Thank you, it's working now. Sorry about this. I should have caught it too.
