### ISSUE TITLE
CSS not appearing on MobileCSP

### ISSUE THREAD

**Issue by rrobidoux** [RunestoneInteractive/RunestoneServer#1722]
The custom css files (e.g., lessons.css) are 

Course: mobilecsp-2021-training-course-2

Page: 2.3. Algorithm Basics

rrobidoux

Styles for the lessons are not being rendered. Looking closely at the HTML code it appears a number of stylesheets were not added to the head element. Interestingly enough, they were added and all is well if I use the csawesome server (csawesome.runestone.academy). The screenshots below show a portion of the head element for the runestone server (not working) and the csawesome server (working). The missing stylesheets should be appearing between the theme-overrides.css and the script element.

Runestone Server (missing stylesheets)
<img width="589" alt="Screen Shot 2021-07-29 at 11 42 28 AM" src="https://user-images.githubusercontent.com/30819358/127523436-c4eba105-179f-4102-ad0a-578660cb20af.png">

CSAwesome Server (all stylesheets included)
<img width="579" alt="Screen Shot 2021-07-29 at 11 45 41 AM" src="https://user-images.githubusercontent.com/30819358/127523601-3fce7ce8-0861-49a9-b2cc-93c47bfc87dd.png">

NOTE: I see that there was a change __init__.py to "update setup to import custom files" on 07/22...perhaps this can shed light on the issue.

**Comment by bnmnetp** [comment]
@rrobidoux I just pulled and rebuild on runestone.academy and I can see that the css files are in index.html at least.

Unless I lost track of which machine I was on when typing commands this is very confusing to me...   csawesome books are just `rsynced` from academy...  I'm guessing that is what must have happened.

**Comment by bnmnetp** [comment]
Also, last Saturday I added mobilecsp and teach-mobilecsp to the automated build process, so we'll have to keep an eye on that to make sure it isn't some kind of hiccup in the scripts.

**Comment by rrobidoux** [comment]
thanks, Brad!
