### ISSUE TITLE
JS error in dynamically loading activecode

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1730]
In [views/layout.html line 282](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/views/layout.html#L282) there's the old method to load activecode. I remember @bnmnetp fixed this nicely for the Runestone Components -- would you apply the same fix here?

**Comment by bjones1** [comment]
Aack, this is more complicated. It looks like we don't load the RS components JS in `layout.html`. Could we do that? It feels somewhat like a re-thinking of e41bc40f, where we put code from `_sphinx_static_files.htm` in `layout.html`. @bnmnetp, what do you think?

**Comment by bjones1** [comment]
...or do we omit the pencil / activecode popup icon on login pages? If we leave this in book-only pages, it's an easy fix...

**Comment by bnmnetp** [comment]
I think scratch activecodes work on all of the instructor dashboard pages, just not the login pages.  I think we could safely omit it from the login pages, but I would keep it available on other pages.  Which I think probably translates to not showing it on any page that uses the default/user controller.
