### ISSUE TITLE
Syntaxerror

### ISSUE THREAD

**Issue by jose-csolo** [RunestoneInteractive/RunestoneServer#1732]
**What Course are you in**
py4e-int

**What Page were you on**
https://runestone.academy/runestone/books/published/py4e-int/objects/Exercises.html
Activity: 16.13.8 Multiple Choice (object_oriented_output)

**What is your username**
jose-csolo
**Describe the bug**

in line 1:   class Pokemon():
and 
line 10:  class GrassType(Pokemon):
there's an space in the beginning of the lines

Whe I've copied and runned the code

![image](https://user-images.githubusercontent.com/85453807/128349675-53779c05-d6d5-4584-9378-fd30359dc0ce.png)

Regards

**Comment by barbarer** [comment]
It will be fixed by Saturday. Thank you!
