### ISSUE TITLE
Due time on assignments show +4 hours ahead

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1738]
The time set on the due date of an assignment is shown incorrectly as 4 hours  ahead of the set time on the assignments page,

![image](https://user-images.githubusercontent.com/4571962/128801029-afbcc4ca-a98e-4951-a68e-a580f70b5a8e.png)

![image](https://user-images.githubusercontent.com/4571962/128801094-ef79497d-7814-4db4-bf03-8028487e9dc6.png)

**Comment by bnmnetp** [comment]
I think this has been a problem for a long long time.  But it is now much more evident because our Interns took the time to make the time display in a more friendly manner.

Should be fixed today.
