### ISSUE TITLE
Save & Run --- Runestone Academy Server errors?

### ISSUE THREAD

**Issue by jeffmilton** [RunestoneInteractive/RunestoneServer#1748]
**What Course are you in**
MSUD_CS1050_Nam

**What Page were you on**
https://csawesome.runestone.academy/runestone/books/published/csawesome/Unit1-Getting-Started/topic-1-3-variables.html

**What is your username**
jeffmilton

**Describe the bug**
When clicking save and run I am getting this error intermittently:
Error communicating with the server.TypeError: NetworkError when attempting to fetch resource.
or 
Unable to connect
or 
Nothing. the green button grays out and ... nothing
or
Error communicating with the server.TypeErorr: Failed to fetch

**Comment by jeffmilton** [comment]
I'm definitely having trouble with runestone academy servers. I have tried multiple computers, multiple platforms, multiple browsers with the same result. I do not have a different internet connection to try however all other websites and services are working without issue. I'm not sure if this is the right place to report a runestone academy issue or if there is even a place to report issues.

**Comment by bnmnetp** [comment]
Sorry for the downtime.  I did not realize there were issues until I got up this morning.  All is working for me now.  Let me know if you have continued troubles.  

Best place to report outages like this is on our slack channel.

**Comment by bnmnetp** [comment]
Actually looking at the monitors for the last 24 hours it looks like there was about 15 minutes of network outage (internal to the hosting provider) around the time you reported this.
