### ISSUE TITLE
Font is white in CodeLens while in Dark Mode,

### ISSUE THREAD

**Issue by CMitchell2205** [RunestoneInteractive/RunestoneServer#1749]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How to Think Like a Computer Scientist: Interactive Edition

**What Page were you on**
2.4
**What is your username**
Not Necessary
**Describe the bug**
While in dark mode, the font in the CodeLens print output box is white, which makes it unreadable.
![Capture](https://user-images.githubusercontent.com/89806344/131392272-b7281840-9553-4ced-94b7-64e610cabbbf.PNG)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by dsanders12** [comment]
@dsanders12 Currently working on this issue.

**Comment by dsanders12** [comment]
It seems this is a RunestoneComponents issue, not a Server issue?
