### ISSUE TITLE
Make warning message on account registration screen more obvious

### ISSUE THREAD

**Issue by chrispauly** [RunestoneInteractive/RunestoneServer#1750]
**Is your feature request related to a problem? Please describe.**
When a new user tries to register an account with invalid characters in their username, the message that appears at the bottom of the registration form is not obvious.  We had multiple students try to create usernames with periods (".") and the message about the issue that appears at the bottom of the form did not look different than the rest of the form enough for the students to notice what they are doing wrong.

**Describe the solution you'd like**
I think any of the following changes would improve the experience.
- Change the color of the text of the warning message. I would also suggest that for accessibility some other texturing change should also happen, adding a border and changing the background color.
- Adding some helptext when inputting a username that indicates what are valid values
- Performing a validation before submitting that could add a boxed border around input boxes that need to be corrected
- Add an indication after submitting of the input field that needs to be updated on the input field that was incorrect.

**Comment by bnmnetp** [comment]
Thanks for the suggestions.

There is a group working on a whole new login flow for runestone that **should** make the whole process much more intuitive.  I’ll definitely pass these on to that team.

**Comment by schweinsbergs** [comment]
@lyisus and I want to work on this for the Berea College class.
