### ISSUE TITLE
Content Error in thinkcpp 5.6.3 Multiple Choice (bool_var_3)

### ISSUE THREAD

**Issue by Glockshna** [RunestoneInteractive/RunestoneServer#1754]
https://csawesome.runestone.academy/runestone/books/published/thinkcpp/Chapter5/booleanvariables.html

A picture says a thousand words. 
![image](https://user-images.githubusercontent.com/5114362/132747396-d23ceac6-56df-491e-884c-3715bcbb6556.png)

A is the correct answer to this problem, however D is the answer it wants. The space should be removed from the first string to make the lesson that it's trying to teach (Pay attention to details) valid.

**Comment by barbarer** [comment]
Good catch.  I will fix it.
