### ISSUE TITLE
settings.enable_captchas breaks startup of Runestone Server

### ISSUE THREAD

**Issue by ascholerChemeketa** [RunestoneInteractive/RunestoneServer#1757]
If `settings.enable_captchas = True` is set in `models/1.py1` then the runestone server fails to start. (Using docker based server setup). Error below is reported in logs. Disabling that setting allows normal startup.

```
^[[35mrunestone_1  |^[[0m Initializing the database
^[[35mrunestone_1  |^[[0m Running: python web2py.py --no-banner -S runestone -M -R applications/runestone/rsmanage/initialize_tables.py
^[[35mrunestone_1  |^[[0m Traceback (most recent call last):
^[[35mrunestone_1  |^[[0m   File "/srv/web2py/gluon/restricted.py", line 219, in restricted
^[[35mrunestone_1  |^[[0m     exec(ccode, environment)
^[[35mrunestone_1  |^[[0m   File "applications/runestone/models/db.py", line 128, in <module>
^[[35mrunestone_1  |^[[0m     from gluon.tools import Recaptcha
^[[35mrunestone_1  |^[[0m ImportError: cannot import name 'Recaptcha' from 'gluon.tools' (/srv/web2py/gluon/tools.py)
```

**Comment by bnmnetp** [comment]
I don't know if Captchas are supported by web2py anymore or not.  I haven't used them in years.  This will require a little investigation.

**Comment by schweinsbergs** [comment]
@LYisus and I are working on this for a project. 

Current hunch right now is based on documentation, ours currently is: 
from gluon.tools import Recaptcha

But the web2py documentation suggests: 
from gluon.tools import Recaptcha2

Investigating.

**Comment by schweinsbergs** [comment]
I got the actual button working, but there's no server-side validation. That's the next thing to tackle. 

The domains need to be all registered through Google, so it might be best for you to register your own keys and change the ones I made. Otherwise if anyone is running through their own server, there's a good chance the Captcha is gonna break the site for them.
