### ISSUE TITLE
Activity 4.13.15 placement in the textbook

### ISSUE THREAD

**Issue by lorrieteaching** [RunestoneInteractive/RunestoneServer#1759]
**What Course are you in**
py4e-int

**What Page were you on**
4.13

**What is your username**
tomekla

**Describe the bug**
Activity 4.13.15 is a write code question that asks students to implement an is_even() function.  At this point in the textbook, students have learned about conditional execution, but functions are not taught until chapter 5.  Suggest this problem be moved to chapter 5.

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
I will fix it.
