### ISSUE TITLE
RunestoneTests error Activity 1.10.13 ActiveCode (ch4Ex9q)

### ISSUE THREAD

**Issue by cbailey-rams** [RunestoneInteractive/RunestoneServer#1768]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot

RHSAPCSA (a copy of csawesome for my course)

**What Page were you on**

1.10 Coding Practice

**What is your username**
cbailey

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

My students were attempting activity 1.10.13 and when anyone went to run the code the same error message is appearing: 

./RunestoneTests.java:24: error: cannot find symbol
                  boolean passed1 = code.contains(target1);
                                    ^
  symbol:   variable code
  location: class RunestoneTests
1 error

This error would appear regardless of what code was in the window. I tried switching courses from RHSAPCSA back to just csawesome and the error still appears.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bhoffman0** [comment]
Sorry, this will be fixed on Saturday.
