### ISSUE TITLE
Pages Show That I Completed Activities, Even Though No Activities Appear on the Page

### ISSUE THREAD

**Issue by jdinda** [RunestoneInteractive/RunestoneServer#1770]
Hi!

I just signed up for the "fopp" Python course as part of a Python class at my community college.  I took this Python class once before (back in 2019), and am taking it again as a refresher.  During my first Python class, we also used Runestone's Python course.

My problem is that as soon as I navigate to a new page in my current "fopp" course, it shows that I have already completed 1 out of <x> activities on the page.   For example, the page linked below does not seem to show any activities that I need to perform (it just shows text for me to read), but the bottom of the page shows that I have completed 2 activities:
https://runestone.academy/runestone/books/published/fopp/GeneralIntro/intro-TheWayoftheProgram.html

I attached a screen shot to show what I'm seeing.  Hopefully it appears below:
![Screen Shot 2021-09-23 at 5 53 46 PM](https://user-images.githubusercontent.com/38171682/134589331-0bb515fd-2777-42b3-a11c-cc2de19ebe52.jpg)

My main concern is whether Runestone sees the activities that I completed back in 2019 when I originally took the Python course, and assumes that I completed them just now.  I don't want to miss out on redoing any of the activities, because I really want to get the best review that I can get.

Thanks very much for any assistance you can provide on this problem.

Sincerely,
Joe

**Comment by jdinda** [comment]
Oops, I meant to say "...1 out of <x> activities on the page."

**Comment by bnmnetp** [comment]
Yes, you get one "activity" for opening the page.... its kind of a freebie in the count of activities.

**Comment by jdinda** [comment]
Hi Bradley,

Thanks very much for your quick reply.

Gotcha.  That's good to know about the "activity" for opening the page.

I didn't think of it previously, but perhaps watching the video is the other activity that causes the count to be 2.  If so, would you say that what I see in the screen shot is correct, then (meaning that I got 2 out of 2 for opening the page and watching the video)?   If so, I'm sorry about that.  I think I had my brain fixated on looking for things to code in CodeLens, or quiz-type things, etc. as "activities."

Thanks again!

**Comment by bnmnetp** [comment]
Watching the video is definitely an activity.
