### ISSUE TITLE
Automating Development Enviorment Setup

### ISSUE THREAD

**Issue by Cortesj** [RunestoneInteractive/RunestoneServer#1775]
Runestone appears to be quite difficult to develop for in-terms of getting the development environment up and running. I believe there can be something done to update scripts such as “dbuild” and the main docker file to better accommodate the building of books and avoid errors whenever possible, within the build process. I have some concepts/ideas of adding functionality or scripts to assist in the build/setup process. I am interested on contributing some of my ideas towards achieving this goal.

Note: I am Berea College student and will be currently evaluating this issue and how to specifically implement/fix said issue.

**Comment by bnmnetp** [comment]
Great!

the first thing you could try that would be very useful is to check out PR #1774 and give it a try!  We will want to build off of that work.

Brad

**Comment by bjones1** [comment]
@cortesj, when you're ready, I can provide some suggestions on how to improve the process. For a quick start, run `curl -fsSLO https://raw.githubusercontent.com/bjones1/RunestoneServer/docker_updates/tests/docker_tools.py | python3 -` from any Linux distro with `curl` installed.

**Comment by Cortesj** [comment]
@bjones1 I've actually been looking through your python script and it looks great so far! What suggestions did you have in mind?

**Comment by bjones1** [comment]
@Cortesj, thanks for the feedback. I'd suggest some integration work: we have a bunch of scripts `scripts/dshell`, etc. These could all be made part of the `docker_tools.py` script -- `docker_tools.py shell`, for example. Also, do they all still work after changing everything? Some testing would be helpful. I can be more specific on how to accomplish these goals if you'd like.
