### ISSUE TITLE
Make book pages customizable for each school

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1776]
It would be very helpful for students to know that they are logged in correctly if the book were more custom for their school.  This could take on many forms, some of them quite easy to implement and some more complicated.

**Easy Things**
1. Have the School name appear in the header or footer of each page
2. Have the Instructors name and institution appear in the table of contents for the book

**Moderate Things**
1. Have the school logo appear in place of the Runestone logo on each page
2. Allow teachers to have a message panel that they can update on the table of contents page with special announcements

**Harder Things**
1. Allow each school to select/create a color scheme that matches their colors.

I'm sure if we did some brainstorming and asked some teachers more ideas would bubble up.

**Comment by bnmnetp** [comment]
@pearcej I think this would be a great project for a group in your course.  They could get started on the easier stuff right away.

**Comment by pearcej** [comment]
@bnmnetp I agree! I will get some of them on it.

**Comment by bhoffman0** [comment]
Awesome ideas!

**Comment by Mocktic** [comment]
I would like to work on this can you guide me through the process

**Comment by bnmnetp** [comment]
Sounds great.  

I would suggest that you make use of the course_attributes table as the books/published endpoint already serves up all the key value pairs from that table.

**Comment by constantinol** [comment]
We have tried using "upload", "string", "byte", and making our own type for the image to replace the Runestone logo, but none of those were successful. 

We were able to complete the tasks listed in "Easy" and we will issue a pull request for this and we hope this information is useful to the next person that takes on the "Moderate" and "Harder" tasks.
