### ISSUE TITLE
Time outs, impossible output

### ISSUE THREAD

**Issue by rfoldgh2** [RunestoneInteractive/RunestoneServer#1786]
I have been using CS Principles with many HS students in California. Time outs are becoming more and more frequent (Today is 10/7/21). At first I thought this was only when an infinite loop had been generated either intentionally or not intentionally, but now it is happening in many other contexts. Typically, a simple code activity (such as 8.7. Chapter 8 Exercises) box will glitch and timeout, and then upon re-running generate impossible values. For example , a simple code snippet that should generate a "1,2,3" will instead generate sets of enormous values such as "67,601, 67,602 and 67,601". Rerunning the code will generate more impossible sets of values such as "86,301, 86,302 and 86,303". 
I wanted you to be aware of these continuing issues, and wonder if anyone is available to give them some intention?

**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot

**What Page were you on**

**What is your username**

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Hi,

Can you please let me know the name of your course?  We have two CS Principles books so I'm not sure which you are talking about.  Is this Python code? Java Code?

The Python code runs in the browser, and is used in 1000's of courses. You are the first to report any issues with timeouts, so it is important to get the details so I can investigate what is going on.  A URL to the exact page is much more helpful than telling me section numbers.  I don't know any section numbers for the books on Runestone as they are generated when the books are built.

Also as the template asks, anything from the javascript console would be very helpful.

Thanks

**Comment by bnmnetp** [comment]
Thanks but you didn't answer the most important question:  What is the name of your course??

**Comment by rfoldgh2** [comment]
CS Principles I though I said that. CS Principles with Python. Is there another more detailed name I am missing?
Thank you.
    On Thursday, October 7, 2021, 04:31:23 PM PDT, Bradley Miller ***@***.***> wrote:  
 
 


Thanks but you didn't answer the most important question: What is the name of your course??

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
