### ISSUE TITLE
Problem with displaying site page - prohibit special characters in component names

### ISSUE THREAD

**Issue by union108** [RunestoneInteractive/RunestoneServer#1789]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
**Foundations of Python Programming**

**What Page were you on**
**7.14.1. Contributed Exercises**

**What is your username**
**union108**

**Describe the bug**
In **Mozilla Firefox (version 93.0)**, **Google Chrome (version 94.0.4606.81)** and **Microsoft Edge (version 94.0.992.47)** browsers, immediately after **ActiveCode (TL_365_wvu_forloop_oddnumbers)** and to the end of the page, when the browser window is enlarged, the layout crumbles. It is not possible to perform tasks in full screen mode.

**Example for Google Chrome (version 94.0.4606.81)**

![Снимок экрана (130)](https://user-images.githubusercontent.com/34376358/137139638-36ce9e35-508a-4bdc-9fd3-3929ad9e752e.png)

![Снимок экрана (131)](https://user-images.githubusercontent.com/34376358/137140345-bbf8a3c3-88d6-4840-b0b8-4ca802865b47.png)

**Traceback**

If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
**Example for Google Chrome (version 94.0.4606.81)**

acfactory.js:175 Error rendering Activecode Problem ex6_11_3
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem r6_ex1
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
2activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem wvu_forloop_oddnumbers
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_L2_norm_loop
                Details: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
3acfactory.js:175 Error rendering Activecode Problem TL_365_L2_norm_loop
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_Balmer_list_loop
                Details: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
2acfactory.js:175 Error rendering Activecode Problem TL_365_Balmer_list_loop
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_matrix_scalar_multiply_loop
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_rainfall_stats
                Details: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
2acfactory.js:175 Error rendering Activecode Problem TL_365_rainfall_stats
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_rainfall_stats_cm
                Details: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
2acfactory.js:175 Error rendering Activecode Problem TL_365_rainfall_stats_cm
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_ex6_11_1
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_ex6_11_2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_ex6_11_3
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_ex_3_4
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_r6_ex1
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_wvu_forloop_oddnumbers
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_sum_100
                Details: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
2acfactory.js:175 Error rendering Activecode Problem TL_365_sum_100
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
acfactory.js:175 Error rendering Activecode Problem TL_365_sequence_x^2
                Details: Error: Syntax error, unrecognized expression: #TL_365_sequence_x^2_question
3acfactory.js:175 Error rendering Activecode Problem TL_365_sequence_x^2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
acfactory.js:175 Error rendering Activecode Problem TL_365_trapezoidal_x^2
                Details: Error: Syntax error, unrecognized expression: #TL_365_trapezoidal_x^2_question
acfactory.js:175 Error rendering Activecode Problem TL_365_trapezoidal_x^2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
acfactory.js:175 Error rendering Activecode Problem TL_365_trapezoidal_x^2
                Details: Error: Syntax error, unrecognized expression: #TL_365_trapezoidal_x^2_question
3acfactory.js:175 Error rendering Activecode Problem TL_365_trapezoidal_x^2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem TL_365_matrix_multiply_loop
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem wvu_codingchallenge_groceryproducts
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_test_1
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_test_2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_1_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_4_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_5_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_6_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_2_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_3_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem hollins_table_intro_7_ac
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem wvu_image_rotation
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem final_exam_1
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem final_exam_2
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem final_exam_3
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem final_exam_4
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem KDL_ch7_8
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
2acfactory.js:175 Error rendering Activecode Problem TL_365_sequence_0_2_0.2_coi_jmc
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem irma_q1_loop
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
activecode.js:270 adding click function for run
acfactory.js:175 Error rendering Activecode Problem sbc_final_11
                Details: TypeError: Cannot read properties of undefined (reading 'textContent')
13activecode.js:270 adding click function for run
921.bundle.js?v=be00bef7ce8bb259171c:1 [Violation] 'setTimeout' handler took 54ms

**Comment by bnmnetp** [comment]
Note: I have worked around this by manually updating the database to remove the offending character.  The page displays properly for me now.
