### ISSUE TITLE
Grading/Unit Test bug - py4e-int - list_writeItemsq

### ISSUE THREAD

**Issue by lorrieteaching** [RunestoneInteractive/RunestoneServer#1792]
**What Course are you in** py4e-int

**What Page were you on**. Assignment question:  list_writeItemsq

**What is your username**  tomekla

**Describe the bug**
The fourth unit test auto-grades as failed, even though the shown expected result and actual result appear to match.

<img width="659" alt="list_writeItemsq_gradingbug" src="https://user-images.githubusercontent.com/67921919/138108340-dd87eff6-305b-4826-a532-5f0bda477f23.png">

**Comment by barbarer** [comment]
I will fix it.
