### ISSUE TITLE
8.14.15 Exercise

### ISSUE THREAD

**Issue by monagur** [RunestoneInteractive/RunestoneServer#1796]
**What Course are you in**
"How to Think Like a Computer Scientist: Interactive Edition"
I am using Chrome.

**What Page were you on**
https://runestone.academy/runestone/books/published/thinkcspy/MoreAboutIteration/Exercises.html
8.14, exercise 15: "Research the Sobel edge detection algorithm and implement it."

**What is your username**
N/A

**Describe the bug**
When running this exercise, I get this error:
"NotImplementedError: Execution limiting is not enabled on line 10"
Line 10 is the following: "sys.setExecutionLimit(20000)"
![Screenshot 8 14 15](https://user-images.githubusercontent.com/93458450/139564862-3b272edd-b543-47b1-8818-a556f5e55cfd.png)

**Comment by bnmnetp** [comment]
You can start by just commenting that line out.

I'll look into why that is causing an error, I suspect that something has changed with our upstream version of Python.
