### ISSUE TITLE
Delete all in Assignments

### ISSUE THREAD

**Issue by ConceptaNjolima** [RunestoneInteractive/RunestoneServer#1805]
**Is your feature request related to a problem? Please describe.**
Yes, currently we have to remove one question at a time. It would be good to have a delete all button

**Describe the solution you'd like**
A button that when clicked removes all the questions from the Bootstrap table

**Comment by abdulahia** [comment]
A group of Berea College students will work on this issue. @ConceptaNjolima @mccoyd15 @abdulahia
