### ISSUE TITLE
2 questions in assessment do not load, can't pass the test as a result.

### ISSUE THREAD

**Issue by arielfcotrim** [RunestoneInteractive/RunestoneServer#1811]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
On coursera: "Python Basics" Course, part of "Python 3 Programming Specialization" by the University of Michigan.

**What Page were you on**
(1) Coursera: Week 4, String Format Method
Runestone: 9.9. Non-mutating Methods on Strings
https://fopp.umsi.education/books/published/fopp/TransformingSequences/NonmutatingMethodsonStrings.html#string-format-method

(2) Coursera: Week 4, Assessment: Methods: Lists and Strings
Runestone: course_1_assessment_9
https://fopp.umsi.education/assignments/doAssignment?assignment_id=9

**What is your username**
Single Sign-On

**Describe the bug**
a. In 9.9. Non-mutating Methods on Strings: None of the interactive/assessment/test your knowledge squares show any info nor can you insert any data and interact with it.
![9 9  Non-mutating Methods on Strings — Foundations of Python Programming - Google Chrome 11_21_2021 10_36_32 AM](https://user-images.githubusercontent.com/93881636/142755380-cf19470d-3036-463e-90b8-b0b929d934b6.png)

(b) in course_1_assessment_9: first 5 questions appear ok and they work. The last two questions aren't formatted, you can type an answer in the answer field but can't check your answer, can't get test to score it, can't pass test as a result (you get stuck with less than 80% no matter what).
![Runestone Interactive - Google Chrome 11_21_2021 10_30_16 AM](https://user-images.githubusercontent.com/93881636/142755382-a8cac5d8-eab0-4718-8019-a76473c52680.png)
![Runestone Interactive - Google Chrome 11_21_2021 10_30_47 AM](https://user-images.githubusercontent.com/93881636/142755383-23400baa-e0ac-4c7b-be3a-61c3c55d0be9.png)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools
![Runestone Interactive - Google Chrome 11_21_2021 10_30_16 AM](https://user-images.githubusercontent.com/93881636/142755211-a46e2e19-9dc5-4ded-a692-34e7fdab5a73.png)
![Runestone Interactive - Google Chrome 11_21_2021 10_30_47 AM](https://user-images.githubusercontent.com/93881636/142755213-c4c4cc1b-8aab-4e18-ba83-1df8b4f11f56.png)

**Comment by presnick** [comment]
This was an issue with deprecated exercises continuing to be assigned in the Coursera assessments. It was fixed there, by removing the exercises from the assessments.

**Comment by arielfcotrim** [comment]
It’s not the first time something similar has happened.
Thanks though!!
