### ISSUE TITLE
py4e-int Activity 4.5.5

### ISSUE THREAD

**Issue by CH97-selfteaching** [RunestoneInteractive/RunestoneServer#1820]
Hello all! I am just beginning to learn how to code (day four, during downtime at my day job) but I believe the question for Activity 4.5.5 is improperly worded. I thought it was a trick question at first! The question assigns a value to the variable x, but the conditional statements contain the operand score. So if I understand everything so far, what would actually print when the code is executed would be NameError. Is that all correct? 

![image](https://user-images.githubusercontent.com/95075666/143558195-7da3389f-ca8e-4fa1-9b54-18fc8a7e0dde.png)

**Comment by barbarer** [comment]
It should be if score = 93.  I will fix it.
