### ISSUE TITLE
Catching errors in DAL operations can cause downstream confusion and more errors

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#1821]
I copied this into its own issue from #1817

Finding this bug brings up another issue: an anti-pattern scattered throughout the Runestone code base, usually in the context of logging. The exception handler leaves the database in a broken state, meaning that all past and future commits will be discarded, producing useless traceback info after the request completes. I propose not catching the error, to provide immediate feedback instead.

The pattern is:

``` Python
try:
    # Some db operation: for example,
    db.useinfo.insert(stuff_that_breaks)
except Exception as e:
    logger.error(f"failed to insert admin log record: {e}")
```

The resulting traceback is:

```
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/main.py", line 439, in wsgibase
    serve_controller(request, response, session)
  File "/home/www-data/web2py/gluon/main.py", line 202, in serve_controller
    raise HTTP(response.status, page, **response.headers)
gluon.http.HTTP: 200 OK

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/main.py", line 455, in wsgibase
    session._try_store_in_db(request, response)
  File "/home/www-data/web2py/gluon/globals.py", line 1254, in _try_store_in_db
    record_id = table.insert(**dd)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 891, in insert
    ret = self._db._adapter.insert(self, row.op_values())
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 546, in insert
    raise e
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 541, in insert
    self.execute(query)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 69, in wrap
    return f(*args, **kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 468, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

This gives absolutely no clue where the error occurred. I found it by browsing my server logs, which was not an obvious approach to me.

Discussion
=======
There are two cases for this error:
1. There were commits before the exception occurred. Then we should raise an error immediately, since we're losing data.
2. There were no commits before the exception occurred. Then we should do a rollback and begin another transaction, which (I think) would allow everything to proceed normally.

However, there's no way I know of to distinguish these two cases. A third option: use some Postgres-specific code (a savepoint?) to run. But this means we won't support sqlite.

Therefore, the simplest approach is to raise an error immediately. We should also search our logs to see if these errors are happening elsewhere and work around them. Here's what I found in my logs:

```
uwsgi.log:ERROR:web2py.app.runestone:failed to insert log record for practice: insert or update on table "useinfo" violates foreign key constraint "useinfo_course_id_fkey"
uwsgi.log:ERROR:web2py.app.runestone:failed to insert log record for practice: insert or update on table "useinfo" violates foreign key constraint "useinfo_course_id_fkey"
uwsgi.log:ERROR:web2py.app.runestone:failed to insert log record for practice: insert or update on table "useinfo" violates foreign key constraint "useinfo_course_id_fkey"
uwsgi.log:ERROR:web2py.app.runestone:failed to insert log record for practice: insert or update on table "useinfo" violates foreign key constraint "useinfo_course_id_fkey"
uwsgi.log:ERROR:web2py.app.runestone:failed to insert log record for practice: insert or update on table "useinfo" violates foreign key constraint "useinfo_course_id_fkey"
uwsgi.log.1631735760:ERROR:web2py.app.runestone:failed to insert log record for practice: value too long for type character varying(512)
```

**Comment by bnmnetp** [comment]
Good points.  I think in many cases though we do want to catch the exception rather than just have the end user seeing a stack trace.  That is not a good user experience.   But leaving the DB in a bad state is also not good.

As I understand it web2py automatically starts a transaction for each request and then commits it at the end unless there is an exception, then it is rolled back.   But if we are explicitly catching that exception then we are foiling web2py's plans.  I think in those cases it is up to us to do the right thing and rollback or attempt to recover in some other way.

I think there are only a few cases where we call commit ourselves. So perhaps it is not as hard to know if there has been a prior commit as you think. This does not feel like an emergency to me since we've been doing this for years, but we should definitely find a way to improve the situation.

I do occasionally get a giant streak of those `current transaction is aborted, commands ignored until end of transaction block` messages that appear in the errors folder. Presumably a side effect of what you described above.


I wonder if this is made worse by the fact that in several files I call admin_logger() from outside of a function.  So this gets called when the controller file is loaded rather than after the function is called.

1.  A rollback may be perfectly fine here
2. We could move the logging call inside the appropriate functions.  

Other places where we have used this pattern may be different.

**Comment by bjones1** [comment]
Rereading my earlier text, I see a mistake: I used the term "commit" when I should instead talk about "writes to the database." If there were previous writes, then catching the exception followed by a rollback causes data loss; otherwise, catching the exception and doing a rollback then starting a new transaction is a good approach. Finding the path the code takes to get to each call of `admin_logger()` (for example, looking at where it's called outside a controller and therefore hasn't performed any db writes) is the only way I can think of to distinguish these two cases, but it seems like a lot of work.

Since these exceptions can produce data loss, I'd propose simply raising the exception so we can track these down and fix them. Perhaps we can do this gradually -- replace calls to `admin_logger()` with `admin_logger(False)` which raises instead of catching -- so we don't produce a lot of exceptions at once?

**Comment by bnmnetp** [comment]
There are only three places where `admin_logger` is called from inside a function.  Those are all in default.py and they are all called at the beginning of the function. So I think the `rollback` I added is good and safe.

Now as to the potentially many other places where this happens that will take some time.

I haven't looked to see if we recreated this anti pattern in the new book server or not.

**Comment by bjones1** [comment]
OK, sounds good.
