### ISSUE TITLE
Server Not Work

### ISSUE THREAD

**Issue by erd0spy** [RunestoneInteractive/RunestoneServer#1829]
I try to run the server on my localhost. I have a sysadmin background and I know Docker, Linux, and Python. I am saying this because I follow the manual on each step but every time I failed. When I try manual installation there is no requirments.txt, I found old ones from forks but rsmanage gives an error every time about runestone libraries. When I try docker installation there is no book-build option and runestone servers failed every time because they can't interact with the dev_runestone database. Can anyone help me to build a server?

**Comment by bnmnetp** [comment]
This fork is a long ways behind the HEAD.

We know that there are documentation issues and things with rsmanage that need to be cleaned up and we are working on those.  It is working fine and will be in production soon.  Then we can catch up on documentation.

Right now the key is to shell into the running container to add and build books.

**Comment by erd0spy** [comment]
I build the containers with docker-tools.py from current branch but docker-tools.py return error when I try shell into container.
