### ISSUE TITLE
20.13. A Tamagotchi Game

### ISSUE THREAD

**Issue by jonathondonager** [RunestoneInteractive/RunestoneServer#1830]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Python Classes and Inheritance through Coursera

**What Page were you on**
20.13. A Tamagotchi Game¶

**What is your username**
Jonathon Donager 

**Describe the bug**
The 4th and last interactive code window doesn't show up. I've tried on multiple machines and multiple browsers. This keeps me from completing the page. 

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by presnick** [comment]
Thanks for the alert, Jonathan. We will try to fix this soon.
