### ISSUE TITLE
Not found in base course

### ISSUE THREAD

**Issue by lleskow** [RunestoneInteractive/RunestoneServer#1838]
Some courses (not all) are down with the message:

{"detail":"Page  not found in base course pythonds."}
{"detail":"Page index.html not found in base course bluebook."}

**Comment by bnmnetp** [comment]
Thanks for the report.

You may have seen the notice that we are moving to a whole new set of servers this week. Cleaning up lots of little things that are missing and broken edge cases.

bluebook and pythonds are both back and operational.

**Comment by lleskow** [comment]
Thank you for the quick fix.
I've seen the notice, it was easy to find and it explained very well the situation.
