### ISSUE TITLE
LTI option for Canvas is not working after new server changes

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1841]
From Randy Macdonald, randy.macdonald@corvallis.k12.or.us
Thanks for all the updates over the winter break.  The LTI option for Canvas is not working for me anymore. At first I got the error message, 'Couldn't find valid settings for this link'.  Then I changed the Launch URL from https://csawesome.runestone.academy/runestone/lti -> https://runestone.academy/runestone/lti.  Now I get,
Not logged in due to the following error(s)
OAuth Security Validation failed: ... (lots of text follows which probably contains sensitive security information, so I'm not sharing the rest)
I've then cleared my browser cache using your method and see the same error.

**Comment by PCaso27301** [comment]
I am encountering the same issue with Moodle LTI. I changed the settings in the External Tool settings and adjusted the link for an individual assignment. When clicking on the link, I get 

**Not logged in due to the following error(s)
user_id is required for this tool to function
<Storage {'assignment_id': '89595'}>**

**Comment by hahders3** [comment]
I am also encountering this error. Any help would be greatly appreciated.

**Comment by bnmnetp** [comment]
This is a known problem and we are working on it as quickly as we can.

**Comment by PCaso27301** [comment]
Looks like it's working now... at least for access. I have to figure out why I'm seeing grades pulled as zeros though. It could be something in my settings.

**Comment by bnmnetp** [comment]
I have pushed changes that I hope will get this all working... please give it a try and let me know!

since I do not have Canvas or Moodle, I am relying on others to help me get this working.  Thanks for your patience.

Brad

**Comment by hahders3** [comment]
Looks like it is working for Canvas. At least I can click on the link and it will take me to the assignment/reading page. I can not try with the test student, I get an error. Not sure how to test it for students. I hope when class starts my students will be able to go there and it will pull the grades.

**Comment by PCaso27301** [comment]
In Moodle, the link brings the student directly to the assignment, but after running the autograder, no score shows up in the Moodle Gradebook. Is there some setting I am missing for the type of grade? I have it set as a point value (Options are point or scale in Moodle). Also, I get some students filled with a 0.00 and others are blank. When I look at the grades in CSAwesome, they all have percents above 0%.

**Comment by bnmnetp** [comment]
I believe this is back working for everyone now.
