### ISSUE TITLE
Link to Instructor Guide broken

### ISSUE THREAD

**Issue by HeidiEllis** [RunestoneInteractive/RunestoneServer#1843]
**Please check the current issues** 
Done

**What Course are you in**
java4python

**What Page were you on**
https://runestone.academy/runestone/static/instructorguide/index.html

**What is your username**
HeidiEllis

**Describe the bug**
I'm getting a 404 Not Found when I attempt to access this page.  I've tried from the right-hand menu on the main page and other pages. 

**Traceback**
None

**Javascript Errors**
N/A

**Comment by HeidiEllis** [comment]
It appears that the appropriate page should be: https://runestone.academy/ns/books/published//instructorguide/index.html
However, I am not sure if the intent of the Runestone community is for this page to be available to the public.

**Comment by bnmnetp** [comment]
Thank you @HeidiEllis I will update our template so that the next time I rebuild the books they will all have the correct link.
