### ISSUE TITLE
Assignments links take students to login page

### ISSUE THREAD

**Issue by llenertzdahlgren** [RunestoneInteractive/RunestoneServer#1845]
I have a python course and Mobile application course.  The assignments link works to take students to the list of assignments, but clicking on the reading link takes them to the login page even though they are already logged in.  The Return to [insert class here] link at the top of the page does the same thing.

**Comment by bnmnetp** [comment]
There is a know problem that causes this behavior if you and/or your students have `@` symbols in their usernames.  I'm working on a fix.

**Comment by bnmnetp** [comment]
If you can get me your course name(s) I would be happy to validate that this is the case.

**Comment by llenertzdahlgren** [comment]
Sure, I appreciate the help.

Python_Test
Mobile_App_Development

Or do you mean the course IDs?

Lorissa Lenertz
Information Technology
Sheyenne Valley Area Career and Technology Center
________________________________
