### ISSUE TITLE
completed question data is not restored to the page from the new server

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1849]
Bug report from David Deutsch:
Work is not saved and completed date next to green check marks shows as 0.
"I've cleared cache, logged out and back in, and tried many combinations.  What happens is it shows the green check but not the completed on date....just shows a date of 0.  Then, if you go back to the course list of all lessons, and select the lesson you just completed, none of your work is saved, and must be redone.  This happens on all of my courses:

https://runestone.academy/ns/books/published/MBA-CSA-2021-22-Deutsch/index.html
https://runestone.academy/ns/books/published/MBA-CSP-2021-22-Deutsch/index.html
https://runestone.academy/ns/books/published/Summer-2021-PD-RPP/index.html

Any other suggestions?  Thanks!

David Deutsch

<img width="1286" alt="Screen Shot 2022-01-03 at 4 41 52 PM" src="https://user-images.githubusercontent.com/4571962/148257669-e2251f8d-9316-4504-a1a6-d3d3417a0969.png">

Montgomery Bell Academy

**Comment by bnmnetp** [comment]
Let me just reassure you that the answers are being saved.  There is a bug in the new server where we are not restoring the counts.

Also I'm not sure why the date is 0 but I'll look into that.  It seems less important than other more pressing bugs.
