### ISSUE TITLE
CSAwesome 6.2.4 Parsons Problems

### ISSUE THREAD

**Issue by annehasseld** [RunestoneInteractive/RunestoneServer#1850]
6.2.4 Two parsons problems do not show correctly. 
![CSAwesome 6 2 4 Parsons Problem Errors AHasseld 1 5 2022](https://user-images.githubusercontent.com/53468660/148280766-003ea2e4-5355-4819-b637-97b1f92fd236.png)

**Comment by bnmnetp** [comment]
Can you please check your javascript console and include any error messages you see?

**Comment by annehasseld** [comment]
I think this is what you are asking for ... let me know if it's not
<pre class="parsonsblocks" data-question_label="6.2.4.5" data-adaptive="true"
data-noindent="true" data-numbered="left" style="visibility: hidden;">
public static void reverse(int[] a)
{
---
int temp = 0;
int half = a.length / 2;
int max = a.length - 1;
---
for (int i = 0; i < half; i++)
{
---
temp = a[i];
---
a[i] = a[max - i];
---
a[max - i] = temp;
---
} // end for
---
} // end method
</pre>
</div>
</div>
<div class="runestone" style="max-width: none;">
<div data-component="parsons" id="pab_4" class="alert alert-warning parsons"
>
<div class="parsons_question parsons-text" >
<p>The following program has the correct code to return the average of the
first 3 items in the array a, but the code is mixed up. Drag the blocks
from the left into the correct order on the right. You will be told if any
of the blocks are in the wrong order or are indented incorrectly.</p>

</div>
<pre class="parsonsblocks" data-question_label="6.2.4.6" data-adaptive="true"
data-numbered="left" style="visibility: hidden;">
public static double avg3(int[] a)
{
---
double total = 0;
---
for (int i = 0; i < a.length && i < 3; i++)
{
---
total = total + a[i];
---
} // end for
return total / 3;
---
} // end method
Anne Hasseld
Computer Science Teacher
Hartland Women In Technology Advisor
Hartland High School
810-626-2344
"Darkness cannot drive out darkness: only light can do that. Hate cannot
drive out hate: only love can do that. " -Dr. Martin Luther King Jr.

**Comment by bnmnetp** [comment]
No, that is the html source for the parsons see -- https://appuals.com/open-browser-console/

I'm looking for Javascript errors that will help me understand what the problem is for these exercises.

**Comment by bnmnetp** [comment]
Also what browser are you using?  I just looked at 6.2.4 in Safari and those parsons problems are fine. -- again that is why the javascript errors from your console will be helpful.

**Comment by bhoffman0** [comment]
They look fine on Chrome too.

**Comment by annehasseld** [comment]
I am using Chrome.
I am at home now, still using chrome but on my macbook.  They display just
fine.
I will try to recreate the problem tomorrow at school.  I apologize!
Anne Hasseld
Computer Science Teacher
Hartland Women In Technology Advisor
Hartland High School
810-626-2344
"Darkness cannot drive out darkness: only light can do that. Hate cannot
drive out hate: only love can do that. " -Dr. Martin Luther King Jr.

**Comment by annehasseld** [comment]
Here are the javascript errors.
Thank you so much for your time and, again, I apologize for not providing
better initial data.
Anne Hasseld
Computer Science Teacher
Hartland Women In Technology Advisor
Hartland High School
810-626-2344
"Darkness cannot drive out darkness: only light can do that. Hate cannot
drive out hate: only love can do that. " -Dr. Martin Luther King Jr.

**Comment by bnmnetp** [comment]
@annehasseld I still don't see any javascript errors.  You may need to use the web interface rather than replying by email to get them to post on GitHub.
