### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by DawnRoss** [RunestoneInteractive/RunestoneServer#1852]
Link sent in email didn't work.  Tried at school and at home.  Completely unable to get into site to teach my students.  Please help!
Username bross_ptaaschool
email bross@ptaaschool.org

**Comment by bnmnetp** [comment]
I can see that the link sent to you is pointing at csawesome.runestone.academy.  Just remove the csawesome part and it should work fine.   You should not use CSAwesome at all anymore.  Please just use https://runestone.academy

**Comment by DawnRoss** [comment]
That worked!!!!!  Thank you so much - I am a teacher again and can grade!!

**Comment by bnmnetp** [comment]
Over the holidays we completely replaced all of our servers.  I posted announcements in many places, but plenty of people still missed them.  Here are the details:  https://runestoneinteractive.org/2021/12/21/academy_downtime.html

You should now use your course name in the URL to your course, which in the long run will really reduce confusion for students on getting into the proper course.

for example https://runestone.academy/ns/books/published/MYCOURSEHERE/index.html

Brad
