### ISSUE TITLE
Expired Security Certificate

### ISSUE THREAD

**Issue by DawnRoss** [RunestoneInteractive/RunestoneServer#1853]
WHen trying to go to your website my students and I started getting notice that your certificate had expired.

**Comment by bnmnetp** [comment]
The certificate does not expire until the end of January.

```
  Certificate Name: dev.runestone.academy
    Domains: runestone.academy dev.runestone.academy
    Expiry Date: 2022-01-31 02:03:36+00:00 (VALID: 24 days)
```
I will renew it this weekend.

**Comment by bnmnetp** [comment]
Renewed it this morning.  Good for another 90 days.
