### ISSUE TITLE
Parsons problems error in all books when not logged in 

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1856]
I finally realized that the Parsons problem bug of not showing is happening when you are not logged in. @bnmnetp try it in incognito mode on https://runestone.academy/ns/books/published/csawesome/Unit7-ArrayList/ListParsonsPractice.html and https://runestone.academy/ns/books/published/StudentCSP/CSPNameNumbers/VariablePracticeParsons.html
![image](https://user-images.githubusercontent.com/4571962/148582331-e8b5ff07-2dab-4aa4-a73a-ab69c8d1f007.png)

**Comment by bnmnetp** [comment]
Interesting... yes another victim of our code getting stricter about error handling.  There should be an easy alternative to fix this and allow the parsons to finish.
