### ISSUE TITLE
My students are entering code for their assignments but for some of the students to code is not being saved. This problem just cropped up.

### ISSUE THREAD

**Issue by psuci** [RunestoneInteractive/RunestoneServer#1857]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.
There was a similar one about loosing student work

**What Course are you in**CEBOXELDER2
Knowing the course will help us a lot

**What Page were you on**

**What is your username**psuci

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by psuci** [comment]
I tried clearing the browser data. I could then see older assignments but not newly created assignments.

**Comment by bnmnetp** [comment]
Your students will need to do the same thing.  With this upgrade it is REALLY REALLY import that everyone logs out and logs back in again with a clear cache.

**Comment by psuci** [comment]
I was wondering about that.
This one totally baffles me.
(I am worried that people like you will not be able to keep things like
this running, or that you will just get too sick of all the hassle).

**Comment by bnmnetp** [comment]
Big server upgrade with lots of new code for serving the pages of the book and handling api calls.  This new server is much stricter about validating incoming data, and was not happy with the format of the timestamp for the due date.  So the request to return the saved answers was denied.

This is why I plead with people to open the javascript console and include any errors with their bug reports.  That error was clearly present and pointed me right to where I needed to look in the code.

**Comment by psuci** [comment]
So what do I do to prevent this happening for my next class?
(I don't know what the the server was unhappy with?)

**Comment by bnmnetp** [comment]
1. Make sure your students log out.
2. Have them clear their browsing history
3. Log back in
4. Make sure they are using the url https://runestone.academy/ns/books/published/csboxelder2/index.html to access your course.
5. If they have any problems please check the Javascript Console in the browser and report any error messages back here.

Thanks,


Brad
