### ISSUE TITLE
Course AC1:  Introduction to Google Sheets and SQL is missing

### ISSUE THREAD

**Issue by jeremyallenjacobson** [RunestoneInteractive/RunestoneServer#1858]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
ac1: Introduction to Google Sheets and SQL

**What Page were you on**
Any page
**What is your username**
jajaco3
**Describe the bug**
When I click the ac1 in my course list, I am taken to a page that states only

 "{"detail":"Page index.html not found in base course ac1."}". 

Additionally, the course that I made from ac1 has the same error message.

**Comment by bnmnetp** [comment]
working fine for me, is it still missing for you?

**Comment by jeremyallenjacobson** [comment]
I just tested and it is working like normal for me now. Thank you!
