### ISSUE TITLE
Cannot create or delete a course

### ISSUE THREAD

**Issue by dianeroux** [RunestoneInteractive/RunestoneServer#1861]
**What Course are you in**
How to Think Like a Computer Scientist: Interactive Edition

**What Page were you on**
Instructor's Page

**What is your username**
dianeroux

**Describe the bug**
When I try to create or delete a course, I get an "Internal Error".

![image](https://user-images.githubusercontent.com/32103576/148701191-f9fb88ab-a28e-4941-b4f6-ce4dae91d934.png)

**Comment by bnmnetp** [comment]
When were you doing this?  I fixed a bug last night and I can see that courses have been building fine all day.  I cannot find that ticket on any of our servers which makes me think it was before I fixed it.

**Comment by bnmnetp** [comment]
Delete course does not work. We added a bunch of Foreign Key constraints in the database so now we will need to delete from the database all student answers and activity for a course before it can be removed.

I think this is not a bad thing from a privacy standpoint especially for high schools as it gives the teacher the ability to remove all student data from our system.

On the other hand I think it is kind of unfair for a student to have a teacher decide that all of their work can just be wiped out.  A student should be able to retain their answers to questions if they so desire.

I'm curious what your goal is for deleting a course?  Just to get it off your list of courses?  Or for student privacy?

**Comment by bnmnetp** [comment]
If you just want to get it out of your list of courses then you can drop the course from the change courses page.

**Comment by dianeroux** [comment]
I was trying to create courses yesterday.  I just tried now, and it works fine.  Thanks.

________________________________

**Comment by dianeroux** [comment]
I was attempting to delete old courses to clean up.  At the college where I teach, the IT department asks us to get rid of anything we are no longer using.  Our records retention policy requires that we keep course records for a year, but I still have old courses in Runestone back to Fall 2018.  Don't you want to get them off the server?

________________________________

**Comment by bnmnetp** [comment]
Yes,  I want to get stuff off the server I don't want to support tables with a billion rows in them, that just drives up my costs.

I want to institute something that meets the following goals:

1. preserves student work for a reasonable amount of time for students that want to use runestone as a reference and want to see work they did in a previous class.
2. Meets high school district privacy policy requirements...
3. Gives teachers some degree of control over removing old course materials
4. Allows students/teachers to remove all trace of themselves from Runestone (required by GDPRs)
5. Preserve some amount of anonymized data for pedagogical research.
