### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by sellstep** [RunestoneInteractive/RunestoneServer#1863]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
CS Awesome (My course is AP_Java_21_22)
Knowing the course will help us a lot

**What Page were you on**
Activity 5.13.3.1 ActiveCode(stepTrackerCode1)

**What is your username**
My username is: sellstep

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?
Some of my students are experiencing a 'code dump' on an assignment based on the built in stepTracker assignment in Unit 5. I have now had 2 students with this error:
'A server error occurred: $1 $2'
- Also, their code that was entered is now gone and unretrievable.

![ServerError-CSAwesome](https://user-images.githubusercontent.com/30213472/148972771-45b23d25-b516-44ba-a590-c820994477b7.png)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bhoffman0** [comment]
Hi, This is an error in your student's code. They need to fill out the name of the class or they will get this error. Line 2 needs to be:
  public class StepTracker
