### ISSUE TITLE
"Question in Context" Links in Assignments broken

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1864]
"Question in Context" Links in Assignments are not working and being sent to the course selection page instead.

**Comment by bnmnetp** [comment]
Yeah, I fixed this a couple days ago.  I had hoped to install it everywhere last night, but ran into some other issues that kept me from getting a clean build.  -- Those are resolved so I"m hoping that when things calm down later tonight I'll be able to do an update with several bug fixes in it.

**Comment by bnmnetp** [comment]
I know this one is annoying.  I simply forgot to update the template for the assignment page to use the new URL scheme.  So it is trying to send everyone to the base course, but since they are logged in already it won't let them and sends them to course selection page instead.

**Comment by bnmnetp** [comment]
Fixed and live!
