### ISSUE TITLE
cppds doesn't recognize logged in user, c++ code doesn't execute 

### ISSUE THREAD

**Issue by y44k0v** [RunestoneInteractive/RunestoneServer#1865]
Browser chrome macos, Version 97.0.4692.71 (Official Build) (x86_64). Only course with this problem (Problem Solving with Algorithms and Data Structures using C++), it shows the login  option under the user icon but when clicked takes you to http://127.0.0.1:8000/runestone/default/user/login (lol). When trying to run C++ code the following appears:

```
Compiling and Running your Code Now...

Error
Error communicating with the server.TypeError: Failed to fetch
```

Python tab runs ok, but it is a c++ course. 
The green button appears as "SAVE & RUN" but the footer has "user not logged in" on the left. Switching to other courses make everything work normal. 

Thanks for looking into it.

**Comment by bnmnetp** [comment]
Thanks for reporting that.  Just a little mis-configuration for that book.  

Should be working fine now.

**Comment by y44k0v** [comment]
All good, Thanks
