### ISSUE TITLE
Trying to access any of "Exercise" pages within Foundations of Python Programming course and getting an internal error

### ISSUE THREAD

**Issue by kyrylooni** [RunestoneInteractive/RunestoneServer#1867]
**What Course are you in**
Foundations of Python Programming

**What Page were you on**
https://fopp.umsi.education/books/published/fopp/Tuples/Exercises.html

 
**What is your username**
kiriloni2k17@gmail.com

**Describe the bug**
As I am trying to access any of the exercise pages through the Table of Contents page, I keep getting the same "Internal Error." The issue appeared about 4 days ago, whereas before it loaded these pages as intended so I was able to work on the exercises. I log in to the textbook using Corsera's "Single Sign On: Interactive Textbook and Practice Opportunities" within the Python3 Specialization.

**Javascript Errors**

JS Console shows it as an error 500

<img width="1679" alt="Screen Shot 2022-01-12 at 7 51 51 PM" src="https://user-images.githubusercontent.com/65361994/149247136-144db3ab-9f13-40e3-8163-9541869e1b4c.png">
<img width="598" alt="Screen Shot 2022-01-12 at 8 00 34 PM" src="https://user-images.githubusercontent.com/65361994/149247144-13c30dfa-4d21-4fcc-a56b-654dcd6b4705.png">

**Comment by bnmnetp** [comment]
Hi, sorry but we have no way of supporting the umich servers, please contact your coursera instructor or TA.
