### ISSUE TITLE
Skipped all questions in an assignment

### ISSUE THREAD

**Issue by RuinousEffigy** [RunestoneInteractive/RunestoneServer#1882]
Good morning (or afternoon). Recently, I was given an assignment to do on runestone and up until after submitting the assignment does any complication occur. When I look to review my grade on the assignment, I get a message saying that all the questions were skipped instead of completed. Additionally, the assignments also say that I never even started them to begin with despite also saying I chose to skip all the questions. I made sure to not switch tabs during the assignment after the first attempt, but that too provided no remedy.
The class I am in is called MCTC APCSA, and my username is VR115167.

**Comment by bnmnetp** [comment]
It sounds like this may have been a timed assignment?  Can you tell me the name of that assignment?

I will try to dig in a bit and see if I can figure out what may be happening, unfortunately this does not seem to be a widespread problem, and I have tried several of the timed assignments myself and all was working fine.

Are you using a recent browser?  which one?  Do you have any filters/plug-ins/extensions that may filter out cookies?

If this happens again it would be super helpful for you to open the Javascript Console in your browser and send any messages or errors you see there.
