### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by lindsaykrisher** [RunestoneInteractive/RunestoneServer#1887]
Could you please reset my password for runestone academy? I am a teacher. Thank you!

**Comment by bnmnetp** [comment]
I'm sorry @lindsaykrisher butI cannot take anonymous requests to reset a password.  If you reach out to me by email using the same email that is in the Runestone database then we can see if we can verify your identity and get this fixed. 

However there are already facilities in Runestone that work fine to get your password reset.
