### ISSUE TITLE
Issue - Activity: 6 ActiveCode (u3_muc_wc6)

### ISSUE THREAD

**Issue by alston13r** [RunestoneInteractive/RunestoneServer#1891]
AP CS A Java Course

3.10 Experimental: Toggle Mixed Up or Write Code Practice
Activity: 6 ActiveCode (u3_muc_wc6)

arodriguez820

The description to the question states "Write code that prints your fine if you are speeding. If you are going over 65 but less than 75, the fine is 50. If you are going at least 75 and less than 85, the fine is 100. Over that the fine is 200. It should not print anything if you are not speeding."
After writing the code and its conditionals, the auto-grader checks if the conditional has (speed >= 65) when the description states "over 65" and not "at least 65".
Just a minor nuisance.

**Comment by bhoffman0** [comment]
Thanks! I will fix it. Should be live on Saturday.
