### ISSUE TITLE
Practice questions not coming

### ISSUE THREAD

**Issue by edogdu** [RunestoneInteractive/RunestoneServer#1892]
I have set up the practice questions fine, but students do not get practice questions after marking sections completed. Can someone please check the course: **Learn_Python_ASU_Spring2022**. Instructor id is edogdu. Thanks,

**Comment by edogdu** [comment]
I hope someone will respond to this issue. My 50 students are waiting this to be resolved soon. Thanks,

**Comment by bhoffman0** [comment]
Do you mean the Practice Tool? Here are some instructions for setting it up: https://www.csawesome.org/runestone-e-book/practice-tool. The practice tool can be buggy.  If you've added a TA, the control seems to go to just one teacher, so have all teachers try setting it. If you haven't checked off enough lessons, it may not have enough practice problems to get it going.

**Comment by edogdu** [comment]
Hi Beryl,

I set the settings in practice. I am the only teacher and there is no TA. I and my students are marking the sections completed, yet we do not get any questions in practice. Please help. Thanks. 

Erdoğan

**Comment by bnmnetp** [comment]
I think there may be a problem with the self-paced option.  Just use the option where you mark sections complete in the practice tab on the instructor interface.

I will find some time to look into the problem with self-paced soon.

**Comment by bhoffman0** [comment]
Yes, I was going to suggest the same thing. Click on Show Practice
Settings. Then change to "Manually by the Instructor" and check off some
units.
[image: image.png]
