### ISSUE TITLE
Applied computing: datasets not available ("request access")

### ISSUE THREAD

**Issue by jeremyallenjacobson** [RunestoneInteractive/RunestoneServer#1893]
In the Applied computing textbook (ac1), clicking the dataset in the section "Motivating scatterplots" of the chapter "Scatter Plots and Correlation" leads to a "request access" Google drive page.

The same issue occurs in the sections "Pivot tables" and "Joining Data" from the chapter "Manipulating Data".

**Comment by bnmnetp** [comment]
Fixed
