### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by lbjorgum** [RunestoneInteractive/RunestoneServer#1896]
Please reset password for Runestone acct for lbjorgum (all other pages giving 404 error)

**Comment by lbjorgum** [comment]
Please reset password for Runestone acct for lbjorgum (all other pages giving 404 error)

**Comment by bnmnetp** [comment]
please just ad https:// in front of the url as suggested.

**Comment by lbjorgum** [comment]
Thank you!
