### ISSUE TITLE
Students' work not saving

### ISSUE THREAD

**Issue by jonnycomes** [RunestoneInteractive/RunestoneServer#1908]
Hello! I am using the Runestone Blue Book this semester to give my students some basic training in SQL. I have two students reporting that the work they have done on an assignment is not showing up in their history after they log out and log back in (and I see no history of their work when grading). Here are more details:

-  Course name: CSC-270-22Spring
- Both times the student completed the entire assignment, but all problems for that assignment are showing no history. Both students have not had this issue on any other assignment.
- First instance:
    - Student: josiah-shields
    - Assignment: SQL - SELECT, FROM, WHERE, ORDER BY
    - Josiah made a video showing his completed assignment before his work disappeared, so I know it's a real issue.
- Second instance:
    - Student: moung-shwe
    -  Assignment: SQL - GROUP BY, HAVING, AS
    -  Note that this is a different assignment than the first instance.

**Comment by bnmnetp** [comment]
I see over 200 saved code runs for josiah and 150 for moung-shwe.   My guess is that they are not pressing the button to reload their history.  The code is not automatically restored when the page is loaded, students must press the load history button to bring back their work.

**Comment by bnmnetp** [comment]
If they are doing the reload history AND they can somehow repeat this I would really appreciate it if you could help them open the Javascript console and send me any errors or debug messages you see in the console.  This is definitely not a widespread issue so its going to require some patience to track down.

**Comment by jonnycomes** [comment]
Thanks for checking on this Brad. I have had students not see the load history button before, but this is something different. I cannot see any history for either student (on those specific assignments) when I am grading. I attached a screenshot showing one of the exercises for Josiah -- all the other exercises on that assignment (but only that assignment) are showing no history for him. I also had Josiah show me his (empty) history in person after seeing him complete some of the exercises. 

![image](https://user-images.githubusercontent.com/43709428/156270710-06419226-d611-411e-be49-76f6f25bf99b.png)




03/01/2022 at 08:15am
--


<br class="Apple-interchange-newline">

**Comment by bnmnetp** [comment]
The most likely culprit is that when we send the logging request to save the code something is missing and not validating on the server side.  That would show up clearly in the javascript console and point me right to the problem.  If he can try it again that would be super helpful.

**Comment by bnmnetp** [comment]
Also, if you could find out the date / approx time and timezone your student was seeing this problem that would help me try to narrow in on potential log messages on the server side.

**Comment by jonnycomes** [comment]
Hi Brad. Thanks again for looking into this. My students and I were unable to recreate the issue today. Everything seems to be saving correctly now for both students. I'm sorry I didn't grab an error or debug message when I first saw the issue. I'll remember to do that in the future.

As for the when, below are a couple screenshots from Josiah showing a save that neither of us can see in the history. The save happened on Feb 17 at 3:17:11 PM Mountain Time. I hope that is helpful.

![image](https://user-images.githubusercontent.com/43709428/156653351-de0ea9b7-e794-44c6-89c7-9fe755bd8e2b.png)

![image](https://user-images.githubusercontent.com/43709428/156653460-f1c759b4-06bd-4f43-a259-086ac8e8e504.png)

**Comment by bnmnetp** [comment]
This weekend I added some code so that if a student is **logged in** but their code or anything they do fails to get recorded on runestone they will get a dialog.  That dialog should have some important debug information attached that will help us get to the bottom of any remaining issues.  At the very least it will alert students to the fact that things are not saved so they will not be surprised.
