### ISSUE TITLE
Incorrect Indentation for Lists Parson's Problem Solutions

### ISSUE THREAD

**Issue by lorrieteaching** [RunestoneInteractive/RunestoneServer#1911]
**What Course are you in**
py4e-int
CSC121-SP22-DurhamTech

**What Page were you on**
Creating and Testing Assignments for Chapter 9 on Lists on 9.17 Mixed Up Code Questions

listMixed_numbers 
<img width="832" alt="listMixed_numbers" src="https://user-images.githubusercontent.com/67921919/157450251-10b73c7e-9c25-405f-be6b-bd857384f72f.png">

listMixed_odd
<img width="919" alt="listMixed_odd" src="https://user-images.githubusercontent.com/67921919/157450319-15f9ad0d-e876-4ffd-bcf9-70c8da8ca994.png">

**What is your username**
tomekla

**Describe the bug**
The solution to some Lists questions do not have proper indenting under the def function header (the next line should be indented, but is marked correct if not indented)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by barbarer** [comment]
These have been fixed or replaced.
