### ISSUE TITLE
504 Gateway Time-Out when trying to access Student Progress page or download log for past courses

### ISSUE THREAD

**Issue by lslavice** [RunestoneInteractive/RunestoneServer#1913]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
engr101umich-f21 and engr101umich-w21

**What Page were you on**
Student Progress and Admin > Download Log

**What is your username**
lslavice (also odoty)

**Describe the bug**
We are getting 504 Gateway Time-Out errors when trying to access the Student Progress pages for these courses. Also when we try to download the logs for both courses.

**Traceback**
N/A

**Javascript Errors**
<img width="1390" alt="Screen Shot 2022-03-15 at 10 22 45 AM" src="https://user-images.githubusercontent.com/70032904/158406676-210564cb-6b4d-4daa-b7fa-e07e7ca6cda5.png">

**Comment by bnmnetp** [comment]
This is a known problem for large courses.  We are working on gathering the data and zipping it up as a background task to avoid the gateway timeout issue.

If you want to email me with the courses I can probably get you a dump.
