### ISSUE TITLE
Missing file for write code question

### ISSUE THREAD

**Issue by DebMDuke** [RunestoneInteractive/RunestoneServer#1915]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Python for Everybody - Interactive as cmsc210

**What Page were you on**
Week 8: Problems

**What is your username**
DebMDuke

**Describe the bug**
I assigned the write code problem 8.14.10 (file_ex_emotionq) and when run in the problem set the file could not be found, however when run after clicking the Question in Context link, the file is available.

![Screen Shot 2022-03-18 at 12 37 28 PM](https://user-images.githubusercontent.com/1023063/159324962-02973646-708a-45f9-83d2-85c0e176fb30.png)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
@barbarer - make sure the `emotion_words.txt` file is done using the datafile directive.  That way it is available in assignments as well as in context.

**Comment by barbarer** [comment]
Will do.  But, they can also click the question in context.

**Comment by barbarer** [comment]
This has been fixed
