### ISSUE TITLE
Random students who are not enrolled in that course are shown in chapter activity report

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1918]
A teacher, Kathy Chang, reported that in her course WHS-2021-P3, 4 students show up in the Chapter Activity table, but they are not in that class and do not show up in the gradebook or manage students. The students who shouldn't be there are: rajnaw890, rohnig910, colngo909, lolhiheyhi.  The first two students are her students from last year. The third student is from this year but in another period/class, and lolhiheyhi is an unknown student.  They only show up in this chapter activity table, not in the roster or gradebook.  Maybe the query goes wrong somewhere when pulling up data.

**Comment by bnmnetp** [comment]
All of the students mentioned have recorded activity in the class WHS-2021-P3.  That is why they show up in the report. 

None of the students are enrolled in that class now, and in every case it is very little activity, so it seems likely that they briefly enrolled themselves mistakenly and then dropped the class from the Change Class page.
