### ISSUE TITLE
Activity: 2.9.2 missing code

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1919]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
Activity: 2.9.2 Automatic Type Conversion (char_operations_AC_2)

**What is your username**
AlexAcosta

**Describe the bug**
Line 7 of the exercise should read 'cout << number << endl;', rather than end with '}'.

**Traceback**
test.cpp: In function ‘int main()’:
test.cpp:5:9: error: variable ‘number’ set but not used [-Werror=unused-but-set-variable]
    5 |     int number;
      |         ^~~~~~
cc1plus: all warnings being treated as errors

**Javascript Errors**
N/A

**Comment by pearcej** [comment]
@barbarer See Issue #1919

**Comment by barbarer** [comment]
Thanks for catching that.  It will be fixed by Saturday.
