### ISSUE TITLE
Activity: 3.1.3 variable inconsistencies

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1920]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
Activity: 3.1.3 Multiple Choice (floating_point_3)

**What is your username**
AlexAcosta

**Describe the bug**
The example code uses 'e_int' and then later 'eInt'. Once the correct answer is entered, it then refers to the variable as 'e_nt'. It's just confusing since the variables are not consistent.

**Traceback**
N/A

**Javascript Errors**
N/A

**Comment by barbarer** [comment]
Thanks for catching this. It will be fixed on Saturday.
