### ISSUE TITLE
Chapter 'activity bar' issue

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1923]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
3.11. Functions with Results

**What is your username**
AlexAcosta

**Describe the bug**
There are 3 code blocks (which cannot be interacted with) and the activity meter at the bottom indicates 1/2 activities complete, but there are no activities to complete to bring it to 2/2.

**Traceback**
N/A

**Javascript Errors**
Maybe?

**Comment by bnmnetp** [comment]
I think this should be 3 separate fillintheblank questions, but it is written as one and is incorrectly formatted.

**Comment by bnmnetp** [comment]
Reopening since this is not yet fixed.

**Comment by barbarer** [comment]
I just didn't commit the change in time for the weekend.
