### ISSUE TITLE
Typo in question results in giving incorrect answers

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1924]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
3.13. Multiple Choice Exercises

**What is your username**
AlexAcosta

**Describe the bug**
Activity: 3.13.3 Multiple Choice (functions_mc3) shows 'int a = 1.5' and when added to 'double b = a + 1.5' results in 3.0 (which is a non-zero, so technically 'b' should not be a correct answer, but in the answer block, it states a = 1, which it does match the shown question for the student.

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
a is an int so the value is 1 and b is correct.
