### ISSUE TITLE
Activecode Exercise Incorrect Instructions

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1926]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
3.15. Activecode Exercises

**What is your username**
AlexAcosta

**Describe the bug**
Activity: 3.15.3 ActiveCode (functions_a3q) indicates on Line 12 to not modify anything below that line. The answer then shows the correct fix to the code is to change code below Line 12 (swapping variables).
Question:
    // DO NOT MODIFY ANYTHING BELOW THIS LINE
    cout << b << " / " << a << " = "; divide (a, b);
}
Answer:
    cout << b << " / " << a << " = "; divide (b, a);
}

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
Thanks for finding this.  It will be fixed by Saturday.
