### ISSUE TITLE
Missing } in activity results in error

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1929]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
4.5 (Activity: 4.5.1 Classifying an Integer (nested_conditionals_AC_1))

**What is your username**
AlexAcosta

**Describe the bug**
The code in Activity: 4.5.1 Classifying an Integer (nested_conditionals_AC_1) needs an additional '}' at the end of the code or it returns an error

**Traceback**
test.cpp: In function ‘int main()’:
test.cpp:17:1: error: expected ‘}’ at end of input
   17 | }
      | ^
test.cpp:4:13: note: to match this ‘{’
    4 | int main () {
      |             ^

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
Good catch.  It will be fixed by Saturday.
