### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1930]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
4.7. Recursion, Activity: 4.7.2 Guessing Game. (recursion_AC_2)

**What is your username**
AlexAcosta

**Describe the bug**
When run, the exercise outputs "Enter your guess!Too high!" repeating until it crashes. Not sure how to fix that.

**Traceback**
Segmentation fault (core dumped)

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
The problem is that cin isn't getting a number from the user.  I will have to check with Brad, the main developer on how to fix this.
