### ISSUE TITLE
Confusing typo in 'mix-n-match' exercise

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1931]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
4.12. Mixed-Up Code Exercises, Parsons (cond_recc_p7)

**What is your username**
AlexAcosta

**Describe the bug**
One block of the 'mix-n-match; code has a string labeled "Knive" and I'm not sure whether it's supposed to be 'Knight' or 'Knave' to match the rest of the code. I think it's supposed to read 'Knight'. It just makes the problem difficult to solve with the typo.

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
You are correct.  It will be fixed on Saturday.
