### ISSUE TITLE
Incorrect solution in chapter review

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1937]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
6.13. Mixed-Up Code Exercises, Parsons (mucp_6_4)

**What is your username**
AlexAcosta

**Describe the bug**
A mixed-up code section lists a solution as;
void repeatHello () {
    int n = 0;
    int n = 0 //assigning a second time and no semi-colon
    while (n < 3) {
        cout << "hello" << endl;
        n++;
        --n; //shouldn't be decrementing AND incrementing - will infinite loop if decrementing
    }
}

When complete, it should read;
void repeatHello () {
    int n = 0;
    while (n < 3) {
        cout << "hello" << endl;
        n++;
    }
}

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
Nice catch.  It will be fixed by Saturday.
