### ISSUE TITLE
Misworded activity instructions?

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1939]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
8.14. Mixed-Up Code Exercises, Parsons (mucp_8_10) (question 15)

**What is your username**
AlexAcosta

**Describe the bug**
The activity instructions states "Let’s write the code for the storeEmployeeData function... regarding their name, id, salary, and address in that order..."
There is no salary or id option in the mix up code blocks and it makes it extremely confusing to figure out what is actually expected to resolve the activity.

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
Thanks for catching it.  I will remove it for now on Saturday.
