### ISSUE TITLE
ActiveCode with missing/invisible code

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1940]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
9.15. Coding Practice, Activity: 9 ActiveCode (cp_9_AC_10q)

**What is your username**
AlexAcosta

**Describe the bug**
After adding the code for the _changeShirts_ and _changePants_ functions, the ActiveCode block returns an error (_ERROR 1_ below) indicating there is not _printOutfit_ function.
After adding the _printOutfit_ function, it returns a different error (_ERROR 2_ below). I guess the _printOutfit_ function exists past the _main_ function that is invisible from my side.
After simply calling _void printOutfit(Outfit o);_ at the top, the activity returned successful results.

**Traceback**

**Javascript Errors**
_>>>ERROR 1:_
test.cpp: In function ‘int main()’:
test.cpp:36:5: error: ‘printOutfit’ was not declared in this scope
   36 |     printOutfit (o);
      |     ^~~~~~~~~~~

_>>>ERROR 2:_
test.cpp:51:6: error: redefinition of ‘void printOutfit(Outfit)’
   51 | void printOutfit (Outfit o) {
      |      ^~~~~~~~~~~
test.cpp:30:6: note: ‘void printOutfit(Outfit)’ previously defined here
   30 | void printOutfit(Outfit o) {
      |      ^~~~~~~~~~~

**Comment by bnmnetp** [comment]
Thanks for reporting this. 

Because the printOutfit function is hidden and included after main, we do need a forward reference declaration of that function.

So, by adding the line you suggest, you are not **calling** it at the top, you are **declaring** that the function exists so that the compiler knows about it.

**Comment by barbarer** [comment]
Thanks for finding this.  It will be fixed on Saturday.
