### ISSUE TITLE
Exercises 9 page of How to think like a computer scientist is not loading

### ISSUE THREAD

**Issue by thijsverwijmeren** [RunestoneInteractive/RunestoneServer#1941]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
ProgrammingSkills21

**What Page were you on**
https://runestone.academy/ns/books/published/ProgrammingSkills21/Strings/Exercises.html

**What is your username**
thijsver

**Describe the bug**
Some exercises are not loading correctly. I (and several of my students) get error messages like these:

System Message: ERROR/3 (/home/bmiller/Runestone/books/thinkcspy/_sources/Strings/Exercises.rst, line 238)

Error in “actex” directive: maximum 1 argument(s) allowed, 6 supplied.

It's the same on Firefox, Chrome, and Microsoft Edge.

**Traceback**

**Javascript Errors**
can't see anything

**Comment by bnmnetp** [comment]
fixed
