### ISSUE TITLE
wrong answer given

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1942]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
Parsons (question14_4_1)

**What is your username**
AlexAcosta

**Describe the bug**
The suggested answer in the mixed-up code is listed as;
void Complex::calculatePolar () {
    mag = sqrt(pow(real, 2) + pow(imag, 2));
    theta = atan(imag / real);
    polar = true;
}
    cartesian = true;
}
It's obvious the issue is the last two lines, but the challenge for the student is that the exercise continues to say the answer is incorrect because it's too short, but then the "correct" answer is wrong.

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by barbarer** [comment]
It was missing a #paired on the distractor.  This has been fixed.
