### ISSUE TITLE
multiple choice question with no possible solution

### ISSUE THREAD

**Issue by gabaleaco** [RunestoneInteractive/RunestoneServer#1943]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How To Think Like a Computer Scientist C++ Edition

**What Page were you on**
Activity: 14.8.4 Multiple Choice (question14_8_4)

**What is your username**
AlexAcosta

**Describe the bug**
See pictures.
![image](https://user-images.githubusercontent.com/77032038/170880723-a3e24a21-75c5-407b-b78e-74321e5879b9.png)
![image](https://user-images.githubusercontent.com/77032038/170880736-416f7a89-37fd-4a79-a42f-fc5f214d340a.png)
![image](https://user-images.githubusercontent.com/77032038/170880752-708ffc5d-9702-4fda-b96f-3aaea4533107.png)
![image](https://user-images.githubusercontent.com/77032038/170880768-2a0f5eaf-31b9-4eca-91d5-a40d3b3c78df.png)

**Traceback**
n/a

**Javascript Errors**
n/a

**Comment by moisedk** [comment]
The issue is in the book source code 
![Screenshot from 2022-07-25 09-45-08](https://user-images.githubusercontent.com/56738242/180793032-a0929eeb-875f-498a-80ff-d83bb5caf4c9.png)

**Comment by barbarer** [comment]
That makes sense!  Thanks for fixing it.
