### ISSUE TITLE
Improvements on docker-build script

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1973]
This is a separate issue to follow up on the [previous discussion](https://github.com/RunestoneInteractive/RunestoneServer/pull/1972#discussion_r914160794).

The problem
============
Even after significant improvements in the docs and the code, the Docker installation process is long and challenging:
- It's the entry point for any developer interested in contributing to the project, so making this work well is important to attracting others to contribute to the project.
- It's 10 steps long, increasing the probability of failure for people trying to follow it.
- It contains OS-specific choices, making the instructions harder to follow.
- It contains instructions for two cases (production vs deployment), making the instructions harder to follow.
- It lacks checks to make sure the previous steps succeeded.
- It fails in a lot of unique ways for each user; there doesn't seems to be an obvious, consistent problem to fix.

Challenges
==============
- The script is currently written in Python, but Python isn't installed by default on OS X or Windows, requiring manual installation steps before any automation can occur.
- There's a lot of OS-dependent code before we get to Docker, which is difficult.
- I don't have a Mac to test on, so there's a fair amount of guessing on anything OS X related.

Successes
============
Working with developers to walk through the install process and looking at and fixing problems they've encountered has improved the situation a lot already. We're in a much better place now.

Goals
==============
Develop a process which:
- Requires the download and execution of only one file (script/binary/whatever).
- Can gather information from the user (Github userid, build a production vs development server, books to install, etc.), then perform the installation process without additional user input.
- Has some diagnostic ability to determine if each step succeeded before proceeding to the next step.
- Retains the existing `docker-tools` script, rather than subsuming it, so that the `docker-tools` functionality remains available for advanced users.
- Is written in a language which runs on Windows/Linux/Mac, instead of requiring a separate script for each platform.
- Provide both a GUI and command-line operation, again to make scripting/advanced use easier.
- Develop a good test suite using a virtual machine, so it's easy to try the process out.

**Comment by bjones1** [comment]
I like the idea of supporting use cases. I think we have good support for authors, with more to come -- support for running books on the Runestone Server env you run will be great! Likewise, providing cloud-based authoring (me + CLI) will also be nice.

For the production use case, I agree that a prebuilt container makes sense. But, there's still a lot that needs to be done to get to this point: install the Docker Desktop, Python 3 (unless we can somehow move `docker-tools` and `rsmanage` into the container), WSL/Ubuntu (Windows), `docker-tools` and `rsmanage`, install books, add users, choose passwords, set the e-mail address for password resets, etc. This IMHO still needs some scripting/intelligence to support well.

- On OS X, I like the idea of creating a Homebrew formula to manage most of the install process. This seems like a very nice way to go. This means OS X users will need to install Homebrew themselves, which is a reasonable expectation for most Mac people. 
- On Ubuntu, a copy-and-paste command would work; it would download a Python script then run that. (I don't like creating a new apt package, since users have to install a key first, which is more hassle).
- On Windows, a copy-and-paste command should work; it would install Python, then download and run a Python script. But, there's still a lot of work needed to take out many of the manual steps in the current process.

If we can accomplish this, then the developer use case becomes even simpler, since getting a useful production system takes care of almost everything needed for developers.

**Comment by bjones1** [comment]
I think we should provide a GUI for some of the currently CLI-based tasks after the server is running -- a nice webpage running on the BookServer that allows an instructor to select and install books, create base courses, add students, etc.

**Comment by bnmnetp** [comment]
We have a web interface for all of that already don't we?  The instructor pages...

**Comment by bjones1** [comment]
Select and install books: I don't know how to do this in the instructor interface.

Create base courses: I don't know how to do this in the instructor interface.

Manage students: the admin / manage students tab in the instructor interface does this already -- you're right. I will update Docker instructions to point them to this page, since I think that's a bit easier than `rsmanage` for our audience (teachers wanting to run their own server, but not necessarily experienced with CLI).

**Comment by bnmnetp** [comment]
I thought you meant creating a course from existing books.

**Comment by bjones1** [comment]
True -- this will definitely take some work. I'll keep this as a lower priority. Having your server-side improvements (clone book, create base course, etc.) would certainly make it easier for a significant group of users.

**Comment by bjones1** [comment]
Some notes on ideas/blockers:

Blocker: how to determine if the Docker Desktop is installed in Windows? The discussion on [Poweruser](https://superuser.com/questions/68611/get-list-of-installed-applications-from-windows-command-line) on WMIC didn't work for me.

TODO: Create a Windows batch file that checks for WSL and Ubuntu and installs them if not, then starts this script in Ubuntu. Perhaps https://github.com/kaisalmen/wsltooling?
