### ISSUE TITLE
20.7.4 exercise gives error

### ISSUE THREAD

**Issue by morey-ow** [RunestoneInteractive/RunestoneServer#1982]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot
ow2521-summer22
**What Page were you on**
https://runestone.academy/ns/books/published/ow2521-summer22/UnitTesting/TestingWithpytest.html

Activity: 20.7.4.1 ActiveCode (ac_grade_pytest)

**What is your username**
morey-ow
**Describe the bug**
"An error occurred in the hidden, included code. Sorry we can't give you a more helpful error message"
<img width="935" alt="Screen Shot 2022-07-16 at 5 02 15 PM" src="https://user-images.githubusercontent.com/96895229/179372343-f2bdcafd-a97b-40ee-a924-ba77c23d4b2b.png">

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> J
<img width="1102" alt="Screen Shot 2022-07-16 at 5 21 08 PM" src="https://user-images.githubusercontent.com/96895229/179372298-e37f10d8-016d-4e22-be2b-71d5c72374d6.png">
avascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Fixed
