### ISSUE TITLE
pronoun usage: think like a cs refers to programmer as he

### ISSUE THREAD

**Issue by morey-ow** [RunestoneInteractive/RunestoneServer#1984]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
thinkcspy
Knowing the course will help us a lot
<img width="1375" alt="Screen Shot 2022-07-16 at 4 32 00 PM" src="https://user-images.githubusercontent.com/96895229/179379445-32d2f397-4846-46cc-83b7-61b1471a6e58.png">

**What Page were you on**

**What is your username**
morey-ow
**Describe the bug**
Not sure if this is appropriate venue to report this as it isn't exactly a bug, but I was disappointed to see that  'programmer' was referred to by the pronoun he in Think Like a Computer Scientist, section 20.6
I've boxed about half of the instances in the included image.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Thanks for pointing this out.   It is something we can certainly do a better job of watching out for both in the original content and in contributions from our instructors. (as is the case with this particular chapter)

Although we should probably develop some style guidelines to give our authors some guidance on pronoun usage.  Feel free to submit a PR with corrections.
