### ISSUE TITLE
Support for LTI 1.3

### ISSUE THREAD

**Issue by douglundin** [RunestoneInteractive/RunestoneServer#1988]
It would be terrific if Runestone would support LTI 1.3. My understanding is you are currently supporting LTI 1.1 for Moodle and one other LMS. Supporting LTI 1.3 would also provide support for our LMS which is D2L.

**Comment by bjones1** [comment]
I would also like to do this, but my bandwidth is pretty limited. Do you have any time/experience implementing LTI in Python? I know a fair amount about the current LTI 1.1 system Runestone uses.

**Comment by douglundin** [comment]
Only because I've researched LTI 1.3 for an integration with IntelliJ but not enough, I'm afraid, to be useful. Perhaps you can point me to the modules that currently implement LTI 1.1?

**Comment by bjones1** [comment]
Sounds good, thanks!
