### ISSUE TITLE
Delete for questions you have authored in instructor page

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#1992]
I think there's no way to delete a question that you have written in the instructor page/Assignments page, other than to flag it. A teacher was asking how to delete the ones they were practicing on.

**Comment by bnmnetp** [comment]
No, there is not.  That was a decision I made long ago.  I didn't want instructors to be randomly deleting questions that may be (or have been) part of an assignment.

I suppose we could relax that and add a delete button to avoid all of the noise from people creating practice questions.  The rule would be you can delete you question UNLESS it is part of a current or past assignment.

**Comment by bhoffman0** [comment]
Sounds like a good rule!
