### ISSUE TITLE
cannot create assignment, no problems in pretext jjj custom course

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneServer#2001]
I created a javajavajava custom course, but in the instructor's page/assignment tab, I do not see the problems in the book and when I click on Add Assignment, there is a popup for a second that disappears without creating a new assignment. The console shows many 404 errors:
![image](https://user-images.githubusercontent.com/4571962/185761296-07f20d0a-01db-4e1c-97fa-6d24c4d2214f.png)

**Comment by bnmnetp** [comment]
Thanks Beryl.

There is a group of files that the book does not need but that the instructor interface has always gotten from the book's _static folder.

I need to update the server to get them from its own static foldler.  But in the meantime I've copied them into the javajavajava book, and I can see questions to make an assignment.

I knew this was a lurking problem but had forgotten about it.  Lets keep this open until I update the server properly.

**Comment by bhoffman0** [comment]
Thanks! I noticed a few things that I could fix.  Looks like headings with pretext c tags in them don't show up in the list on runestone. That second one was Using \<c>Strings\</c>.
![image](https://user-images.githubusercontent.com/4571962/185762254-12c0902f-aac8-4c0c-bd4b-3e1edb556bcc.png)
Tags also seem to cause problems in answers on the assignments page, but it's fine in the e-book page in context:
![image](https://user-images.githubusercontent.com/4571962/185762419-78f30ee6-3079-42df-a483-e640ffd16804.png)

**Comment by bnmnetp** [comment]
OK, I'll have to look into whats going on with the tags on the assignment page.  It looks like the render function used by the admin interface is escaping them somehow.

Lots of things that we assumed to be text only in RST are now html in PreTeXt .  We can make things look a lot better but there are going to be places like this where we have to undo that assumption.
