### ISSUE TITLE
CSPrinciples Problem ch3ex8muc

### ISSUE THREAD

**Issue by meldukes3** [RunestoneInteractive/RunestoneServer#2002]
**What Course are you in**
CSPrinciples (there should probably be a way to choose which course the issue is coming from. Would be easier to sort and search.

**What Page were you on**
ch3ex8muc
**What is your username**
meldukes3
**Describe the bug**
In the problem listed above, the equation to calculate the number of wings is incorrect. The current equation is numWings = cost/money and SHOULD be numWings = money/cost.
![Error ch3ex8muc](https://user-images.githubusercontent.com/111777009/185972676-236c78da-944b-47cf-8a11-6fe37f668177.png)

**Comment by barbarer** [comment]
Good catch.  It will be fixed by Saturday.
