### ISSUE TITLE
Can't access Instructor Page

### ISSUE THREAD

**Issue by lslavice** [RunestoneInteractive/RunestoneServer#2003]
**Please check the current issues** 
I don't see this anywhere

**What Course are you in**
engr101umich-f22

**What Page were you on**
Trying to access instructor page

**What is your username**
lslavice

**Describe the bug**
I can't get to the page. I get this: 

Internal error

Ticket issued: [runestone/68.40.187.201.2022-08-28.14-31-48.5ebfc69e-0c34-457d-b91b-55071dcb3a69](https://runestone.academy/admin/default/ticket/runestone/68.40.187.201.2022-08-28.14-31-48.5ebfc69e-0c34-457d-b91b-55071dcb3a69)

So, yes, I know that a ticket was issued, but I don't know how many of those are autogenerated, and I didn't want this to get lost in the crowd. My class starts tomorrow and I need access to the instructor page. 

**Javascript Errors**
Nothing is displayed in the JavaScript Console

**Comment by pearcej** [comment]
Same here. And from colleague who sent me the following:

Description of issue:
I am using books on Runestone Academy to teach two courses.  Until today, the platform worked perfectly for both classes.  This morning I signed on to create an assignment for tomorrow's class, and was unable to reach my Instructor's Page.  I am able to get to the content of the book itself without issue, but there are four links I cannot access:
- Assignments
- Instructor's Page
- Peer Instruction (Instructor)
- Peer Instruction (Student)
When I click any of those links, I am given the following message:
"Internal Error
Ticket Issued: "
followed by a link to a ticket number.  Clicking on that ticket link takes me to a similar page that says:
"Internal Error
Ticket Issued: unrecoverable"
I only need the Assignments and Instructor's Page links for my course, but the other two display the same behavior.  I have not found any other issues.

**Comment by bnmnetp** [comment]
When I updated the software this morning I forgot that I needed to do a database migration.  This caused an error for almost every page of the instructor interface.

Its back now.

**Comment by bnmnetp** [comment]
PS - this is why I do updates on the weekend -- so we can catch problems like this when traffic is low and before people need it for class on monday morning.

**Comment by pearcej** [comment]
You are the BEST, @bnmnetp!
