### ISSUE TITLE
Add a New Instructor search does not find name

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#2010]
**What Course are you in**
LHSIntroCS_2022

**What Page were you on**
Instructor/Admin/AddTA

**What is your username**
lhsadmin

**Describe the bug**
I tried to Add a New Instructor and started by searching for a name. The searching does not seem to work at all. I tried to look for Sabrina for example and the name is in the list of people in the class, but it did not do anything when I press <return>.

I guess this is a fairly minor issue since I can still add a TA by manually scrolling to the persons name and pressing the + button. So the major feature is OK, but it was just odd for the search to not work.

**Traceback**
N/A

**Javascript Errors**
N/A

**Comment by bnmnetp** [comment]
When I do a search it filters the list just fine even down to a single user, but you still have to click on that user and then press + to add them as a TA.

If it is not filtering the list can you please check the javascript console for any errors that might be related?

**Comment by psmaker** [comment]
It is not filtering the student list at all (I can click on any user and add them just fine though). 

When I press on the Admin tab, I get the following:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/28868409/191098841-5262caa8-ec2f-489a-b07b-5f7be13c11d8.png">

When I try to go to:  https://cdn.jsdelivr.net/npm/handsontable@7.2.2/dist/numbro.min.js.map

I get the following: 

`Couldn't find the requested file /dist/numbro.min.js.map in handsontable.`

**Comment by bnmnetp** [comment]
That is not the problem.  The .map file is just to help the browser if you ever need to debug the numbro.min.js file.  It provides a map from the un-minified version to the minified version.

OK, if nothing else what browser/version/os are you using?

I've been using Chrome and Chromium based browsers lately.  So I haven't tested it in Firefox or Safari for a while.

**Comment by psmaker** [comment]
I"m using Safari version 15.6.1 / Mac OS Monterey

I just tried it on Chrome and the search works exactly like I would expect.
So it seems to be a browser issue.

**Comment by bnmnetp** [comment]
Yes,

I just learned that Safari does not allow you to style form elements like options in a select list.  so changing their `style.display` to none works in every browser except Safari and IE -- not good company.

There are not even very good workarounds other than removing the options from the list but of course then you would have to re-add some or all when the user clears the search or hits the backspace.
