### ISSUE TITLE
 Practice feature can choose undesired questions

### ISSUE THREAD

**Issue by KellyShurtz** [RunestoneInteractive/RunestoneServer#2011]
Issue: **Practice** feature can choose undesired questions

My Runestone username is: **KellyShurtz**    (email: kelly.shurtz@ucas-edu.net)

I'm using **thinkcspy** in my Runestone course which is called: **ThinkCS_2022-23**

I recently turned on the daily _Practice_ feature and then check-marked sections from the first four chapters of the book for my students to review via **Practice**. The _Practice_ feature is working fine, but I was surprised to see strange questions showing up, so I have since turned the _Practice_ feature off.

After investigating I discovered that **Practice** is including more than just the author created questions for the selected chapters, it appears that the Community Contributed questions located within those chapter sections are also being selected by **Practice**. For example, here are just two Community Contributed questions from chapter 1 that my students were seeing:
 
![question1_1_1kc](https://user-images.githubusercontent.com/113934334/191127075-4c1312e6-a71e-42a9-bd29-e7b051121e2f.png)

![keep1_3_3](https://user-images.githubusercontent.com/113934334/191127125-b3e58835-c07a-4566-b0be-d1940046db26.png)

I am aware that I can click **Flag for Review** for questions like these, but most Community Contributed questions are not inappropriate, there are just too many of them, and most are either exact copies or derivations of each other, so that students are seeing basically the same questions too often, thus reducing the efficacy of their _Spaced Repetition Practice_ sessions.

I do like that I can add my own questions and that they can be included in **Practice,** but I don't like that just anyone can create questions that my students will see during their _Practice_ sessions.

I would like to recommend that instructors be given the option to limit the questions that will be presented to their students via **Practice**. This could be accomplished in different ways.

1.	Allow instructors to check specific questions, much like we do when creating assignments (this would be my preference).

2.	Provide multiple switches or check boxes for instructors to select any combination of: author questions, instructor questions, and other Community Contributed questions.
 
3.	Of course the simplest solution would be to not give instructors a choice and have **Practice** only use author created questions.

_Note: I believe the reason that there are so many strange or duplicate Community Contributed questions and exercises is because the **Make Private** checkbox defaults to unchecked; but that is a different issue that I will post separately from this one._ 

Thanks for making these books available to us.
-Kelly Shurtz

**Comment by bnmnetp** [comment]
Thanks for creating the issue and the ideas.

I don't think 3 is a viable solution as some instructors add questions specifically for practice.

Multiple options and switches just makes the code more complicated and difficult to maintain and the interface more difficult to use.

Allowing instructors to choose is a good idea, but would take time to implement.  I did not write the original and have not looked at any of the tree picker code in years!

An easy to implement solution that may be a stop gap is to eliminate any of the questions that are flagged for review from the pool.  

Changing the default to make new questions private by default is also a reasonable idea.

I could also attempt a mass cleansing of questions by finding all of the questions that have not been used in an assignment and either make sure they are flagged or simply remove them.
