### ISSUE TITLE
Non-accessible colours on library page

### ISSUE THREAD

**Issue by lisahines** [RunestoneInteractive/RunestoneServer#2012]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**I checked the current issues first!**

**What Course are you in**
Knowing the course will help us a lot
**I am just browsing but having a really hard time!**

**What Page were you on**
**https://runestone.academy/ns/books/index**

**What is your username**

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Not sure if this is actually a bug, but it is almost impossible to read the book titles on the page: [](https://runestone.academy/ns/books/index).  I think it could be a really easy fix by probably just changing one line in a CSS file, but I am not sure how to do that in the project.  When I hover over them, the colour is better, but there is still not enough contrast. 
 Thanks!**

![Screenshot 2022-10-05 103747](https://user-images.githubusercontent.com/8307461/194088078-c845c6be-c829-4fc9-8d35-d72e6a6dbae3.jpg)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Thanks,  It is not nearly that bad on my screen and browser.  Amazing the difference in color!

That said, changing the color of the title to white would be super easy and I think it would be much more readable.

**Comment by lisahines** [comment]
> Thanks, It is not nearly that bad on my screen and browser. Amazing the difference in color!
> 
> That said, changing the color of the title to white would be super easy and I think it would be much more readable.

It's interesting because the screenshot and my browser actually look very different - it is actually harder to read on my browser than the screenshot.  I think white font would be the way to go here because it would provide the appropriate contrast needed.
