### ISSUE TITLE
PreText version not recording all progress in gradebook and green bar

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/RunestoneServer#2016]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
How to Think Like a Computer Scientist PreText Edition

**What Page were you on**
General issue with all pages

**What is your username**
EricReed

**Describe the bug**
Two possibly related issues:
- Students are not getting credit for the Introduction Page and the glossary page, and receiving less than full completion (e.g. 4/5 activities) on other pages.  Perhaps the basic credit for reading the page is not registering?
- When students navigate away from the page and then return, their answers are still there but the green progress bar shows no progress until they redo the exercises.  Gradebook reporting seems okay other than the issue mentioned above, but students experience anxiety.

**Comment by bnmnetp** [comment]
Thanks for reporting this... It is in fact recording everything, but something is obviously not working when restoring the page.  Its probably tied into some new naming conventions we went to for the move to the books authored with PreTeXt.  I may get it fixed today or it may take another week.

I always started out the semester by reassuring my students that they would not be punished for a bug in my software.  Things go wrong and we'll make them right.  Tell your students I'm sorry to have contributed to their anxiety.

**Comment by bnmnetp** [comment]
I have confirmed my hypothesis on what is causing the problem.  Now I just need to come up with a solution.

**Comment by mrericreed** [comment]
Excellent, thank you!  I do still think a small bit might not be reporting, all of my students are receiving less than full credit in the gradebook for the assignments, which has not happened globally in the past with the non-pretext version.  My current course is FA2022CS49.

Definitely the message I conveyed is "have no fear."

Thank you again!

**Comment by bnmnetp** [comment]
OK, the green bar is now updating.... The counts for each page are actually not correct.  For example https://runestone.academy/ns/books/published/httlacs/general-intro_executing-python-in-this-book.html the green bar says 3 activities when there are clearly 5 on the page.  I'm working with Rob to get this fixed on the PreTeXt side.

The only 2 that really matter for scoring purposes are the last two multiple choice questions so I can see why some of your students might be seeing a full green bar but not getting full credit if they haven't completed the right activities.  They should just do them all anyway right 😄 .

We should be able to get this resolved fairly quickly.

Thanks for your patience and being a trailblazer with this version of the book!

Brad

**Comment by mrericreed** [comment]
Totally makes sense.  Thank you so much for this!

**Comment by bnmnetp** [comment]
I think that as of this morning everything should be sorted.  I'm seeing correct activity counts and the green bar is updating correctly and restoring properly on a page reload.

**Comment by bnmnetp** [comment]
Also -- Search is back!
