### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ackurtzy** [RunestoneInteractive/RunestoneServer#2019]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
AP CSA

**What Page were you on**
1.7.2

**What is your username**
AndrewKurtz

**Describe the bug**
Very simple typo. Under Java Keyword summary, aritmetic should be arithmetic

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bhoffman0** [comment]
fixed
