### ISSUE TITLE
Unable to update auto-grading for code questions

### ISSUE THREAD

**Issue by kursattuncel** [RunestoneInteractive/RunestoneServer#2020]
Hi,

I'm unable to update auto-grade for code questions.

https://youtu.be/NUVt-n6u7Zg

This is the problem screen recording.

This happened after this weekend I think.

**Comment by bnmnetp** [comment]
Those questions do not have unittests and thus cannot be autograded.

**Comment by kursattuncel** [comment]
Thank you. I'm closing the case.
