### ISSUE TITLE
LTI Integration screen mixed up

### ISSUE THREAD

**Issue by kursattuncel** [RunestoneInteractive/RunestoneServer#2021]
Hi,

After trying to login from LTI integration, the welcome screen hides the "Apply Changes" button.

Students can only press enter to apply the changes. This problem started a few days ago.

![Screenshot 2022-10-24 220610](https://user-images.githubusercontent.com/5817179/197615854-8438486d-424a-4c9e-8e55-ac23b6c55ba5.png)

**Comment by bnmnetp** [comment]
I just discovered that myself.  Working on a fix.

**Comment by bnmnetp** [comment]
I just pushed a fix...

Sorry I missed that in my testing.
