### ISSUE TITLE
Grading Summary table overlapping student exercises

### ISSUE THREAD

**Issue by Alex-Jordan** [RunestoneInteractive/RunestoneServer#2024]
In the Instructor Page Grading tab, I select "assignment" then choose an assignment. I select all questions. I choose a student.

Now on the right I see a column with that student's version of all the exercises. Also the Grading Summary table has appeared. (You may need to click the Grading Summary table button first.)

The table and the column of student exercises overlap each other so that neither is clearly readable.

A screenshot:
<img width="1231" alt="Screen Shot 2022-10-25 at 3 48 40 PM" src="https://user-images.githubusercontent.com/4732672/197896520-63e333b2-6f7a-485d-82d9-81131fbae085.png">

**Comment by Solomonwoldetensay** [comment]
How to rest the password for runestone
