### ISSUE TITLE
Student Activity versus Student Progress page

### ISSUE THREAD

**Issue by dostertp** [RunestoneInteractive/RunestoneServer#2033]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Bolles_CSP_22_23

**What Page were you on**
https://runestone.academy/runestone/dashboard/subchapoverview
versus
https://runestone.academy/dashboard/studentreport?id=WAHEEDD23

**What is your username**
dostert

**Describe the bug**
The student report and student progress seem to be showing two different things. My student insisted they completed the sections. I check the student progress CSV and found nothing. Looking at their specific report for their username, sure enough, it has all of the section in question marked. Considering I use the Student Activity csv for grading purposes, this greatly worries me.
[problem](https://bolles-my.sharepoint.com/:i:/g/personal/dostertp_bolles_org/Efw7BSobXr9MsWYdVz8Hg0UBPOLTFo-NKvgUA55HGLoThQ?e=CxLdQx)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Hi,

Unfortunately I can't access the sharepoint link.

The data you can download for the CSV is the "gold standard". all student activities are recorded there and the subchapoverview report uses that data.  If an activity fails to save to that table in the database the student will get a dialog telling them that their latest actions did not save.  We don't delete anything from that table unless a student removes their account or the data becomes more than two years old.

If there are sections in the second report that are checked but there is no corresponding data in the CSV file or the first report that would indicate that the student simply clicked the button at the bottom of the page to mark that page complete without actually doing the work.

**Comment by dostertp** [comment]
Ah, so the expected problem of "the student wasn't telling the truth". Thank you for the prompt reply.
