### ISSUE TITLE
Just a simple typo which made me confused 

### ISSUE THREAD

**Issue by ignas74** [RunestoneInteractive/RunestoneServer#2034]
(https://runestone.academy/ns/books/published//cppds/AlgorithmAnalysis/AnAnagramDetectionExample.html)
Q9

int main(){
    int i = n;
    int count = 0;
    while (i > 0){
        count = count + 1;
        i = i // 2;
        ^^^^^^
    }
    return 0;
}

**Comment by pearcej** [comment]
got it.
