### ISSUE TITLE
Assignment Status Not Updating

### ISSUE THREAD

**Issue by krish1patel** [RunestoneInteractive/RunestoneServer#2036]
The status of any assignment cannot be updated. In the assignments page, the drop down can be clicked and it is possible to click on another progress indicator besides "Track my Progress" yet the system isn't being updated(when the page is reloaded, the status resets to "Track my Progress" ). The status won't update when an assignment is opened either, both blue colored "In Progress" buttons are unresponsive.

**Comment by bnmnetp** [comment]
I can't reproduce this, can you please follow the instructions for writing a  bug report and give me some more information.
