### ISSUE TITLE
CS Awesome not tracking student progress - yes they are logged in

### ISSUE THREAD

**Issue by sellstep** [RunestoneInteractive/RunestoneServer#2038]
Student is in CS Awesome, lesson 6.1 

Trying to complete an assignment that I made. - is getting the following error:

runestone.academy says

Failed to save your code
Status is 401
Detail" null

I would prefer to not post the students username - mine is sellstep

Thanks!
Stephen Sell
Computer Science Teacher
Northwest High School, Germantown, MD

**Comment by bhoffman0** [comment]
This is usually a browser cache problem. Try having them logout, clear the browser cache (ctrl-F5), and then log back in.  Or they could try a different browser, computer, or their phone to see if it's that one machine/browser having problems.

**Comment by bnmnetp** [comment]
The 401 code means that the server has no proof that they are in fact logged in.  This can happen occasionally when the students authentication token expires while they are in the middle of an assignment.  

I increased the timeout to be 15 weeks for the spring semester to try to minimize the number of times this happens.  In that case just copying the work to the clipboard and then clicking the logout menu option and then logging back in should do the trick.
