### ISSUE TITLE
Account Access Issue: RUNESTONE not Sending Reset E-mail 

### ISSUE THREAD

**Issue by Jackthe1st** [RunestoneInteractive/RunestoneServer#2042]
Runestone reported sending a password reset link to my u-mail, but nothing ever came through to my u-mail account. The u-mail account is the e-mail account that I used to create the account, and the username is u6038554. Can you please help me access my account?

**Comment by bnmnetp** [comment]
There is not a username u6038554.  I don't know what u-mail is, but have you checked your spam folder?  We send hundreds and hundreds of password reset emails every day.  If you are enrolled in a course your instructor can also reset your password.

I cannot reset passwords only based on github issues, especially without a valid username.
