### ISSUE TITLE
Incorrectly Written Problem

### ISSUE THREAD

**Issue by crm3218** [RunestoneInteractive/RunestoneServer#2044]
Hello,

This isn't really a programming error but I don't see anywhere else to report this. 

In Section 5.10 of CS Principles: Big Ideas in Programming, the 5th question states that the turtle "Ari" should create a line to the east and "Chris" to the west. However, the accepted correct answer blocks have Ari turn 180º and has Chris only move forward. Since turtles face east by default, shouldn't it be written the other way around? 
Thanks,
Caitlin

**Comment by barbarer** [comment]
Yes, this was wrong.  I have fixed it.
