### ISSUE TITLE
typo in slides for analyzing sorts part 2

### ISSUE THREAD

**Issue by ldelaneyDHS** [RunestoneInteractive/RunestoneServer#2051]
**What Course are you in**
Mobile CSP

**What Page were you on**
5.7 Analyzing Sorts

**Describe the bug**
On the slides for Lesson 5.07 Part 2, slides 69-71 say "binary sort" has a complexity of N^2, but they should match slide 68 and say "bubble sort" has a complexity of N^2

https://docs.google.com/presentation/d/11zhzSU677gmWQdiSYCajgtRUuAUgizcOLTBHbeyvR4E/edit#slide=id.g39015c1fe_11137

**Comment by paulinelake** [comment]
The slides have been updated. Thank you for reporting the error.
