### ISSUE TITLE
Improper Link

### ISSUE THREAD

**Issue by puliyadivinod** [RunestoneInteractive/RunestoneServer#365]
As show in the screenshot, link is placed wrong it takes us to 127.0.0.1:8000

![screenshot from 2014-02-20 14 58 03](https://f.cloud.github.com/assets/703531/2216800/6a558160-9a11-11e3-91c9-2239e6787b58.png)

**Comment by sprenks18** [comment]
Similar issue on this page: 
http://interactivepython.org/runestone/static/overview/instructor.html

Most of the links are using 127.0.0.1 as the host name.
