### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by RipuDamanSingh** [RunestoneInteractive/RunestoneServer#438]
Logging in issue.
The system does not log me back in.
Once I reset the password,  It works for that session only.
When I log out, and try to log in again, it does not let me log back in.  Says password or user name is invalid.
Effectively each time I use it, I have to reset my password.

Regards!

**Comment by 999masks** [comment]
unable to use my login credentials from old web page to https://runestone.academy . it does not recognize my email as well.
