### ISSUE TITLE
Small typo in binary heap implementation example

### ISSUE THREAD

**Issue by jpierce42** [RunestoneInteractive/RunestoneServer#507]
Hi folks,

Suspect I've found a small typo in the section on binary heap implementation in Problem Solving with Algorithms & Data Structures:  http://interactivepython.org/runestone/static/pythonds/Trees/BinaryHeapImplementation.html

In the last example on the page, a diagram shows the sequence of swaps needed to build a heap from a single list [9, 6, 5, 2, 3] using the percDown function defined earlier in the section:

![](http://interactivepython.org/runestone/static/pythonds/_images/buildheap.png)

This is followed by a series of lists showing the state of the heap list at each index.  It seems to me like the 5 and 6 in these lists are out of order (swapped, compared to their positions in the initial list & diagram):

i = 2  [0, 9, 5, 6, 2, 3]
i = 1  [0, 9, 2, 6, 5, 3]
i = 0  [0, 2, 3, 6, 5, 9]

I could be missing something; I'm new to this stuff.  Just wanted to point it out.  Thanks!  :)

**Comment by conzty01** [comment]
@bnmnetp Would you rather fix the graphic and keep the number of exchanges that occur when building the heap or change the text and ActiveCode and keep the graphic the same?

Option 2 would reduce the number of exchanges when building the heap which would shorten the Codelens that is 164 steps long, but doing so would also give fewer examples of the percolation effect.
