### ISSUE TITLE
Typing error - inconsistency between Figure 4 and ActiveCode1 - Chapter:  Trees and Tree Algorithms - Section: Binary Heap Implementation - Heap Operations 

### ISSUE THREAD

**Issue by wernber** [RunestoneInteractive/RunestoneServer#522]
There is an inconsistency between Figure 4 and ActiveCode1.

In Figure 4 and also in the text, the initial list is  [9, 6, 5, 2, 3], but in ActiveCode1 the list is  [9, 5, 6, 2, 3].
This means, numbers "5" and "6" are switched.

---

The same issue also applies to the paperback book, 2n edition:

Chapter 6: Trees - 6.6.3.4: Heap Operations - page 265/266

There is an inconsistency between Figure 6.18 and Figure 6.19.

In Figure  Figure 6.18 and also in the text, the initial list is  [9, 6, 5, 2, 3], but in  Figure 6.18 the list is  [9, 5, 6, 2, 3].
This means, numbers "5" and "6" are switched.

**Comment by conzty01** [comment]
Duplicate Issue: #507
