### ISSUE TITLE
On problem 3 in the Files Exercises, it says that Sue's max is 9 and her min is 11. Even on the answer code.

### ISSUE THREAD

**Issue by sackthings** [RunestoneInteractive/RunestoneServer#538]
On problem 3 in the Files Exercises, it says that Sue's max is 9 and her min is 11. Even on the answer code.

**Comment by AmonRS** [comment]
This is because the scores are stored as strings. Using max() and min() on strings is weird.

**Comment by bnmnetp** [comment]
fixed
