### ISSUE TITLE
remove students

### ISSUE THREAD

**Issue by mhaugrud** [RunestoneInteractive/RunestoneServer#546]
Please remove all students from my course (haugrud). They are from last semester.
Consider making this feature available to instructors.
I also cannot seem to make sections of a course

**Comment by bnmnetp** [comment]
Hi,

I am travelling in Vietnam the month of January, so I will not be able to get to this until after the 23rd.  I would recommend that you change the start date of the course on the instructors page and rebuild.  This *should* accomplish most of what you want.

Brad

**Comment by mhaugrud** [comment]
That is quite a trip. Because of the delay there is no need to remove the students. However I would like to see this as a feature in the system.

**Comment by bnmnetp** [comment]
If you delete the students, then they would not be able to log in after the semester and retrieve any of their past work.  

Did changing the start date give you the desired effect on managing your course, or are there other things I'm not thinking of?
