### ISSUE TITLE
Infix, Prefix and Postfix, Q-14 confusing question/answer

### ISSUE THREAD

**Issue by nfosterky** [RunestoneInteractive/RunestoneServer#551]
Q-14: Modify the infixToPostfix function so that it can convert the following expression: 5 \* 3 ^ (4 - 2):
Correct Answer: 5 3 4 2 - ^ *

I think the question or the answer needs to be changed. Maybe the question should be
Q-14: Change the expression to postfix.

or the answer should be changed.

**Comment by AmonRS** [comment]
question has been changed.
