### ISSUE TITLE
Booted back to home page after short inactivity.

### ISSUE THREAD

**Issue by jmiddel** [RunestoneInteractive/RunestoneServer#555]
I just can't walk away for some time and come back to my work, I'm bcd at the home page and have go back to my spot, and nothing is saved although I clicked Save. I am logged in at the time.

**Comment by jmiddel** [comment]
The issue is not resolved, and is impeding my learning.
Closed #555 <https://github.com/bnmnetp/runestone/issues/555> .

‹
Reply to this email directly or view it on GitHub
<https://github.com/bnmnetp/runestone/issues/555#event-234644010> .

**Comment by bnmnetp** [comment]
I can't reproduce the problem, and you have given me very little information to try to figure out what the problem might be in your particular situation.  I'm sorry you are still having trouble but 99% of these login/registration problems are transient user errors.

What username are you using?  What course are you registered for?  What browser, operating system, etc.  If you know how to get to the Javascript console then any error messages in the console would be helpful.

**Comment by bnmnetp** [comment]
I took a guess based on your github id, and it looks like you are registered for a course called 'Python'  are you a student in this course?  This course has not been updated in about 18 months, so there is a whole development cycle missing.  

If you are the instructor I would ask you to rebuild this course from the instructors dashboard.  

If you are a student, and other students are having similar problems then you should ask the instructor to rebuild the course for you.

If you just randomly registered for this course, I would suggest you edit your profile and use the 'thinkcspy' course.

**Comment by jmiddel** [comment]
Thank you, that helps :) I am not the instructor, but will gladly petition
him to rebuild the course.
I took a guess based on your github id, and it looks like you are registered
for a course called 'Python'  are you a student in this course?  This course
has not been updated in about 18 months, so there is a whole development
cycle missing.  

If you are the instructor I would ask you to rebuild this course from the
instructors dashboard.

If you are a student, and other students are having similar problems then
you should ask the instructor to rebuild the course for you.

If you just randomly registered for this course, I would suggest you edit
your profile and use the 'thinkcspy' course.

‹
Reply to this email directly or view it on GitHub
<https://github.com/bnmnetp/runestone/issues/555#issuecomment-74208061> .
