### ISSUE TITLE
ajax invocations fail on importing coach (gluon custom importer)

### ISSUE THREAD

**Issue by olberger** [RunestoneInteractive/RunestoneServer#561]
I'm running a test installation of RuneStone over version "2.9.12-stable+timestamp.2015.01.17.06.11.03" of web2py, and it seems ajax calls are broken.

I get errors 500. The corresponding web2py tickets tell me about the following traceback:

```
Traceback (most recent call last):
  File "/var/www/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
  File "/var/www/web2py/applications/runestone/controllers/ajax.py", line 10, in <module>
    from coach import get_lint
  File "/var/www/web2py/gluon/custom_import.py", line 92, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
ImportError: No module named runestone.modules.coach
```

I believe there's something weird with this custom importer's fallback.

This should be replicable in the docker container I've setup : https://www-public.tem-tsp.eu/~berger_o/weblog/2015/02/13/testing-the-runestone-interactive-python-courses-server-in-docker/

**Comment by olberger** [comment]
Hmmm ... my bad. It seems I've been connecting to a wrong version of the web2py server somehow.

**Comment by olberger** [comment]
Hmmm... actually, even with proper configuration, this still seems to be happening. Reopening

**Comment by olberger** [comment]
Hmm... it seems this coach stuff isn't really critical, so I ended pu removing it, by applying the following patch:
```diff
diff --git a/controllers/ajax.py b/controllers/ajax.py
index 07e1378..63188a5 100644
--- a/controllers/ajax.py
+++ b/controllers/ajax.py
@@ -6,8 +6,8 @@ from collections import Counter
 from diff_match_patch import *
 import os, sys
 # kind of a hacky approach to import coach functions
-sys.path.insert(0,os.path.dirname(__file__))
-from coach import get_lint
+#sys.path.insert(0,os.path.dirname(__file__))
+#from coach import get_lint
 
 logger = logging.getLogger("web2py.app.eds")
 logger.setLevel(logging.DEBUG)
@@ -74,7 +74,7 @@ def runlog():    # Log errors and runs with code
         event = 'activecode'
     dbid = db.acerror_log.insert(sid=sid,div_id=div_id,timestamp=ts,course_id=course,code=code,emessage=error_info)
     db.useinfo.insert(sid=sid,act=act,div_id=div_id,event=event,timestamp=ts,course_id=course)
-    lintAfterSave(dbid, code, div_id, sid)
+#    lintAfterSave(dbid, code, div_id, sid)
     response.headers['content-type'] = 'application/json'
     res = {'log':True}
     if setCookie:
```

**Comment by bnmnetp** [comment]
Well, thats not a patch I would apply to the master branch, but I can see how it gets you around your current problem.  

I guess I need to update my dev web2py environment!  I just checked an I am running 2.5.1-stable.  I'm guessing the web2py team did something to defeat my cleverness and I shall need to relocate the necessary functions to a genuine module that web2py can deal with properly.

runestone.modules.coach is definitely not a module right now.

**Comment by bnmnetp** [comment]
Very strange indeed.   I just installed the latest stable web2py and built everything from the ground up.  I am not seeing the error.

Brad

**Comment by pathakneeti** [comment]
how did we end up solving this problem? I have the same issue, only difference is that instead of line 224 mine says 227 with respect to "restricted.py".
