### ISSUE TITLE
Statement of accomplishment

### ISSUE THREAD

**Issue by weitzhandler** [RunestoneInteractive/RunestoneServer#566]
Hi,

I wish there would be a statement of accomplishment or certificate issued for those who complete a book.

**Comment by bnmnetp** [comment]
Hi, 

That is a very interesting suggestion.  

What level of activity would qualify for a certificate?  How many chapters?  How many quiz questions?  How many homework exercises etc.  I think we have the data to make such a decision, the question is just deciding on a level of activity and correctness that is worthy of a certificate.  We would probably have to institute some kind of final project for each chapter using the unittest framework or something that could provide some automated grading capability to ensure that someone hadn't just randomly engaged in a bunch of activities.

The second question is would it matter?  Who would recognize such a certificate?   Maybe it would not matter too much if it was motivating and kept learners going in the book.

What do others think?

**Comment by weitzhandler** [comment]
Yeah. Mainly a motivator. And for people like me a statement IS a great motivator. It also makes you think about accomplishing a goal, keeping you busy coming back and make the necessary homework.

In general, I love Khan Academy idea, but I hate videos, and besides, it doesn't issue certificates.
But the idea of progressive learning is great.

I'd say both learning (Mark lesson as learned), quizzes, exams, and final exams should make up the final score.
A separate certificate should be awarded for each book/course.
