### ISSUE TITLE
There are pages in which I can't highlighting text.

### ISSUE THREAD

**Issue by haje01** [RunestoneInteractive/RunestoneServer#567]
There are several pages in which I can't highlight texts. Those pages have following JS errors in common:

[Error] TypeError: undefined is not an object (evaluating 'f.msie')
    (anonymous function) (jquery.ba-bbq.min.js, line 18)
    global code (jquery.ba-bbq.min.js, line 18)

[Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.
    selectNodeContents (rangy-core.js, line 10)
    selectNodeContents (rangy-core.js, line 10)
    selectCharacters (rangy-textrange.js, line 33)
    restoreCharacterRanges (rangy-textrange.js, line 33)
    (anonymous function) (user-highlights.js, line 402)
    each (jquery.js, line 3)
    (anonymous function) (user-highlights.js, line 399)
    c (jquery.js, line 3)
    add (jquery.js, line 3)
    restoreSelection (user-highlights.js, line 396)
    enableUserHighlights (user-highlights.js, line 53)
    gotUser (bookfuncs.js, line 559)
    c (jquery.js, line 3)
    fireWith (jquery.js, line 3)
    k (jquery.js, line 5)
    r (jquery.js, line 5)

I'm using Safari 8.0.3 & Firefox 35.0.1 (My OS is Mac OSX Yosemite)
Here is an example:
    http://interactivepython.org/runestone/static/pythonds/SortSearch/Hashing.html

**Comment by bnmnetp** [comment]
Hi,

I just tried the page, and I'm not having any problems making and restoring
You can highlight on other pages?  
You are sure that you are logged in?
This error message looks like it is trying to restore some previous highlights and you are now reloading the page?  How long ago did you make the highlights?

**Comment by haje01** [comment]
Yes, I was logged in.

I tried Chrome and IE browser on my Windows machine, still happened there.
I've found that 'Mark as completed' button also not work.

In my opinion, there might be something in **rangy-core.js** which causes this problem. Different browsers show different error messages on the module:

Safari:

    [Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.

Firefox:

    TypeError: Argument 1 of Range.selectNodeContents is not an object.

Chrome (Windows)

    Uncaught NotFoundError: Filed to execute 'selectNodeContents' on 'Range': The node provided is null.

There are no such error in pages on which I can highlight.

Hmm... It's strange that it happens especially in Hash Section and you could not reproduce the error.

**Comment by bnmnetp** [comment]
Interesting. Could you send me your username. I would like to investigate in the database and see if I can figure out what may be wrong in the highlights table. 

Brad
