### ISSUE TITLE
Turtles not displaying

### ISSUE THREAD

**Issue by humensky** [RunestoneInteractive/RunestoneServer#569]
I have recently been working on some of the exercises involving turtles.  Starting today, when I hit run, nothing happens.  The screen is blank and no turtle drawing displays.  I tried setworldcoordinates to a bigger range because I thought maybe I had zoomed in too far, but I still get nothing.

**Comment by bnmnetp** [comment]
Which book/course are you using?  Can you paste in an example of something that does not work?  As far as I can tell everything should be fine.

Brad
