### ISSUE TITLE
Where I can find my highlights

### ISSUE THREAD

**Issue by fertingoff** [RunestoneInteractive/RunestoneServer#573]
Hi folks! Your format is really awesome! Thank you for that.
The only question I have so far is where I can find my highlights?
Thank you.

**Comment by bnmnetp** [comment]
That is a great idea that we have not implemented yet.  Today your highlights are just there when you go back to the page.  I'll add this to the features list.

**Comment by fertingoff** [comment]
Great! Txh. Keep it up!

--  
BR, Art
