### ISSUE TITLE
saved activecode not visible

### ISSUE THREAD

**Issue by mhaugrud** [RunestoneInteractive/RunestoneServer#577]
I have students edit and save certain activecode exercises as assignments. Occasionally I am unable to see what they have save although I can see that the exercise was saved. I have attached pictures of the course log showing the exercise being saved and what I see when I attempt to view the assignment. I can see what other students saved for this exercise.
![c3](https://cloud.githubusercontent.com/assets/7073974/6849225/e0b2c728-d39f-11e4-8425-ee4a7204254e.PNG)
![c1](https://cloud.githubusercontent.com/assets/7073974/6849275/52d62516-d3a0-11e4-9021-3049b234f5bd.PNG)
![c2](https://cloud.githubusercontent.com/assets/7073974/6849277/56683ce6-d3a0-11e4-9e6c-b3b1b6639e8a.PNG)

**Comment by bnmnetp** [comment]
Have you tried clicking in the editor widget on the modal popup?   I don't know what causes it, but I have seen that sometimes myself.

Also, if a student has a ``.`` in their username that causes trouble -- its a jquery selector thing...

I changed the registration validation a week ago to catch that, but that could be a problem too.

**Comment by mhaugrud** [comment]
When I go to the popup for his code, I just see 6 blank lines. I cannot run it.
I just viewed the html source for the assignment grading web page. The data for this student is very different than the other students: See the picture

**Comment by bnmnetp** [comment]
Strange, I see a row in the database for this guy with no timestamp and a grade of 0 entered.  But I can also see he has made two saves of a program.

I have deleted the rows without timestamps from the database.  Check and see if you are still getting the same error.

BTW, There was no picture attached to your last message.  

![screenshot 2015-03-26 16 21 58](https://cloud.githubusercontent.com/assets/51115/6849871/e47f949a-d3d5-11e4-89bf-4daa56f62891.png)

**Comment by mhaugrud** [comment]
That solved the problem!
Could you do the same for this same student for ch05_1, ch05_2, chp05_3, scratch_06_01, ch05_4, ch05_unaryselection, sel2, sel4, ch06_boolfun1, ch06_boolfun2, scratch_06_03 (these were all done in the previous assignment)

Here is the picture again

**Comment by bnmnetp** [comment]
done.  Let me know if that fixed it for others.

The rows with no timestamps have no code in them for the student but they do have a grade of 0.  I'm wondering if this was a problem when you entered the grade for the student??

Anyway let me know if some of these are still not showing up.

Brad

**Comment by mhaugrud** [comment]
Brad,
Thanks so much. The problem could not be from entering the grade because I was unable to see the saved code before I did enter a grade.

**Comment by bnmnetp** [comment]
OK, at least that gives me something to go on to try and track this down.  -- How could a row get created for this student for this assignment with a grade of 0 but no code or timestamp or other information in the row...  I can see there are other instances of this for other people as well....

I'm not going to get this fixed for a couple of weeks as our Easter break here in Malta starts tomorrow and I'm headed out to Morocco with our students early tomorrow morning.
