### ISSUE TITLE
Active code uses Python 3 while Codelens uses Python 2

### ISSUE THREAD

**Issue by yoder531** [RunestoneInteractive/RunestoneServer#579]
I'm running into issues with the interactive python book as the Active Code window uses Python 3, whereas the Codelens uses Python 2. Hence, a statement such as a = input("Enter a value:") will run in the active code window but will not execute in Codelens. It seems like a simple fix would be to have Codelens open with version 3.3 instead of 2.7 as the Python tutor supports Python 3.

**Comment by bnmnetp** [comment]
Thanks,

Sorry for the trouble this is causing you.   I know that we need to get more strict about the semantics of a few things related to Python 2/3

* The python3 flag in Skulpt now really only impacts division.  -- default is to python2
* I have hacked The print statement to act like a function but there is a much better solution in progress.
* The python3 flag should change how ``input`` behaves  -- default for input behavior is python3
* The run this in Python Tutor should also respect the setting of the python3 flag.

Hopefully we can address many of these in our summer hacking window.

Parts of this can be addressed here, but other parts need to be addressed in the Skulpt repo.

Brad

**Comment by csev** [comment]
Brad - could you add an example somewhere as to how to trigger the Python 3 flag - I grepped the entire source and could not find out how to make it work.  Thanks in advance.

**Comment by presnick** [comment]
@bnmnetp It looks like all the hardcoded `.. codelens` examples are still generating py2, while clicking on codelens in the book yields py3 execution. I tried adding `:python: py3` in the .rst file, but that doesn't seem to control creation of the trace. Is there some parameter that can be passed to pg_logger.exec_script_str_local in order to get a python3 execution?

**Comment by bnmnetp** [comment]
Barb had a pair of students working on updating the codelens directive to use the latest version.  This will allow us to choose python version as well as a variety of languages.  Not sure the timeline for getting a PR from them.

**Comment by presnick** [comment]
Thanks. We'll just wait, then.
