### ISSUE TITLE
AVL Tree Performance: parentheses are not shown in log(N_h +1)

### ISSUE THREAD

**Issue by olvas** [RunestoneInteractive/RunestoneServer#587]
At the end of the section:

> If we rearrange the terms, and take the base 2 log of both sides and then solve for h we get
> the following derivation:
> ![screenshot1](https://cloud.githubusercontent.com/assets/8470906/7446408/19d58ea6-f1e0-11e4-80ce-a8b79c99950d.png)

Probably, it should be like this:
![codecogseqn](https://cloud.githubusercontent.com/assets/8470906/7446477/79312aca-f1e2-11e4-8746-775cc085dcaa.png)

**Comment by bnmnetp** [comment]
Fixed -- Finally!!!
