### ISSUE TITLE
Big-O Notation section won't mark Complete

### ISSUE THREAD

**Issue by jasonganub** [RunestoneInteractive/RunestoneServer#589]
I've tried numerous times but the section's mark complete button is malfunctioning.

**Comment by bnmnetp** [comment]
Can you provide a link to the page that is causing you the trouble?  Also if you could send me or provide for me your username that would enable me to do some debugging as to why it is failing for you on this one page, but is not failing for me.

Brad

**Comment by jasonganub** [comment]
Hi Brad,

Username: jasonganub
URL:
http://interactivepython.org/runestone/static/pythonds/AlgorithmAnalysis/BigONotation.html

The button works on every other page but this one, thanks!
Jason
