### ISSUE TITLE
Office 365 ID

### ISSUE THREAD

**Issue by MrBarnes** [RunestoneInteractive/RunestoneServer#590]
I'd like to try using the turtle courses woth our students. All students and teachers have office365 ID's however the sign on with microsoft does not seem to recognise them. On some sites it seems to work fine but on others they are not recognised as microsoft accounts.
Is there a way to solve this? I don't really want students to set up another set of usernames and passwords.

**Comment by bnmnetp** [comment]
Hi,

Sorry you are having trouble with your Microsoft logins.  I use a third party provider called Janrain to provide this service.  I check a few boxes on a form to enable logins from facebook, microsoft, et. al.  and it works.  Every few weeks I look at a graph to see which services people use to login. Microsoft gets a few, Google the most.

I have no idea why it may not be working for your students.  It could be that your school's firewall is blocking some aspect of Janrain's processing, or something else entirely.  I'm curious if you have tried any of the other social login options from your site.

Sorry I'm not more help about this.

Brad

**Comment by MrBarnes** [comment]
I'll have a play with several different options later and let you know what I discover.


Rick


Rick Barnes
Head of Computer Science and Information Technology
barnesr@bedalehigh.n-yorks.sch.uk
www.bedalehigh.n-yorks.sch.uk <http://www.bedalehigh.n-yorks.sch.uk/>   <http://www.bedalehigh.n-yorks.sch.uk/> Bedale High School
Fitzalan Rd
Bedale
North Yorkshire
DL8 2EQ
pls. visit www.bhs-vle.net<http://www.bhs-vle.net/>
for the ICT Departments
Virtual Learning Environment    tel:01677 422419
Fax:01677 425488
________________________________
