### ISSUE TITLE
General Introduction / Syntax errors typo

### ISSUE THREAD

**Issue by nhquiroz** [RunestoneInteractive/RunestoneServer#608]
On the [Syntax errors chapter](http://interactivepython.org/runestone/static/thinkcspy/GeneralIntro/Syntaxerrors.html), there is a typo on the second paragraph, fourth sentence: "You will not be able to complete the execution your program."

It should says: "You will not be able to complete the execution **of** your program."

**Comment by bnmnetp** [comment]
fixed
