### ISSUE TITLE
Update navigation help page to reflect the new layout

### ISSUE THREAD

**Issue by rosewcs345** [RunestoneInteractive/RunestoneServer#626]
Just seeing link to Table of Contents on the left and menu icons to the right.
![pagenavigation](https://cloud.githubusercontent.com/assets/715952/9313120/1f68e6e4-44ef-11e5-8c5c-2f509fe8d1e6.PNG)
Not seeing above menu or widgets.

Here's a sample of what I'm seeing in Chrome, Firefox: and IE:
![sample](https://cloud.githubusercontent.com/assets/715952/9313331/6310c622-44f0-11e5-8ca8-826090485f6f.PNG)

**Comment by bnmnetp** [comment]
Sorry, false advertising.  We removed that dropdown a year ago, and I just have not gotten around to updating the help page.

**Comment by rosewcs345** [comment]
So there is no easy way to navigate to the next section without going back
to the Table of Contents??

On Mon, Aug 17, 2015 at 4:59 PM, Brad Miller <notifications@github.com>
wrote:

> Sorry, false advertising. We removed that dropdown a year ago, and I just
> have not gotten around to updating the help page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/626#issuecomment-131959755>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*

**Comment by bnmnetp** [comment]
Yes,
At the bottom of every page there are links to go to the next or previous section.

![screenshot 2015-08-17 16 03 40](https://cloud.githubusercontent.com/assets/51115/9316265/a270cb4c-44f9-11e5-9e69-4e833e1aefc2.png)

**Comment by rosewcs345** [comment]
Oh, I see it now -- Fantastic!!
Will you be updating the "Getting Around the Book" section?

On Mon, Aug 17, 2015 at 5:04 PM, Brad Miller <notifications@github.com>
wrote:

> Yes,
> At the bottom of every page there are links to go to the next or previous
> section.
>
> [image: screenshot 2015-08-17 16 03 40]
> <https://cloud.githubusercontent.com/assets/51115/9316265/a270cb4c-44f9-11e5-9e69-4e833e1aefc2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/626#issuecomment-131960810>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*

**Comment by bnmnetp** [comment]
To be honest its pretty far down my priority list, and I'm currently waist deep in prepping two new classes for the upcoming semester.  So I would not look for it from me before the start of classes.

Most people seem to discover the forward and back buttons with no problem, so hopefully it will not be a problem for your students either.

**Comment by rosewcs345** [comment]
No problem, I will make a note of it and pass it on.
I can certainly understand how buried you are (as I am . . . ), and I
appreciate all your fine work!!

On Mon, Aug 17, 2015 at 5:15 PM, Brad Miller <notifications@github.com>
wrote:

> To be honest its pretty far down my priority list, and I'm currently waist
> deep in prepping two new classes for the upcoming semester. So I would not
> look for it from me before the start of classes.
>
> Most people seem to discover the forward and back buttons with no problem,
> so hopefully it will not be a problem for your students either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnmnetp/runestone/issues/626#issuecomment-131962797>.
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*
