### ISSUE TITLE
Quicksort code mangled

### ISSUE THREAD

**Issue by daemianmack** [RunestoneInteractive/RunestoneServer#635]
The code that loads with the default view of http://interactivepython.org/runestone/static/pythonds/SortSearch/TheQuickSort.html#lst-quick is somewhat mangled.

**Comment by textbook** [comment]
http://stackoverflow.com/questions/33020945/python-quicksort-code-error

**Comment by bnmnetp** [comment]
fixed.  there was a bug that was causing the editor to eat the < and continue to eat characters until it thought it was done with an html tag.  That is fixed.
