### ISSUE TITLE
The highlight option is not working

### ISSUE THREAD

**Issue by deepak1197** [RunestoneInteractive/RunestoneServer#646]
When i make a selection , i get a highlight option but when i click on it. It does nothing.

**Comment by bnmnetp** [comment]
Hi,

Please see this link for information on more helpful bug reports:  http://interactivepython.org/runestone/static/help/bugreports.html

Question:  When you refresh the page do you see your highlights?

**Comment by bnmnetp** [comment]
This should be fixed if the book you are using has been rebuilt recently.
