### ISSUE TITLE
bug in indentation

### ISSUE THREAD

**Issue by alfredli** [RunestoneInteractive/RunestoneServer#651]
I have found out in my mac, the indentation is always wrong. I move and copy the code to show the double indent, but in your page,it is single indent. how to solve this problem??? Loss a lot of time

**Comment by bnmnetp** [comment]
Sorry, I don't understand.   Are you trying to copy and paste code out of the activecode editor?  What are you pasting it into?

I do not understand what you mean by single indent versus double indent.

Brad
