### ISSUE TITLE
Does not render properly(which prevent signing in) in firefox 40.0.3 

### ISSUE THREAD

**Issue by eswarm** [RunestoneInteractive/RunestoneServer#652]
Hello,

I am not able to login through social sites, because it does not allow me to click on the buttons. 

Version Firefox : 40.0.3 

Please refer to the screenshot for the exact problem. 

![screen](https://cloud.githubusercontent.com/assets/381511/10335008/e2ff3e66-6d0b-11e5-829d-ccd9ed944ff6.png)

Thanks.

**Comment by eswarm** [comment]
Just to add, the same page works fine in chrome.

**Comment by bnmnetp** [comment]
Yes, this is a known problem, that I cannot fix.  I need Janrain to change their implementation to work with Firefox.
