### ISSUE TITLE
Syntax error in List of Lists Tree example first code snippet

### ISSUE THREAD

**Issue by freakanth** [RunestoneInteractive/RunestoneServer#659]
I wanted to bring a small error to your notice from the above Section. The first code snippet from this section:

myTree = ['a',   #root
      ['b',  #left subtree
       ['d' [], []],
       ['e' [], []] ],
      ['c',  #right subtree
       ['f' [], []],
       [] ]
     ]

produces an error when copy-pasted in the interpreter due to the absence of commas after 'd', 'e' and 'f'.

Thanks for the great tutorials!

**Comment by bnmnetp** [comment]
You are correct.  I have fixed that in the source.
