### ISSUE TITLE
An Anagram Detection Example

### ISSUE THREAD

**Issue by yanyuzhe** [RunestoneInteractive/RunestoneServer#660]
def compare(str1, str2):
    time1= time.time()
    dict1 = {}
    dict2 = {}

    list1 = list(str1)
    list2 = list(str2)

    for i, j in zip(list1, list2):
        if i in dict1:
            dict1[i] += 1
        else:
            dict1[i] = 1

        if j in dict2:
            dict2[j] += 1
        else:
            dict2[j] = 1

    if dict1 == dict2:
        return True
    else:
        return False

This is fastest way. compares to the examples that you listed

**Comment by bnmnetp** [comment]
Hi, 

Thanks for the solution.  

Although I think your solution is more "pythonic" in its use of dictionaries, and using zip to iterate in parallel I'm not sure that it is **fundamentally** different than the fourth solution provided in the book.  In order for python to determine whether ``dict1 == dict2`` it must iterate over the items in each dictionary.

Unfortunately, your use of zip is problematic when the two strings are of different lengths.

```
>>> zip(list("apple"),list("people"))
[('a', 'p'), ('p', 'e'), ('p', 'o'), ('l', 'p'), ('e', 'l')]
```

Note that zip discards the extra letter in the list made from the string people

**Comment by bnmnetp** [comment]
Thanks for the inspiration.  http://reputablejournal.com/anagramsrevisited.html
