### ISSUE TITLE
Not able to login and mark the lines. No readers are being shown online. 

### ISSUE THREAD

**Issue by garg10may** [RunestoneInteractive/RunestoneServer#661]
I am trying to access http://interactivepython.org/runestone/static/java4python/Java4Python.html#

While the home page of interactive python shows me logined and I think other books are working fine, though not tried all. I am able to mark http://interactivepython.org/runestone/static/pythonds/BasicDS/InfixPrefixandPostfixExpressions.html#general-infix-to-postfix-conversion on this page.

**Comment by bnmnetp** [comment]
Hi,

You should use this version:  http://interactivepython.org/runestone/static/java4pythoni/Java4Python.html#introduction,

and I should have the old version redirect to this one.
