### ISSUE TITLE
Start Maze Project

### ISSUE THREAD

**Issue by mstoth** [RunestoneInteractive/RunestoneServer#671]
Starting the TDD Maze Project

**Comment by bnmnetp** [comment]
What does "Starting the TDD Maze Project" mean?

**Comment by mstoth** [comment]
Sorry, I'm learning how to use the interactive python site. I am trying to create a section for a course I will be teaching but probably don't have a clue about how to do it yet. I don't mean for this to be public.


-------- Original Message --------
Subject: Re: [RunestoneServer] Start Maze Project (#671)

**Comment by bnmnetp** [comment]
OK, I'll close this.

There are some videos that may be helpful on the instructors page, and there is also a google group ( https://groups.google.com/forum/#!forum/runestone_instructors )  for instructors.  You may answers to a lot of your questions in one of those places.

Brad

**Comment by mstoth** [comment]
ok, sorry for the trouble.


-------- Original Message --------
Subject: Re: [RunestoneServer] Start Maze Project (#671)
