### ISSUE TITLE
Google Social ID registration username with invalid characters

### ISSUE THREAD

**Issue by abkfenris** [RunestoneInteractive/RunestoneServer#672]
My students email addresses are in the form of first initial last name .16@

So I would be akerney.16@. They are getting errors that a period is not an allowed username character as the social auth populates the username from the beginning of their email address. 

They are able to register successfully without using social auth.

**Comment by bnmnetp** [comment]
Yes, the . in the username was causing problems with the CSS in the grading interface.  The easiest solution was to disallow the dots in the usernames.  I will check, but I think the underlying problem may be fixed and we might be able to allow the dots again.
