### ISSUE TITLE
Hi, I can't register at all. I've made a dozen tries. Can you help me to fix it ?

### ISSUE THREAD

**Issue by zakbin01** [RunestoneInteractive/RunestoneServer#673]

**Comment by bnmnetp** [comment]
Probably not, unless you can tell me a bit more about what is going on, including the error messages you are seeing and how you are trying to register.

**Comment by zakbin01** [comment]
Hi Brad
I've fixed the point...Thanks for your feed back


2016-01-21 17:54 GMT+01:00 Brad Miller <notifications@github.com>:
