### ISSUE TITLE
Errors around ActiveCode: 2 (pixelex1)

### ISSUE THREAD

**Issue by DuncanBetts** [RunestoneInteractive/RunestoneServer#675]
I noticed an error on the page regarding 2-Dimensional Iteration: Image Processing

http://interactivepython.org/runestone/static/thinkcspy/MoreAboutIteration/2DimensionalIterationImageProcessing.html

The page reads:

When you run the program you can see that the image has a width of 400 pixels and a height of 244 pixels.

However the output of ActiveCode: 2 (pixelex1) indicates the file has a width of 702 and a height of 428.

I right-clicked on the image in question and selected View Image Info and was given the following tidbit that I'm sure explains this discrepancy:

400px × 244px (scaled to 702px × 428px)

I also noticed when adjusting

p = img.getPixel()

within that active code box, if I request values for a pixel outside the range 1, 1 through 400, 244 I get 0, 0, 0.

**Comment by bnmnetp** [comment]
Thanks for the report.  This seems to be related to our CSS and Bootstrap formatting is automatically scaling the window for me.  This did not happen before, so something has definitely changed in the browsers that is causing this new behavior.

I don't like the fact that the underlying image API reports the scaled size, but does not provide valid pixel values!
