### ISSUE TITLE
newimg should be win in text (2-Dimensional Iteration: Image Processing)

### ISSUE THREAD

**Issue by DuncanBetts** [RunestoneInteractive/RunestoneServer#676]
The first paragraph after ActiveCode: 4: (acimg_1), second sentence, talks about an image object called newimg.

This image object isn't present in the example.

There is an object called win, I think that's the one the text intends to refer to.

Also the line numbers are off by 1 line.

**Comment by bnmnetp** [comment]
Ah no, I just forgot to update the text after I change the example to be more 'animated'

The old code simply ran until it had converted the entire image, and then displayed it.  In this version the students can see the image as it is being converted pixel by pixel.
