### ISSUE TITLE
Profile Update Error

### ISSUE THREAD

**Issue by usalam** [RunestoneInteractive/RunestoneServer#677]
My username was generated on my email address which contains a "."

I cannot change my username and cannot update my profile because I get the following error:
"Your username may not contain a . or ' or space or any other special characters just letters and numbers"

Pleas see screenshot and link.

![image](https://cloud.githubusercontent.com/assets/7535134/12538775/71a0f49e-c2b0-11e5-96ca-eb8280441027.png)

http://interactivepython.org/runestone/default/user/profile?_next=/runestone/default/index#

Thanks,

Utshob

**Comment by tobydragon** [comment]
I had the same problem with my (older) username tdragon@ithaca.edu
