### ISSUE TITLE
Problem with the exercises in how to think like a computer scientist

### ISSUE THREAD

**Issue by Laserlion** [RunestoneInteractive/RunestoneServer#682]
The exercises in this section do not have a place for me to run my own program

**Comment by bnmnetp** [comment]
Sorry, I don't know what you mean by 'this section',  which section are you referring to?   Can you provide a link?

Every exercise should have a Show/Hide code button that will make a space for you to work on the exercise.

**Comment by Laserlion** [comment]
I apologize. I found it now.
