### ISSUE TITLE
Unsorted lists versus unordered lists

### ISSUE THREAD

**Issue by GloriaAnholt** [RunestoneInteractive/RunestoneServer#686]
In the Algorithms and Data Structures textbook, the description of lists found here:

http://interactivepython.org/runestone/static/pythonds/BasicDS/Lists.html#lists

states:

"A list is a collection of items where each item holds a relative position with respect to the others. More specifically, we will refer to this type of list as an **unordered list**. We can consider the list as having a first item, a second item, a third item, and so on. We can also refer to the beginning of the list (the first item) or the end of the list (the last item). For simplicity we will assume that lists cannot contain duplicate items.

For example, the collection of integers 54, 26, 93, 17, 77, and 31 might represent a simple unordered list of exam scores."

But if you check Wikipedia's definition of a list, it states that lists are ordered:

" In computer science, a list or sequence is an abstract data type that represents an **ordered** sequence of values, where the same value may occur more than once."

(https://en.wikipedia.org/wiki/List_%28abstract_data_type%29)

Which is to say, because lists are singly or doubly linked, the must necessarily be _ordered_, but not _sorted_. I believe you mean your example to state that it is an **unsorted** list, not an **unordered** list.

Best,
Gloria

**Comment by bnmnetp** [comment]
Thanks, I like the distinction, but I think you would not find the wikipedia definition to be consistently used throughout the literature.  I'll keep it in mind for a future revision though.

**Comment by kevin868** [comment]
somewhat related to this - I was thrown by the Set demonstration in Control Structures? (in the last demo video for that page).. your output set contains everything in ORDER while Sets are typically unordered. 
So your set( list comprehension of ['cat, 'dog', rabbit'] ... ) retains its order.
Then is ordered Set the default for Skulpt? I was unable to find it in their documentation / Git.

**Comment by bnmnetp** [comment]
No sets are not ordered in skulpt.  You just happened to get an example where they were ordered by accident.
