### ISSUE TITLE
Wrong Questions

### ISSUE THREAD

**Issue by 203336** [RunestoneInteractive/RunestoneServer#694]
![screen shot 2016-03-24 at 12 22 42 pm](https://cloud.githubusercontent.com/assets/18055050/14023941/4831c912-f1bd-11e5-9787-1a7142dbe9d6.png)
![screen shot 2016-03-24 at 12 30 21 pm](https://cloud.githubusercontent.com/assets/18055050/14023942/48398904-f1bd-11e5-9f80-dd970ef185d1.png)
Thank you for making Runestone such a great source for learning and practicing Java before the APCS exam.  However, as I was taking the Java Review APCS Practice Test #3, I noticed that when the question was inside the white text box, there would also be a question for another problem above in the yellow text box.  I did not have confusion about which question to answer because the question in the yellow text box did not relate to the presented code at all.  However, I just wanted to let you know about the issue.  Thank you!

**Comment by bnmnetp** [comment]
I don't think I see the problem in your screenshot.  @ericsonga do you understand the problem being described here?

**Comment by 203336** [comment]
The question at the top of the yellow box is unrelated to the actual question that is inside the white box.  It says, "Assume that list... call of mystery(4)?" above when that has nothing to do with the questions involving inheritance and Strings, which are in the white box.  The question pertaining to the Animal and Bear classes is lower in the white box than in the screenshot, but the mystery(4) question is still written above it.
