### ISSUE TITLE
Video doesn't play.

### ISSUE THREAD

**Issue by DarinM1967** [RunestoneInteractive/RunestoneServer#695]
http://interactivepython.org/runestone/static/thinkcspy/SimplePythonData/Variables.html

HW: Google Pixel C
OS: Marshmallow
Browser: Chrome

Clicking on the "Play" button on either the video window or in the bar below it, causes the "Pause" button to appear on either, but the video doesn't play. Reloading page doesn't fix issue.

**Comment by bnmnetp** [comment]
The videos use standard html5 video tags.  Have you tried this on any other hardware?  I am not able to reproduce the problem on any of my devices.

**Comment by DarinM1967** [comment]
Perhaps the issue is because the videos that seem to have this problem are
.mov files and not the standard .mp3, .mp4, .ogg files.  I was able to play
one of them after I downloaded it and installed VLC app.

The videos use standard html5 video tags. Have you tried this on any other
hardware? I am not able to reproduce the problem on any of my devices.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/RunestoneInteractive/RunestoneServer/issues/695#issuecomment-202359632>

**Comment by bnmnetp** [comment]
I'll look into this a bit more.  The videos were all encoded in 2013 and have been working fine in Safari, Chrome, and Firefox.  I'm quite surprised that they are not working for you as there is both a .mov and a .webm  source video.  I thought that Chrome fully supported .webm

Brad

**Comment by DarinM1967** [comment]
I understand and there's no rush. The reason maybe because I'm using Chrome
on my android tablet which might not have built in codes for .move files.
