### ISSUE TITLE
Doesn't save my recent work.

### ISSUE THREAD

**Issue by DarinM1967** [RunestoneInteractive/RunestoneServer#697]
HW: Google Pixel C
OS: Marshmallow
Browser: Google Chrome
Link: http://interactivepython.org/runestone/static/thinkcspy/SimplePythonData/Exercises.html

Problem: Maded sure I was logged in, after finishing each problem, running and saving them. I closed my browser, reopened it, went back to exercise page, clicked "Show/Hide Code", but none off my work was saved. Repeated above steps, and confirmed the only first save was saved.

**Comment by bnmnetp** [comment]
Again, I cannot recreate the problem you describe.  Is this problem still occurring?
