### ISSUE TITLE
Everyday Python Codelens problem

### ISSUE THREAD

**Issue by cornof** [RunestoneInteractive/RunestoneServer#701]
Hi,

Thanks for building this tutorial!

I am using a MacBook Air OSX 10.9.5
I see the bug in the Firefox  45.0.2 and Safari 9.0.3

In the "Etch Solution" Codelens, I get this error when I step through the code.

On line 1 -  import turtle

Program terminated
ImportError: turtle not supported

Thanks for taking a look at this.
I don't check this account, but you can reach me at dawn@coderdojosv.org

Dawn Murakami

**Comment by bnmnetp** [comment]
Ah, I see.  Codlens does not support turtle graphics, I should disable the button for that.

**Comment by bnmnetp** [comment]
fixed
