### ISSUE TITLE
Question references wrong exercise

### ISSUE THREAD

**Issue by DuncanBetts** [RunestoneInteractive/RunestoneServer#702]
On page: [http://interactivepython.org/runestone/static/thinkcspy/Lists/Exercises.html](http://interactivepython.org/runestone/static/thinkcspy/Lists/Exercises.html)

Question 3 / ActiveCode: 2 (ex_9_3)

Questions reads:

"Starting with the list in Exercise 1, write Python statements to do the following:"

This should refer you to the list in Exercise 2, not 1.

I say this because

The list in Exercise 1 is:
a = [1, 2, 3]

Part D of Q3 requests that you Find the index of "hello".

The list in Exercise 2 is:
myList = '76, 92.3, "hello", True, 4, 76'

Hope this helps :)

**Comment by bnmnetp** [comment]
fixed by https://github.com/RunestoneInteractive/thinkcspy/commit/50d95c69da6c5340be4c45e6d664b5c9c4822a61
