### ISSUE TITLE
Java code issue

### ISSUE THREAD

**Issue by phantamanta44** [RunestoneInteractive/RunestoneServer#704]
On the [polymorphism Java page](http://interactivepython.org/runestone/static/JavaReview/OOBasics/ooPoly.html), the code for 10-9-1 should not compile because the function `Shape#what()` has no return value.

**Comment by bnmnetp** [comment]
My Java is a bit rusty, but when you declare a function to return void that means it does not return a value.

**Comment by phantamanta44** [comment]
The issue is that you're trying to pass a void value to System.out.print, which the compiler doesn't like.

**Comment by bnmnetp** [comment]
I see the problem you are pointing out.  I'll pass this along to the author.
