### ISSUE TITLE
New Design for Instructor Interface

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#705]
Over the last week I've been spending some time with my iPad and Apple Pencil, sketching out some rough ideas for a new instructor interface.  I would love some feedback or alternative ideas about how this might look.

1. The initial screen with some visualizations to help the instructor get an overview of how the course and individual students are progressing.
<img width="1366" alt="my ideas - 2" src="https://cloud.githubusercontent.com/assets/51115/14899763/2cf9b46e-0d53-11e6-88da-915d5a4af14f.png">

2.  An admin screen for changing start dates, rebuilding, adding sections and TAs, etc.

<img width="1366" alt="my ideas - 3" src="https://cloud.githubusercontent.com/assets/51115/14899825/9479a98c-0d53-11e6-9dea-cbae3b02e7fa.png">

3. A new interface for grading.  Can be organized Assignment -> Student or Student -> Assignment

<img width="1366" alt="my ideas - 4" src="https://cloud.githubusercontent.com/assets/51115/14899878/baa88bdc-0d53-11e6-8b75-0469a546ba14.png">

4.  Creating/Editing an assignment.  You can now see and search for assignments, or add your own assignments by typing them into an editor box.  By assembling the list of questions you create an assignment for your students.  Assignments will be added to the database, and made available for other instructors to build on.

<img width="1366" alt="my ideas - 5" src="https://cloud.githubusercontent.com/assets/51115/14899941/ebb0db62-0d53-11e6-95dd-d2e0d8d5dab1.png">

Please leave comments or your own sketches of alternative ideas!

**Comment by mmoldavan** [comment]
I've been working on an activity & exercise analytics dashboard as a research project -- See https://github.com/RunestoneInteractive/RunestoneServer/pull/706

It may be a good starting point for the "Student Progress" tab section. I like the other tabs / features too, much needed improvements!

**Comment by DanielCHennessy** [comment]
Looks good to me.

It might also be handy to have a button on programming assignments to download all student submissions for that assignment to your local computer.  The reason: late in the year my class has branched into using urllib, tkinter, and various other modules that won't run on Runestone, but I'm still having them submit the code on Runestone.  Sometimes you need to actually run a student's code to see how his/her GUI looks, etc., which in this case must be done locally.

**Comment by bnmnetp** [comment]
Good idea @DanielCHennessy, I do the same thing.

**Comment by bnmnetp** [comment]
I'm going to close this since the UI has been implemented and is in beta.
