### ISSUE TITLE
Conditionals Example Problem - JavaReview book

### ISSUE THREAD

**Issue by NickTheMighty** [RunestoneInteractive/RunestoneServer#716]
In the active code 2, the question should be asking
Try changing the code above to boolean isHeads = false;. What line will be printed before the after conditional?
versus
Try changing the code above to boolean isHeads = true;. What line will be printed before the after conditional?
Because the answer is correct only when you change the isHeads variable to false.

**Comment by bnmnetp** [comment]
@NickTheMighty What book?  What chapter?  Give us a link to the page so we know what you are talking about.

**Comment by NickTheMighty** [comment]
Sorry for the lack of specifics, I'm not accustomed to this yet.
Here is the link: http://interactivepython.org/runestone/static/JavaReview/Conditionals/cbasics.html
Runestone/static/javareview/conditionals/cbasics
