### ISSUE TITLE
Replace Janrain with open source social auth package

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#721]
@flysaiah I would like to add this one to your list.  It might require a little investigation, but I know there are some good open source python modules that handle the authentication with facebook, google, twitter and others.

**Comment by flysaiah** [comment]
After a good amount of time looking, the only one that really stands out is python-social-auth (https://github.com/omab/python-social-auth). It doesn't natively support web2py, but it appears that someone has written a basic web2py plugin to integrate python-social-pauth (https://code.google.com/archive/p/w2p-social-auth/). I need a little time to figure out how authentication currently works, as well as how plugins in web2py work, but I'm going to start trying to implement this plugin as soon as I understand.

**Comment by johnkershaw** [comment]
Lack of Google integration is a huge turn-off for educators. I want to maximise time spent learning, not managing logins and passwords. 

1. Click the link
2. Log in with your school google account
3. There is no step 3

**Comment by bnmnetp** [comment]
Social Auth is also a big turn-off for student privacy advocates.

The 2 minutes it takes you to create a username on Runestone is minuscule compared to the time you'll spend learning.
