### ISSUE TITLE
The3n1Sequence limit inputs to positive integers

### ISSUE THREAD

**Issue by MobiusHorizons** [RunestoneInteractive/RunestoneServer#722]
In the 3n+1 [module](http://interactivepython.org/runestone/static/thinkcspy/MoreAboutIteration/The3n1Sequence.html), the function takes an unvalidated input `n`, and goes on to assume that it is a non-negative integer (the conditions under which the [Collatz conjecture](https://en.wikipedia.org/wiki/Collatz_conjecture) works.)

This is specifically problematic because in the question at the bottom it asks:
>iter-5-1: Consider the code that prints the 3n+1 sequence in ActiveCode box 6. Will the while loop in this code always terminate for any value of n?

The answer being asked for is `No one knows.` which is true for the Collatz conjecture, but not true for the piece of code at the top.

It can be forced into an infinite loop simply by using the value `n = -1` or any negative number. The function should also check to make sure the value is an integer, as any non-integer real-number would also never resolve to `1`.

Either validate your inputs, change the wording of the question, or accept `No` as the correct answer.

**Comment by bnmnetp** [comment]
Thanks for that clarification.  I'll change the wording of the question to clarify that we are only considering positive values for integers.
