### ISSUE TITLE
depreciated code

### ISSUE THREAD

**Issue by Akadine** [RunestoneInteractive/RunestoneServer#724]
On any page, for example [this page](http://interactivepython.org/runestone/static/thinkcspy/SimplePythonData/UpdatingVariables.html) I have noticed some graphical gliches (like code windows showing before the js is loaded to position and style it resulting in a "popping" effect) that does not break the overall program and is not show stopping. Out of curiosity, I opened the developer tools on chrome and noticed three errors, and I tried other pages as well with the same results. Upon further analysis it seems that you are linking to old jQuery and Rangy. Please update before features are discontinued breaking your code.

**Comment by bnmnetp** [comment]
I think we are mostly down to an outdated version of rangy-core.  But when I try to replace it things go bad as it  is apparently not backward compatible. :-(   It also looks like development has stopped on rangy as the last commit was over a year ago.

Is there a newer/better library we should adopt for highlighting?
