### ISSUE TITLE
Problem with reloading saved code: get hidden code back.

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#726]
On any acdtivecode where there is some hidden code (after the ==== line in the .rst file), if you click "Save and Run", when you go back to prior versions, you will have the ==== and the hidden code shown.

I think it would be best to not record this code when saving, though stripping it out on retrieval would also be fine.

I'm not sure what we're doing differently than with the old manual Save and Load, where this problem did not happen. Might go back to that code to find a solution.

**Comment by bnmnetp** [comment]
It probably is a difference in where we grab the code from right before we make the logging call.

The benefit of sending the test code along is that we later know what the tests are and can know whether they were passing all of the tests.  I could see this being useful for later analysis, but I agree that we don't want to show it on the timeline.

Probably for later analysis we can always inject the tests, so I think I'm agreeing that we should not send the test code.

**Comment by bnmnetp** [comment]
Turns out we've been logging the code + the included code + any suffix code for quite a while now.  When we made things autosave we just saved the logged code, not the code that was explicitly saved.

Its easy to change, but we should decide exactly what we want.
