### ISSUE TITLE
Can't login to my account on Interactive Python

### ISSUE THREAD

**Issue by KaiserPhemi** [RunestoneInteractive/RunestoneServer#728]
Hi,
I can't login to my account on Interactive Python. After several password reset, I still get an "invalid login".

Username: kaiser.phemi@protonmail.ch

Please review and revert.

Many thanks

**Comment by bnmnetp** [comment]
Hi, Your email address is not your username.  Please check the 
FAQ.  You will see your username at the top of the user menu.

**Comment by KaiserPhemi** [comment]
Thanks
