### ISSUE TITLE
Error in rebuilding my course ''ProbSolving2016''. Many thanks!

### ISSUE THREAD

**Issue by mohmaj** [RunestoneInteractive/RunestoneServer#732]
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 98, in run_sphinx
    scd, ct = findChaptersSubChapters(path.join(sourcedir, '_sources', idxname))
UnboundLocalError: local variable 'idxname' referenced before assignment

**Comment by bnmnetp** [comment]
Hi, Sorry for that.  We are doing a bunch of summer development work, and I missed that one.

I have pushed a fix, and **tested it** and a rebuild should work now.

**Comment by mohmaj** [comment]
Hi Brad,

Many thanks for the quick reply.

The course did get rebuilt but I get the following message when I try to
access it:

[image: Inline images 2]

Many thanks,
>>mohammad

**Comment by bnmnetp** [comment]
Your images are not showing up above.

I just tried:  http://interactivepython.org/runestone/static/ProbSolving2016/index.html

And had no trouble accessing the page.

**Comment by bnmnetp** [comment]
Aha!  I think I figured it out.

We removed the splash page from the thinkcspy book.  Which means that the index file for your custom course needed to be updated.  I knew that, but I hadn't done it yet.  I've done it now, so if you have a moment, please rebuild again and let me know how it goes.

Brad
