### ISSUE TITLE
Questions are not properly saved with assignments

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#771]
In the new interface, I created an assignment and added a question.  But when I come back to the assignment later the question is not there.

**Comment by millro04** [comment]
I can't seem to recreate this problem. Maybe when we do our hangout we can do some screen shares. Are you getting any errors in the console or any errors printed from the controller?

**Comment by bnmnetp** [comment]
Are you using the new dashboard branch?

The only thing I'm seeing in the console is:  `'NoneType' object has no attribute 'name'`

**Comment by millro04** [comment]
I'm having some issues with it. I've switched over to the new branch but when I run the server and open up the interface I get a ticket error saying 'relation "user_chapter_progress" already exists'

**Comment by bnmnetp** [comment]
That is because I fixed a problem with that table and its migration.

The "solution" is to edit db.py and change fake_migrate_all=False  to True, restart your server, and then bring up the main runestone page.  This will clean up the files in databases and you will be all set.  Once you have loaded the homepage successfully you can change the fake_migrate_all back to False.

**Comment by millro04** [comment]
Ok. That got me this error now - '<type 'exceptions.ImportError'> Cannot import module 'applications.runestone.modules.requests'

Also, I think I found something that might help with this question issue. In the new dashboard branch, admin.py is not the same admin.py I had committed in my master branch. Specifically the admin function is missing some stuff. And we also eventually renamed that to 'def instructors' to make it more generic for the overall interface. 

If you look at `https://github.com/millro04/RunestoneServer/blob/master/controllers/admin.py`, line 578, and compare it to def admin in the dashboard branch you should see those differences. Unless I copied the dashboard branch over incorrectly.

**Comment by bnmnetp** [comment]
Yes,  Because we want each tab to have its own controller.  When you look at the admin tab you do not need to have the data for the assignments tab.  So I split them up into two functions - admin for the admin tab and assignments for the assignments tab.

The error you are getting is because requests is needed for the bug reports  `pip install requests`

**Comment by millro04** [comment]
Ah, okay that makes sense. 

Well the requests error is gone...but, I am getting this now. 

`<class 'psycopg2.ProgrammingError'> operator does not exist: character varying = integer LINE 1: ...id FROM user_courses WHERE ((user_courses.user_id = 21) AND ... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.`

I think this is something we ran into in Michigan but I can't remember what the fix was.

**Comment by bnmnetp** [comment]
Look in the database at your user_coures I'll bet you haven't done the manual conversion on that table to match the new schema.  See #733 for the commands to run in psql to fix it.

**Comment by millro04** [comment]
Ok that worked, I at least have everything up and running now so I can start to fix some of these issues. I'm still able to successfully add questions right now, but I will continue to look into it. In the meantime I will look at the other opened issues too.

**Comment by bnmnetp** [comment]
Ok good. I can add a question too. But when I reload the page it disappears. We can do a hangout tomorrow to walk through this one.

**Comment by millro04** [comment]
Ok sounds good. I have an eye appointment at 11:30 so either in the morning or after lunch would be best, let me know and I'll be available.

**Comment by bnmnetp** [comment]
Just for the record, I've now tracked this down to line 805 in admin.py

````
    type = db(db.assignment_types.id == type_id).select(db.assignment_types.name).first().name
```
first() is not returning anything hence the NoneType object has no attribute name error.

The question is why?

**Comment by bnmnetp** [comment]
Answer:  Because my assignment_types table has two rows one for participation and one for Homework.  I'll bet you have more / different ones initialized in your db?

**Comment by bnmnetp** [comment]
And the assignment_type value in the question_assignment table is Null, because it all starts here:

```
    try:
        type_id = db(db.assignment_types.name == type).select(db.assignment_types.id).first().id
    except:
        type_id = None
```
