### ISSUE TITLE
Safari does not support the nifty html5 calendar dropdown but typing in a mm/dd/yyyy date causes a 500

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#775]
Not sure how this is being formatted by chrome, but it works when you select the date from the calendar in chrome but not when you type in the date in Safari.

We ought to look at using one of the jQuery ui widgets for this so it is consistent in all browsers.  And supports the date+time

Also we need to understand/verify what timezone the timestamp is communicated in to the server.

**Comment by millro04** [comment]
I think I know part of the problem - in the controller we split the duedate field from the form on '-', because that is how it came back from Chrome. I can just move that code into a try except block, and if splitting on '-' doesn't work then we will split on '/' instead. That should allow you to at least type in a date manually in Safari.

**Comment by bnmnetp** [comment]
Ah, thats nasty because the example text shows that you should write the date with a /

**Comment by bnmnetp** [comment]
This page has a nice looking jQuery plugin, that would work on all browsers and provide a consistent return value:  http://xdsoft.net/jqplugins/datetimepicker/

**Comment by millro04** [comment]
The tutorial for that plugin says to include this script tag, '<script src="/jquery.js"></script>'....Do we already load the jQuery js file somewhere else? If so I don't want to load the same thing twice.

**Comment by bnmnetp** [comment]
yes, we are always loading jQuery.js

**Comment by millro04** [comment]
Is it ok to add the other two css and js files needed for the plugin in runestone/static/css and runestone/static/js?
