### ISSUE TITLE
Show in CodeLens broken in Chrome

### ISSUE THREAD

**Issue by sschaub** [RunestoneInteractive/RunestoneServer#826]
On the following page (for example):

http://interactivepython.org/runestone/static/thinkcspy/SimplePythonData/OperatorsandOperands.html

I'm seeing the following issue in Chrome on Windows:

Examples that have a "Show in Codelens" button are broken in the following way in Chrome: Clicking "Show in CodeLens" displays a large white box, but there is no CodeLens inside the box. In other browsers (Firefox, IE, and Edge), clicking "Show in CodeLens" displays a large white box with CodeLens inside.

The examples that are specifically Codelens examples (which do not require the user to click Show in Codelens) work properly in Chrome. This issue is present only when clicking the "Show in Codelens" button.

**Comment by bnmnetp** [comment]
I just tried some of the examples in the chapter you link to on Chrome on my Mac and the show in codelens feature is working fine.

Could you check the Javascript Console and see if you are getting any error messages that might help us figure out why its happening to you?

**Comment by sschaub** [comment]
Ok, I've tried this on the same version of Chrome on another Windows 10 computer, and am not seeing the same issue. So, it's related somehow to my installation. I tried disabling all Chrome extensions to see if one of them was interfering, and still got the issue. I'll continue to try to track this down, but in the meantime, I'm going to close this as not reproducible.
