### ISSUE TITLE
remove students from a course

### ISSUE THREAD

**Issue by mhaugrud** [RunestoneInteractive/RunestoneServer#832]
Please allow the instructor to remove students from a course. When students drop the course they remain in the Runestone course cluttering the class list. Perhaps removing could implemented by putting the selected students in the default Runestone course.

**Comment by bnmnetp** [comment]
The student should not be deleted, but they should be unenrolled from the course. -- switch their enrollment to the basecourse.  In addition 

* any assignment/grading information should be deleted
* useinfo data should be updated to reflect basecourse as the course_id
* the code and acerror_log tables should be updated so the student is in the basecourse

The interface should look like the interface for adding an instructor.

**Comment by bnmnetp** [comment]
When you remove a student from the course and make the updates above, also generate a log message event='moved'  act='sid:<fromclass>:<toclass>'

In later analysis this will allow us to account for students that were removed from the course
