### ISSUE TITLE
Grading interface gets confused when you change the first column

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#835]
I started out by choosing student in the first column, then assignment in the second column.  The third column correctly showed me the questions to grade and perfectly went through the questions for that student!

Then I went back to the first column and chose assignment.  Questions popped up in the second column, but I could not get the third column to show me students.

Can you take a look at this @millro04

**Comment by millro04** [comment]
Yes, looks like I just missed adding the option back in. I won't be home until this afternoon, then I'll get it fixed.
