### ISSUE TITLE
Middle column dropdown for new grading interface should allow student or question

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#839]
Currently only allows question in the dropdown

![image](https://cloud.githubusercontent.com/assets/1077198/17985568/677eb49c-6ae4-11e6-9d00-862452c763dc.png)

**Comment by bnmnetp** [comment]
@millro04 I agree.  Can we do this?

**Comment by presnick** [comment]
Note: it will make some of the logic more complicated in admin.js gradeIndividualItem(), where some assumptions are made about not allowing everything in all columns. Perhaps we should live this for now and make it a later wish-list thing. As is, it's just creating a little extra work for graders, when they put student in left column and have to reselect the assignment for each new student. We can live with that for a while.

**Comment by millro04** [comment]
Ok. So the new combinations we want to add are:
1) chapter > student > question
2) assignment > student > question

Does that seem right? Pretty much whenever question is an option in the middle column also have student be an option?

**Comment by presnick** [comment]
Yes, that's what we'd want,  but it's not to priority.

sent from mobile-- strange words are probably auto-correct gone awry.
