### ISSUE TITLE
get_problem crashing in grading interface

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#851]
The `get_problem` function has problems.  At least in the old grading interface...

It is looking for request.vars.assignment when there is none .. I think it is looking for id  This results in the assignment begin None and things go downhill from there.

**Comment by bnmnetp** [comment]
I made a quick and dirty patch which seems to keep things going, but not sure.

```
    assignment_name = request.vars.assignment
    if not assignment_name:
        assignment_name = request.vars.id

    assignment = db((db.assignments.name == assignment_name) & (db.assignments.course == auth.user.course_id)).select().first()
    try:
        deadline = assignment.duedate
    except:
        deadline = None
```

**Comment by presnick** [comment]
Will look into this tomorrow.

sent from mobile-- strange words are probably auto-correct gone awry.
