### ISSUE TITLE
csp-8-3-2 has no correct solutions - off by one error

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [RunestoneInteractive/RunestoneServer#860]
The code segment is:

output = ""
x = -5
while x < 0:
    x = x + 1
    output = output + str(x) + " "
print(output)

The "correct" answer on the page is 
-4 -3 -2 -1
But the actual answer is
-4 -3 -2 -1 0

This is because of an off by one error. When x == -1, it is added to output. Then it is compared in the while loop, and -1 < 0, so it continues, adding 0 to output.

**Comment by johnkershaw** [comment]
This is fixed in the current live version:

https://runestone.academy/runestone/books/published/StudentCSP/CSPWhileAndForLoops/whileCount.html

Has -4, -3, -2, -1, 0

As per commit on 23 Jan 2018: e505f163096082794fe3f7060273055b73afe1f2

Close?

**Comment by bnmnetp** [comment]
Thanks
