### ISSUE TITLE
Calculating the autograded score for unittests

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#861]
@presnick 

I have been creating practice / autograded exercises for data structures.  and I love it!  This may be the best thing for students that we did all summer!

But I'm looking at the _autograde_one_ac function and I see this code:

```
    score = 0
    id = None
    if most_recent:
        pct_correct = int(most_recent.act.split(':')[1])
        if pct_correct == 100:
            score = points
        id = most_recent.id
```

A couple of problems:
1. The percentages are in the useinfo table as floats, so it crashes.
2. It looks like they can only get full credit if they pass everything.  Shouldn't the score correspond to the number of tests they passed at least instead of all or nothing?  Or is your idea that since it is autograded and they can work on it until it is right that it should be all or nothing??

In any case I'm going to change it to convert to a float and commit that.

**Comment by presnick** [comment]
The grading is based on passing all the unit tests for that question. If
they pass them all, they get the points for the problem, otherwise not.
What did you have in mind?
