### ISSUE TITLE
History slider/scrubber behaves oddly with most recent code (?)

### ISSUE THREAD

**Issue by aerenchyma** [RunestoneInteractive/RunestoneServer#867]
Several of our students report that when pressing Save & Run, they get the output for the code they've just written, but without pressing anything else, the code input window changes to the original code. When they "Load History", they see only the original, not the most recent version they saved, but if they move back one 'version', they see their most recent code.

I have to do more investigation to determine whether this is 100% "user error" such as it is. I have not reproduced it. I did see it happen on two students' computers that they needed to move the slider back to get their most recent code, and I /believed/ they were doing exactly what I would do (save and run, edit, save and run, refresh, load history). Have you (anyone else) encountered this?

**Comment by aerenchyma** [comment]
cc @presnick

**Comment by bnmnetp** [comment]
I have also seen this with one of my students, but I cannot reproduce it.  We need to have it happen where we can get into the javascript debugger and see what is happening.
