### ISSUE TITLE
MisTest

### ISSUE THREAD

**Issue by netranga** [RunestoneInteractive/RunestoneServer#872]
Hi,
I am a student taking AP Computer Science Principles. I had lost internet connection as I was starting the Chapter1&2 Exam and after I had gotten connection back, I refreshed the page and it had said I already had taken the exam and that I skipped all 5 questions. I was wondering if this was possible to be reset because I need to take this exam for a grade. Thanks.

**Comment by bnmnetp** [comment]
We need to fix this situation this summer.

@gardhi01, @conzty01, @ericsonga   I suggest that when a teacher creates a textbook they get a key/password for their course that can be used to reset a timed exam.  The question is how...

1.  There could be an inconspicuous button by the exam that the instructor could press in the students browser which would then bring up a password dialog for the teacher.  Once the password is entered correctly the localstorage for the exam is cleared and the exam is reloaded for the student to take.

2.  There could be a reset button that the student presses and that causes an API call to take place to verify that the instructor has granted permission for this student to reset this particular timed exam.

I think approach 1 is a lot more efficient for in-class usage, whereas approach 2 is more scale-able when students are taking timed exams outside the classroom.  It is a pain for the student to have to seek out the instructor when they are supposed to have taken a quiz like this.

3. It Just occured to me that a student could request a reset but would not be able to change any answers that had already been submitted. -- This might work fine, especially if we prevented any feedback from showing for questions that were skipped...  This would require no additional work on the part of the instructor...

I think the instances where we need to do a reset have been reduced by a previous bug fix which makes it very difficult for a student to accidentally navigate away from the page during an exam, but still... This does make me think that we want to keep the solution to this relatively inexpensive.  I wouldn't want to put a ton of work into something that is not a huge problem.

Thoughts or other ideas??

**Comment by conzty01** [comment]
We have brainstormed some and have determined that option three would be the most convenient from both the students and instructors' perspectives.  As an amendment to the proposal, we think that it would be beneficial for the instructor to be notified of such a retake without necessarily needing to approve such an action.  This would help find any occurrences of students manually causing a test to be unfinished and prompting a reset in order for them to receive additional time to answer the questions.
