### ISSUE TITLE
Compile error in: Java for Python Programmers

### ISSUE THREAD

**Issue by ThonyPrice** [RunestoneInteractive/RunestoneServer#880]
Hi,

In ActiveCode 4 (Swing) I receive the following error:

![screen shot 2016-10-20 at 13 11 32](https://cloud.githubusercontent.com/assets/22328250/19557676/28ece7bc-96c7-11e6-9cf3-48b69a42bd06.jpg)

**Comment by bnmnetp** [comment]
Sorry, you currently cannot do Java graphical programs in the textbook.
