### ISSUE TITLE
Wrong "its" in "Randomly Walking Turtles"

### ISSUE THREAD

**Issue by peteli05** [RunestoneInteractive/RunestoneServer#882]
In "Randomly Walking Turtles" (http://interactivepython.org/runestone/static/CS150Sp16/MoreAboutIteration/RandomlyWalkingTurtles.html), in the sentences "If its heads then turn to the left 90 degrees. If its tails then turn to the right 90 degrees," the word "its" should be replaced by the word "it's." "Its" is the possessive of "it," which makes no sense in this context; "it's" is a contraction that means "it is." 

Also, the following begins with the word "which" and is therefore a question: "Which type of loop can be used to perform the following iteration: You choose a positive integer at random and then print the numbers from 1 up to and including the selected integer." Please amend it so that it contains a question mark.

**Comment by Techfolio** [comment]
I agree with Peteli05. In ["Randomly Walking Turtles" step two,](http://interactivepython.org/runestone/static/CS150Sp16/MoreAboutIteration/RandomlyWalkingTurtles.html) use 

> it's.

Alternatively, I reworded the three sentences in step two (see below). I think the suggested wording reads more smoothly and helps clarify the heads/tails reference in case the reader's country uses different phrasing for the front/back of a coin. Suggested wording:

> Flip a coin. If the coin lands on heads, turn to the left 90 degrees. If it lands on tails, turn to the right 90 degrees.  
  
Peteli05's second suggestion refers to a Check for Understanding question on the same page.

Current wording:

> iter-4-1: Which type of loop can be used to perform the following iteration: You choose a positive integer at random and then print the numbers from 1 up to and including the selected integer.

Suggested wording:

> iter-4-1: Which type of loop allows you to choose a random positive integer and then print the numbers from 1 up to and including the selected integer?
