### ISSUE TITLE
ERROR : "Sorry, Something went wrong" (After login. Please see attached Screenshots)

### ISSUE THREAD

**Issue by gp-dataresona** [RunestoneInteractive/RunestoneServer#889]
I am unable to view the content after Sign in via my google account. 
Kindly see the attached screenshots for further details.

<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/8675809/21400791/618673f0-c777-11e6-86f2-92206a59a243.png">

<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/8675809/21400789/617b5eac-c777-11e6-8786-e0d43ba844cb.png">

<img width="1440" alt="3" src="https://cloud.githubusercontent.com/assets/8675809/21400790/617e4b9e-c777-11e6-9069-6893ddf659c5.png">

**Comment by bnmnetp** [comment]
There is no course named python3  what course were you trying to register for?

**Comment by gp-dataresona** [comment]
I tried to register for - "How to Think Like a Computer Scientist" and "Problem Solving with Algorithms and Data Structures Using Python".
