### ISSUE TITLE
Compiling and Running code

### ISSUE THREAD

**Issue by tmjain** [RunestoneInteractive/RunestoneServer#898]
Not a single problem under the AP computer science review will complete the compiling and running code action. This started happening yesterday.

Here is the most recent problem I tried that was giving me trouble: http://interactivepython.org/runestone/static/JavaReview/OOBasics/objects&Classes.html?lastPosition=185
I have already reloaded the page and cleared the caches multiple times.
I have tried solving the problems on two different mac book pros and on each mac I tried using safari and firefox but still none of the problems will comple the action of compiling and running code.
In addition to the mac computer I tried solving the questions on a windows hp laptop but still to no avail the problems(responses)  will not compile. 
my username on interactivePython is tmjain. And my email is trishalajain01@gmail.com

**Comment by bnmnetp** [comment]
Hi,

I just tested a couple of examples myself and had no problem running the examples.

The system that compiles and runs the java code is located in New Zealand, perhaps it was down for maintenance at the time you were trying to run the code?  I'm not sure but I can check with the group there.

Please let me know ASAP if you are still having the problem.

**Comment by tmjain** [comment]
Hello!
Thanks for getting back to me so quick!
I tried it again this morning and everything was working fine again
