### ISSUE TITLE
Question Error on "Mixed Up Code Practice" Runestone Java Review

### ISSUE THREAD

**Issue by cesarsandoval7678** [RunestoneInteractive/RunestoneServer#901]
Webpage Link: http://interactivepython.org/runestone/static/JavaReview/LoopBasics/LoopParsonsPractice.html

Browser and Computer Information: Using "safari" browser on macbook pro

Problem: The beginning of question 6-14-3 on "mixed up code practice" in the loops section of the java review for the apcsa exam should read "The main method in the following class should print up from 5 to 50" instead of "The main method in the following class should print up from 0 to 50". The variable x is initialized to 5 and not 0, so the while loop will print numbers from 5 to 50 (incrementing by 5). I know this is a minor problem, but it may confuse anyone who is beginning to learn the material

**Comment by bnmnetp** [comment]
Fixed.
