### ISSUE TITLE
Medium Multiple Choice Questions For Conditionals 

### ISSUE THREAD

**Issue by Yoshimar1** [RunestoneInteractive/RunestoneServer#903]
Under Conditionals, in Medium Multiple Choice Questions, the third question contains an error.  The code says:
if (x > 2) x = x * 2;
if (x > 4) x = 0;
Which of the following is equivalent to the code?
According to the site, the correct answer is if (x>2) x = 0;, and when that is selected the "correct" box states that if x were to be greater than two, it would be changed to zero.  That is not true, because if x was 3 it would become 6, not 0.

**Comment by bnmnetp** [comment]
Yes, but then Java would do the second check, we agree that x is now 6 so the second if statement would also be true.
