### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by wshong99** [RunestoneInteractive/RunestoneServer#907]
Hi, I am running "EngComp1" course based on thinkcspy.
I edited my assignment page yesterday and have been trying to rebuild my course, 
but I keep receiving a "404 Not Found" error.
I can access my instructor page and see everything is there, but
my students report that they receive the same 404 error when they log in.
Please advise me how I can retrieve my course pages.
Thank you very much!

**Comment by bnmnetp** [comment]
Hi,
Sorry, but since the move to the new hardware and OS the course builder has been a bit unreliable.  Please try rebuilding again.  I will try to dig into this later today.

**Comment by bnmnetp** [comment]
I kicked off a manual rebuild, so that you will not get the 404 anymore.  I'm still not sure why the build is failing sometimes.  I cannot reproduced the problem at the moment.  But I'll keep looking.

**Comment by wshong99** [comment]
Thank you very much for your kind response!
I tried to rebuild my course, but the assignment page was not updated.
I attempted the rebuilding again, and have the same 404 error.

**Comment by bnmnetp** [comment]
Hi,  I've made  a modification to change the way the build works.  This seems to be more reliable, at least for me, but it also has the benefit of producing a lot more debug output in case it fails.  Please rebuild again and let me know how it goes.

Brad

**Comment by wshong99** [comment]
My course page is finally resuscitated with all the assignments and grades intact!
Thank you so much for your hard work and kind help!!

**Comment by bnmnetp** [comment]
Your welcome.

Your grades and assignments were never in danger.  Those are stored in the database and handled quite separately.  Each course has its own statically built site and it was the static site builder that was failing.
