### ISSUE TITLE
[typo other copyediting]1.13.2. Inheritance: "getLabel" is changed to "getName" randomly

### ISSUE THREAD

**Issue by danielsauceda** [RunestoneInteractive/RunestoneServer#908]
Love the Website.

There is a small bug, you switch of method convention of getLabel and getName:
Listing 8 has the following method
```
...
def getLabel(self):
    return self.label
...
```

however by Listing 14 we change from getLabel to using getName()
```
...
def getPinA(self):
    if self.pinA == None:
        return input("Enter Pin A input for gate " + self.getName()+"-->")
...
```
This is also true for the Active_Code at the end

**Comment by bnmnetp** [comment]
Thanks, we plan to rewrite many of these examples into a new version of the book that is much more pythonic.  Hence no getters/setters like this.  But we'll fix this up anyway to make sure this version is better.

**Comment by bnmnetp** [comment]
Just committed a fix to pythonds for this.  Should be live soon.
