### ISSUE TITLE
Making Custom Courses More Scalable

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#914]
## Background

As originally designed, the Runestone -- Textbook as a Service system (TBaaS) used the Sphinx system to build a complete copy of the desired textbook for each custom course.   Certainly in 2012 when we started down this road I didn't have any idea that we would end up with thousands of courses created.  Nearly 2500 to date.  These courses are stored in the static folder so that the nginx server can serve the static pages leaving the web2py application to be primarily an API server and a dynamic page server for the instructors interface.  The advantage of this is that for the most part the CONTENT of the course is statically served and will work fine even if the web2py server tips over. -- which over the years it has proven itself to be quite reliable.  I also thought that more instructors would want to customize the content of their courses.  To date, very very few instructors have actually made significant changes to the content.

The proliferation of courses has made the static folder grow to over 200GB while this might not sound like a lot in the current context of Terabytes of data it raises several problems:

* It does not really map well onto cost effective hosting systems -- Most provide 40GB for a reasonable cost with further data getting fairly costly.
* It is *really wasteful* of disk space.  Most of the courses in the static folder are essentially identical with the exception of a few entries in the eBookConfig object.
* It requires instructors to manually do a rebuild (an inherently confusing action for most) to get typos fixed as well as to obtain bug fixes in the javascript.
* It leads to a very slow and brittle process for "creating a custom course" -- The scheduler is slow and somewhat flaky.

Several months ago I started thinking about potential solutions to parts of this problem.  Namely the scheduler and how to make life better for the handful of instructors that really wanted to customize their textbooks.  When I had to upgrade the amount of storage available yet again a few months ago and started experimenting with different hosting options.

## Proposal

In this issue I'm proposing a two pronged approach to both the scaling problem as well as the custom build problems.

1.  For the majority of the instructors they can use a SINGLE build of each base book.  But we will need to populate four key elements of the eBookConfig object:

```
  eBookConfig.course
  eBookConfig.logLevel
  eBookConfig.loginRequired
  eBookConfig.python3
```

Populating those things seems like a very solvable problem, and will save us a ton of disk space and make creating a custom course nearly instantaneous.  In the worst case each page could be dynamically populated server side through the standard templating system.  I think a better approach is to populate them client side either getting the information from a session cookie or an API call.

2. For the group of instructors that make custom assignments I believe we can easily populate the assignment pages for the course dynamically. -- Thanks to Paul insisting that we store the html for each question in the database!

3.  For the group of instructors that wants to heavily customize a book, by doing significant editing or moving around of content we will use the Jenkins CI server as I have piloted with a few instructors already.

Tagging @presnick and @ericsonga for comment.

**Comment by bnmnetp** [comment]
@bjones1 -- would welcome the help on migrating to flask.  Here are some thoughts we can discuss.

**Comment by bjones1** [comment]
Great! I'd love to help. I'll take a look at the `eBookConfig` object to come up to speed.
