### ISSUE TITLE
New Architecture Migration

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#920]
# New Architecture Migration Plan
## Part I -- The Student/Book interface

* In this stage the instructor interface will remain a web2py application 
* However we will Implement new server that uses a versioned copy of the book for *most* courses. 
  * This alleviates the “build” process for a course
  * Instructors that really want to customize will use Jenkins
  * Need to talk about assignments and how they are dynamically presented.
* To serve these new courses we will use Flask -- It is much more flexible (and fast) for us to serve with Flask and lets us move to Python3
* How does a user identify what course they are in?
  * This information now comes from from eBookConfig.course
    * This could be filled in by a single function call when a page is loaded
    * From the session cookie if present
    * From an API call if there is no session cookie
  * Another option is that the eBookConfig object is filled in using render_template
      * This means that every page will get served by Flask and is not static anymore.  This would simplify login management but would probably have a cost in server load…. Need to measure and compare
* Migrate the API calls to Flask (really just ajax.py)
* What about the DB? -- I think MongoDB would be a big win, but I need to prove it.

@presnick @bjones1

**Comment by bjones1** [comment]
Neat. Migrating just Ajax should be a breeze. I'm fairly familiar with SQLAlchemy, so I'd personally lean toward using that. However, learning something new is a good thing, too.

**Comment by bnmnetp** [comment]
I like the document oriented idea of Mongo where we could keep all the information for a single user for a single page together to grab in one gulp.  But we could also write a server side API endpoint that would do the same thing while keeping the data in relational form.  

Keeping the database "as is" is probably  the right thing to do for this stage of the migration plan.  If this part of the project goes off to MongoDB we would have to write a bridge to push everything the instructor interface needs into Postgres anyway.

**Comment by bjones1** [comment]
Here's code for checking web2py passwords.

``` Python
from gluon import DAL
from gluon.validators import CRYPT

class PasswordChecker:
    def __init__(self,
        # A web2py-style database URI containing passwords to check.
        db_uri,
        # Any user with a valid password.
        username,
        # A path to the ``auth.key`` file used by the application's web2py.
        auth_key_path='applications/runestone/private/auth.key'):

        # Read the private key.
        with open('applications/runestone/private/auth.key') as f:
            key = f.read().strip()

        # From any user, read the salt used.
        self.db = DAL(db_uri)
        any_user_password = self.get_user_password(username)
        # Get the salt value used to encrypt it.
        alg, salt, encrypted_password = any_user_password.split('$')

        # Create the web2py encrypter.
        self.crypt = CRYPT(key=key, salt=str(salt))

    def encrypt_password(self,
        # The plain-text password to encrypt.
        password):

        return str(self.crypt(password)[0])

    # Given a user, return that user's encrypted password from the database.
    def get_user_password(self,
        # The username to use.
        username):

        return self.db.executesql("select password from auth_user where auth_user.username=?;", placeholders=[username])[0][0]

    # Return True if the plain-text password, after encryption, matches the stored password.
    def check_password(self,
        # The user whose password will check checked.
        username,
        # The plain-text password to check.
        password):

        return self.get_user_password(username) == self.encrypt_password(password)

# Given a password and salt, encrypt it.
def encrypt_password(password, salt):
    # Read the private key used to encrypt.
    key = open('applications/runestone/private/auth.key', 'r').read().strip()
    # Create the web2py encrypter.
    c = CRYPT(key=key, salt=str(salt))
    # Run it.
    return str(c(password)[0])

pc = PasswordChecker('sqlite://db.sqlite', 'Bryan')
print(pc.check_password('Bryan', 'verysilly'))
print(pc.check_password('Bryan', 'verysilly1'))
```

**Comment by bnmnetp** [comment]
Bryan,

Nice example.  The only downside is that once you import gluon.anything you are back in the land of python 2.7  -- looking at the validators.py code I think we can extract what we need out of there for use with Python3 .   Or we may just need to look at the code and write our own crypt method.  web2py uses sha512 and we know where the salt comes from so we ought to be able to replicate it.

Brad

**Comment by bjones1** [comment]
Ah, good point. (The other obvious fix I overlooked was to use sqlalchemy, instead of DAL). Per https://github.com/web2py/web2py/issues/1353#issue-159010482, perhaps the web2py master might work (haven't checked). If you'd like, I can look at this when I finish up other tasks (fitb, assignments).

**Comment by bjones1** [comment]
This now works on Python 3, based on a nightly build with one [patch](https://github.com/web2py/web2py/issues/1685) applied. The updated code below uses sqlalchemy instead of DAL to read the data, and offers a few improvements.

``` python
from sqlalchemy import create_engine, text
from gluon.validators import CRYPT

class PasswordChecker:
    def __init__(self,
        # A sqlalchemy-style database URI containing passwords to check.
        db_uri,
        # A path to the ``auth.key`` file used by the application's web2py.
        auth_key_path):

        # Read the private key.
        with open(auth_key_path) as f:
            key = f.read().strip()

        # From any user, read the salt used.
        self.engine = create_engine(db_uri)
        any_user_password = self.engine.execute(text("select password from auth_user where auth_user.password<>'';")).fetchone()[0]

        # Get the salt value used to encrypt it.
        alg, salt, encrypted_password = any_user_password.split('$')

        # Create the web2py encrypter.
        self.crypt = CRYPT(key=key, salt=salt)

    def encrypt_password(self,
        # The plain-text password to encrypt.
        password):

        return str(self.crypt(password)[0])

    # Return True if the plain-text password, after encryption, matches the stored password.
    def check_password(self,
        # The user whose password will check checked.
        username,
        # The plain-text password to check.
        password):

        db_user_password = self.engine.execute(text("select password from auth_user where auth_user.username=:username;"), username=username).fetchone()[0]
        return db_user_password == self.encrypt_password(password)



pc = PasswordChecker('sqlite:///E:\\Runestone\\web2py\\db.sqlite', 'E:/Runestone/web2py/applications/runestone/private/auth.key')
print(pc.check_password('bjones', 'verysilly'))
print(pc.check_password('bjones', 'verysilly1'))
```
