### ISSUE TITLE
autograde more practice types like Parsons and fill in the blank

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#924]

**Comment by bnmnetp** [comment]
Paul,

If you dont' think you can realistically work on this one, we could assign it to @gardhi01 and @conzty01 .


It seems to me this should be separable from the interface work you are doing.  right??

**Comment by presnick** [comment]
Yes, please reassign it. 

The one point of connection with the interface is that @bjones1 will need to know the new strings that are allowed to designate the new type of autograding.

Note for @gardhi01 and @conzty01: the place to add more autograders is in assignments.py _autograde_one_q, where it dispatches on the autograde field's value: unittest, first_answer, etc. You will just define some new possible values for that field (e.g., for parson's problems,  "correct order", "correct order and indentation").

**Comment by bnmnetp** [comment]
OK, maybe we can agree on those strings up front, and document what is already there here.

activecode:    unittest
mchoice: first_answer, last_answer
clickableArea
fillintheblank
dragndrop
parsons
timed_exam??
ALL: visited  ??

Hmm, it seems like first_answer, last_answer would be appropriate for clickableArea, fillintheblank, dragndrop and parsons.  But that is not unique to each type.  However the question type is in the database in the question table which looks like it is available in autograde_one_q so I think we can dispatch based on both pieces of information when needed.?

looping @bjones1 into the discussion.

**Comment by bjones1** [comment]
Codelens problems can optionally provide a correct answer, right? So they can be autograded?

Also, since activecode problems can include a unit test, can't they also be graded as first_answer, last_answer, or does the database not store that?

**Comment by presnick** [comment]
To be more complete, activecode could be:
First_answer
Last-answer
Last_answer_before_deadline
Best_answer
Best_answer_before_deadline

Also, unittests could be graded all_or_none, as they are now, or
percentage_of_tests_passed.

Somehow have to cross the choice of which code run to grade with the all vs
pct choice.

sent from mobile-- strange words are probably auto-correct gone awry.

**Comment by bnmnetp** [comment]
Seems to me like we have several orthogonal concepts:

1.  Before deadline versus last answer before I grade  -- this is a filter on what questions answers could be considered.  My guess is that for most instructors this is a course policy.
2. first_answer, last_answer, or best_answer  -- this is a more specific filter on which of the available answers to actually grade.
3. unittest:  all_or_nothing versus percent_correct  -- this is a scoring algorithm

**Comment by presnick** [comment]
Agree. Before or after deadline is set at the level of the assignment
currently, and can stay there instead of being a per question thing.

**Comment by bnmnetp** [comment]
I was just cleaning up some old PR's and issues when I happened on this bit of code in grouped_assignments.py:

```
def canonicalize(div_id):
    # needs to take a parameter for which book; hardcoded for pip2 right now
    # used in calculating time spent for grading "use" assignment types
    if ".html" in div_id:
        full_url = div_id
        # return canonical url, without #anchors
        if full_url.rfind('#') > 0:
            full_url = full_url[:url.rfind('#')]
        full_url = full_url.replace('/runestone/static/pip2/', '')
        return full_url
    else:
        return div_id
```

The comment leads me to believe that this will be important to fix for general purpose usage grading.
