### ISSUE TITLE
Broken admin interface

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#940]
In getting runestone up and running on my work PC, I built everything from scratch. From what I can tell, there's no longer a way to get to the admin interface for a newly-created user -- `runestone.controllers.admin.index` (which only required a login) redirects to `runestone.controllers.admin.admin` (which calls `verifyInstructorStatus`). I think I need a way to get to `runestone.designer.index` to create a new course which I own, but there's no way to this page except through the admin interface, which requires me to be a designer.

Or did I overlook something obvious?

**Comment by bnmnetp** [comment]
You beat me to it, I was going to do a clean install to a linux VM today.

This is definitely a flaw in our logic and testing.  All of us testing already had users that were instructors.

I think we need a big giant button somewhere on the front page that says "I WANT TO MAKE MY OWN COURSE AND BE THE INSTRUCTOR"  This button would take you to the designer.  It is one of the most FAQs I get by email.

**Comment by bjones1** [comment]
:) Sounds good to me...

**Comment by bnmnetp** [comment]
Add button to the home page that takes them to designer/index controller.
