### ISSUE TITLE
Student progress by page is blank

### ISSUE THREAD

**Issue by MarkEstefanos** [RunestoneInteractive/RunestoneServer#946]
I'm getting an issue when trying to view student progress by page:
<img width="1440" alt="screen shot 2017-06-29 at 5 40 42 pm" src="https://user-images.githubusercontent.com/7613936/27716299-47589c36-5cf2-11e7-9ce7-1d7f16121113.png">

Any ideas?

**Comment by bnmnetp** [comment]
Mark,

We are in the midst of ripping out all of the old elements of the instructor interface this summer.  I'm guessing you pulled a version of the server from github in some in-between state. The latest version on github will send you directly to the new instructors interface.  (probably still linked to and labelled as beta on what you have)

There will be lots of active development of the interface throughout the summer, but feel free to let us know whats not working for you.

Brad
