### ISSUE TITLE
Auto-grade field in assignment page does not save

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#956]
I can change the Empty status in the interface to something.  But It does not save.  When I refresh the page it is back to Empty.

<img width="1188" alt="screenshot 2017-07-05 13 21 21" src="https://user-images.githubusercontent.com/51115/27976026-66e3607a-632a-11e7-8130-9c3a85ae969a.png">

**Comment by bjones1** [comment]
Fixed in https://github.com/RunestoneInteractive/RunestoneServer/tree/assignment_interface, please close.
