### ISSUE TITLE
future of assessment_type field

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#959]
It does not look like the assessment type field is getting set in the new assignment builder.   BUT, the grading interface uses this to decide what to show...

Is this the field we will use to flag whether something is a 'reading' inline thing or should the column go away?

The grading interface should have some kind of filter on which things to show?  What about auto grading?

**Comment by bjones1** [comment]
I *think* this is resolved with the current contents of https://github.com/RunestoneInteractive/RunestoneServer/tree/assignment_interface. @bnmnetp, would you close if so?
