### ISSUE TITLE
The database should not allow a course to have multiple questions with the same div_id

### ISSUE THREAD

**Issue by gardhi01** [RunestoneInteractive/RunestoneServer#962]
Because the autograder assumes a unique div_id within a particular course, it tends to act strangely when a course has more than one question with the same name (such as multiple questions named uniqueid). When a question is added to the database, there should be a test to make sure the database doesn't already contain that (course, div_id) pair.

**Comment by bnmnetp** [comment]
@gardhi01 -- In my database I have a constraint that makes the divid + basecourse  unique.

If you look in questions.py in the models folder you will see the command that needs to be run.  @presnick commented out the code that tried to add this constraint every time the model was loaded.

It would be nice to find a way to make this happen on a one time basis automatically.

Maybe we need a special controller that we can call one time to do these initializations and special setups.
