### ISSUE TITLE
Remove old div_ids table -- not used anymore

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#966]
As far as I can tell, and I've searched the controllers and models code the div_ids table is not needed as everything is using the questions table.

This is as it should be as in looking at the code I can see that the div_ids table is not even getting populated correctly anymore.

Tagging @presnick and @bjones1  for confirmation.

**Comment by presnick** [comment]
Not needed as far as I know-- we are putting things into the questions
table now.  But I might be missing something.

sent from mobile-- strange words are probably auto-correct gone awry.
