### ISSUE TITLE
error: invalid view (admin/sections_create.html)

### ISSUE THREAD

**Issue by madsesmith** [RunestoneInteractive/RunestoneServer#971]
I tried to create a new section from my instructor page and got the following error:
<img width="999" alt="interactivepython.org/runestone/admin/sections_create error is: invalid view" src="https://user-images.githubusercontent.com/4765540/28594161-f5cbbad6-715c-11e7-93ef-814e7ea0afc6.png">

**Comment by bnmnetp** [comment]
Thanks for pointing that out.  I think its been like that for quite a while.  My suspicion is it got taken out when we introduced the new interface -- scroll down to where it says Beta -- There is a tab in there that will allow you to add sections.

**Comment by madsesmith** [comment]
@bnmnetp Thanks, I was able to add sections on that page. However, there's another link there to the defunct page:
<img width="422" alt="link to broken page from beta instructor section" src="https://user-images.githubusercontent.com/4765540/28595092-5d3be9d6-7160-11e7-8b04-62685d020ff0.png">

**Comment by bnmnetp** [comment]
I'll clean up that All sections link shortly.  In the meantime, I've cleaned up a few other things and you shouldn't need to worry about that link anymore.
