### ISSUE TITLE
Collapsible sections for instructor assignment authoring page

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#974]
I think, rather than the two columns, it would be better to make the Readings segment and Problems segment each take the full column (readings segment on top), but be collapsible. Initially, just the headings would be shown and you could click on the heading to expand or collapse the section.

This will give us more screen real estate for the tables. Also, I suspect that many instructors will use a different assignment object (with different deadline) for readings assignment and problem sets. It will be nice if they can open us just segment that they want to fill in.

**Comment by bjones1** [comment]
This should be fixed in 7e76f56515fce264ce7d849bd3557f6964f81b8d. Would you take a look?
