### ISSUE TITLE
Revision to design of readings segment of instructor assignment interface

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneServer#975]
The tree picker specifies which subchapters the student is supposed to read. Each subchapter has a number of embedded interactive activities (e.g., activecodes, mchoice, parsons, etc.).

When an instructor inserts a subchapter (or set of subchapters, by selecting a chapter) from the tree picker, that adds a row to the table for the subchapter. It does not explicitly add a row for each of the interactive activities in the subchapter. This is as it should be: there would be too much clutter to show all of the interactive activities separately here.

I propose that we get rid of the three assignment-level "Readings properties" fields: Threshold, points_to_award, and Autograder. Instead, we will use properties of the assignment_question for each individual subchapter.

In the table row for each subchapter, we would have the following fields:

- Chapter
- Subchapter
- Activity count (this would be the number of interactive elements, plus one for opening the page; returned by the python code on the server when the subchapter is inserted; not editable here)
- \# required (defaults to 1, or last value that was set for this field on some other row; jscript validation requires it to be an integer less than or equal to the activity count)
- Points (defaults to 1, or last value that was set for this field on some other row)
- Auto-grade (possible values are: ["Interaction", "Correct Answer"], default to "Interaction" or last value that was set for this field on some other row)
- Which to grade (possible values are: ["First answer", "Last answer", "Best answer"], default to "Best answer" or last value that was set for this field on some other row)

The total points would be calculated using the same mechanism used with the embedded problems table. Indeed, the total points: div would move up to the Assignment properties segment of the page, out of the Problems segment.

Here's what we would need to do to implement this:

- [x] Add field "activities_required" of type integer in table assignment_questions
- [x] Remove fields "threshold", "points_to_award", and "readings_autograder" from models/grouped_assignments/assignments table
- [x] In admin.py/add__or_update_assignment_question, if reading_assignment is true, do a query on the questions table to get the number of interactive activities associated with that subchapter, and add one for the activity of opening the page at all. Return this in the json
- [x] In admin.js, get the returned number of activities and write it into the table row for that subchapter
- [x] In assignments.py/autograde, see if the assignment_question is of type reading_assignment. If so, handle it differently (find all the questions associated with the subchapter and call _autograde_one_q on them with 1 point for each; sum the scores; if greater than or equal to activities_required, assign all the points, else 0 points; if activities_required is 0, assign proportionally (point * sum_of_points/activity_count). This is similar to the code currently in _compute_assignment_total, though not exactly the same.
- [x] In assignments/_compute_assignment_total, remove the code that deals with thresholds and just set score = total

**Comment by bjones1** [comment]
So, from a GUI perspective, this table is similar to the problems table, but has two more fields: activity count (not editable, provided by the server) and # required (editable with validation)? If so, this shouldn't be too hard. @bnmnetp, I think you volunteered to help with the server side on this?

**Comment by bnmnetp** [comment]
Yes. I will help

**Comment by bnmnetp** [comment]
Now that I'm populating the question table with 'page' questions for every page, we don't have to add 1 for the third bullet since the 'page' question will be part of the count.

In the assignment_questions table, the number of activities should translate to the number of points?

**Comment by presnick** [comment]
I think the number of points should be instructor-settable-- you get a
maximum of <n> points for this subchapter, which is either all-or-nothing
(if a number of required activities is set) or is a pro-rated fraction of
<n> if the author sets the required number of activities to 0.

**Comment by bjones1** [comment]
I don't understand the difference between # required and points. Is this the threshold: if students get # required, they receive points for the reading assignment?

**Comment by bjones1** [comment]
For auto-grade is "manual" still a possible choice?

**Comment by bjones1** [comment]
I just made a BUNCH of changes pushed to my assignment_interface branch. I now need some server support before I can really test:

- The `save_assignment` endpoint no longer receives a threshold, points_to_award, or readings_autograder fields, since these are now properties of an reading table row, not the overall readings properties.
- The `add__or_update_assignment_question` endpoint now receives the new num_required field (for readings only). It should return and additional field, activity_count.
- The `get_assignment` endpoint needs to provide more fields in the assignment_data.pages_data struct: activity_count, num_required, points, autograde, autograde_possible_values, which_to_grade, which_to_grade_possible_values.

**Comment by bnmnetp** [comment]
1. fixed  already.
2. I thought it was returning activity_count
3. ???

**Comment by presnick** [comment]
"manual" is not a possible choice for auto-grade on the reading
assignments, in my opinion.

**Comment by bjones1** [comment]
Great! Thanks.
