### ISSUE TITLE
Can't change Auto-grade / Which to grade

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#981]
​I can't modify the auto-grade/which-to-grade options in the Problems section of Assignments. I change it, save it, and then when I switch tabs to force a refresh on the Assignment page, it reverts back to the old original settings.

![image](https://user-images.githubusercontent.com/28868409/28997438-ca756290-79c9-11e7-85e0-77cc0a6c2e28.png)

(I'm using the LHSIntroCS custom copy of thinkcspy in dev.runestone.academy - Try2 is the name of the assignment.)

**Comment by bnmnetp** [comment]
This change 59a6132 also fixes this problem.
