### ISSUE TITLE
Help with server build

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#982]
I have a _nearly_ working build - register new user, logon, build copy of thinkcspy, navigate around the new book and do exercises.

But, the Assignments don't allow me to see the tree of problems in the Reading or the Problems section.
![image](https://user-images.githubusercontent.com/28868409/28997795-300ff590-79d2-11e7-83e1-84659111612b.png)
When I did the `runestone build` of thinkcspy, I had these statements - (over 400 of them...)
```
Unable to save to source_code table in activecode.py. Possible problems:                                       
1. dburl or course_id are not set in conf.py for your book
2. unable to connect to the database using dburl
```
Also, when I `runestone build`  or `runestone deploy` or `start` I got the following:
`Skipping all DB operations because environment variables not set up`

But, I'm pretty sure I setup my DBNAME, DBPASS, DBHOST, DBUSER.
```
(env2) runestone makwong$ printenv | grep DB
DBNAME=runestone
DBHOST=localhost
DBPASS=
DBUSER=makwong
```

**Comment by bnmnetp** [comment]
The docs are outdated. Use DBURL instead of the individuals DB vars

**Comment by psmaker** [comment]
That did the trick! Everything looks to be working now. Thanks!
