### ISSUE TITLE
Feature: Editing or Deleting Custom Problem by Author

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#987]
It might be a nice feature if the author could edit or delete custom problems.

The reason is if a custom problem is incorrect/buggy/whatever, it cannot be fixed/deleted and then remains in the database for someone else to use (and be frustrated with a bad problem).

Extended feature would be to be able to notify some other Author of a possible problem with their problem so that they can fix it.

**Comment by bnmnetp** [comment]
Its not obvious, but if you search for the problem by the name you gave it you can edit it.  We need to detect that you are the author of the problem and not force you to give the problem a new new if that is the case, so this should remain open until that is fixed.
