### ISSUE TITLE
Feature: Partial credit for Problems

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#988]
It would be nice for some percentage of points to be given for problems - specifically ActiveCode with unit tests that can possibly calculate a percentage of partial credit. 

In our previous Java course, we used a Web-CAT auto-grading system with unit testers for assignments that assigned partial points for some amount of functionality.

**Comment by bnmnetp** [comment]
If the auto-grade is set to %correct for an activecode question with a unittest that is how it should behave.  The student would get credit according to the % of tests that were passed.

**Comment by psmaker** [comment]
How would a ActiveCode unit test return a % correct? By this I mean, 100% for fully correct or 80% for mostly correct, but one corner case assertion failed. Maybe there is some method of returning a score, but I'm just not familiar with it.  Thanks!

**Comment by bnmnetp** [comment]
When you try to solve a problem that has unit tests written for it, the ActiveCode / unittest interface reports the % of tests that pass to the student on the page.  This is the information that is used to give partial credit.

**Comment by psmaker** [comment]
Is there some example or some doc on this % return method? Sorry if it is out there.

**Comment by bnmnetp** [comment]
No, no docs on all of this yet.   Every time I sit down to write some docs or make a video on the UI for this new interface I end up fixing bugs!  Soon I hope!!

**Comment by bnmnetp** [comment]
But, you may find this helpful:  http://interactivepython.org/runestone/static/overview/overview.html#id17

**Comment by psmaker** [comment]
I realized this was must a misunderstanding on my part.

When you were you used the phrase "% of tests", you meant the percentage of assertion statements that passed within the activecode unittest. 

I get it now!!  So, this is all good.  I tried it out and it is fully sufficient.
