### ISSUE TITLE
Edited Question does not show up in student Assignment view

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#989]
Test case: Write a custom problem based on a previous problem in database
_(Note: Using **Write** to write a brand new problem does not exhibit this issue)_

1. A Search was done to copy a good problem already in the database.
2. Problem was edited, name was changed and id was changed to match. No other code change.
3. **Edit Question** was pressed to save it.
4. Problem was added successfully to the assignment table.
5. When then viewing it in the student's Assignment view, it is not there. Also, when re-Search'ing for the problem again, it is listed, but Preview is not there because `Preview not available for null`.
6. But, when Edit is pressed, the text for the problem is indeed there. But, not the html...

![image](https://user-images.githubusercontent.com/28868409/29005604-694ccd30-7a93-11e7-948c-b72b16e0bb3f.png)

(In writing this, I realized that it would be "nice" to have Preview ability in the Edit Question page... As a test writer, I think that I would just hit the Edit button, copy the text of the code, then go back to the Write so that I can access the Preview ability....)

**Comment by bnmnetp** [comment]
Yes, the editing of questions definitely needs to be brought up to date.   I can see that there is no lhs_try4 in the database.  It seems it never gets past the UI.

- [ ] We need an API endpoint something like _add__or_update_question()
- [ ] We really should add a column to the table or an icon next to the question name that would allow the instructor to edit the question from the table.
- [ ] as an aside it would be nice to click on a question in the table to preview that question in the preview window.
- [ ] Add option to preview the question when editing.  -- Seems like we should not do this with a popup but use the same interface we use for creating a question in the first place.
- [ ] as mentioned elsewhere, we should verify the author column and if the author is the same as the editor then renaming is not necessary.

**Comment by psmaker** [comment]
I'm sorry - you won't find lhs_try4 in the dev.runestone database.  It was something I did in my own local build where I pulled the very latest from gitHub. I was not able to fully test this test situation in the dev.runestone server - it still had the issue #984 where the Edit page had the single quoted line. So, I updated my local build with the #984 fix and that is where I am seeing this issue.

**Comment by psmaker** [comment]
The edit_question() seems to only write tag/difficulty/name/question_text. It seems to be missing a lot of other stuff - especially the htmlsrc. That explains why the questions looks blank in the actual Assignment part of the book.

The create_question() relies on the user to have pressed the Preview button to create the htmlsrc. If by chance they did not, and just proceeded with the Done, then there would be no htmlsrc.

When the different Tab are selected, the qrawhtml (assignment.html) should be null'ed out. 

I see odd behavior where if one Searches for a question - the qrawhtml will reflect the selected question and show nicely. Then if the Write Tab is then selected after the Search, the edit box will open up with some other rst code in it and yet the qrawhtml from the previous Search is still shown. So, there is this moment of inconsistency until the Preview button is pressed to regenerate the qrawhtml.

**Comment by bnmnetp** [comment]
@psmaker you may need to clear the cache in your browser in order to get the latest admin.js file to load with the fix for #984

**Comment by bjones1** [comment]
I'd be happy to modify the table, but I'll need to look at this interface, since I haven't used it. What UI process do you want? An "edit" column in the table that's only available for user-written questions?

**Comment by bnmnetp** [comment]
@bjones1 Our original concept was that *any* question would be editable.  An instructor might take any question as a starting point for a new question.  I think an edit column would be the clearest way to make this visible.

**Comment by psmaker** [comment]
@bnmnetp I tried a variety of things to clear the cache - even going to a different computer that had not been used for this site - and still had the single line quoted Edit issue.

**Comment by bjones1** [comment]
Instead of an edit column, what about making the question name in the table a clickable hyperlink? Clicking on it would then preview the question. Next to the preview would be an edit button to edit the question.

(I'm only able to help with the table stuff -- preview/edit is beyond me. But if you can provide me with what you want the hyperlink to do or an onclicked JS function to call, that's easy.)

**Comment by bnmnetp** [comment]
I definitely think that clicking on the question name to bring up a preview is a good thing to do.  Adding an edit button to that would seem pretty natural.  It seems unlikely that people will know which question they want to edit without looking anyway.

**Comment by bjones1** [comment]
Done -- see https://github.com/bjones1/RunestoneServer/tree/preview_question. (But this will need an edit button added to the preview part...)

**Comment by bnmnetp** [comment]
This is all done.  I've added #1001 as a bit of cleanup that still needs to be done.
