### ISSUE TITLE
Ordering Assignments

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#991]
Is there a way to order the assignments? When new assignments are made, they just seem to be placed in random order in the Student view. It would be nice to be able to order it (kind of like we can order the reading/questions w/ that nice table row-reordering...)

**Comment by bnmnetp** [comment]
Its a database query that pulls up the assignments for the course.  I can order it by due date or the id of the assignment with minimal effort.

If you want to manually order them, we can add that as a feature request.  Not sure it will get done before school starts though.

**Comment by psmaker** [comment]
Due date ordering if easy would be nice for now

**Comment by bnmnetp** [comment]
Done, I also spruced up that page to show the due date and the description next to the link.

**Comment by psmaker** [comment]
Just checked it out, beautiful!  Thanks!
