### ISSUE TITLE
Auto-grade of question not scoring it

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#992]
Test: Create Assignment w/ 1 question. 1 of 3 student completes it. Auto-grade it.
Database: LHSIntroCS / Assignment Try7

The computed score is still 0 even though it had been complete and it shows correctly on the right preview screen.

![image](https://user-images.githubusercontent.com/28868409/29043977-28a91b46-7b72-11e7-9ad0-f3a45c964b6a.png)

**Comment by bnmnetp** [comment]
Is this on the dev.runestone.academy site?

How does it show up in the grade book??

**Comment by bnmnetp** [comment]
Nevermind, I was able to reproduce and fix.
