### ISSUE TITLE
In Grade view, Preview of student response is incorrect

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#993]
Test: Add question, only 1 of 3 students answer, auto-grade all three
Where: in dev database, LHS_Admin, Assignment Try7 

In the Grade view, the instructor view of the student response is incorrect.

In the picture below, the right most window is the LSH_Chrome user answer w/o anything chosen. In the left window, the instructor sees that the student has answered the questions correctly. The auto-grade score is correctly 0 though.

![image](https://user-images.githubusercontent.com/28868409/29046272-954fb3a0-7b7b-11e7-92aa-cb83e8f27c58.png)

**Comment by bnmnetp** [comment]
Ugh, another good catch.

The answer you are seeing is coming from the browsers localStorage.  We use localStorage in the browser to cache the users answers to questions.  This is great when a page of the book is loaded and not so great when you are grading.  Luckily each component "knows" when its being used by the grader (this.graderactive === true)  so its easy to turn off restoring from localStorage.

**Comment by psmaker** [comment]
Fix looks maybe good... Just a clarification - it will always show the **Best Answer**? (I tried changing the problem type to Last Answer, but it doesn't show the last answer, maybe it is always showing the best answer?)

**Comment by bnmnetp** [comment]
Yes, the grader will always show the best answer -- prior to the deadline if the deadline is being enforced.  This seems like fair behavior to me as many students do try out other answers once they have done the correct answer just to see the feedback.

**Comment by psmaker** [comment]
Yeah, definitely, clarification would be good if for instructor has chosen one of the other grading methods. Maybe just some text on the preview screen.
