### ISSUE TITLE
Student sees "not yet graded" when problem has been completed

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#994]
Test: Assign a bunch of questions from Chapter 1 to 3 students. LHS_Chrome student does 5 correct, 1 wrong and the rest blank.
Where: LHS_IntroCS book, Assignment Try8, Student: LHS_Chrome

After grading and releasing, the student sees one of his problems that he did correctly, marked as "not yet graded".

Adding the points credited in the student view, it shows 2 points. But he received 6 points credit. Possibly he got 1 point credit for an active code problem that he ran.

![image](https://user-images.githubusercontent.com/28868409/29047278-e28333fa-7b7f-11e7-90b1-0491f70b2f62.png)

**Comment by psmaker** [comment]
Perhaps related. A problem that was missed showed a 1 point credit. Not sure if this 1 point was really in the total, but it is inconsistent with the answer.
![image](https://user-images.githubusercontent.com/28868409/29047426-87e0a4b8-7b80-11e7-910e-757f92e7442e.png)

**Comment by bnmnetp** [comment]
I can't reproduce this one. -- are you doing this on your own system?  Is it fully up to date?

**Comment by psmaker** [comment]
Hmm.... It was on the dev site. But, when I checked just now the Student view, the "Not Yet Graded" disappeared and all of them have Score values. A mystery why that is... So, all 6 points scored are accounted for.

But, I still see the 2nd issue in the subsequent comment. First I thought maybe because I had "Best Answer" chosen, that maybe I had checked the right answer at one point. Then I changed the type to "Last Answer" for that problem. But the score is still 1 for the incorrect answer.

I'll see if I can reproduce this one as well.

I don't know if you have access to the LHSIntroCS database on the dev site to help you see this problem or not.

**Comment by bnmnetp** [comment]
yep, I can see the database.

Yes we do have a small problem in that the code I wrote to display a question in the grader uses the same mechanism as the chapter to grab the students response.  It has no knowledge of the question and whether best answer or whatever was selected.  For multiple choice questions if the student ever answered the question correctly (which lhs_chrome did) then that will be the answer shown.  

I'll keep this open until we figure out a good way to handle this.
