### ISSUE TITLE
Editing question

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#997]
First of all, the new edit flow is really nice - the ability to click on questions to see the preview screen on the right hand side and an edit button - all very nice!

I saw some odd behavior with the following steps:

1) Select a question to edit
2) Edit it
3) Preview and save it back to the same ID
4) Select another question to edit
5) Edit it.  
    **ISSUE**: The edit box appears with the _previous_ question. One cannot edit another question unless you reload the Assignment page.
6) Reload Assignment page.
7) Select and edit question from step 1. 
    **ISSUE**: The code in the edit box is a single line that is no longer cleanly editable.
![image](https://user-images.githubusercontent.com/28868409/29100904-8d261528-7c63-11e7-8783-f4a5885a683e.png)

**QUESTION** When taking ex_2_10, another author's questions, and then saving it w/o changing the name, I noticed that it saved OK, and that I was now the author of ex_2_10. But, also, in the original book, where ex_2_10 is also called, it had the original author's version of ex_2_10. Is this the intended behavior? I thought maybe it would reject saving it unless the name was changed, or the editor was also the original author.

**Comment by bnmnetp** [comment]
Strange, I saw that behavior for a while, then I thought I had it fixed!  Plus you are not seeing a good question.  Are you up to date?  Have you rebuilt your course?  Cleared your cache?

**Comment by psmaker** [comment]
Rebuilt, ran on new machine never having run dev site just to be sure. Same issues.

I repeated the sequence of steps in my Try11 assignment, I edited db_ex3_8. Same issues.

**Comment by bnmnetp** [comment]
Just pushed a fix for this.  It was very strange, I could see that I was getting the right text to populate the editing textarea but some old value was being displayed.  I was using `textarea.innerHTML = blah` Switched to using `$("#editRST").val(blah)` and now it works reliably.

**Comment by psmaker** [comment]
I just tried this sequence:

Edit a problem. Save it (to the same name).
Edit same problem again. 

The .rst show up with the odd %0A characters.

But, the multiple edits of different problems within the same assignment is working well w/o reloading the page. Some one of the two issues seems fixed.

**Comment by bnmnetp** [comment]
somehow I missed the %0A thing.  That is actually easy to fix.  I just had to delete a line of code.  One of my students didn't fully understand when to user HTTP GET versus POST.  This is fixed in github but need to make a new beta release to fix it on the site.
