### ISSUE TITLE
Feature? Writing out assignment grades

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#998]
Is there a way to save out to a simple CSV grades of assignments.

Something like User Name, Last Name, First Name, Section, Assignment 1, Assignment 2, etc... might suffice.

**Comment by bnmnetp** [comment]
Yes, the grade book page has a link to let you download a csv file.

**Comment by psmaker** [comment]
In the old interface, there was a Download button, but I can't find any in the new interface. The Grading tab doesn't have it unless I'm just looking in totally the wrong place. The Doc tab doesn't take me anywhere. I didn't see it under any of the other tabs. Am I missing something really obvious?

**Comment by bnmnetp** [comment]
<img width="870" alt="screenshot 2017-08-09 07 51 14" src="https://user-images.githubusercontent.com/51115/29122379-b636af94-7cd7-11e7-94ce-29ad0a2ae5e9.png">

**Comment by psmaker** [comment]
Oh!! Duh! I wasn't even getting to this screen cuz I had not hit the "Gradebook" button.

Sorry to waste your time...
