### ISSUE TITLE
Delete question from questions section not working again?

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#999]
The x button or unchecking the question picker does not seem to remove the question from the assignment table.

(Reading section deletion is OK.)

**Comment by bnmnetp** [comment]
This is for a question you wrote yourself?  If so, yes we are still working on it.

**Comment by psmaker** [comment]
No, it is for a question in the tree. I click the box and it adds to the table. I click the box again and the check mark disappears, but remains in the table. I click the box again and it appears in the table again - duplicated.

When I press the x to delete, it brings up a preview of the question.

**Comment by bnmnetp** [comment]
Yes, it seems that making the question name "clickable" has somehow made the whole row clickable.  its easy enough to unlink the question name, and restore the delete functionality, but hopefully we can find a better solution.

**Comment by bjones1** [comment]
I assume this is the same as the issue we worked on this morning? If so, I believe you can close it.

**Comment by bnmnetp** [comment]
Yes, this seems fine.
